from sources import USL_SOURCES
usl_sources = list(USL_SOURCES)
    
Import("env")
Import("PackTar")
import os
    
if 'dist' in COMMAND_LINE_TARGETS or 'install' in COMMAND_LINE_TARGETS:
    for file in os.listdir("."):
        if file.find(".cpp") != -1 or file.find(".h") != -1:
            PackTar(env["TARFILE"], file)
    PackTar(env["TARFILE"], "SConscript")
    
env.Library("usl", usl_sources)
