usl_sources = Split("""
code.cpp         lexer.cpp     token.cpp      types.cpp
code.h           lexer.h       token.h        types.h
debug.cpp        memory.cpp    tokenizer.cpp  usl.cpp
debug.h          memory.h      tokenizer.h
interpreter.cpp  position.cpp  tree.cpp
interpreter.h    position.h    tree.h""")

Import("env")
Import("PackTar")

env.Library("usl", usl_sources)
