// Contract fixtures: documents every implementation must accept (valid) or
// reject (invalid). Edit this file, then run `npm run fixtures` to regenerate
// packages/protocol/fixtures/. A test fails if the files are out of date.
import {
  MATCH_TICKET_AUDIENCE,
  STANDARD_RULES,
  type MatchSetup,
  type MatchTicketClaims,
  type SimVersion,
} from '../src/index.ts';

export interface FixtureCase {
  schema: string;
  name: string;
  valid: boolean;
  /** For invalid cases: which check rejects it. */
  stage?: 'schema' | 'semantic';
  note: string;
  value: unknown;
}

export const SIM_VERSION: SimVersion = {
  versionMinor: 125,
  netProtocol: 49,
  dataHash: '3f9a6c1e8b2d47a05e6f1c2b3a4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f',
};

const HASH_A = 'a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90';
const HASH_B = 'b0c1d2e3f405162738495a6b7c8d9e0fb0c1d2e3f405162738495a6b7c8d9e0f';
const HASH_C = 'c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4';
const HASH_D = 'd00dd00dd00dd00dd00dd00dd00dd00dd00dd00dd00dd00dd00dd00dd00dd00d';
const ACCOUNT_1 = '0b8f6f2e-3c4d-4e5f-8a9b-0c1d2e3f4a5b';
const ACCOUNT_2 = '1c9a7a3f-4d5e-4f60-9bac-1d2e3f4a5b6c';
const MATCH_ID = '7e3c1d2b-9a8f-4e6d-8c5b-4a3f2e1d0c9b';
const ROOM_ID = '5d4c3b2a-1f0e-4d9c-8b7a-6f5e4d3c2b1a';
const JOB_ID = '9f8e7d6c-5b4a-4392-8170-6f5e4d3c2b1a';
const NOW = '2026-10-01T12:00:00Z';
const MAP_ID = '2a1b0c9d-8e7f-4a6b-9c5d-3e2f1a0b9c8d';
const MAP_INFO = {
  id: MAP_ID,
  owner: {
    id: ACCOUNT_1,
    displayName: 'Alice',
    kind: 'registered',
    createdAt: NOW,
  },
  title: 'Two Rivers',
  description: 'Two rivers split the land; fords in the middle.',
  visibility: 'public',
  hidden: false,
  madeWith: 'hand',
  latestVersion: {
    hash: HASH_A,
    size: 48211,
    width: 128,
    height: 128,
    teamCount: 2,
    minVersionMinor: 125,
    simVersion: SIM_VERSION,
    validation: 'valid',
    fileTitle: 'Two Rivers',
    preview: 'ready',
    previewUrl: `https://play.example.org/api/v1/maps/${MAP_ID}/versions/${HASH_A}/preview.png`,
    downloadUrl: `https://play.example.org/api/v1/maps/${MAP_ID}/versions/${HASH_A}/file`,
    createdAt: NOW,
  },
  stats: { plays: 12, downloads: 30, likes: 4 },
  createdAt: NOW,
  updatedAt: NOW,
};

/** Two humans, one each on a two-team catalog map. */
export const SETUP_CATALOG_1V1: MatchSetup = {
  schemaVersion: 1,
  simVersion: SIM_VERSION,
  seed: 2463534242,
  map: { kind: 'catalog', hash: HASH_A },
  teams: [
    { team: 0, alliance: 0 },
    { team: 1, alliance: 1 },
  ],
  seats: [
    { seat: 0, kind: 'human', team: 0, name: 'Alice', accountId: ACCOUNT_1 },
    { seat: 1, kind: 'human', team: 1, name: 'Bob', accountId: ACCOUNT_2 },
  ],
  rules: STANDARD_RULES,
  experiments: [],
};

/** One human against three AIs on a generated four-colony map, human vs all. */
export const SETUP_GENERATED_FFA: MatchSetup = {
  schemaVersion: 1,
  simVersion: SIM_VERSION,
  seed: 42,
  map: {
    kind: 'generated',
    generator: {
      generatorId: 'even-ground',
      revision: 3,
      params: { width: 7, height: 7, teams: 4, workers: 4, wheat: 100, wood: 120 },
      seed: 987654321,
      candidates: 5,
      startingUnitLevel: 0,
    },
    hash: HASH_B,
  },
  teams: [
    { team: 0, alliance: 0 },
    { team: 1, alliance: 1 },
    { team: 2, alliance: 1 },
    { team: 3, alliance: 1 },
  ],
  seats: [
    { seat: 0, kind: 'human', team: 0, name: 'Alice', accountId: ACCOUNT_1 },
    { seat: 1, kind: 'ai', team: 1, name: 'AI 2', ai: 'nicowar' },
    { seat: 2, kind: 'ai', team: 2, name: 'AI 3', ai: 'cortex' },
    { seat: 3, kind: 'ai', team: 3, name: 'AI 4', ai: 'maxima', aiConfig: 'aggression=2' },
  ],
  rules: { ...STANDARD_RULES, mapDiscovered: true },
  experiments: [],
};

/** A save continued online, a human sharing control with an AI, every rule changed. */
export const SETUP_SAVE_SHARED: MatchSetup = {
  schemaVersion: 1,
  simVersion: SIM_VERSION,
  seed: 0,
  map: { kind: 'upload', format: 'save', hash: HASH_C },
  teams: [
    { team: 0, alliance: 0 },
    { team: 1, alliance: 0 },
    { team: 2, alliance: 2 },
  ],
  seats: [
    { seat: 0, kind: 'human', team: 0, name: 'Zoë the Builder' },
    { seat: 1, kind: 'ai', team: 0, name: 'AI 1', ai: 'cabino' },
    { seat: 2, kind: 'human', team: 1, name: 'Bob', accountId: ACCOUNT_2 },
    { seat: 3, kind: 'ai', team: 2, name: 'AI 3', ai: 'warrush' },
  ],
  rules: {
    prestigeVictory: false,
    suddenDeathMinutes: 45,
    mapDiscovered: true,
    allyTeamsFixed: false,
    resourceGrowthDisabled: true,
    resourceScarcityLevel: 3,
    instantConstruction: true,
    stockpileStartLevel: 2,
    hungerDisabled: true,
    unitUpgradesDisabled: true,
    glassCannonLevel: 2,
    unitsFearless: true,
    permadeathDisabled: true,
    peacefulMode: true,
    buildingHpLevel: 1,
  },
  experiments: ['guard-area-balancing'],
};

function edit<T>(value: T, change: (copy: T) => void): T {
  const copy = structuredClone(value);
  change(copy);
  return copy;
}

type Mutable = Record<string, unknown>;

export const TICKET_CLAIMS: MatchTicketClaims = {
  iss: 'https://play.example.org',
  aud: MATCH_TICKET_AUDIENCE,
  sub: ACCOUNT_1,
  jti: 'a9b8c7d6-e5f4-4a3b-9c2d-1e0f9a8b7c6d',
  iat: 1790000000,
  nbf: 1790000000,
  exp: 1790000600,
  matchId: MATCH_ID,
  seat: 0,
  accountId: ACCOUNT_1,
  simVersion: SIM_VERSION,
  humanSeats: [0, 1],
  relayUrl: 'wss://relay-eu1.play.example.org/relay',
  entitlements: [],
};

const ROOM_STATE = {
  id: ROOM_ID,
  code: 'K7QX2M',
  inviteUrl: 'https://play.example.org/j/K7QX2M',
  name: "Alice's room",
  visibility: 'link',
  status: 'open',
  hostAccountId: ACCOUNT_1,
  simVersion: SIM_VERSION,
  map: { kind: 'catalog', hash: HASH_A },
  teams: [
    { team: 0, alliance: 0 },
    { team: 1, alliance: 1 },
  ],
  seats: [
    {
      seat: 0,
      team: 0,
      occupant: { kind: 'human', accountId: ACCOUNT_1, displayName: 'Alice', ready: true },
    },
    { seat: 1, team: 1, occupant: { kind: 'open' } },
  ],
  rules: STANDARD_RULES,
  experiments: [],
  members: [
    { accountId: ACCOUNT_1, displayName: 'Alice', kind: 'registered', connected: true, seat: 0 },
  ],
  revision: 4,
  createdAt: NOW,
};

const SELF_ACCOUNT = {
  id: ACCOUNT_1,
  displayName: 'Alice',
  kind: 'registered',
  createdAt: NOW,
  role: 'user',
  status: 'active',
  identities: [{ provider: 'google', linkedAt: NOW }],
  entitlements: [],
};

const MATCH_ASSIGNMENT = {
  matchId: MATCH_ID,
  seat: 0,
  ticket: 'eyJhbGciOiJFZERTQSJ9.e30.c2ln',
  ticketExpiresAt: '2026-10-01T12:10:00Z',
  relayUrl: 'wss://relay-eu1.play.example.org/relay',
  setup: SETUP_CATALOG_1V1,
  mapUrl: `https://play.example.org/api/v1/blobs/maps/${HASH_A}`,
};

const dist = (count: number, mean: number, p50: number, p95: number, max: number) => ({
  count,
  mean,
  p50,
  p95,
  max,
});

/** RelayNetworkSummary v1 of a 30-minute 1v1 (shape as glob2-relay writes it). */
const RELAY_NETWORK = {
  schema: 'RelayNetworkSummary',
  schema_version: 1,
  tick_rate_millihz: 25000,
  end_tick: 45000,
  duration_ms: 1800000,
  bundles: { broadcast: 45000, bytes: 1203412 },
  arbitration: { ticks: 1800, unanimous: 1800, majority: 0, flagged: 0, timed_out: 0 },
  peak_backlog: { pending_ticks: 3, pending_entries: 4, pending_bytes: 96 },
  rejected_peers: 0,
  seats: [
    {
      seat: 0,
      orders: {
        sequenced: 812,
        bytes: 14310,
        deferred: 9,
        defer_ticks: dist(9, 1.111, 1, 2, 2),
        duplicates_ignored: 0,
        dropped: 0,
        flood_rejections: 0,
        max_queued_ahead_ticks: 3,
      },
      voice: { sequenced: 0, bytes: 0 },
      traffic: {
        frames_received: 4630,
        bytes_received: 61980,
        bundles_sent: 45000,
        bundle_bytes_sent: 1203412,
        log_bundles_sent: 0,
        log_bundle_bytes_sent: 0,
      },
      lag_ticks: dist(3600, 6.8, 7, 9, 14),
      checksums: {
        reports: 1800,
        lateness_ticks: dist(1800, 7.1, 7, 9, 15),
        told_to_rejoin: 0,
        flagged: 0,
        late_mismatches: 0,
      },
      connection: {
        connects: 1,
        disconnects: 0,
        grace_used_ms: 0,
        longest_absence_ms: 0,
        left_by_grace: false,
        left_by_quit: true,
        left_tick: 45000,
      },
      rtt_us: dist(900, 41250.5, 40960, 52224, 88010),
    },
    {
      seat: 1,
      orders: {
        sequenced: 640,
        bytes: 11022,
        deferred: 31,
        defer_ticks: dist(31, 1.4, 1, 3, 4),
        duplicates_ignored: 2,
        dropped: 0,
        flood_rejections: 0,
        max_queued_ahead_ticks: 4,
      },
      voice: { sequenced: 12, bytes: 9800 },
      traffic: {
        frames_received: 4410,
        bytes_received: 59105,
        bundles_sent: 44210,
        bundle_bytes_sent: 1190117,
        log_bundles_sent: 790,
        log_bundle_bytes_sent: 13295,
      },
      lag_ticks: dist(3560, 11.2, 10, 19, 162),
      checksums: {
        reports: 1781,
        lateness_ticks: dist(1781, 11.6, 10, 20, 160),
        told_to_rejoin: 0,
        flagged: 0,
        late_mismatches: 0,
      },
      connection: {
        connects: 2,
        disconnects: 1,
        grace_used_ms: 6230,
        longest_absence_ms: 6230,
        left_by_grace: false,
        left_by_quit: true,
        left_tick: 45000,
      },
      rtt_us: dist(897, 121400.2, 114688, 241664, 1310720),
    },
  ],
};

/**
 * ClientNetworkSummary v1 written by an engine (TurnEngineHarness, seat 1: 70 ms
 * latency with jitter and loss, one 3 s outage), series cut to two points.
 */
const CLIENT_NETWORK = {
  catch_up: {
    episodes: 1,
    ticks: 80,
    wall_us: 0,
  },
  desync: {
    flagged: 0,
    rejoins: 0,
    resync_requests: 0,
  },
  elapsed_us: 38630000,
  input_delay_unmatched: 0,
  input_delay_us: {
    count: 30,
    max: 780000,
    mean: 604833.333,
    p50: 606208,
    p95: 770048,
  },
  jitter_buffer: {
    buffered_ticks: {
      count: 871,
      max: 11,
      mean: 7.97,
      p50: 8,
      p95: 10,
    },
    target_ticks: {
      count: 871,
      max: 9,
      mean: 7.998,
      p50: 8,
      p95: 9,
    },
  },
  jitter_us: {
    count: 67,
    max: 260000,
    mean: 176119.403,
    p50: 192512,
    p95: 241664,
  },
  match: {
    final_tick: 951,
    human_seat_mask: 3,
    platform: 'Mac OS X',
    players: 3,
    relay_id: 'relay-eu1-a',
    relay_region: 'eu-west',
    seat: 1,
    sim_version: '125-49-3f9a6c1e8b2d47a05e6f1c2b3a4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f',
    tick_rate_millihz: 25000,
    transport: 'online',
  },
  order_validation: {
    seats: [
      {
        accepted: 33,
        rejected: 0,
        rejected_by_reason: {},
        seat: 0,
        stale: 0,
        voice_rejected: 0,
      },
      {
        accepted: 30,
        rejected: 0,
        rejected_by_reason: {},
        seat: 1,
        stale: 0,
        voice_rejected: 0,
      },
    ],
  },
  orders: {
    dropped_local: 922,
    frames_sent: 30,
    outstanding_max: 3,
    queued_offline: 0,
    resent: 0,
    submitted: 30,
  },
  presence: {
    seats: [
      {
        final_state: 'connected',
        seat: 0,
        time_us: {
          connected: 38320000,
          not_connected: 310000,
        },
        transitions: {
          connected: 1,
        },
      },
      {
        final_state: 'connected',
        seat: 1,
        time_us: {
          connected: 37430000,
          lagging: 890000,
          not_connected: 310000,
        },
        transitions: {
          connected: 2,
          lagging: 1,
        },
      },
    ],
    transitions: 4,
  },
  reconnects: {
    count: 1,
    down_now: false,
    downtime_us: 2620000,
    longest_downtime_us: 2620000,
  },
  reloads: {
    count: 0,
    fast_forward_ticks: 0,
    fast_forward_us: 0,
    load_us: 0,
  },
  rtt_us: {
    count: 67,
    max: 450000,
    mean: 230223.881,
    p50: 200704,
    p95: 434176,
  },
  schema: 'ClientNetworkSummary',
  schema_version: 1,
  series: {
    dropped_points: 0,
    interval_us: 5000000,
    points: [
      {
        buffered_ticks: {
          count: 114,
          max: 9,
          mean: 6.114,
          p50: 7,
          p95: 8,
        },
        bytes_received: 1345,
        bytes_sent: 356,
        catch_up_ticks: 0,
        downtime_us: 0,
        end_tick: 114,
        end_us: 5035000,
        frames_received: 75,
        frames_sent: 22,
        input_delay_us: {
          count: 7,
          max: 780000,
          mean: 587857.143,
          p50: 540672,
          p95: 780000,
        },
        jitter_us: {
          count: 9,
          max: 240000,
          mean: 233333.333,
          p50: 233472,
          p95: 240000,
        },
        live_ticks: 114,
        mean_nudge: -0.03,
        orders_submitted: 7,
        presence_transitions: 2,
        reconnects: 0,
        rtt_us: {
          count: 9,
          max: 450000,
          mean: 242222.222,
          p50: 208896,
          p95: 450000,
        },
        stall_us: {
          count: 1,
          max: 75000,
          mean: 75000.0,
          p50: 75000,
          p95: 75000,
        },
        start_tick: 0,
        start_us: 0,
        target_ticks: {
          count: 114,
          max: 8,
          mean: 7.579,
          p50: 8,
          p95: 8,
        },
        ticks_executed: 114,
        ticks_faster: 8,
        ticks_slower: 106,
        voice_received: 0,
        voice_sent: 0,
      },
      {
        buffered_ticks: {
          count: 126,
          max: 10,
          mean: 8.357,
          p50: 9,
          p95: 10,
        },
        bytes_received: 1196,
        bytes_sent: 291,
        catch_up_ticks: 0,
        downtime_us: 0,
        end_tick: 240,
        end_us: 10060000,
        frames_received: 77,
        frames_sent: 20,
        input_delay_us: {
          count: 4,
          max: 645000,
          mean: 621250.0,
          p50: 606208,
          p95: 645000,
        },
        jitter_us: {
          count: 9,
          max: 230000,
          mean: 226666.667,
          p50: 230000,
          p95: 230000,
        },
        live_ticks: 126,
        mean_nudge: 0.003,
        orders_submitted: 5,
        presence_transitions: 0,
        reconnects: 0,
        rtt_us: {
          count: 9,
          max: 440000,
          mean: 265555.556,
          p50: 200704,
          p95: 440000,
        },
        stall_us: {
          count: 0,
          max: 0,
          mean: 0.0,
          p50: 0,
          p95: 0,
        },
        start_tick: 114,
        start_us: 5035000,
        target_ticks: {
          count: 126,
          max: 8,
          mean: 8.0,
          p50: 8,
          p95: 8,
        },
        ticks_executed: 126,
        ticks_faster: 41,
        ticks_slower: 11,
        voice_received: 0,
        voice_sent: 0,
      },
    ],
  },
  stalls: {
    count: 2,
    duration_us: {
      count: 2,
      max: 3245000,
      mean: 1660000.0,
      p50: 75000,
      p95: 3245000,
    },
    longest_us: 3245000,
    total_us: 3320000,
  },
  tick_rate_nudge: {
    live_ticks: 871,
    max_abs: 0.05,
    mean: -0.001,
    ticks_faster: 232,
    ticks_slower: 193,
  },
  ticks: {
    executed: 951,
    live: 871,
  },
  traffic: {
    bundle_bytes: 6654,
    bundle_entries: 63,
    bundles_received: 430,
    bytes_received: 8423,
    bytes_sent: 1969,
    frames_received: 537,
    frames_sent: 141,
  },
  voice: {
    received: 0,
    received_bytes: 0,
    sent: 0,
    sent_bytes: 0,
  },
} as const;

const VERIFIED_OUTCOME = {
  finalTick: 45000,
  teams: [
    { team: 0, outcome: 'won', prestige: 210 },
    { team: 1, outcome: 'lost', eliminatedTick: 44990, prestige: 35 },
  ],
  resultHash: HASH_D,
  replayHash: HASH_C,
};

export const fixtureCases: FixtureCase[] = [
  // ------------------------------------------------------------ SimVersion
  {
    schema: 'SimVersion',
    name: 'current',
    valid: true,
    note: 'A sim version.',
    value: SIM_VERSION,
  },
  {
    schema: 'SimVersion',
    name: 'short-data-hash',
    valid: false,
    stage: 'schema',
    note: 'dataHash must be 64 lowercase hex digits.',
    value: { ...SIM_VERSION, dataHash: 'abc123' },
  },
  // ------------------------------------------------------------ MatchSetup
  {
    schema: 'MatchSetup',
    name: 'catalog-1v1',
    valid: true,
    note: 'Two humans on a catalog map, standard rules.',
    value: SETUP_CATALOG_1V1,
  },
  {
    schema: 'MatchSetup',
    name: 'generated-human-vs-ais',
    valid: true,
    note: 'One human against three allied AIs on a generated map; revealed map; AI runtime config.',
    value: SETUP_GENERATED_FFA,
  },
  {
    schema: 'MatchSetup',
    name: 'save-shared-control-all-rules',
    valid: true,
    note: 'Uploaded save; human + AI share team 0; every rule non-default; an experiment; non-ASCII name.',
    value: SETUP_SAVE_SHARED,
  },
  {
    schema: 'MatchSetup',
    name: 'missing-rules',
    valid: false,
    stage: 'schema',
    note: 'Every field is required; there are no defaults.',
    value: edit(SETUP_CATALOG_1V1 as unknown as Mutable, (s) => delete s['rules']),
  },
  {
    schema: 'MatchSetup',
    name: 'unknown-ai',
    valid: false,
    stage: 'schema',
    note: 'AI ids are the closed CLI-name set.',
    value: edit(SETUP_GENERATED_FFA, (s) => {
      (s.seats[1] as Mutable)['ai'] = 'skynet';
    }),
  },
  {
    schema: 'MatchSetup',
    name: 'javascript-ai-unsupported',
    valid: false,
    stage: 'schema',
    note: 'JavaScript controllers are not accepted online yet.',
    value: edit(SETUP_GENERATED_FFA, (s) => {
      (s.seats[1] as Mutable)['ai'] = 'javascript';
    }),
  },
  {
    schema: 'MatchSetup',
    name: 'unknown-property',
    valid: false,
    stage: 'schema',
    note: 'MatchSetup rejects unknown properties: an unknown rule must not be silently ignored.',
    value: edit(SETUP_CATALOG_1V1 as unknown as Mutable, (s) => {
      (s['rules'] as Mutable)['lowGravity'] = true;
    }),
  },
  {
    schema: 'MatchSetup',
    name: 'seed-out-of-range',
    valid: false,
    stage: 'schema',
    note: 'seed is a Uint32.',
    value: { ...SETUP_CATALOG_1V1, seed: 4294967296 },
  },
  {
    schema: 'MatchSetup',
    name: 'uppercase-map-hash',
    valid: false,
    stage: 'schema',
    note: 'Hashes are lowercase hex.',
    value: { ...SETUP_CATALOG_1V1, map: { kind: 'catalog', hash: HASH_A.toUpperCase() } },
  },
  {
    schema: 'MatchSetup',
    name: 'future-schema-version',
    valid: false,
    stage: 'schema',
    note: 'An unknown schemaVersion must be rejected, not guessed at.',
    value: { ...SETUP_CATALOG_1V1, schemaVersion: 2 },
  },
  {
    schema: 'MatchSetup',
    name: 'rule-level-out-of-range',
    valid: false,
    stage: 'schema',
    note: 'glassCannonLevel is 0..2.',
    value: { ...SETUP_CATALOG_1V1, rules: { ...STANDARD_RULES, glassCannonLevel: 3 } },
  },
  {
    schema: 'MatchSetup',
    name: 'generated-without-hash',
    valid: false,
    stage: 'schema',
    note: 'A match needs the generated map hash; generation happens before start.',
    value: edit(SETUP_GENERATED_FFA as unknown as Mutable, (s) => {
      delete (s['map'] as Mutable)['hash'];
    }),
  },
  {
    schema: 'MatchSetup',
    name: 'seats-not-contiguous',
    valid: false,
    stage: 'semantic',
    note: 'Seats are numbered 0..k-1 in order.',
    value: edit(SETUP_CATALOG_1V1, (s) => {
      s.seats[1]!.seat = 2;
    }),
  },
  {
    schema: 'MatchSetup',
    name: 'seat-on-missing-team',
    valid: false,
    stage: 'semantic',
    note: 'A seat must reference one of the listed teams.',
    value: edit(SETUP_CATALOG_1V1, (s) => {
      s.seats[1]!.team = 5;
    }),
  },
  {
    schema: 'MatchSetup',
    name: 'teams-out-of-order',
    valid: false,
    stage: 'semantic',
    note: 'Teams are listed 0..n-1 in order.',
    value: edit(SETUP_CATALOG_1V1, (s) => {
      s.teams = [
        { team: 1, alliance: 1 },
        { team: 0, alliance: 0 },
      ];
    }),
  },
  {
    schema: 'MatchSetup',
    name: 'name-too-long-in-bytes',
    valid: false,
    stage: 'semantic',
    note: '20 characters but 40 UTF-8 bytes; BasePlayer names are limited to 32 bytes.',
    value: edit(SETUP_CATALOG_1V1, (s) => {
      s.seats[0]!.name = 'é'.repeat(20);
    }),
  },
  {
    schema: 'MatchSetup',
    name: 'account-in-two-seats',
    valid: false,
    stage: 'semantic',
    note: 'An account holds at most one seat.',
    value: edit(SETUP_CATALOG_1V1, (s) => {
      (s.seats[1] as Mutable)['accountId'] = ACCOUNT_1;
    }),
  },
  {
    schema: 'MatchSetup',
    name: 'generator-team-count-mismatch',
    valid: false,
    stage: 'semantic',
    note: 'The generator "teams" control must equal the number of setup teams.',
    value: edit(SETUP_GENERATED_FFA, (s) => {
      if (s.map.kind === 'generated') s.map.generator.params['teams'] = 3;
    }),
  },
  // ---------------------------------------------------------------- Tickets
  {
    schema: 'MatchTicketClaims',
    name: 'player-ticket',
    valid: true,
    note: 'Claims of the ticket in fixtures/tickets/valid.jwt.',
    value: TICKET_CLAIMS,
  },
  {
    schema: 'MatchTicketClaims',
    name: 'missing-match-id',
    valid: false,
    stage: 'schema',
    note: 'matchId is required.',
    value: edit(TICKET_CLAIMS as unknown as Mutable, (c) => delete c['matchId']),
  },
  {
    schema: 'MatchTicketClaims',
    name: 'seat-out-of-range',
    valid: false,
    stage: 'schema',
    note: 'Seats are 0..11.',
    value: { ...TICKET_CLAIMS, seat: 12 },
  },
  {
    schema: 'MatchTicketClaims',
    name: 'wrong-audience',
    valid: false,
    stage: 'schema',
    note: 'aud must be glob2-relay.',
    value: { ...TICKET_CLAIMS, aud: 'glob2-api' },
  },
  // ------------------------------------------------------------------ Relay
  {
    schema: 'RelayRegistration',
    name: 'startup',
    valid: true,
    note: 'Relay start-up registration.',
    value: {
      relayId: 'relay-eu1-a',
      publicUrl: 'wss://relay-eu1.play.example.org/relay',
      region: 'eu-west',
      build: 'glob2-relay 0.9.25+3f9a6c1',
      turnProtocol: 1,
      capacity: { maxMatches: 200 },
      load: { matches: 0, connections: 0 },
      draining: false,
    },
  },
  {
    schema: 'RelayRegistration',
    name: 'bad-region',
    valid: false,
    stage: 'schema',
    note: 'Regions are lowercase ids.',
    value: {
      relayId: 'relay-eu1-a',
      publicUrl: 'wss://relay-eu1.play.example.org/relay',
      region: 'EU West',
      build: 'x',
      turnProtocol: 1,
      capacity: { maxMatches: 200 },
      load: { matches: 0, connections: 0 },
      draining: false,
    },
  },
  {
    schema: 'RelayHeartbeat',
    name: 'busy',
    valid: true,
    note: 'Heartbeat with one active match.',
    value: {
      relayId: 'relay-eu1-a',
      load: { matches: 1, connections: 2, cpu: 0.12 },
      draining: false,
      activeMatchIds: [MATCH_ID],
    },
  },
  {
    schema: 'RelayMatchEnded',
    name: 'completed',
    valid: true,
    note: 'A completed match with one reconnect.',
    value: {
      matchId: MATCH_ID,
      relayId: 'relay-eu1-a',
      simVersion: SIM_VERSION,
      startedAt: '2026-10-01T12:00:05Z',
      endedAt: '2026-10-01T12:30:05Z',
      finalTick: 45000,
      reason: 'completed',
      seats: [
        { seat: 0, disconnects: 0, droppedForDesync: false },
        { seat: 1, disconnects: 1, droppedForDesync: false },
      ],
      desync: { flagged: false, minoritySeats: [] },
      record: { sha256: HASH_D, size: 183422, formatVersion: 1 },
    },
  },
  {
    schema: 'RelayMatchEnded',
    name: 'unknown-reason',
    valid: false,
    stage: 'schema',
    note: 'reason is completed, abandoned or aborted.',
    value: {
      matchId: MATCH_ID,
      relayId: 'relay-eu1-a',
      simVersion: SIM_VERSION,
      startedAt: '2026-10-01T12:00:05Z',
      endedAt: '2026-10-01T12:30:05Z',
      finalTick: 45000,
      reason: 'timeout',
      seats: [],
      desync: { flagged: false, minoritySeats: [] },
      record: { sha256: HASH_D, size: 1, formatVersion: 1 },
    },
  },
  {
    schema: 'RelayMatchEnded',
    name: 'with-network',
    valid: true,
    note: 'A relay that measures the network adds its RelayNetworkSummary (optional).',
    value: {
      matchId: MATCH_ID,
      relayId: 'relay-eu1-a',
      simVersion: SIM_VERSION,
      startedAt: '2026-10-01T12:00:05Z',
      endedAt: '2026-10-01T12:30:05Z',
      finalTick: 45000,
      reason: 'completed',
      seats: [
        { seat: 0, disconnects: 0, quitTick: 45000, droppedForDesync: false },
        { seat: 1, disconnects: 1, quitTick: 45000, droppedForDesync: false },
      ],
      desync: { flagged: false, minoritySeats: [] },
      record: { sha256: HASH_D, size: 183422, formatVersion: 1 },
      network: RELAY_NETWORK,
    },
  },
  {
    schema: 'RelayNetworkSummary',
    name: 'one-vs-one',
    valid: true,
    note: 'Per-seat relay measurements of a 30-minute match; seat 1 reconnected once.',
    value: RELAY_NETWORK,
  },
  {
    schema: 'RelayNetworkSummary',
    name: 'lan-host-without-rtt',
    valid: true,
    note: 'rtt_us is optional: a LAN host measures no round trip. Unknown fields are allowed (newer engines).',
    value: {
      ...RELAY_NETWORK,
      future_counter: 3,
      seats: RELAY_NETWORK.seats.map(({ rtt_us: _rtt, ...seat }) => seat),
    },
  },
  {
    schema: 'RelayNetworkSummary',
    name: 'version-2',
    valid: false,
    stage: 'schema',
    note: 'Version 1 readers refuse other versions; a v2 changes field meanings.',
    value: { ...RELAY_NETWORK, schema_version: 2 },
  },
  {
    schema: 'RelayNetworkSummary',
    name: 'negative-count',
    valid: false,
    stage: 'schema',
    note: 'Counters are non-negative integers.',
    value: {
      ...RELAY_NETWORK,
      seats: [
        {
          ...RELAY_NETWORK.seats[0],
          connection: { ...RELAY_NETWORK.seats[0]!.connection, disconnects: -1 },
        },
      ],
    },
  },
  {
    schema: 'ClientNetworkSummary',
    name: 'online-seat',
    valid: true,
    note: 'A client summary as the engine writes it next to the replay. Not uploaded anywhere.',
    value: CLIENT_NETWORK,
  },
  {
    schema: 'ClientNetworkSummary',
    name: 'without-series',
    valid: true,
    note: 'GLOB2_NET_SUMMARY leaves the series out; order_validation is null without the order check.',
    value: { ...CLIENT_NETWORK, series: undefined, order_validation: null },
  },
  {
    schema: 'ClientNetworkSummary',
    name: 'unknown-transport',
    valid: false,
    stage: 'schema',
    note: 'transport is lan or online.',
    value: { ...CLIENT_NETWORK, match: { ...CLIENT_NETWORK.match, transport: 'tcp' } },
  },
  {
    schema: 'RelayRecordReceipt',
    name: 'stored',
    valid: true,
    note: 'Answer to PUT /internal/v1/matches/{matchId}/record.',
    value: { matchId: MATCH_ID, sha256: HASH_D, size: 183422 },
  },
  {
    schema: 'RelayMatchEndedResponse',
    name: 'duplicate',
    valid: true,
    note: 'A repeated end report (relay spool retry) is acknowledged without changes.',
    value: { ok: true, duplicate: true },
  },
  // --------------------------------------------------------------- Realtime
  {
    schema: 'RealtimeRequest',
    name: 'hello',
    valid: true,
    note: 'The first frame on a socket.',
    value: {
      type: 'request',
      id: '1',
      method: 'session.hello',
      params: {
        protocol: 1,
        client: { platform: 'desktop', version: '0.9.25', simVersion: SIM_VERSION },
      },
    },
  },
  {
    schema: 'RealtimeRoomKickParams',
    name: 'kick',
    valid: true,
    note: 'The host removes a member; they cannot rejoin the room for 10 minutes.',
    value: { roomId: ROOM_ID, accountId: ACCOUNT_2 },
  },
  {
    schema: 'RealtimeRoomKickParams',
    name: 'missing-account',
    valid: false,
    stage: 'schema',
    note: 'A kick names the member.',
    value: { roomId: ROOM_ID },
  },
  {
    schema: 'RealtimeRequest',
    name: 'missing-id',
    valid: false,
    stage: 'schema',
    note: 'Requests need a correlation id.',
    value: { type: 'request', method: 'room.join', params: { code: 'K7QX2M' } },
  },
  {
    schema: 'RealtimeResponse',
    name: 'ok',
    valid: true,
    note: 'Successful response.',
    value: { type: 'response', id: '7', ok: true, result: { room: ROOM_STATE } },
  },
  {
    schema: 'RealtimeResponse',
    name: 'error',
    valid: true,
    note: 'Failed response.',
    value: {
      type: 'response',
      id: '7',
      ok: false,
      error: { code: 'update_required', message: 'This instance needs a newer game version.' },
    },
  },
  {
    schema: 'RealtimeResponse',
    name: 'unknown-error-code',
    valid: false,
    stage: 'schema',
    note: 'Error codes are a closed set.',
    value: { type: 'response', id: '7', ok: false, error: { code: 'oops', message: 'x' } },
  },
  {
    schema: 'RealtimeServerMessage',
    name: 'room-state-event',
    valid: true,
    note: 'Event frame.',
    value: { type: 'event', event: 'room.state', data: { room: ROOM_STATE } },
  },
  {
    schema: 'RealtimeSessionHelloParams',
    name: 'with-token',
    valid: true,
    note: 'Hello from a signed-in browser client.',
    value: {
      protocol: 1,
      client: { platform: 'browser', version: '0.9.25', simVersion: SIM_VERSION },
      accessToken: 'eyJhbGciOiJFZERTQSJ9.e30.c2ln',
    },
  },
  {
    schema: 'RealtimeSessionHelloParams',
    name: 'future-protocol',
    valid: false,
    stage: 'schema',
    note: 'protocol must be 1.',
    value: {
      protocol: 2,
      client: { platform: 'browser', version: '0.9.25', simVersion: SIM_VERSION },
    },
  },
  {
    schema: 'RealtimeSessionHelloResult',
    name: 'guest',
    valid: true,
    note: 'Hello answered for a signed-in guest.',
    value: {
      sessionId: '2a3b4c5d-6e7f-4a8b-9c0d-1e2f3a4b5c6d',
      serverTime: NOW,
      simSupported: true,
      account: { ...SELF_ACCOUNT, kind: 'guest', identities: [] },
    },
  },
  {
    schema: 'RealtimeAuthHandoffBeginResult',
    name: 'attempt',
    valid: true,
    note: 'Browser sign-in attempt.',
    value: {
      attemptId: '3b4c5d6e-7f80-4a9b-8c1d-2e3f4a5b6c7d',
      signInUrl: 'https://play.example.org/signin?attempt=3b4c5d6e-7f80-4a9b-8c1d-2e3f4a5b6c7d',
      confirmationCode: 'KQ7M2X',
      expiresAt: '2026-10-01T12:10:00Z',
      resumeToken: 'Zm9vYmFyYmF6cXV4cXV1eGNvcmdlZ3JhdWx0Z2FycGx',
    },
  },
  {
    schema: 'RealtimeEventAuthHandoffCompleted',
    name: 'completed',
    valid: true,
    note: "Sign-in pushed to the waiting socket, switching to the identity's account.",
    value: {
      attemptId: '3b4c5d6e-7f80-4a9b-8c1d-2e3f4a5b6c7d',
      linked: false,
      session: {
        account: SELF_ACCOUNT,
        tokens: {
          tokenType: 'Bearer',
          accessToken: 'eyJhbGciOiJFZERTQSJ9.e30.c2ln',
          accessTokenExpiresAt: '2026-10-01T12:15:00Z',
          refreshToken: 'rt_9Zt2v0Yb8k1mQ3s5u7w9y1A3C5E7G9I1',
          refreshTokenExpiresAt: '2026-12-30T12:00:00Z',
        },
      },
    },
  },
  {
    schema: 'RealtimeRoomJoinParams',
    name: 'by-code',
    valid: true,
    note: 'Join by invite code.',
    value: { code: 'K7QX2M' },
  },
  {
    schema: 'RealtimeRoomJoinParams',
    name: 'with-regions',
    valid: true,
    note: 'Join by invite code, reporting relay round trips for match placement.',
    value: { code: 'K7QX2MWP4D', regions: [{ region: 'eu-west', rttMs: 41 }] },
  },
  {
    schema: 'RealtimeRoomJoinParams',
    name: 'code-with-punctuation',
    valid: false,
    stage: 'schema',
    note: 'Codes are 6-16 letters and digits.',
    value: { code: 'K7-QX2M' },
  },
  {
    schema: 'RealtimeRoomCreateParams',
    name: 'generated-map',
    valid: true,
    note: 'Create a link-only room on a generated map (hash filled in later).',
    value: {
      name: "Alice's room",
      visibility: 'link',
      map: {
        kind: 'generated',
        generator: (SETUP_GENERATED_FFA.map as { generator: unknown }).generator,
      },
    },
  },
  {
    schema: 'RealtimeRoomSetSeatParams',
    name: 'add-ai',
    valid: true,
    note: 'Host puts an AI in seat 1.',
    value: { roomId: ROOM_ID, seat: 1, occupant: { kind: 'ai', ai: 'cortex' } },
  },
  {
    schema: 'RealtimeRoomSetSeatParams',
    name: 'lock',
    valid: true,
    note: 'Host closes an empty seat.',
    value: { roomId: ROOM_ID, seat: 2, occupant: { kind: 'locked' } },
  },
  {
    schema: 'RealtimeRoomSetSeatParams',
    name: 'human-for-someone-else',
    valid: false,
    stage: 'schema',
    note: 'Nobody can seat another player; players take seats themselves (kind self).',
    value: { roomId: ROOM_ID, seat: 1, occupant: { kind: 'human', accountId: ACCOUNT_2 } },
  },
  {
    schema: 'RealtimeMatchReconnectParams',
    name: 'relay-refused',
    valid: true,
    note: 'The assigned relay refused the new match (Reject 5); ask for another relay.',
    value: { matchId: MATCH_ID, relayUnavailable: true },
  },
  {
    schema: 'RealtimeQueueJoinParams',
    name: 'with-regions',
    valid: true,
    note: 'Join a queue with relay round-trip probes.',
    value: {
      queueId: 'ranked-1v1',
      regions: [
        { region: 'eu-west', rttMs: 32 },
        { region: 'us-east', rttMs: 110 },
      ],
    },
  },
  {
    schema: 'RealtimeQueueJoinParams',
    name: 'no-ai-opponent',
    valid: true,
    note: 'Join a queue but opt out of AI backfill.',
    value: {
      queueId: 'ranked-1v1',
      regions: [{ region: 'eu-west', rttMs: 32 }],
      allowAiOpponent: false,
    },
  },
  {
    schema: 'RealtimeQueueRespondParams',
    name: 'accept',
    valid: true,
    note: 'Accept a proposed ranked match.',
    value: { proposalId: '0b6a7f6e-8d1c-4a59-9a43-2f0c3d1e5b77', accept: true },
  },
  {
    schema: 'RealtimeEventQueueProposal',
    name: 'ranked-accept',
    valid: true,
    note: 'A ranked 1v1 group waiting for both players to accept.',
    value: {
      proposalId: '0b6a7f6e-8d1c-4a59-9a43-2f0c3d1e5b77',
      ticketId: '5d0f2c43-6a3e-4c8e-b8f1-9e2a7c4d3b10',
      queueId: 'ranked-1v1',
      requiresAccept: true,
      expiresAt: '2026-10-01T12:00:10Z',
      humans: 2,
      ais: 0,
    },
  },
  {
    schema: 'RealtimeEventQueueProposal',
    name: 'ranked-accept-with-seats',
    valid: true,
    note: 'The same prompt with the map and seats the client shows; resent when someone accepts.',
    value: {
      proposalId: '0b6a7f6e-8d1c-4a59-9a43-2f0c3d1e5b77',
      ticketId: '5d0f2c43-6a3e-4c8e-b8f1-9e2a7c4d3b10',
      queueId: 'ranked-1v1',
      requiresAccept: true,
      expiresAt: '2026-10-01T12:00:10Z',
      humans: 2,
      ais: 0,
      rated: true,
      backfilled: false,
      region: 'eu-west',
      map: { generatorId: 'even-ground', width: 128, height: 128 },
      seats: [
        {
          slot: 0,
          side: 0,
          kind: 'human',
          displayName: 'Bradley',
          rating: 1528,
          provisional: false,
          response: 'accepted',
          you: true,
        },
        {
          slot: 1,
          side: 1,
          kind: 'human',
          displayName: 'Kestrel',
          rating: 1540,
          response: 'pending',
        },
      ],
    },
  },
  {
    schema: 'RealtimeEventQueueProposal',
    name: 'ai-backfill',
    valid: true,
    note: 'No person was found: an AI takes the seat and the match starts without a prompt.',
    value: {
      proposalId: '0b6a7f6e-8d1c-4a59-9a43-2f0c3d1e5b77',
      ticketId: '5d0f2c43-6a3e-4c8e-b8f1-9e2a7c4d3b10',
      queueId: 'ranked-1v1',
      requiresAccept: false,
      humans: 1,
      ais: 1,
      rated: true,
      backfilled: true,
      map: { generatorId: 'symmetric-arena', width: 128, height: 128 },
      seats: [
        {
          slot: 0,
          side: 0,
          kind: 'human',
          displayName: 'Bradley',
          rating: 1528,
          response: 'not_required',
          you: true,
        },
        {
          slot: 1,
          side: 1,
          kind: 'ai',
          displayName: 'Cortex',
          ai: 'cortex',
          rating: 1601,
          response: 'not_required',
        },
      ],
    },
  },
  {
    schema: 'RealtimeEventQueueProposal',
    name: 'seat-bad-response',
    valid: false,
    stage: 'schema',
    note: 'Seat responses are pending, accepted, declined, timeout or not_required.',
    value: {
      proposalId: '0b6a7f6e-8d1c-4a59-9a43-2f0c3d1e5b77',
      ticketId: '5d0f2c43-6a3e-4c8e-b8f1-9e2a7c4d3b10',
      queueId: 'ranked-1v1',
      requiresAccept: true,
      humans: 2,
      ais: 0,
      seats: [{ slot: 0, side: 0, kind: 'human', displayName: 'Bradley', response: 'maybe' }],
    },
  },
  {
    schema: 'RealtimeEventQueueStatus',
    name: 'searching',
    valid: true,
    note: 'Search progress with the rating range, region and the AI that would fill the seat.',
    value: {
      ticketId: '5d0f2c43-6a3e-4c8e-b8f1-9e2a7c4d3b10',
      queueId: 'ranked-1v1',
      waitedSeconds: 42,
      ratingWindow: 100,
      aiBackfillAt: '2026-10-01T12:01:00Z',
      ratingRange: { min: 1430, max: 1630 },
      rating: 1528,
      provisional: false,
      region: 'eu-west',
      rttMs: 28,
      allowAiOpponent: true,
      backfillAi: { ai: 'cortex', rating: 1601 },
      typicalWaitSeconds: 40,
    },
  },
  {
    schema: 'RealtimeQueueUpdateParams',
    name: 'disallow-ai',
    valid: true,
    note: 'Untick "Allow an AI opponent" while searching.',
    value: { ticketId: '5d0f2c43-6a3e-4c8e-b8f1-9e2a7c4d3b10', allowAiOpponent: false },
  },
  {
    schema: 'RealtimeMatchRematchParams',
    name: 'after-quick-match',
    valid: true,
    note: 'Ask for (or join) the rematch room of a quick match.',
    value: { matchId: MATCH_ID, regions: [{ region: 'eu-west', rttMs: 28 }] },
  },
  {
    schema: 'RealtimeEventMatchRematchOffered',
    name: 'offered',
    valid: true,
    note: 'The other player opened the rematch room.',
    value: { matchId: MATCH_ID, roomId: ROOM_ID, code: 'K7QX4M', host: 'Kestrel' },
  },
  {
    schema: 'RelayRegionList',
    name: 'two-regions',
    valid: true,
    note: 'Regions a client probes before queueing.',
    value: {
      items: [
        { region: 'eu-west', probeUrl: 'https://play.example.org/relay/relay-1', relays: 1 },
        { region: 'us-east', probeUrl: 'https://us.play.example.org/relay/relay-2', relays: 2 },
      ],
    },
  },
  {
    schema: 'RealtimeEventQueueProposalEnded',
    name: 'removed-after-decline',
    valid: true,
    note: 'The client declined and is blocked from queueing for a minute.',
    value: {
      proposalId: '0b6a7f6e-8d1c-4a59-9a43-2f0c3d1e5b77',
      ticketId: '5d0f2c43-6a3e-4c8e-b8f1-9e2a7c4d3b10',
      outcome: 'removed',
      reason: 'declined',
      cooldownUntil: '2026-10-01T12:01:10Z',
    },
  },
  {
    schema: 'RealtimeEventMatchStart',
    name: 'assignment',
    valid: true,
    note: 'match.start pushed to a seated client.',
    value: MATCH_ASSIGNMENT,
  },
  {
    schema: 'RealtimeEventMatchStart',
    name: 'assignment-rated-preview',
    valid: true,
    note: 'A rated queue match: the map title and the rating preview the results screen greys out until verified.',
    value: {
      ...MATCH_ASSIGNMENT,
      mapTitle: 'Even Ground',
      ratingPreview: {
        ladder: 'ranked-1v1',
        before: 1528,
        ifWon: 1543,
        ifLost: 1511,
        provisional: false,
      },
    },
  },
  {
    schema: 'RealtimeEventMatchStart',
    name: 'assignment-preview-missing-ifLost',
    valid: false,
    stage: 'schema',
    note: 'A rating preview carries both outcomes.',
    value: {
      ...MATCH_ASSIGNMENT,
      ratingPreview: { ladder: 'ranked-1v1', before: 1528, ifWon: 1543, provisional: true },
    },
  },
  {
    schema: 'RealtimeEventMatchStart',
    name: 'assignment-with-relay',
    valid: true,
    note: 'Newer servers name the relay and its region (network telemetry context).',
    value: { ...MATCH_ASSIGNMENT, relayId: 'relay-eu1-a', relayRegion: 'eu-west' },
  },
  {
    schema: 'RealtimeEventMatchStart',
    name: 'assignment-with-bad-setup',
    valid: false,
    stage: 'semantic',
    note: 'The embedded setup must pass MatchSetup semantics.',
    value: edit(MATCH_ASSIGNMENT, (a) => {
      a.setup = edit(SETUP_CATALOG_1V1, (s) => {
        s.seats[1]!.team = 5;
      });
    }),
  },
  // ------------------------------------------------------------------- REST
  {
    schema: 'GuestSignInRequest',
    name: 'returning-guest',
    valid: true,
    note: 'Returning guest presents its device credential.',
    value: { deviceCredential: 'q2Vx0YbZ8k1mQ3s5u7w9y1A3C5E7G9I1K3M5O7Q9S1U', platform: 'android' },
  },
  {
    schema: 'GuestSignInRequest',
    name: 'short-credential',
    valid: false,
    stage: 'schema',
    note: 'Device credentials are 256-bit base64url (43 characters).',
    value: { deviceCredential: 'abc', platform: 'android' },
  },
  {
    schema: 'InstanceInfo',
    name: 'official',
    valid: true,
    note: 'Instance description.',
    value: {
      name: 'Globulation 2',
      origin: 'https://play.example.org',
      realtimeUrl: 'wss://play.example.org/realtime',
      supportedSimVersions: [SIM_VERSION],
      authProviders: [
        { id: 'google', kind: 'oidc', displayName: 'Google' },
        { id: 'apple', kind: 'apple', displayName: 'Apple' },
      ],
      queues: [
        { id: 'ranked-1v1', name: 'Ranked 1v1', mode: '1v1', rated: true, aiBackfillSeconds: 90 },
      ],
      guestsAllowed: true,
    },
  },
  { schema: 'RoomState', name: 'open-room', valid: true, note: 'A room.', value: ROOM_STATE },
  {
    schema: 'RoomState',
    name: 'generating-map-locked-seat',
    valid: true,
    note: 'A three-colony generated map still generating; the host locked seat 2.',
    value: {
      ...ROOM_STATE,
      map: {
        kind: 'generated',
        generator: {
          generatorId: 'even-ground',
          revision: 2,
          params: { width: 7, height: 7, teams: 3 },
          seed: 77,
          candidates: 5,
          startingUnitLevel: 0,
        },
      },
      mapStatus: 'pending',
      teams: [
        { team: 0, alliance: 0 },
        { team: 1, alliance: 1 },
        { team: 2, alliance: 2 },
      ],
      seats: [...ROOM_STATE.seats, { seat: 2, team: 2, occupant: { kind: 'open' }, locked: true }],
    },
  },
  {
    schema: 'InviteInfo',
    name: 'open-room',
    valid: true,
    note: 'What an invite link points at.',
    value: {
      code: 'K7QX2MWP4D',
      status: 'open',
      roomName: "Alice's room",
      hostDisplayName: 'Alice',
      simVersion: SIM_VERSION,
      seatsTotal: 2,
      seatsTaken: 1,
      inviteUrl: 'https://play.example.org/j/K7QX2MWP4D',
    },
  },
  {
    schema: 'MapVersionInfo',
    name: 'pending',
    valid: true,
    note: 'A catalog version just uploaded: no map facts until an engine agent validated it.',
    value: {
      hash: HASH_A,
      size: 48211,
      simVersion: SIM_VERSION,
      validation: 'pending',
      preview: 'pending',
      downloadUrl: `https://play.example.org/api/v1/maps/${MAP_ID}/versions/${HASH_A}/file`,
      createdAt: NOW,
    },
  },
  {
    schema: 'MapDetail',
    name: 'public-map',
    valid: true,
    note: 'GET /api/v1/maps/{id}: a public map with one valid, previewed version.',
    value: {
      map: MAP_INFO,
      versions: [MAP_INFO.latestVersion],
      viewer: { owner: false, moderator: false, liked: true, reported: false },
    },
  },
  {
    schema: 'MapInfo',
    name: 'unknown-visibility',
    valid: false,
    stage: 'schema',
    note: 'Maps are public, unlisted or private.',
    value: { ...MAP_INFO, visibility: 'friends' },
  },
  {
    schema: 'CreateMapRequest',
    name: 'title-only',
    valid: true,
    note: 'Everything but the title is optional; visibility defaults to unlisted.',
    value: { title: 'Two Rivers' },
  },
  {
    schema: 'CreateMapRequest',
    name: 'unknown-field',
    valid: false,
    stage: 'schema',
    note: 'Request bodies are strict.',
    value: { title: 'Two Rivers', hidden: true },
  },
  {
    schema: 'ResolveMapReportRequest',
    name: 'resolve-and-hide',
    valid: true,
    note: 'A moderator upholds a report and hides the map.',
    value: { status: 'resolved', note: 'Offensive title.', hideMap: true },
  },
  {
    schema: 'MapUpload',
    name: 'valid-save',
    valid: true,
    note: 'A validated save with its players, for reteaming.',
    value: {
      id: '3e2d1c0b-9a8f-4e7d-8c6b-5a4f3e2d1c0b',
      format: 'save',
      sha256: HASH_C,
      size: 734211,
      simVersion: SIM_VERSION,
      status: 'valid',
      fileName: 'evening game.sgl',
      map: { width: 128, height: 128, teamCount: 2 },
      versionMinor: 125,
      title: 'Evening game',
      players: [
        { name: 'Alice', team: 0, kind: 'human' },
        { name: 'Bob', team: 1, kind: 'human' },
      ],
      downloadUrl: `https://play.example.org/api/v1/blobs/maps/${HASH_C}`,
      createdAt: NOW,
    },
  },
  {
    schema: 'MapUpload',
    name: 'unknown-format',
    valid: false,
    stage: 'schema',
    note: 'Uploads are maps or saves.',
    value: {
      id: '3e2d1c0b-9a8f-4e7d-8c6b-5a4f3e2d1c0b',
      format: 'replay',
      sha256: HASH_C,
      size: 1,
      simVersion: SIM_VERSION,
      status: 'pending',
      downloadUrl: `https://play.example.org/api/v1/blobs/maps/${HASH_C}`,
      createdAt: NOW,
    },
  },
  {
    schema: 'MatchDetail',
    name: 'verified',
    valid: true,
    note: 'A verified rated match.',
    value: {
      match: {
        id: MATCH_ID,
        simVersion: SIM_VERSION,
        origin: 'queue',
        queueId: 'ranked-1v1',
        rated: true,
        status: 'ended',
        verification: 'verified',
        mapHash: HASH_A,
        startedAt: '2026-10-01T12:00:05Z',
        endedAt: '2026-10-01T12:30:05Z',
        durationTicks: 45000,
        participants: [
          {
            seat: 0,
            team: 0,
            kind: 'human',
            displayName: 'Alice',
            accountId: ACCOUNT_1,
            outcome: 'won',
            disconnects: 0,
            rating: { ladder: 'ranked-1v1', before: 1500, after: 1532.4, provisional: true },
          },
          {
            seat: 1,
            team: 1,
            kind: 'human',
            displayName: 'Bob',
            accountId: ACCOUNT_2,
            outcome: 'lost',
            disconnects: 1,
          },
        ],
      },
      setup: SETUP_CATALOG_1V1,
      teams: [
        {
          team: 0,
          outcome: 'won',
          prestige: 210,
          statistics: { units: 61 },
          timeline: [
            { tick: 0, units: 6, buildings: 1, prestige: 0, hp: 0, attack: 0, defense: 0 },
            { tick: 512, units: 9, buildings: 3, prestige: 4, hp: 120, attack: 0, defense: 0 },
          ],
        },
        {
          team: 1,
          outcome: 'lost',
          prestige: 35,
          eliminatedTick: 44990,
          statistics: {},
          timeline: [],
        },
      ],
      artifacts: [
        {
          kind: 'replay',
          url: `https://play.example.org/api/v1/matches/${MATCH_ID}/artifacts/replay`,
          size: 90211,
          sha256: HASH_C,
        },
      ],
      map: { title: 'Even Ground', mapId: MAP_ID, width: 128, height: 128 },
      verificationDetail: {
        orderRejections: [
          { seat: 1, rejected: 2, stale: 0, reasons: { foreign_unit: 2 }, firstRejectedTick: 812 },
        ],
      },
      economy: [
        {
          matchId: MATCH_ID,
          accountId: ACCOUNT_1,
          seat: 0,
          points: [
            {
              tick: 512,
              units: 9,
              buildings: 3,
              prestige: 4,
              averageUnits: 8.5,
              averageBuildings: 3,
              averagePrestige: 2,
              gamesAtTick: 4,
            },
          ],
        },
      ],
      network: [
        {
          seat: 0,
          quality: 'good',
          rttMs: { p50: 41, p95: 52 },
          lagMs: { p50: 280, p95: 360 },
          disconnects: 0,
          offlineMs: 0,
          ordersSequenced: 812,
          ordersDeferred: 9,
          rejoins: 0,
          leftBy: 'quit',
        },
        {
          seat: 1,
          quality: 'poor',
          rttMs: { p50: 115, p95: 242 },
          lagMs: { p50: 400, p95: 760 },
          disconnects: 1,
          offlineMs: 6230,
          ordersSequenced: 640,
          ordersDeferred: 31,
          rejoins: 1,
          leftBy: 'quit',
        },
      ],
    },
  },
  {
    schema: 'MatchDetail',
    name: 'array-timeline',
    valid: false,
    stage: 'schema',
    note: 'Timelines are sample objects, not bare rows.',
    value: {
      match: {
        id: MATCH_ID,
        simVersion: SIM_VERSION,
        origin: 'room',
        rated: false,
        status: 'ended',
        verification: 'verified',
        mapHash: HASH_A,
        participants: [],
      },
      setup: SETUP_CATALOG_1V1,
      teams: [{ team: 0, outcome: 'won', prestige: 1, statistics: {}, timeline: [[1, 2, 3]] }],
      artifacts: [],
    },
  },
  {
    schema: 'InstanceStats',
    name: 'home',
    valid: true,
    note: 'The home page numbers.',
    value: {
      playersOnline: 12,
      activeWindowMinutes: 15,
      liveMatches: 3,
      matchesToday: 41,
      generatedAt: NOW,
    },
  },
  {
    schema: 'InstanceStats',
    name: 'negative-count',
    valid: false,
    stage: 'schema',
    note: 'Counts are never negative.',
    value: {
      playersOnline: -1,
      activeWindowMinutes: 15,
      liveMatches: 0,
      matchesToday: 0,
      generatedAt: NOW,
    },
  },
  {
    schema: 'PlayerProfile',
    name: 'registered',
    valid: true,
    note: 'A registered player with a rating, its history and aggregates.',
    value: {
      account: { id: ACCOUNT_1, displayName: 'Alice', kind: 'registered', createdAt: NOW },
      detail: 'full',
      ratings: [
        {
          ladder: 'ranked-1v1',
          rating: 1532.4,
          mu: 27.1,
          sigma: 4.8,
          games: 11,
          wins: 7,
          provisional: false,
          rank: 3,
        },
      ],
      ratingHistory: [
        {
          ladder: 'ranked-1v1',
          matchId: MATCH_ID,
          at: NOW,
          result: 'won',
          before: 1500,
          after: 1532.4,
          provisional: false,
        },
      ],
      recentMatches: [],
      aggregates: {
        windowDays: 90,
        games: 11,
        wins: 7,
        losses: 4,
        winRates: [
          {
            dimension: 'queue',
            key: 'ranked-1v1',
            label: '1 vs 1 ranked',
            games: 11,
            wins: 7,
            winRate: 0.6364,
          },
          { dimension: 'generator', key: 'evenGround', games: 5, wins: 4, winRate: 0.8 },
        ],
        medianTicks: 36000,
        meanTicks: 37250.5,
      },
    },
  },
  {
    schema: 'PlayerProfile',
    name: 'guest',
    valid: true,
    note: 'Guests get a minimal profile.',
    value: {
      account: { id: ACCOUNT_2, displayName: 'Guest-4821', kind: 'guest', createdAt: NOW },
      detail: 'minimal',
      ratings: [],
      ratingHistory: [],
      recentMatches: [],
    },
  },
  {
    schema: 'AiLeaderboard',
    name: 'one-version',
    valid: true,
    note: 'AI entities of a ladder grouped by sim version.',
    value: {
      ladder: 'ranked-1v1',
      groups: [
        {
          simVersion: SIM_VERSION,
          current: true,
          entries: [
            {
              rank: 1,
              entity: { kind: 'ai', ai: 'nicowar', simVersion: SIM_VERSION },
              rating: 1610,
              mu: 30.2,
              sigma: 6.1,
              games: 3,
              wins: 2,
              provisional: true,
            },
          ],
        },
      ],
    },
  },
  {
    schema: 'LeaderboardPage',
    name: 'with-ai',
    valid: true,
    note: 'A ladder with a player and an AI entity.',
    value: {
      ladder: 'ranked-1v1',
      entries: [
        {
          rank: 1,
          entity: {
            kind: 'account',
            account: { id: ACCOUNT_1, displayName: 'Alice', kind: 'registered', createdAt: NOW },
          },
          rating: 1712,
          mu: 29.1,
          sigma: 2.2,
          games: 48,
          wins: 31,
          provisional: false,
        },
        {
          rank: 2,
          entity: { kind: 'ai', ai: 'maxima', simVersion: SIM_VERSION },
          rating: 1690,
          mu: 28.4,
          sigma: 3.9,
          games: 12,
          wins: 7,
          provisional: true,
        },
      ],
    },
  },
  {
    schema: 'AccessTokenClaims',
    name: 'guest',
    valid: true,
    note: 'Claims of a guest access token.',
    value: {
      iss: 'https://play.example.org',
      aud: 'glob2-platform',
      sub: ACCOUNT_1,
      jti: JOB_ID,
      iat: 1790856000,
      exp: 1790856600,
      client_id: 'desktop',
      sid: ROOM_ID,
      kind: 'guest',
      role: 'user',
    },
  },
  {
    schema: 'AccessTokenClaims',
    name: 'ticket-audience',
    valid: false,
    stage: 'schema',
    note: 'An access token never carries the relay audience.',
    value: {
      iss: 'https://play.example.org',
      aud: 'glob2-relay',
      sub: ACCOUNT_1,
      jti: JOB_ID,
      iat: 1790856000,
      exp: 1790856600,
      client_id: 'desktop',
      sid: ROOM_ID,
      kind: 'guest',
      role: 'user',
    },
  },
  {
    schema: 'LocalRegisterRequest',
    name: 'upgrade',
    valid: true,
    note: 'A local username and password (only on instances that enable local accounts).',
    value: { username: 'alice_92', password: 'correct horse battery', platform: 'desktop' },
  },
  {
    schema: 'LocalRegisterRequest',
    name: 'short-password',
    valid: false,
    stage: 'schema',
    note: 'Passwords have at least 10 characters.',
    value: { username: 'alice_92', password: 'hunter2', platform: 'desktop' },
  },
  {
    schema: 'RealtimeEventAuthHandoffCompleted',
    name: 'linked',
    valid: true,
    note: 'A guest linked a provider through the browser and is now registered.',
    value: {
      attemptId: JOB_ID,
      linked: true,
      session: {
        account: SELF_ACCOUNT,
        tokens: {
          tokenType: 'Bearer',
          accessToken: 'eyJhbGciOiJFZERTQSJ9.e30.c2ln',
          accessTokenExpiresAt: '2026-10-01T12:10:00Z',
          refreshToken: 'q2Vx0YbZ8k1mQ3s5u7w9y1A3C5E7G9I1K3M5O7Q9S1U',
          refreshTokenExpiresAt: '2026-11-30T12:00:00Z',
        },
      },
    },
  },
  {
    schema: 'RealtimeEventAuthHandoffFailed',
    name: 'conflict',
    valid: true,
    note: 'The identity already belongs to another account; the client may offer to switch.',
    value: {
      attemptId: JOB_ID,
      reason: 'conflict',
      conflict: {
        reason: 'identity_in_use',
        provider: 'google',
        account: { id: ACCOUNT_2, displayName: 'Bob', kind: 'registered', createdAt: NOW },
      },
    },
  },
  {
    schema: 'AdminMuteRequest',
    name: 'too-long',
    valid: false,
    stage: 'schema',
    note: 'Mutes last at most a year.',
    value: { minutes: 600000 },
  },
  // ------------------------------------------------------------------- Jobs
  {
    schema: 'EngineJob',
    name: 'generate-map',
    valid: true,
    note: 'Generate a map from a descriptor.',
    value: {
      jobId: JOB_ID,
      kind: 'generate-map',
      simVersion: SIM_VERSION,
      payload: { generator: (SETUP_GENERATED_FFA.map as { generator: unknown }).generator },
    },
  },
  {
    schema: 'EngineJob',
    name: 'validate-map',
    valid: true,
    note: 'Validate an uploaded save.',
    value: {
      jobId: JOB_ID,
      kind: 'validate-map',
      simVersion: SIM_VERSION,
      payload: { blobHash: HASH_C, format: 'save' },
    },
  },
  {
    schema: 'EngineJob',
    name: 'render-preview',
    valid: true,
    note: 'Render a preview PNG.',
    value: {
      jobId: JOB_ID,
      kind: 'render-preview',
      simVersion: SIM_VERSION,
      payload: { mapHash: HASH_A, maxSizePx: 512 },
    },
  },
  {
    schema: 'EngineJob',
    name: 'verify-match',
    valid: true,
    note: 'Verify a finished match from its record.',
    value: {
      jobId: JOB_ID,
      kind: 'verify-match',
      simVersion: SIM_VERSION,
      payload: { matchId: MATCH_ID, setup: SETUP_CATALOG_1V1, recordHash: HASH_D },
    },
  },
  {
    schema: 'EngineJob',
    name: 'payload-of-other-kind',
    valid: false,
    stage: 'schema',
    note: 'The payload must match the job kind.',
    value: {
      jobId: JOB_ID,
      kind: 'verify-match',
      simVersion: SIM_VERSION,
      payload: { mapHash: HASH_A, maxSizePx: 512 },
    },
  },
  {
    schema: 'EngineJob',
    name: 'verify-match-bad-setup',
    valid: false,
    stage: 'semantic',
    note: 'The setup inside a verify job must pass MatchSetup semantics.',
    value: {
      jobId: JOB_ID,
      kind: 'verify-match',
      simVersion: SIM_VERSION,
      payload: {
        matchId: MATCH_ID,
        setup: edit(SETUP_CATALOG_1V1, (s) => {
          s.seats[1]!.seat = 3;
        }),
        recordHash: HASH_D,
      },
    },
  },
  {
    schema: 'EngineJobResult',
    name: 'verified',
    valid: true,
    note: 'An agent reports a verified match.',
    value: {
      jobId: JOB_ID,
      kind: 'verify-match',
      ok: true,
      result: { verdict: 'verified', outcome: VERIFIED_OUTCOME },
      agent: 'engine-agent-125-1',
    },
  },
  {
    schema: 'EngineJobResult',
    name: 'failed',
    valid: true,
    note: 'An agent reports a failure.',
    value: {
      jobId: JOB_ID,
      kind: 'generate-map',
      ok: false,
      error: { code: 'internal', message: 'generator refused the parameters' },
      agent: 'engine-agent-125-1',
    },
  },
  {
    schema: 'ValidateMapResult',
    name: 'save-with-players',
    valid: true,
    note: 'A valid save: map facts plus the players recorded in it (for reteaming).',
    value: {
      valid: true,
      mapHash: HASH_C,
      map: { width: 128, height: 128, teamCount: 2 },
      versionMinor: 125,
      players: [
        { name: 'Alice', team: 0, kind: 'human' },
        { name: 'Cortex', team: 1, kind: 'ai' },
      ],
    },
  },
  {
    schema: 'ValidateMapResult',
    name: 'invalid',
    valid: true,
    note: 'The engine could not load the file.',
    value: { valid: false, reason: 'not a Globulation 2 map' },
  },
  {
    schema: 'VerifyVerdict',
    name: 'verified',
    valid: true,
    note: 'Every client agreed with the verifier.',
    value: { verdict: 'verified', outcome: VERIFIED_OUTCOME },
  },
  {
    schema: 'VerifyVerdict',
    name: 'verified-with-history',
    valid: true,
    note: 'Teams may carry final counters and the 512-tick timeline from the verifier result.',
    value: {
      verdict: 'verified',
      outcome: {
        ...VERIFIED_OUTCOME,
        teams: VERIFIED_OUTCOME.teams.map((team, index) => ({
          ...team,
          statistics: { units: 12 + index, workers: 9, buildings: 4, totalHp: 2400 },
          timeline: [
            { tick: 0, units: 4, buildings: 1, prestige: 0, hp: 800, attack: 0, defense: 0 },
            { tick: 512, units: 6, buildings: 2, prestige: 0, hp: 1300, attack: 40, defense: 0 },
          ],
        })),
      },
    },
  },
  {
    schema: 'VerifyVerdict',
    name: 'diverged',
    valid: true,
    note: 'Seat 1 reported checksums the verifier did not reproduce.',
    value: { verdict: 'diverged', clients: [1], outcome: VERIFIED_OUTCOME },
  },
  {
    schema: 'VerifyVerdict',
    name: 'unverifiable',
    valid: true,
    note: 'No client matched the verifier.',
    value: { verdict: 'unverifiable', reason: 'checksum mismatch at tick 25 for every seat' },
  },
  {
    schema: 'VerifyVerdict',
    name: 'diverged-without-clients',
    valid: false,
    stage: 'schema',
    note: 'A diverged verdict names at least one seat.',
    value: { verdict: 'diverged', clients: [], outcome: VERIFIED_OUTCOME },
  },
];
