#!/usr/bin/env python3
"""Generate a strict, reviewer-readable inventory of the current runtime pack."""
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / 'docs/high-resolution/ASSET-PROVENANCE.md'
CATEGORIES = {
    'current': 'AI upscale with constrained finishing',
    'outline_repair': 'AI upscale with constrained finishing',
    'painted_repair': 'AI upscale with constrained finishing',
    'crystal_repair': 'AI upscale with constrained finishing',
    'resource constrained': 'AI upscale with constrained finishing',
    'world constrained': 'AI upscale with constrained finishing',
    'soft mask resampling': 'Non-AI mask resampling',
    'shared-material rugged corner masks v5; quiet flat grass': 'Generated material with deterministic tiling',
    'quiet ripples; periodic material v3': 'Generated material with deterministic tiling',
}

def render():
    manifest = json.loads((ROOT / 'data/highres/v1/manifest.json').read_text())
    rows = []
    for frame in manifest['frames']:
        recipe = frame['recipe']
        original = recipe.startswith('recovered original')
        category = 'Recovered original' if original else CATEGORIES[recipe]
        sources = frame.get('sources', [])
        if original:
            assert sources, frame['id']
        for source in sources:
            assert hashlib.sha256((ROOT / source['path']).read_bytes()).hexdigest() == source['sha256']
        for layer in frame['layers']:
            path = ROOT / 'data/highres/v1' / layer['file']
            assert hashlib.sha256(path.read_bytes()).hexdigest() == layer['sha256']
        native = '—'
        if sources:
            source = sources[0]
            size = source.get('native_size')
            if size:
                native = '%s×%s' % tuple(size)
            native += ' ([source](../../%s))' % source['path']
        rows.append((frame['id'], category, '%s×%s' % (frame['width'], frame['height']), native, recipe))
    counts = Counter(row[1] for row in rows)
    lines = ['# Runtime artwork provenance', '',
             'Generated by `python3 tools/artwork/runtime_provenance.py`; validate with `--check`.', '',
             'This inventory describes the active pack, not every historical experiment. '
             'All frames use 4× runtime canvases; that does not imply 4× native detail. '
             'Native canvas dimensions include transparent padding. '
             '“Recovered original” includes deterministic resizing, matte extraction, layer separation and renders from original Blender rigs, without AI.', '',
             'Generated terrain combines selected generated materials with deterministic masks and edge correction. '
             'Mask resampling adds no invented texture detail. Unit animation textures are rendered from the original Blender rigs.', '',
             '| Source category | Frames |', '| --- | ---: |']
    lines += ['| %s | %d |' % item for item in sorted(counts.items())]
    lines += ['', f'Total: **{len(rows)} frames**. Source/output SHA-256 hashes, native sizes and selected layers are retained in '
              '[the pack manifest](../../data/highres/v1/manifest.json). '
              'See [original export recipes](../../datasrc/gfx/RECOVERED-RUNTIME.md) for limitations.', '',
              '| Frame | Source category | Logical canvas | Native canvas/source | Recipe |',
              '| --- | --- | --- | --- | --- |']
    lines += ['| `%s` | %s | %s | %s | %s |' % row for row in sorted(rows)]
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = render()
    if args.check:
        assert OUTPUT.read_text() == result, 'Stale inventory: rerun runtime_provenance.py'
        print('PASS complete recipe classification, source/output hashes and current inventory')
    else:
        OUTPUT.write_text(result)
        print('Wrote', OUTPUT.relative_to(ROOT))
