"""Registry of every native test and test-adjacent program.

test/SConscript builds two doctest binaries from these tables and scons/mobile_build.py
cross-compiles the same lists. Paths are relative to test/ unless they start with '#',
which is the repository root.

Placement rule: a test joins UNIT_TESTS if it needs neither GlobalContainer nor any
client object; otherwise it joins ENGINE_TESTS. Entry options:
  cxxflags  extra compiler flags for that translation unit only
  defines   extra preprocessor defines for that translation unit only
  require   build features the entry needs: 'wss', 'not-mingw', 'opengl'
"""

# Linked into both test binaries.
SUPPORT = [
    'support/TestMain.cpp',
    'support/Glob2Test.cpp',
    'support/GlobalContainerSlot.cpp',
]

# Linked into glob2-engine-tests only.
ENGINE_SUPPORT = [
    'support/EngineFixtures.cpp',
]

# glob2-engine-tests: every client object except the entry point, plus these.
ENGINE_TESTS = [
    # This fixture selects SDL's dummy driver; isolate its client context from display cases.
    'ScreenExecutionHarness.cpp',
    ('AIRecoveryCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('GUIInteractionCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('GUIOrderCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('EditorActionCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    'LegacyAreaWaitTest.cpp',
    ('LegacyScriptCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    'AIDecisionCoverageTest.cpp',
    'CastorContinuationTest.cpp',
    'CortexNetCoverageTest.cpp',
    ('CortexActionCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('CortexPolicyCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('ScriptCompatibilityTest.cpp', dict(cxxflags=['-fno-access-control'])),
    'ScriptIntegrationTest.cpp',
    'ScriptPresentationTest.cpp',
    'ScriptEditorTest.cpp',
    'ScriptRealisticTest.cpp',
    ('ScriptSessionTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('ScriptSimulationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    'BuildingExpelHarness.cpp',
    'BuildingGradientInvalidationHarness.cpp',
    'FetchApportionmentHarness.cpp',
    'GameGUISelectionHarness.cpp',
    'SceneExtractTest.cpp',
    ('ClientChannelsTest.cpp', dict(cxxflags=['-fno-access-control'])),
    'HiringBucketHarness.cpp',
    'HungryDefeatHarness.cpp',
    'ImmobileUnitGradientHarness.cpp',
    'InnSwapHarness.cpp',
    'LevelGateHarness.cpp',
    'ResourceFetchTargetHarness.cpp',
    'RoundTripHungerGateHarness.cpp',
    'TerrainResourcesHarness.cpp',
    ('AISavePortabilityHarness.cpp', dict(cxxflags=['-fno-access-control'])),
    'BuildingFootprintHarness.cpp',
    'ClearingFlagGradientTest.cpp',
    'CortexGeometryHarness.cpp',
    'EnteringUnitSaveHarness.cpp',
    'MapGradientInvalidationTest.cpp',
    ('NicowarFarmingHarness.cpp', dict(cxxflags=['-fno-access-control'])),
    'RuntimeContinuationTest.cpp',
    'SharedWorkerLifecycleTest.cpp',
    'TrappedUnitLifecycleTest.cpp',
    'UnitContinuationHarness.cpp',
    'SavegameSafetyHarness.cpp',
    'UntrustedFilesTest.cpp',
    ('TournamentCompatibilityTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('maxima/MaximaRelocationIntegrationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    'CombGeneratorTest.cpp',
    'OrchardCommonsConversionTest.cpp',
    'PortableGameHarness.cpp',
    'TeamStatsSaveHarness.cpp',
    ('EngineSessionHarness.cpp', dict(cxxflags=['-fno-access-control'])),
    ('MapRenderResizeHarness.cpp', dict(cxxflags=['-fno-access-control'])),
    ('PointBarRenderTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('maxima/MaximaCombatIntegrationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    'maxima/MaximaDiagnosticsTest.cpp',
    ('maxima/MaximaDirectorRegressionTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('maxima/MaximaEconomyRegressionTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('maxima/MaximaFarmingIntegrationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('maxima/MaximaImplementationIntegrationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    'maxima/MaximaLifecycleTest.cpp',
    'maxima/MaximaStrategyTest.cpp',
    # Rendering and window harnesses: most cases need a display ([display]); entries that
    # call OpenGL outside HAVE_OPENGL guards are left out of opengl=0 builds.
    'DrawableSurfaceBlendTest.cpp',
    ('EnteringUnitDrawHarness.cpp', dict(require={'opengl'})),
    ('FailingUnitMarkersHarness.cpp', dict(require={'opengl'})),
    'FullscreenAspectHarness.cpp',
    'HighResolutionIntegrationHarness.cpp',
    'PortableRendererHarness.cpp',
    'SoftwareRendererTest.cpp',
    ('RuntimePackCheck.cpp', dict(require={'opengl'})),
    ('TextRasterHarness.cpp', dict(require={'opengl'})),
    ('TorusRenderIntegrationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('UnitHighResolutionCacheTest.cpp', dict(require={'opengl'})),
    ('UnitTeamColorCacheTest.cpp', dict(require={'opengl'})),
    ('UnitTeamShaderTest.cpp', dict(require={'opengl'})),
    'WindowResizeHarness.cpp',
    'SettingsScreenTest.cpp',
    'SettingsGraphicsTest.cpp',
    'SettingsExperimentsTest.cpp',
    'GuardAreaBalanceTest.cpp',
    'GameSpeedTest.cpp',
    'UIPresentationHarness.cpp',
    'UIIconsTest.cpp',
    'GameGUITouchHarness.cpp',
    # Command-line harnesses whose modes became cases.
    'CustomGameSetupHarness.cpp',
    'TeamLimitTest.cpp',
    'MapPreviewHarness.cpp',
    ('MapGeneratorDefaultsTest.cpp', dict(cxxflags=['-fno-access-control'])),
]

# glob2-unit-tests: libgag, libusl, the production sources below and stubs.
UNIT_TESTS = [
    'EventQueueTest.cpp',
    'MapGeneratorGoldenCoverageTest.cpp',
    'USLCoverageTest.cpp',
    'SurfaceCoverageTest.cpp',
    'ImageAssetTest.cpp',
    'ScriptRuntimeTest.cpp',
    'ScriptNumericTest.cpp',
    ('UnitDrawBatchTest.cpp', dict(require={'opengl'})),
    ('MapGeometryCacheTest.cpp', dict(require={'opengl'})),
    ('SpriteDrawBatchTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('OpaqueRectangleBatchTest.cpp', dict(cxxflags=['-fno-access-control'])),
    # Former CppUnit suite (TestsRunner).
    'AllyTeamWidgetIndexTest.cpp',
    'BitArrayTest.cpp',
    'SceneBufferTest.cpp',
    'BrushAccumulatorTest.cpp',
    'BrushCoverageTest.cpp',
    'BrushToolHitTest.cpp',
    'BuildingFailureDisplayTest.cpp',
    'CortexUpgradeTest.cpp',
    'EditorWidgetLayoutTest.cpp',
    'FertilityFieldTest.cpp',
    'FetchApportionmentTest.cpp',
    'FilenameStripTest.cpp',
    'GameMusicControllerTest.cpp',
    'GhostBuildingOverlapTest.cpp',
    'GradientBFSTest.cpp',
    'GradientTest.cpp',
    'HelloWorldTest.cpp',
    'KeyActionLookupTest.cpp',
    'MapQueryTest.cpp',
    'MessageRecipientsTest.cpp',
    'OverlayFillTest.cpp',
    'PanelButtonHitTest.cpp',
    'ParticleCrossfadeTest.cpp',
    'PerlinNoiseTest.cpp',
    'PlayerVoiceDrainTest.cpp',
    'SpriteCenteringTest.cpp',
    'TurretScanTileTest.cpp',
    'UnitAnimationTest.cpp',
    'UnitDrawGeometryTest.cpp',
    'UnitTimingTest.cpp',
    'natsort/NatSortTest.cpp',
    # Former standalone programs compiled by test/SConstruct or directly in CI.
    'BasePlayerSaveLoadTest.cpp',
    'BaseTeamSaveLoadTest.cpp',
    'BulletSaveLoadTest.cpp',
    'CloudFieldTest.cpp',
    'ExperimentalFeaturesTest.cpp',
    'GameHeaderDefaultAlliancesTest.cpp',
    'GameHeaderTextSaveLoadTest.cpp',
    'GameHintsTest.cpp',
    'GameObjectivesTest.cpp',
    'LocalTimeTest.cpp',
    'MapExploredAreaSaveLoadTest.cpp',
    'MapRenderGeometryTest.cpp',
    'MersenneTwisterTest.cpp',
    'NetGamePlayerManagerTest.cpp',
    'RuntimeBuildingOrderSaveLoadTest.cpp',
    'TorusGeometryTest.cpp',
    'TorusPickingTest.cpp',
    'TriboolTest.cpp',
    'WinningConditionDecodeTest.cpp',
    'WinningConditionPrestigeToggleTest.cpp',
    'WinningConditionSuddenDeathToggleTest.cpp',
    'NetSendOrderDecodeTest.cpp',
    'OrderAlterateAreaTest.cpp',
    'ReplayStepCounterTest.cpp',
    'CampaignBoundsHarness.cpp',
    'CampaignDescriptionCacheHarness.cpp',
    'CampaignLoadHarness.cpp',
    'CampaignSelectionHarness.cpp',
    'WinningConditionsHarness.cpp',
    'BufferedFileStreamHarness.cpp',
    'ComputeExecutorHarness.cpp',
    'GradientPipelineHarness.cpp',
    ('MobileCertificateHarness.cpp', dict(require={'wss'})),
    'MobileDocumentsHarness.cpp',
    'MobileInputHarness.cpp',
    ('MobileTemporaryFilesHarness.cpp', dict(require={'not-mingw'})),
    'PerformanceTelemetryHarness.cpp',
    'ScrollPhysicsTest.cpp',
    'SoundMixerTrackSelectionHarness.cpp',
    'UILayoutHarness.cpp',
    'GlobalGradientHarness.cpp',
    'PathGradientHarness.cpp',
    'maxima/MaximaContinuationTest.cpp',
    'maxima/MaximaFoodLedgerStandaloneTest.cpp',
    'maxima/MaximaDefenseStandaloneTest.cpp',
    'maxima/MaximaFarmingStandaloneTest.cpp',
    'maxima/MaximaForceModelStandaloneTest.cpp',
    'maxima/MaximaLabourStandaloneTest.cpp',
    'maxima/MaximaPlacementStandaloneTest.cpp',
    'maxima/MaximaReconStandaloneTest.cpp',
    'maxima/MaximaStaffingControlStandaloneTest.cpp',
    'maxima/MaximaTacticsStandaloneTest.cpp',
]

# Production sources the unit binary links. Plain entries reuse the client build's
# object; entries with `defines` are compiled again for the unit binary only.
UNIT_PRODUCTION_SOURCES = [
    '#src/script/ScriptValue.cpp',
    '#src/script/ScriptRuntime.cpp',
    '#src/BitArray.cpp',
    '#src/Brush.cpp',
    '#src/BrushCoverage.cpp',
    '#src/OverlayFill.cpp',
    '#src/PlayerVoice.cpp',
    '#src/Utilities.cpp',
    '#src/ai/maxima/AIMaximaDefense.cpp',
    '#src/ai/maxima/AIMaximaFarming.cpp',
    '#src/ai/maxima/AIMaximaFoodLedger.cpp',
    '#src/ai/maxima/AIMaximaForceModel.cpp',
    '#src/ai/maxima/AIMaximaPlacement.cpp',
    '#src/ai/maxima/AIMaximaRecon.cpp',
    '#src/ai/maxima/AIMaximaTactics.cpp',
    '#src/ai/shared_runtime/GradientBFS.cpp',
    '#src/building/BuildingUtils.cpp',
    '#src/gui/GameGUIKeyActions.cpp',
    '#src/gui/GameMusicController.cpp',
    '#src/map/FertilityField.cpp',
    '#src/map/Map.cpp',
    '#src/map/MapQuery.cpp',
    '#src/map/MapTerrain.cpp',
    '#src/map/edit/MapEditKeyActions.cpp',
    '#src/map/generator/shared/Noise.cpp',
    '#src/map/gradient/BuildingGradientSearch.cpp',
    '#src/map/gradient/MapGradientDirection.cpp',
    '#src/map/gradient/MapGradientChamfer.cpp',
    '#src/map/gradient/MapGradientPropagation.cpp',
    '#src/net/message/MessageRecipients.cpp',
    '#src/unit/UnitUtils.cpp',
    '#src/BasePlayer.cpp',
    '#src/BaseTeam.cpp',
    '#src/Bullet.cpp',
    '#src/ExperimentalFeatures.cpp',
    '#src/GameHeader.cpp',
    '#src/GameHints.cpp',
    '#src/GameObjectives.cpp',
    '#src/SimplexNoise.cpp',
    '#src/WinningConditions.cpp',
    '#src/ai/shared_runtime/BuildingOrder.cpp',
    '#src/map/io/MapExploredAreaIO.cpp',
    '#src/net/NetGamePlayerManager.cpp',
    '#src/net/NetReteamingInformation.cpp',
    '#src/Campaign.cpp',
    '#src/SoundMixer.cpp',
    '#mobile/Documents.cpp',
    ('#mobile/CertificateTrust.cpp', dict(require={'wss'})),
    ('#mobile/TemporaryFiles.cpp', dict(require={'not-mingw'})),
    '#src/ReplayReader.cpp',
    '#src/ReplayWriter.cpp',
    # Without the client's Brush and Game surfaces: only the byte marshalers are wanted.
    ('#src/OrderModify.cpp', dict(defines=['YOG_SERVER_ONLY'])),
    ('#src/OrderBuilding.cpp', dict(defines=['YOG_SERVER_ONLY'])),
    ('#src/net/message/OrderMessages.cpp', dict(defines=['YOG_SERVER_ONLY'])),
]

# Replacement definitions for production symbols the unit binary does not link.
UNIT_STUBS = [
    'unit/stubs/Sha1.cpp',
    'unit/stubs/MapSectorStubs.cpp',
    'unit/stubs/MapHeaderStubs.cpp',
    'unit/stubs/OrderStubs.cpp',
    'unit/stubs/GameGUIStubs.cpp',
    'unit/stubs/RaceStubs.cpp',
    'unit/stubs/RuntimeStubs.cpp',
]

# Standalone programs: (target, source, alias, group). group 'test' programs are run by
# CI through their own runners; 'tools' are developer utilities and benchmarks. The
# transport programs the browser tests drive stay in src/SConscript under 'transport-test'.
PROGRAMS = [
    ('MapReportHarness', 'MapReportHarness.cpp', 'map-report-test', 'test'),
    ('MaximaStrategyDump', 'maxima/MaximaStrategyDump.cpp', 'maxima-strategy-dump', 'tools'),
    ('MenuColonyHarness', '#tools/MenuColonyHarness.cpp', 'menu-colony-harness', 'test'),
    ('SoftwareRenderBenchmark', 'SoftwareRenderBenchmark.cpp', 'software-render-benchmark', 'tools'),
    ('torus-render-benchmark', 'TorusRenderBenchmark.cpp', 'torus-render-benchmark', 'tools'),
]

# Old per-harness alias -> test binary. Kept for one release so documented commands and
# shell history keep working; delete after that.
LEGACY_ALIASES = {
    'ai-save-portability-test': 'glob2-engine-tests',
    'building-expel-test': 'glob2-engine-tests',
    'building-footprint-test': 'glob2-engine-tests',
    'building-gradient-invalidation-test': 'glob2-engine-tests',
    'clearing-gradient-test': 'glob2-engine-tests',
    'comb-generator-test': 'glob2-engine-tests',
    'cortex-geometry-test': 'glob2-engine-tests',
    'entering-unit-save-test': 'glob2-engine-tests',
    'fetch-apportionment-test': 'glob2-engine-tests',
    'global-gradient-test': 'glob2-unit-tests',
    'gradient-invalidation-test': 'glob2-engine-tests',
    'hiring-bucket-test': 'glob2-engine-tests',
    'hungry-defeat-test': 'glob2-engine-tests',
    'immobile-unit-gradient-test': 'glob2-engine-tests',
    'inn-swap-test': 'glob2-engine-tests',
    'level-gate-test': 'glob2-engine-tests',
    'map-render-resize-test': 'glob2-engine-tests',
    'maxima-continuation-test': 'glob2-unit-tests',
    'maxima-food-ledger-test': 'glob2-unit-tests',
    'maxima-relocation-test': 'glob2-engine-tests',
    'nicowar-farming-test': 'glob2-engine-tests',
    'orchard-conversion-test': 'glob2-engine-tests',
    'path-gradient-test': 'glob2-unit-tests',
    'point-bar-render-test': 'glob2-engine-tests',
    'portable-game-test': 'glob2-engine-tests',
    'resource-fetch-target-test': 'glob2-engine-tests',
    'round-trip-hunger-gate-test': 'glob2-engine-tests',
    'runtime-continuation-test': 'glob2-engine-tests',
    'savegame-safety-test': 'glob2-engine-tests',
    'selection-test': 'glob2-engine-tests',
    'session-test': 'glob2-engine-tests',
    'team-stats-save-test': 'glob2-engine-tests',
    'terrain-test': 'glob2-engine-tests',
    'tournament-compatibility-test': 'glob2-engine-tests',
    'trapped-unit-test': 'glob2-engine-tests',
    'unit-continuation-test': 'glob2-engine-tests',
    'torus-render-test': 'glob2-engine-tests',
    'unit-render-tests': 'glob2-engine-tests',
    'unit-hd-cache-test': 'glob2-engine-tests',
    'runtime-pack-check': 'glob2-engine-tests',
    'aspect-test': 'glob2-engine-tests',
    'resize-test': 'glob2-engine-tests',
    'text-raster-test': 'glob2-engine-tests',
    'portable-renderer-test': 'glob2-engine-tests',
    'failing-unit-markers-test': 'glob2-engine-tests',
    'entering-unit-draw-test': 'glob2-engine-tests',
    'highres-integration-test': 'glob2-engine-tests',
    'settings-tests': 'glob2-engine-tests',
    'speed-tests': 'glob2-engine-tests',
    'gameplay-touch-test': 'glob2-engine-tests',
    'ui-presentation-test': 'glob2-engine-tests',
    'custom-setup-test': 'glob2-engine-tests',
    'map-preview-test': 'glob2-engine-tests',
    'map-generator-defaults-test': 'glob2-engine-tests',
    'buffered-file-test': 'glob2-unit-tests',
    'compute-executor-test': 'glob2-unit-tests',
    'gradient-pipeline-test': 'glob2-unit-tests',
    'mobile-certificate-test': 'glob2-unit-tests',
    'mobile-documents-test': 'glob2-unit-tests',
    'mobile-input-test': 'glob2-unit-tests',
    'mobile-temporary-files-test': 'glob2-unit-tests',
    'performance-telemetry-test': 'glob2-unit-tests',
    'screen-test': 'glob2-unit-tests',
    'ui-layout-test': 'glob2-unit-tests',
}


def scripting_entries():
    """Shared in-process corpus for browser and the standalone iOS test app.

    TeamStatsSaveHarness owns the production conversion fixture and lifecycle
    cases. Its unrelated registered cases are excluded by the JavaScript* suite
    filter. Both desktop binaries and Android use the full registry above.
    """
    selected = {'ScriptCompatibilityTest.cpp', 'ScriptIntegrationTest.cpp', 'ScriptPresentationTest.cpp',
                'ScriptRealisticTest.cpp', 'ScriptSessionTest.cpp', 'ScriptSimulationTest.cpp',
                'TeamStatsSaveHarness.cpp', 'ScriptRuntimeTest.cpp', 'ScriptNumericTest.cpp', 'ImageAssetTest.cpp'}
    return [entry for entry in ENGINE_TESTS + UNIT_TESTS
            if (entry if isinstance(entry, str) else entry[0]) in selected]
