"""Registry of every native test and test-adjacent program.

test/SConscript builds two doctest binaries from these tables and scons/mobile_build.py
cross-compiles the same lists. Paths are relative to test/ unless they start with '#',
which is the repository root: a domain's tests sit beside the code they test.

Placement rule: a test joins UNIT_TESTS if it needs neither GlobalContainer nor any
client object; otherwise it joins ENGINE_TESTS. Entry options:
  cxxflags  extra compiler flags for that translation unit only
  defines   extra preprocessor defines for that translation unit only
  require   build features the entry needs: 'wss', 'not-mingw', 'opengl'
"""

# Linked into both test binaries.
SUPPORT = [
    'support/TestMain.cpp',
    'support/Glob2Test.cpp',
    'support/GlobalContainerSlot.cpp',
]

# Linked into glob2-engine-tests only.
ENGINE_SUPPORT = [
    'support/EngineFixtures.cpp',
]

# glob2-engine-tests: every client object except the entry point, plus these.
ENGINE_TESTS = [
    ('#src/unit/render/ColonySkinPreviewTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/audio/MusicSetTest.cpp',
    '#src/audio/MusicStreamTest.cpp',
    # SDL driver/device fixtures run in their own engine-test process.
    '#src/audio/SoundMixerTrackSelectionHarness.cpp',
    ('#src/ui/screens/MusicScreensTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/ai/LegacyAIStateTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/ai/AIStateContinuationTest.cpp',
    '#src/ai/BuildingCapabilitiesTest.cpp',
    '#src/ai/shared_runtime/RuntimeBuildingOrderSaveLoadTest.cpp',
    ('#src/ai/AICustomCatalogTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/building/types/BuildingCatalogTest.cpp',
    '#src/building/BuildingProductionCombatTest.cpp',
    '#src/building/BuildingCatalogFixtureHarness.cpp',
    '#src/building/BuildingCatalogBenchmark.cpp',
    ('#src/map/gradient/BuildingGradientBenchmark.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/building/BuildingServicesTest.cpp',
    # This fixture selects SDL's dummy driver; isolate its client context from display cases.
    '#libgag/src/ScreenExecutionHarness.cpp',
    ('#libgag/src/MacScrollMonitorTest.mm', dict(require={'mac'})),
    ('#libgag/src/MacScrollVisualHarness.cpp', dict(require={'mac'})),
    ('#src/ai/AIRecoveryCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),

    ('GameplayRecordingIntegrationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/hud/GUIInteractionCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/hud/GUIOrderCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/map/editor/EditorActionCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/scripting/sgsl/LegacyAreaWaitTest.cpp',
    ('#src/scripting/sgsl/LegacyScriptCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/ai/AIDecisionCoverageTest.cpp',
    ('#src/ai/AIRulesTest.cpp', dict(cxxflags=['-fno-access-control'])),
    # Calls Cortex's and Numbi's private helpers to drive single offense decisions.
    ('#src/ai/telemetry/AITargetTelemetryTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/ai/castor/CastorContinuationTest.cpp',
    '#src/ai/cortex/CortexNetCoverageTest.cpp',
    ('#src/ai/cortex/CortexActionCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/ai/cortex/CortexPolicyCoverageTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/scripting/javascript/ScriptCompatibilityTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/scripting/javascript/ScriptIntegrationTest.cpp',
    '#src/ai/telemetry/AITelemetryDialogTest.cpp',
    '#src/hive/HiveIntegrationTest.cpp',
    '#src/scripting/javascript/ScriptPresentationTest.cpp',
    '#src/scripting/map/ScriptEditorTest.cpp',
    '#src/scripting/javascript/ScriptRealisticTest.cpp',
    ('#src/scripting/javascript/ScriptSessionTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/scripting/javascript/ScriptSimulationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/building/BuildingExpelHarness.cpp',
    '#src/map/gradient/BuildingGradientInvalidationHarness.cpp',
    '#src/building/FetchApportionmentHarness.cpp',
    '#src/hud/GameGUISelectionHarness.cpp',
    '#src/render/scene/SceneExtractTest.cpp',
    '#src/game/diagnostics/GameDiagnosticsTest.cpp',
    ('#src/team/stats/WinProbabilityTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/engine/sim/ClientChannelsTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/building/HiringBucketHarness.cpp',
    '#src/unit/HungryDefeatHarness.cpp',
    '#src/map/gradient/ImmobileUnitGradientHarness.cpp',
    '#src/building/InnSwapHarness.cpp',
    '#src/building/LevelGateHarness.cpp',
    '#src/unit/ResourceFetchTargetHarness.cpp',
    '#src/unit/MarketFetchHarness.cpp',
    ('#src/unit/MarketsV2Test.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/unit/RoundTripHungerGateHarness.cpp',
    '#src/map/TerrainResourcesHarness.cpp',
    '#src/map/pathfind/TerrainHazardBenchmark.cpp',
    '#src/map/TerrainEcologyHarness.cpp',
    ('#src/map/TerrainPropertiesTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/net/LockstepSessionTest.cpp',
    '#src/game/orders/OrderValidationTest.cpp',
    '#src/online/MatchSetupTest.cpp',
    ('#src/net/turn/TurnEngineHarness.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/net/LanIdentityTest.cpp', dict(require={'wss'})),
    ('#src/net/lan/LanMatchHarness.cpp', dict(require={'wss'}, cxxflags=['-fno-access-control'])),
    ('#src/ai/AISavePortabilityHarness.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/building/BuildingFootprintHarness.cpp',
    '#src/map/MapTilingHarness.cpp',
    '#src/map/gradient/ClearingFlagGradientTest.cpp',
    '#src/ai/cortex/CortexGeometryHarness.cpp',
    '#src/unit/EnteringUnitSaveHarness.cpp',
    '#src/map/gradient/MapGradientInvalidationTest.cpp',
    ('#src/map/gradient/GradientPreparationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/ai/nicowar/NicowarFarmingHarness.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/ai/shared_runtime/RuntimeContinuationTest.cpp',
    '#src/game/SharedWorkerLifecycleTest.cpp',
    '#src/unit/TrappedUnitLifecycleTest.cpp',
    '#src/unit/UnitContinuationHarness.cpp',
    'SavegameSafetyHarness.cpp',
    'UntrustedFilesTest.cpp',
    ('TournamentCompatibilityTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/ai/maxima/MaximaRelocationIntegrationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/map/generator/CombGeneratorTest.cpp',
    '#src/map/generator/OrchardCommonsConversionTest.cpp',
    'PortableGameHarness.cpp',
    '#src/team/stats/TeamStatsSaveHarness.cpp',
    '#src/team/stats/TeamLabourStatsTest.cpp',
    ('#src/engine/EngineSessionHarness.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/net/turn/TurnNetConnectionTest.cpp',
    '#src/online/RelayTransportTest.cpp',
    '#src/online/OnlineResultTest.cpp',
    ('#src/online/OnlineScreenLifetimeTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/online/PlatformRoomTest.cpp',
    '#src/online/OnlineServicesTest.cpp',
    ('#src/net/WssBackpressureTest.cpp', dict(require={'wss'})),
    ('#src/render/MapRenderResizeHarness.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/render/PointBarRenderTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/ai/maxima/MaximaCombatIntegrationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/ai/maxima/MaximaDiagnosticsTest.cpp',
    ('#src/ai/maxima/MaximaDirectorRegressionTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/ai/maxima/MaximaEconomyRegressionTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/ai/maxima/MaximaFarmingIntegrationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/ai/maxima/MaximaImplementationIntegrationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/ai/maxima/MaximaLifecycleTest.cpp',
    '#src/ai/maxima/MaximaStrategyTest.cpp',
    # Rendering and window harnesses: most cases need a display ([display]); entries that
    # call OpenGL outside HAVE_OPENGL guards are left out of opengl=0 builds.
    '#libgag/src/DrawableSurfaceBlendTest.cpp',
    '#libgag/src/FontKerningTest.cpp',
    '#src/ui/OnlineWordingTest.cpp',
    ('#src/render/EnteringUnitDrawHarness.cpp', dict(require={'opengl'})),
    ('#src/render/FailingUnitMarkersHarness.cpp', dict(require={'opengl'})),
    '#libgag/src/FullscreenAspectHarness.cpp',
    ('#src/render/HighResolutionIntegrationHarness.cpp', dict(cxxflags=['-fno-access-control'])),
    '#libgag/src/PortableRendererHarness.cpp',
    '#src/render/SoftwareRendererTest.cpp',
    '#src/render/terrain/TerrainMaterialsTest.cpp',
    ('#src/render/TerrainPresentationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#libgag/src/RuntimePackCheck.cpp', dict(require={'opengl'})),
    ('#libgag/src/TextRasterHarness.cpp', dict(require={'opengl'})),
    ('#src/render/torus/TorusRenderIntegrationTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#src/unit/render/UnitHighResolutionCacheTest.cpp', dict(require={'opengl'})),
    ('#src/unit/render/UnitTeamColorCacheTest.cpp', dict(require={'opengl'})),
    ('#src/unit/render/UnitTeamShaderTest.cpp', dict(require={'opengl'})),
    '#libgag/src/WindowResizeHarness.cpp',
    '#src/ui/settings/SettingsScreenTest.cpp',
    '#src/ui/settings/SettingsGraphicsTest.cpp',
    '#src/ui/ThemeCatalogTest.cpp',
    '#src/ui/settings/SettingsExperimentsTest.cpp',
    '#src/ui/settings/SettingsBuildingsTest.cpp',
    '#src/app/SystemLanguageTest.cpp',
    '#src/game/orders/GuardAreaBalanceTest.cpp',
    ('#src/game/orders/FarmAreaTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/game/GameSpeedTest.cpp',
    '#src/ui/UIPresentationHarness.cpp',
    '#src/ui/UIIconsTest.cpp',
    '#src/hud/touch/GameGUITouchHarness.cpp',
    # Command-line harnesses whose modes became cases.
    '#src/game/screens/CustomGameSetupHarness.cpp',
    '#src/team/TeamLimitTest.cpp',
    '#src/map/preview/MapPreviewHarness.cpp',
    ('#src/map/generator/MapGeneratorDefaultsTest.cpp', dict(cxxflags=['-fno-access-control'])),
]

# glob2-unit-tests: libgag, libusl, the production sources below and stubs.
UNIT_TESTS = [
    '#src/map/TerrainRegistryTest.cpp',
    '#libgag/src/TextStreamTest.cpp',
    '#libgag/src/AssetLoaderTest.cpp',
    '#libgag/src/SpriteLoadTest.cpp',
    '#libgag/src/RenderFramePacerTest.cpp',
    '#libgag/src/FontMetricsTest.cpp',
    '#libgag/src/PackedArrayTest.cpp',
    '#libgag/src/EventQueueTest.cpp',
    '#src/map/generator/MapGeneratorGoldenCoverageTest.cpp',

    '#libgag/src/GameplayRecordingTest.cpp',
    '#libgag/src/RecordingSessionTest.cpp',
    'support/RecordingValidationProcess.cpp',
    '#libusl/test/USLCoverageTest.cpp',
    '#libgag/src/SurfaceCoverageTest.cpp',
    '#libgag/src/ImageAssetTest.cpp',
    '#src/scripting/javascript/ScriptRuntimeTest.cpp',
    '#src/hive/HiveWorkerTest.cpp',
    '#src/scripting/javascript/ScriptNumericTest.cpp',
    ('#libgag/src/UnitDrawBatchTest.cpp', dict(require={'opengl'})),
    ('#libgag/src/MapGeometryCacheTest.cpp', dict(require={'opengl'})),
    ('#libgag/src/SpriteDrawBatchTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#libgag/src/SpriteSheetTest.cpp', dict(cxxflags=['-fno-access-control'])),
    ('#libgag/src/OpaqueRectangleBatchTest.cpp', dict(cxxflags=['-fno-access-control'])),
    # Former CppUnit suite (TestsRunner).
    '#src/hud/AllyTeamWidgetIndexTest.cpp',
    '#src/common/BitArrayTest.cpp',
    '#libgag/src/BidiTextTest.cpp',
    '#src/render/scene/SceneBufferTest.cpp',
    '#src/map/BrushAccumulatorTest.cpp',
    '#src/map/BrushCoverageTest.cpp',
    '#src/map/editor/BrushToolHitTest.cpp',
    '#src/building/hud/BuildingFailureDisplayTest.cpp',
    '#src/ai/cortex/CortexUpgradeTest.cpp',
    '#src/map/editor/EditorWidgetLayoutTest.cpp',
    ('#src/map/FertilityFieldTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/building/FetchApportionmentTest.cpp',
    '#src/common/FilenameStripTest.cpp',
    '#src/audio/GameMusicControllerTest.cpp',
    '#src/hud/GhostBuildingOverlapTest.cpp',
    '#src/ai/shared_runtime/GradientBFSTest.cpp',
    '#src/field/FieldTraversalTest.cpp',
    ('#src/map/gradient/GradientTest.cpp', dict(cxxflags=['-fno-access-control'])),
    'HelloWorldTest.cpp',
    '#libgag/src/Sha1Test.cpp',
    'VendoredJsonTest.cpp',
    '#src/online/HttpFetchUrlTest.cpp',
    '#src/online/PlatformProtocolTest.cpp',
    '#src/online/InstanceConfigTest.cpp',
    '#src/online/InviteLinkTest.cpp',
    '#src/online/MapCacheTest.cpp',
    '#src/online/SkinAuthorizationTest.cpp',
    '#src/online/SkinDownloadsTest.cpp',
    '#src/online/SkinSpritesTest.cpp',
    '#src/online/ReplayAppearanceTest.cpp',
    '#src/online/PlatformClientTest.cpp',
    '#src/online/OnlineResourcesTest.cpp',
    '#src/online/QuickMatchTest.cpp',
    '#src/online/MapCatalogTest.cpp',
    '#src/ui/KeyActionLookupTest.cpp',
    ('#src/map/MapQueryTest.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/net/message/MessageRecipientsTest.cpp',
    '#src/render/overlay/OverlayFillTest.cpp',
    '#src/render/ZoomDetailTest.cpp',
    '#src/render/FogFadeTest.cpp',
    '#src/team/stats/MetricSeriesTest.cpp',
    '#src/game/rules/TeamLayoutTest.cpp',
    '#src/hud/input/PanelButtonHitTest.cpp',
    '#src/hud/draw/ParticleCrossfadeTest.cpp',
    '#src/map/generator/shared/PerlinNoiseTest.cpp',
    '#src/audio/PlayerVoiceDrainTest.cpp',
    '#src/hud/draw/SpriteCenteringTest.cpp',
    '#libgag/src/SkinMeshTest.cpp',
    '#src/building/TurretScanTileTest.cpp',
    '#src/unit/render/UnitAnimationTest.cpp',
    '#src/unit/render/UnitDrawGeometryTest.cpp',
    '#src/unit/UnitTimingTest.cpp',
    '#natsort/NatSortTest.cpp',
    # Former standalone programs compiled by test/SConstruct or directly in CI.
    '#src/game/player/BasePlayerSaveLoadTest.cpp',
    '#src/team/BaseTeamSaveLoadTest.cpp',
    '#src/game/BulletSaveLoadTest.cpp',
    '#src/render/clouds/CloudFieldTest.cpp',
    '#src/game/ExperimentalFeaturesTest.cpp',
    '#src/game/GameHeaderDefaultAlliancesTest.cpp',
    '#src/game/GameHeaderTextSaveLoadTest.cpp',
    '#src/game/GameHintsTest.cpp',
    '#src/game/GameObjectivesTest.cpp',
    '#src/map/io/MapExploredAreaSaveLoadTest.cpp',
    '#src/map/preview/MapRenderGeometryTest.cpp',
    '#src/common/MersenneTwisterTest.cpp',
    '#src/render/torus/TorusGeometryTest.cpp',
    '#src/render/torus/TorusPickingTest.cpp',
    '#src/render/torus/TorusTextureTilesTest.cpp',
    '#src/ai/shared_runtime/TriboolTest.cpp',
    '#src/game/WinningConditionDecodeTest.cpp',
    '#src/game/WinningConditionPrestigeToggleTest.cpp',
    '#src/game/WinningConditionSuddenDeathToggleTest.cpp',
    '#src/net/message/NetSendOrderDecodeTest.cpp',
    '#src/net/turn/TurnProtocolTest.cpp',
    '#src/net/turn/TurnHarnessTest.cpp',
    '#src/net/turn/TurnTelemetryTest.cpp',
    '#src/net/ConnectionQualityTest.cpp',
    '#src/game/orders/OrderAlterateAreaTest.cpp',
    '#src/replay/ReplayStepCounterTest.cpp',
    '#src/campaign/CampaignBoundsHarness.cpp',
    '#src/campaign/CampaignDescriptionCacheHarness.cpp',
    '#src/campaign/CampaignLoadHarness.cpp',
    '#src/campaign/CampaignSelectionHarness.cpp',
    '#src/game/WinningConditionsHarness.cpp',
    '#libgag/src/BufferedFileStreamHarness.cpp',
    '#src/common/ComputeExecutorHarness.cpp',
    '#src/map/gradient/GradientPipelineHarness.cpp',
    ('#mobile/MobileCertificateHarness.cpp', dict(require={'wss'})),
    '#mobile/MobileDocumentsHarness.cpp',
    '#libgag/src/MobileInputHarness.cpp',
    ('#mobile/MobileTemporaryFilesHarness.cpp', dict(require={'not-mingw'})),
    '#libgag/src/PerformanceTelemetryHarness.cpp',
    '#libgag/src/ScrollPhysicsTest.cpp',
    '#libgag/src/GestureScrollTest.cpp',
    '#src/hud/GameSpeedControlTest.cpp',
    '#src/hud/GameEventFeedTest.cpp',
    '#src/audio/MusicBufferTest.cpp',
    '#src/audio/MusicProducerTest.cpp',
    '#libgag/src/ui/UILayoutHarness.cpp',
    '#src/map/gradient/GlobalGradientHarness.cpp',
    ('#src/map/gradient/PathGradientHarness.cpp', dict(cxxflags=['-fno-access-control'])),
    '#src/ai/maxima/MaximaContinuationTest.cpp',
    '#src/ai/maxima/MaximaFoodLedgerStandaloneTest.cpp',
    '#src/ai/maxima/MaximaDefenseStandaloneTest.cpp',
    '#src/ai/maxima/MaximaFarmingStandaloneTest.cpp',
    '#src/ai/maxima/MaximaForceModelStandaloneTest.cpp',
    '#src/ai/maxima/MaximaLabourStandaloneTest.cpp',
    '#src/ai/maxima/MaximaPlacementStandaloneTest.cpp',
    '#src/ai/maxima/MaximaReconStandaloneTest.cpp',
    '#src/ai/maxima/MaximaStaffingControlStandaloneTest.cpp',
    '#src/ai/maxima/MaximaTacticsStandaloneTest.cpp',
]

# Production sources the unit binary links. Plain entries reuse the client build's
# object; entries with `defines` are compiled again for the unit binary only.
UNIT_PRODUCTION_SOURCES = [
    '#src/map/TerrainRegistry.cpp',
    '#src/scripting/javascript/ScriptValue.cpp',
    '#src/scripting/javascript/ScriptRuntime.cpp',
    '#src/hive/HiveWorker.cpp',
    '#src/common/BitArray.cpp',
    '#src/map/Brush.cpp',
    '#src/map/BrushCoverage.cpp',
    '#src/render/overlay/OverlayFill.cpp',
    '#src/audio/PlayerVoice.cpp',
    '#src/common/Utilities.cpp',
    '#src/ai/maxima/AIMaximaDefense.cpp',
    '#src/ai/maxima/AIMaximaFarming.cpp',
    '#src/ai/maxima/AIMaximaFoodLedger.cpp',
    '#src/ai/maxima/AIMaximaForceModel.cpp',
    '#src/ai/maxima/AIMaximaPlacement.cpp',
    '#src/ai/maxima/AIMaximaRecon.cpp',
    '#src/ai/maxima/AIMaximaTactics.cpp',
    '#src/ai/shared_runtime/GradientBFS.cpp',
    '#src/building/BuildingUtils.cpp',
    '#src/hud/input/GameGUIKeyActions.cpp',
    '#src/audio/GameMusicController.cpp',
    '#src/audio/MusicStream.cpp',
    '#src/audio/MusicProducer.cpp',
    '#src/map/FertilityField.cpp',
    '#src/map/Map.cpp',
    '#src/map/MapCells.cpp',
    '#src/map/MapQuery.cpp',
    '#src/map/MapTerrain.cpp',
    '#src/map/editor/MapEditKeyActions.cpp',
    '#src/map/generator/shared/Noise.cpp',
    '#src/map/gradient/BuildingGradientSearch.cpp',
    '#src/map/gradient/MapGradientDirection.cpp',
    '#src/map/gradient/MapGradientChamfer.cpp',
    '#src/map/gradient/MapGradientPropagation.cpp',
    '#src/map/gradient/ResourceSeedCache.cpp',
    '#src/resource/Resources.cpp',
    '#src/map/pathfind/MapPathfindPoint.cpp',
    '#src/net/message/MessageRecipients.cpp',
    '#src/render/FogFade.cpp',
    '#src/team/stats/MetricCatalog.cpp',
    '#src/team/stats/MetricSeries.cpp',
    '#src/game/rules/TeamLayout.cpp',
    '#src/unit/UnitUtils.cpp',
    '#src/game/player/BasePlayer.cpp',
    '#src/team/BaseTeam.cpp',
    '#src/game/Bullet.cpp',
    '#src/game/ExperimentalFeatures.cpp',
    '#src/game/GameHeader.cpp',
    '#src/building/types/BuildingCatalog.cpp',
    '#src/building/types/Buildings.cpp',
    '#src/building/types/BuildingTypesColony.cpp',
    '#src/building/types/BuildingTypesDefence.cpp',
    '#src/building/types/BuildingTypesFlags.cpp',
    '#src/building/types/BuildingTypesUpgrade.cpp',
    '#src/game/GameHints.cpp',
    '#src/game/GameObjectives.cpp',
    '#src/render/clouds/SimplexNoise.cpp',
    '#src/game/WinningConditions.cpp',
    '#src/team/stats/WinProbability.cpp',
    '#src/map/io/MapExploredAreaIO.cpp',
    '#src/online/HttpFetchCommon.cpp',
    '#src/online/InstanceConfig.cpp',
    '#src/online/InviteLink.cpp',
    '#src/online/MapCache.cpp',
    '#src/online/MapCatalog.cpp',
    '#src/online/OnlineHandoff.cpp',
    '#src/online/OnlineResources.cpp',
    '#src/online/MemoryStorage.cpp',
    '#src/online/PlatformClient.cpp',
    '#src/online/PlatformProtocol.cpp',
    '#src/online/QuickMatch.cpp',
    '#src/online/RelayProbe.cpp',
    '#src/online/Sha256.cpp',
    '#src/online/SkinAuthorization.cpp',
    '#src/online/SkinDownloads.cpp',
    '#src/online/SkinSpriteManifest.cpp',
    '#src/online/SkinSprites.cpp',
    '#src/online/ReplayAppearance.cpp',
    '#src/online/SimVersion.cpp',
    '#src/campaign/Campaign.cpp',
    '#src/audio/SoundMixer.cpp',
    '#mobile/Documents.cpp',
    ('#mobile/CertificateTrust.cpp', dict(require={'wss'})),
    ('#mobile/TemporaryFiles.cpp', dict(require={'not-mingw'})),
    '#src/net/turn/JitterBuffer.cpp',
    '#src/net/turn/MatchRecord.cpp',
    '#src/net/turn/TurnMessages.cpp',
    '#src/net/turn/TurnSequencer.cpp',
    '#src/net/turn/TurnSession.cpp',
    '#src/net/turn/TurnTelemetry.cpp',
    '#src/replay/ReplayReader.cpp',
    '#src/replay/ReplayWriter.cpp',
    '#src/replay/ReplayTelemetry.cpp',
    # Without the client's Brush and Game surfaces: only the byte marshalers are wanted.
    ('#src/game/orders/OrderModify.cpp', dict(defines=['GLOB2_ORDER_CODEC_ONLY'])),
    ('#src/game/orders/OrderBuilding.cpp', dict(defines=['GLOB2_ORDER_CODEC_ONLY'])),
    ('#src/net/message/OrderMessages.cpp', dict(defines=['GLOB2_ORDER_CODEC_ONLY'])),
]

# Replacement definitions for production symbols the unit binary does not link.
UNIT_STUBS = [
    'unit/stubs/MapSectorStubs.cpp',
    'unit/stubs/MapHeaderStubs.cpp',
    'unit/stubs/OrderStubs.cpp',
    'unit/stubs/GameGUIStubs.cpp',
    'unit/stubs/RaceStubs.cpp',
]

# Standalone programs: (target, source, alias, group). group 'test' programs are run by
# CI through their own runners; 'tools' are developer utilities and benchmarks. The
# transport programs the browser tests drive stay in src/SConscript under 'transport-test'.
PROGRAMS = [
    ('SaveSizeHarness', 'SaveSizeHarness.cpp', 'save-size-harness', 'tools'),

    ('recording-multiplayer-peer', '#src/net/turn/RecordingMultiplayerPeer.cpp', 'recording-multiplayer-test', 'tools'),
    ('MapReportHarness', '#src/map/tools/MapReportHarness.cpp', 'map-report-test', 'test'),
    ('MaximaStrategyDump', '#src/ai/maxima/MaximaStrategyDump.cpp', 'maxima-strategy-dump', 'tools'),
    ('MenuColonyHarness', '#tools/MenuColonyHarness.cpp', 'menu-colony-harness', 'test'),
    ('AssetLoadingBenchmark', '#tools/AssetLoadingBenchmark.cpp', 'asset-loading-benchmark', 'tools'),
    ('SoftwareRenderBenchmark', '#src/render/SoftwareRenderBenchmark.cpp', 'software-render-benchmark', 'tools'),
    ('torus-render-benchmark', '#src/render/torus/TorusRenderBenchmark.cpp', 'torus-render-benchmark', 'tools'),
]

# Old per-harness alias -> test binary. Kept for one release so documented commands and
# shell history keep working; delete after that.
LEGACY_ALIASES = {
    'ai-save-portability-test': 'glob2-engine-tests',
    'building-expel-test': 'glob2-engine-tests',
    'building-footprint-test': 'glob2-engine-tests',
    'building-gradient-invalidation-test': 'glob2-engine-tests',
    'clearing-gradient-test': 'glob2-engine-tests',
    'comb-generator-test': 'glob2-engine-tests',
    'cortex-geometry-test': 'glob2-engine-tests',
    'entering-unit-save-test': 'glob2-engine-tests',
    'fetch-apportionment-test': 'glob2-engine-tests',
    'global-gradient-test': 'glob2-unit-tests',
    'gradient-invalidation-test': 'glob2-engine-tests',
    'hiring-bucket-test': 'glob2-engine-tests',
    'hungry-defeat-test': 'glob2-engine-tests',
    'immobile-unit-gradient-test': 'glob2-engine-tests',
    'inn-swap-test': 'glob2-engine-tests',
    'level-gate-test': 'glob2-engine-tests',
    'map-render-resize-test': 'glob2-engine-tests',
    'maxima-continuation-test': 'glob2-unit-tests',
    'maxima-food-ledger-test': 'glob2-unit-tests',
    'maxima-relocation-test': 'glob2-engine-tests',
    'nicowar-farming-test': 'glob2-engine-tests',
    'orchard-conversion-test': 'glob2-engine-tests',
    'path-gradient-test': 'glob2-unit-tests',
    'point-bar-render-test': 'glob2-engine-tests',
    'portable-game-test': 'glob2-engine-tests',
    'resource-fetch-target-test': 'glob2-engine-tests',
    'round-trip-hunger-gate-test': 'glob2-engine-tests',
    'runtime-continuation-test': 'glob2-engine-tests',
    'savegame-safety-test': 'glob2-engine-tests',
    'selection-test': 'glob2-engine-tests',
    'session-test': 'glob2-engine-tests',
    'team-stats-save-test': 'glob2-engine-tests',
    'terrain-test': 'glob2-engine-tests',
    'tournament-compatibility-test': 'glob2-engine-tests',
    'trapped-unit-test': 'glob2-engine-tests',
    'unit-continuation-test': 'glob2-engine-tests',
    'torus-render-test': 'glob2-engine-tests',
    'unit-render-tests': 'glob2-engine-tests',
    'unit-hd-cache-test': 'glob2-engine-tests',
    'runtime-pack-check': 'glob2-engine-tests',
    'aspect-test': 'glob2-engine-tests',
    'resize-test': 'glob2-engine-tests',
    'text-raster-test': 'glob2-engine-tests',
    'portable-renderer-test': 'glob2-engine-tests',
    'failing-unit-markers-test': 'glob2-engine-tests',
    'entering-unit-draw-test': 'glob2-engine-tests',
    'highres-integration-test': 'glob2-engine-tests',
    'settings-tests': 'glob2-engine-tests',
    'speed-tests': 'glob2-engine-tests',
    'gameplay-touch-test': 'glob2-engine-tests',
    'ui-presentation-test': 'glob2-engine-tests',
    'custom-setup-test': 'glob2-engine-tests',
    'map-preview-test': 'glob2-engine-tests',
    'map-generator-defaults-test': 'glob2-engine-tests',
    'buffered-file-test': 'glob2-unit-tests',
    'compute-executor-test': 'glob2-unit-tests',
    'gradient-pipeline-test': 'glob2-unit-tests',
    'mobile-certificate-test': 'glob2-unit-tests',
    'mobile-documents-test': 'glob2-unit-tests',
    'mobile-input-test': 'glob2-unit-tests',
    'mobile-temporary-files-test': 'glob2-unit-tests',
    'performance-telemetry-test': 'glob2-unit-tests',
    'screen-test': 'glob2-unit-tests',
    'ui-layout-test': 'glob2-unit-tests',
}


def scripting_entries():
    """Shared in-process corpus for browser and the standalone iOS test app.

    TeamStatsSaveHarness owns the production conversion fixture and lifecycle
    cases. Its unrelated registered cases are excluded by the JavaScript* suite
    filter. Both desktop binaries and Android use the full registry above.
    """
    selected = {'#src/scripting/javascript/ScriptCompatibilityTest.cpp', '#src/scripting/javascript/ScriptIntegrationTest.cpp', '#src/scripting/javascript/ScriptPresentationTest.cpp',
                '#src/scripting/javascript/ScriptRealisticTest.cpp', '#src/scripting/javascript/ScriptSessionTest.cpp', '#src/scripting/javascript/ScriptSimulationTest.cpp',
                '#src/team/stats/TeamStatsSaveHarness.cpp', '#src/scripting/javascript/ScriptRuntimeTest.cpp', '#src/scripting/javascript/ScriptNumericTest.cpp', '#libgag/src/ImageAssetTest.cpp'}
    return [entry for entry in ENGINE_TESTS + UNIT_TESTS
            if (entry if isinstance(entry, str) else entry[0]) in selected]


def source_path(source):
    """Repository-relative path of a registry entry."""
    return source[1:] if source.startswith('#') else 'test/' + source
