
import sys, os, ntpath, glob
Import("env")
Import("PackTar")
if env['mingwcross']:
    Import("crossroot_abs")


if 'dist' or 'install' in COMMAND_LINE_TARGETS:
    PackTar(env["TARFILE"], "glob2.ico")
    PackTar(env["TARFILE"], "header.bmp")
    PackTar(env["TARFILE"], "side.bmp")
    PackTar(env["TARFILE"], "win32_installer.nsi")

    PackTar(env["TARFILE"], "SConscript")


if 'dist' not in COMMAND_LINE_TARGETS:
    Return()



def genlists():
    #
    # FUNCTION TAKEN FROM http://nsis.sourceforge.net/Talk:Uninstall_only_installed_files
    #
    def open_file_for_writing(filename):
        "return a handle to the file to write to"
        try:
            h = open(filename, "w")
        except:
            print "Problem opening file %s for writing" % filename
            print __doc__
            sys.exit(1)
        return h

    #
    # OPEN FILES
    #
    install_list = open_file_for_writing("install_list.nsh")
    uninstall_list = open_file_for_writing("uninstall_list.nsh")

    #
    # PREPARE ARRAY FOR UNINSTALL LIST
    #
    folder_list = []
    file_list = []

    #
    # INSTALL LIST
    #
    for path, dirs, files in list(os.walk('../data')) + list(os.walk('../maps')) + list(os.walk('../campaigns')) + list(os.walk('../scripts')):
        if env['mingwcross']:
            path = ntpath.normpath(path)        # Switch / to \\
        path = path[3:]     # Strip '..\\' from path.
        print >> install_list, "SetOutPath $INSTDIR\\" + path
        folder_list.append(path)
        for f in files:
            if (f != "SConscript" and f != "SConstruct"):
                print >> install_list, "File ..\\" + path + "\\" + f
                file_list.append(path + "\\" + f)

    print >> install_list, "SetOutPath $INSTDIR"

    dllpaths = ['..']
    if env['mingwcross']:
        dllpaths = [crossroot_abs + '/bin', crossroot_abs + '/lib']

    for cpath in dllpaths:
        if not os.path.exists(cpath):
            continue
        for file in list(os.listdir(cpath)):
            if (file.find(".dll", -4) != -1):
                if env['mingwcross']:
                    cpath = ntpath.normpath(cpath)      # Switch / to \\
                print >> install_list, "File %s\\%s" % (cpath, file)
                file_list.append(file)


    #
    # UNINSTALL LIST
    #
    file_list.reverse()
    for file in file_list:
        print >> uninstall_list, "Delete $INSTDIR\\" + file
    folder_list.reverse()
    for folder in folder_list:
        print >> uninstall_list, "RMDir $INSTDIR\\" + folder

    #
    # CLOSE FILES
    #
    install_list.close()
    uninstall_list.close()





Execute(Delete('install_list.nsh'))
Execute(Delete('uninstall_list.nsh'))
genlists()
if Execute('makensis win32_installer.nsi'):
    Exit(1)

