import os
Import("env")
Import("PackTar")

if 'dist' or 'install' in COMMAND_LINE_TARGETS:
    for file in os.listdir("."):
        if file.find(".png") != -1:
            PackTar(env["TARFILE"], file)
            env.Install(env["INSTALLDIR"]+"/glob2/data/gfx", file)

    env.Alias("install", env["INSTALLDIR"]+"/glob2/data/gfx")

    PackTar(env["TARFILE"], "SConscript")

SConscript("cursor/SConscript")
SConscript("gui/SConscript")
