language: c

services:
- docker

env:
  matrix:
   #- BUILD_IMG=ubuntu:16.04 DEPS=python3 # requires a manually installed scons version which works with Python 3
   - BUILD_IMG=ubuntu:18.04 DEPS="python3    "
   - BUILD_IMG=ubuntu:20.04 DEPS="   "
   - BUILD_IMG=ubuntu:20.10 DEPS="   "
   - BUILD_IMG=ubuntu:21.04 DEPS="   "

script: docker run --rm=true -v $HOME:$HOME:rw $BUILD_IMG /bin/sh -c "sed -i '/^#\sdeb-src /s/^#//' /etc/apt/sources.list && apt-get update && env DEBIAN_FRONTEND=noninteractive apt-get build-dep --yes glob2 && env DEBIAN_FRONTEND=noninteractive apt-get install --yes $DEPS cmake libfreetype6-dev libx11-dev libxext-dev libxcursor-dev libxi-dev libxrandr-dev libasound2-dev libpulse-dev && cd $PWD && python3 scons/sdl3_dependencies.py --prefix build/sdl3/prefix --work build/sdl3/sources && export GLOB2_SDL3_PREFIX=$PWD/build/sdl3/prefix && /usr/bin/env python3 /usr/bin/scons -j16 && /usr/bin/env python3 /usr/bin/scons -j16 install"
