# Generated from Glob2 CLI 2 command definitions.
_glob2_complete() {
  local cur prev path='' word opts='' values='' kind='' prefix='' i
  cur=${COMP_WORDS[COMP_CWORD]}; prev=${COMP_WORDS[COMP_CWORD-1]}
  if [[ $cur == --*=* ]]; then prev=${cur%%=*}; prefix=$prev=; cur=${cur#*=};
  elif [[ $prev == = ]]; then prev=${COMP_WORDS[COMP_CWORD-2]}; fi
  for ((i=1;i<COMP_CWORD;i++)); do
    word=${COMP_WORDS[i]}
    if [[ $i == 1 && $word == help ]]; then continue; fi
    case "$path|$word" in
      '|play') path='play';;
      '|replay') path='replay';;
      '|map') path='map';;
      '|game') path='game';;
      '|match') path='match';;
      '|online') path='online';;
      '|ai') path='ai';;
      '|script') path='script';;
      '|assets') path='assets';;
      '|dev') path='dev';;
      '|info') path='info';;
      '|help') path='help';;
      '|completion') path='completion';;
      'ai|check') path='ai check';;
      'assets|compose-buildings') path='assets compose-buildings';;
      'assets|render-skin') path='assets render-skin';;
      'assets|skin-info') path='assets skin-info';;
      'dev|random-games') path='dev random-games';;
      'dev|stress-maps') path='dev stress-maps';;
      'dev|textshots') path='dev textshots';;
      'dev|dump-resources') path='dev dump-resources';;
      'dev|dump-wheat') path='dev dump-wheat';;
      'dev|dump-tiled') path='dev dump-tiled';;
      'dev|hive-worker') path='dev hive-worker';;
      'game|run') path='game run';;
      'game|repeat') path='game repeat';;
      'info|version') path='info version';;
      'info|sim-version') path='info sim-version';;
      'info|catalog') path='info catalog';;
      'info|paths') path='info paths';;
      'map|generate') path='map generate';;
      'map|study') path='map study';;
      'map|generators') path='map generators';;
      'map|preview') path='map preview';;
      'map|render') path='map render';;
      'map|import-image') path='map import-image';;
      'map|export-image') path='map export-image';;
      'map|inspect-package') path='map inspect-package';;
      'map|validate-set') path='map validate-set';;
      'match|verify') path='match verify';;
      'online|join') path='online join';;
      'online|play-map') path='online play-map';;
      'online|host-map') path='online host-map';;
      'online|turn-client') path='online turn-client';;
      'script|check') path='script check';;
      'script|attach') path='script attach';;
    esac
  done
  case "$path" in
    '') opts='play replay map game match online ai script assets dev info help completion';;
    'ai') opts='check';;
    'assets') opts='compose-buildings render-skin skin-info';;
    'dev') opts='random-games stress-maps textshots dump-resources dump-wheat dump-tiled hive-worker';;
    'game') opts='run repeat';;
    'info') opts='version sim-version catalog paths';;
    'map') opts='generate study generators preview render import-image export-image inspect-package validate-set';;
    'match') opts='verify';;
    'online') opts='join play-map host-map turn-client';;
    'script') opts='check attach';;
    'play') opts='--fullscreen --no-fullscreen --resizable --no-resizable --custom-cursor --no-custom-cursor --mute --no-mute --renderer --graphics-detail --window-size --username --editor-script --record --videoshot --record-fps --record-encoder --record-crf --record-chapter-ticks --data-dir --generator-package --building-catalog --compute-threads --help ';;
    'replay') opts='--fullscreen --no-fullscreen --resizable --no-resizable --custom-cursor --no-custom-cursor --mute --no-mute --renderer --graphics-detail --window-size --username --editor-script --record --videoshot --record-fps --record-encoder --record-crf --record-chapter-ticks --data-dir --generator-package --building-catalog --compute-threads --help ';;
    'map generate') opts='--seed --set --width --height --teams --workers --preview --preview-size --preview-scale --data-dir --generator-package --output --report-file --config --map-image --export-generator-package --help ';;
    'map study') opts='--output-dir --profile --building-catalog --data-dir --generator-package --seed --set --candidates --rotations --write-map --report --perturb --building-artwork --help ';;
    'map generators') opts='--format --data-dir --generator-package --help ';;
    'map preview') opts='--data-dir --generator-package --output --report-file --preview --preview-size --preview-scale --help ';;
    'map render') opts='--data-dir --generator-package --output --render-max-pixels --render-field --field-color --help ';;
    'map import-image') opts='--seed --set --width --height --teams --workers --preview --preview-size --preview-scale --data-dir --generator-package --output --report-file --image-seam-width --help ';;
    'map export-image') opts='--data-dir --generator-package --output --help ';;
    'map inspect-package') opts='--output --report-file --help ';;
    'map validate-set') opts='--report-file --preview --gallery --phase --variation --help ';;
    'game run') opts='--output-dir --profile --building-catalog --data-dir --generator-package --compute-threads --map-file --load-game --generator --game-seed --map-seed --set --candidates --player --ai-param --ai-script --map-script --alliance --win-condition --win-probability --experiment --rule --fork-rule --ticks --gradient-delay --resource-growth-delay --ai-order-delay --save --telemetry --write-replay --benchmark-warmup --diagnostic-fields --diagnostic-interval --diagnostic-png --building-artwork --help ';;
    'game repeat') opts='--data-dir --generator-package --compute-threads --ticks --runs --building-catalog --help ';;
    'match verify') opts='--output-dir --profile --compute-threads --map-file --help ';;
    'online join') opts='--fullscreen --no-fullscreen --resizable --no-resizable --custom-cursor --no-custom-cursor --mute --no-mute --renderer --graphics-detail --window-size --username --editor-script --record --videoshot --record-fps --record-encoder --record-crf --record-chapter-ticks --data-dir --generator-package --building-catalog --compute-threads --instance --help ';;
    'online play-map') opts='--fullscreen --no-fullscreen --resizable --no-resizable --custom-cursor --no-custom-cursor --mute --no-mute --renderer --graphics-detail --window-size --username --editor-script --record --videoshot --record-fps --record-encoder --record-crf --record-chapter-ticks --data-dir --generator-package --building-catalog --compute-threads --instance --hash --title --help ';;
    'online host-map') opts='--fullscreen --no-fullscreen --resizable --no-resizable --custom-cursor --no-custom-cursor --mute --no-mute --renderer --graphics-detail --window-size --username --editor-script --record --videoshot --record-fps --record-encoder --record-crf --record-chapter-ticks --data-dir --generator-package --building-catalog --compute-threads --instance --hash --title --help ';;
    'online turn-client') opts='--output-dir --profile --compute-threads --map-file --orders-per-second --max-seconds --seed --help ';;
    'ai check') opts='--format --help ';;
    'script check') opts='--help ';;
    'script attach') opts='--data-dir --generator-package --help ';;
    'assets compose-buildings') opts='--base --package --artwork-bundle --format --help ';;
    'assets render-skin') opts='--manifest --texture --material --output-dir --help ';;
    'assets skin-info') opts='--format --help ';;
    'dev random-games') opts='--data-dir --generator-package --fullscreen --no-fullscreen --resizable --no-resizable --custom-cursor --no-custom-cursor --mute --no-mute --renderer --graphics-detail --window-size --username --editor-script --record --videoshot --record-fps --record-encoder --record-crf --record-chapter-ticks --compute-threads --display --runs --ticks --ai-types --map --matchup --save-game-as --building-catalog --help ';;
    'dev stress-maps') opts='--data-dir --generator-package --help ';;
    'dev textshots') opts='--fullscreen --no-fullscreen --resizable --no-resizable --custom-cursor --no-custom-cursor --mute --no-mute --renderer --graphics-detail --window-size --username --editor-script --record --videoshot --record-fps --record-encoder --record-crf --record-chapter-ticks --data-dir --generator-package --building-catalog --compute-threads --output-dir --help ';;
    'dev dump-resources') opts='--data-dir --generator-package --help ';;
    'dev dump-wheat') opts='--data-dir --generator-package --team --help ';;
    'dev dump-tiled') opts='--data-dir --generator-package --repeat-x --repeat-y --colonies --swarms --help ';;
    'dev hive-worker') opts='--help ';;
    'info version') opts='--format --help ';;
    'info sim-version') opts='--format --help ';;
    'info catalog') opts='--format --data-dir --generator-package --help ';;
    'info paths') opts='--format --data-dir --help ';;
    'help') opts='--format --help ';;
    'completion') opts='--help ';;
  esac
  case "$path|$prev" in
    'play|--renderer') kind='enum'; values='gpu software';;
    'play|--graphics-detail') kind='enum'; values='full reduced';;
    'play|--window-size') kind='resolution'; values='';;
    'play|--username') kind='string'; values='';;
    'play|--editor-script') kind='enum'; values='sgsl usl';;
    'play|--record') kind='file'; values='';;
    'play|--videoshot') kind='string'; values='';;
    'play|--record-fps') kind='integer'; values='';;
    'play|--record-encoder') kind='enum'; values='auto software';;
    'play|--record-crf') kind='integer'; values='';;
    'play|--record-chapter-ticks') kind='integer'; values='';;
    'play|--data-dir') kind='directory'; values='';;
    'play|--generator-package') kind='file'; values='';;
    'play|--building-catalog') kind='file'; values='';;
    'play|--compute-threads') kind='compute'; values='';;
    'replay|--renderer') kind='enum'; values='gpu software';;
    'replay|--graphics-detail') kind='enum'; values='full reduced';;
    'replay|--window-size') kind='resolution'; values='';;
    'replay|--username') kind='string'; values='';;
    'replay|--editor-script') kind='enum'; values='sgsl usl';;
    'replay|--record') kind='file'; values='';;
    'replay|--videoshot') kind='string'; values='';;
    'replay|--record-fps') kind='integer'; values='';;
    'replay|--record-encoder') kind='enum'; values='auto software';;
    'replay|--record-crf') kind='integer'; values='';;
    'replay|--record-chapter-ticks') kind='integer'; values='';;
    'replay|--data-dir') kind='directory'; values='';;
    'replay|--generator-package') kind='file'; values='';;
    'replay|--building-catalog') kind='file'; values='';;
    'replay|--compute-threads') kind='compute'; values='';;
    'map generate|--seed') kind='integer'; values='';;
    'map generate|--set') kind='assignment'; values='';;
    'map generate|--width') kind='integer'; values='';;
    'map generate|--height') kind='integer'; values='';;
    'map generate|--teams') kind='integer'; values='';;
    'map generate|--workers') kind='integer'; values='';;
    'map generate|--preview') kind='file'; values='';;
    'map generate|--preview-size') kind='integer'; values='';;
    'map generate|--preview-scale') kind='enum'; values='2 4 8';;
    'map generate|--data-dir') kind='directory'; values='';;
    'map generate|--generator-package') kind='file'; values='';;
    'map generate|--output') kind='file'; values='';;
    'map generate|--report-file') kind='file'; values='';;
    'map generate|--config') kind='file'; values='';;
    'map generate|--map-image') kind='file'; values='';;
    'map generate|--export-generator-package') kind='file'; values='';;
    'map study|--output-dir') kind='directory'; values='';;
    'map study|--profile') kind='string'; values='';;
    'map study|--building-catalog') kind='file'; values='';;
    'map study|--data-dir') kind='directory'; values='';;
    'map study|--generator-package') kind='file'; values='';;
    'map study|--seed') kind='integer'; values='';;
    'map study|--set') kind='assignment'; values='';;
    'map study|--candidates') kind='integer'; values='';;
    'map study|--rotations') kind='integer'; values='';;
    'map study|--report') kind='enum'; values='headroom diagnostics timing terrain';;
    'map study|--perturb') kind='string'; values='';;
    'map study|--building-artwork') kind='file'; values='';;
    'map generators|--format') kind='enum'; values='text json';;
    'map generators|--data-dir') kind='directory'; values='';;
    'map generators|--generator-package') kind='file'; values='';;
    'map preview|--data-dir') kind='directory'; values='';;
    'map preview|--generator-package') kind='file'; values='';;
    'map preview|--output') kind='file'; values='';;
    'map preview|--report-file') kind='file'; values='';;
    'map preview|--preview') kind='file'; values='';;
    'map preview|--preview-size') kind='integer'; values='';;
    'map preview|--preview-scale') kind='enum'; values='2 4 8';;
    'map render|--data-dir') kind='directory'; values='';;
    'map render|--generator-package') kind='file'; values='';;
    'map render|--output') kind='file'; values='';;
    'map render|--render-max-pixels') kind='integer'; values='';;
    'map render|--render-field') kind='file'; values='';;
    'map render|--field-color') kind='string'; values='';;
    'map import-image|--seed') kind='integer'; values='';;
    'map import-image|--set') kind='assignment'; values='';;
    'map import-image|--width') kind='integer'; values='';;
    'map import-image|--height') kind='integer'; values='';;
    'map import-image|--teams') kind='integer'; values='';;
    'map import-image|--workers') kind='integer'; values='';;
    'map import-image|--preview') kind='file'; values='';;
    'map import-image|--preview-size') kind='integer'; values='';;
    'map import-image|--preview-scale') kind='enum'; values='2 4 8';;
    'map import-image|--data-dir') kind='directory'; values='';;
    'map import-image|--generator-package') kind='file'; values='';;
    'map import-image|--output') kind='file'; values='';;
    'map import-image|--report-file') kind='file'; values='';;
    'map import-image|--image-seam-width') kind='integer'; values='';;
    'map export-image|--data-dir') kind='directory'; values='';;
    'map export-image|--generator-package') kind='file'; values='';;
    'map export-image|--output') kind='file'; values='';;
    'map inspect-package|--output') kind='file'; values='';;
    'map inspect-package|--report-file') kind='file'; values='';;
    'map validate-set|--report-file') kind='file'; values='';;
    'map validate-set|--preview') kind='file'; values='';;
    'map validate-set|--gallery') kind='enum'; values='0 1';;
    'map validate-set|--phase') kind='integer'; values='';;
    'map validate-set|--variation') kind='integer'; values='';;
    'game run|--output-dir') kind='directory'; values='';;
    'game run|--profile') kind='string'; values='';;
    'game run|--building-catalog') kind='file'; values='';;
    'game run|--data-dir') kind='directory'; values='';;
    'game run|--generator-package') kind='file'; values='';;
    'game run|--compute-threads') kind='compute'; values='';;
    'game run|--map-file') kind='file'; values='';;
    'game run|--load-game') kind='file'; values='';;
    'game run|--generator') kind='string'; values='';;
    'game run|--game-seed') kind='integer'; values='';;
    'game run|--map-seed') kind='integer'; values='';;
    'game run|--set') kind='assignment'; values='';;
    'game run|--candidates') kind='integer'; values='';;
    'game run|--player') kind='string'; values='';;
    'game run|--ai-param') kind='assignment'; values='';;
    'game run|--ai-script') kind='string'; values='';;
    'game run|--map-script') kind='file'; values='';;
    'game run|--alliance') kind='integer'; values='';;
    'game run|--win-condition') kind='enum'; values='death allies prestige opponents script';;
    'game run|--win-probability') kind='integer'; values='';;
    'game run|--experiment') kind='string'; values='';;
    'game run|--rule') kind='assignment'; values='';;
    'game run|--fork-rule') kind='assignment'; values='';;
    'game run|--ticks') kind='integer'; values='';;
    'game run|--gradient-delay') kind='integer'; values='';;
    'game run|--resource-growth-delay') kind='integer'; values='';;
    'game run|--ai-order-delay') kind='integer'; values='';;
    'game run|--save') kind='string'; values='';;
    'game run|--telemetry') kind='enum'; values='checksums team-timeline maxima gradient-stats';;
    'game run|--benchmark-warmup') kind='integer'; values='';;
    'game run|--diagnostic-fields') kind='enum'; values='maxima';;
    'game run|--diagnostic-interval') kind='integer'; values='';;
    'game run|--building-artwork') kind='file'; values='';;
    'game repeat|--data-dir') kind='directory'; values='';;
    'game repeat|--generator-package') kind='file'; values='';;
    'game repeat|--compute-threads') kind='compute'; values='';;
    'game repeat|--ticks') kind='integer'; values='';;
    'game repeat|--runs') kind='integer'; values='';;
    'game repeat|--building-catalog') kind='file'; values='';;
    'match verify|--output-dir') kind='directory'; values='';;
    'match verify|--profile') kind='string'; values='';;
    'match verify|--compute-threads') kind='compute'; values='';;
    'match verify|--map-file') kind='file'; values='';;
    'online join|--renderer') kind='enum'; values='gpu software';;
    'online join|--graphics-detail') kind='enum'; values='full reduced';;
    'online join|--window-size') kind='resolution'; values='';;
    'online join|--username') kind='string'; values='';;
    'online join|--editor-script') kind='enum'; values='sgsl usl';;
    'online join|--record') kind='file'; values='';;
    'online join|--videoshot') kind='string'; values='';;
    'online join|--record-fps') kind='integer'; values='';;
    'online join|--record-encoder') kind='enum'; values='auto software';;
    'online join|--record-crf') kind='integer'; values='';;
    'online join|--record-chapter-ticks') kind='integer'; values='';;
    'online join|--data-dir') kind='directory'; values='';;
    'online join|--generator-package') kind='file'; values='';;
    'online join|--building-catalog') kind='file'; values='';;
    'online join|--compute-threads') kind='compute'; values='';;
    'online join|--instance') kind='string'; values='';;
    'online play-map|--renderer') kind='enum'; values='gpu software';;
    'online play-map|--graphics-detail') kind='enum'; values='full reduced';;
    'online play-map|--window-size') kind='resolution'; values='';;
    'online play-map|--username') kind='string'; values='';;
    'online play-map|--editor-script') kind='enum'; values='sgsl usl';;
    'online play-map|--record') kind='file'; values='';;
    'online play-map|--videoshot') kind='string'; values='';;
    'online play-map|--record-fps') kind='integer'; values='';;
    'online play-map|--record-encoder') kind='enum'; values='auto software';;
    'online play-map|--record-crf') kind='integer'; values='';;
    'online play-map|--record-chapter-ticks') kind='integer'; values='';;
    'online play-map|--data-dir') kind='directory'; values='';;
    'online play-map|--generator-package') kind='file'; values='';;
    'online play-map|--building-catalog') kind='file'; values='';;
    'online play-map|--compute-threads') kind='compute'; values='';;
    'online play-map|--instance') kind='string'; values='';;
    'online play-map|--hash') kind='string'; values='';;
    'online play-map|--title') kind='string'; values='';;
    'online host-map|--renderer') kind='enum'; values='gpu software';;
    'online host-map|--graphics-detail') kind='enum'; values='full reduced';;
    'online host-map|--window-size') kind='resolution'; values='';;
    'online host-map|--username') kind='string'; values='';;
    'online host-map|--editor-script') kind='enum'; values='sgsl usl';;
    'online host-map|--record') kind='file'; values='';;
    'online host-map|--videoshot') kind='string'; values='';;
    'online host-map|--record-fps') kind='integer'; values='';;
    'online host-map|--record-encoder') kind='enum'; values='auto software';;
    'online host-map|--record-crf') kind='integer'; values='';;
    'online host-map|--record-chapter-ticks') kind='integer'; values='';;
    'online host-map|--data-dir') kind='directory'; values='';;
    'online host-map|--generator-package') kind='file'; values='';;
    'online host-map|--building-catalog') kind='file'; values='';;
    'online host-map|--compute-threads') kind='compute'; values='';;
    'online host-map|--instance') kind='string'; values='';;
    'online host-map|--hash') kind='string'; values='';;
    'online host-map|--title') kind='string'; values='';;
    'online turn-client|--output-dir') kind='directory'; values='';;
    'online turn-client|--profile') kind='string'; values='';;
    'online turn-client|--compute-threads') kind='compute'; values='';;
    'online turn-client|--map-file') kind='file'; values='';;
    'online turn-client|--orders-per-second') kind='real'; values='';;
    'online turn-client|--max-seconds') kind='real'; values='';;
    'online turn-client|--seed') kind='integer'; values='';;
    'ai check|--format') kind='enum'; values='text json';;
    'script attach|--data-dir') kind='directory'; values='';;
    'script attach|--generator-package') kind='file'; values='';;
    'assets compose-buildings|--base') kind='file'; values='';;
    'assets compose-buildings|--package') kind='file'; values='';;
    'assets compose-buildings|--artwork-bundle') kind='file'; values='';;
    'assets compose-buildings|--format') kind='enum'; values='text json';;
    'assets render-skin|--manifest') kind='file'; values='';;
    'assets render-skin|--texture') kind='file'; values='';;
    'assets render-skin|--material') kind='file'; values='';;
    'assets render-skin|--output-dir') kind='directory'; values='';;
    'assets skin-info|--format') kind='enum'; values='text json';;
    'dev random-games|--data-dir') kind='directory'; values='';;
    'dev random-games|--generator-package') kind='file'; values='';;
    'dev random-games|--renderer') kind='enum'; values='gpu software';;
    'dev random-games|--graphics-detail') kind='enum'; values='full reduced';;
    'dev random-games|--window-size') kind='resolution'; values='';;
    'dev random-games|--username') kind='string'; values='';;
    'dev random-games|--editor-script') kind='enum'; values='sgsl usl';;
    'dev random-games|--record') kind='file'; values='';;
    'dev random-games|--videoshot') kind='string'; values='';;
    'dev random-games|--record-fps') kind='integer'; values='';;
    'dev random-games|--record-encoder') kind='enum'; values='auto software';;
    'dev random-games|--record-crf') kind='integer'; values='';;
    'dev random-games|--record-chapter-ticks') kind='integer'; values='';;
    'dev random-games|--compute-threads') kind='compute'; values='';;
    'dev random-games|--runs') kind='integer'; values='';;
    'dev random-games|--ticks') kind='integer'; values='';;
    'dev random-games|--ai-types') kind='string'; values='';;
    'dev random-games|--map') kind='string'; values='';;
    'dev random-games|--matchup') kind='string'; values='';;
    'dev random-games|--save-game-as') kind='file'; values='';;
    'dev random-games|--building-catalog') kind='file'; values='';;
    'dev stress-maps|--data-dir') kind='directory'; values='';;
    'dev stress-maps|--generator-package') kind='file'; values='';;
    'dev textshots|--renderer') kind='enum'; values='gpu software';;
    'dev textshots|--graphics-detail') kind='enum'; values='full reduced';;
    'dev textshots|--window-size') kind='resolution'; values='';;
    'dev textshots|--username') kind='string'; values='';;
    'dev textshots|--editor-script') kind='enum'; values='sgsl usl';;
    'dev textshots|--record') kind='file'; values='';;
    'dev textshots|--videoshot') kind='string'; values='';;
    'dev textshots|--record-fps') kind='integer'; values='';;
    'dev textshots|--record-encoder') kind='enum'; values='auto software';;
    'dev textshots|--record-crf') kind='integer'; values='';;
    'dev textshots|--record-chapter-ticks') kind='integer'; values='';;
    'dev textshots|--data-dir') kind='directory'; values='';;
    'dev textshots|--generator-package') kind='file'; values='';;
    'dev textshots|--building-catalog') kind='file'; values='';;
    'dev textshots|--compute-threads') kind='compute'; values='';;
    'dev textshots|--output-dir') kind='directory'; values='';;
    'dev dump-resources|--data-dir') kind='directory'; values='';;
    'dev dump-resources|--generator-package') kind='file'; values='';;
    'dev dump-wheat|--data-dir') kind='directory'; values='';;
    'dev dump-wheat|--generator-package') kind='file'; values='';;
    'dev dump-wheat|--team') kind='integer'; values='';;
    'dev dump-tiled|--data-dir') kind='directory'; values='';;
    'dev dump-tiled|--generator-package') kind='file'; values='';;
    'dev dump-tiled|--repeat-x') kind='integer'; values='';;
    'dev dump-tiled|--repeat-y') kind='integer'; values='';;
    'dev dump-tiled|--colonies') kind='integer'; values='';;
    'dev dump-tiled|--swarms') kind='integer'; values='';;
    'info version|--format') kind='enum'; values='text json';;
    'info sim-version|--format') kind='enum'; values='text json';;
    'info catalog|--format') kind='enum'; values='text json';;
    'info catalog|--data-dir') kind='directory'; values='';;
    'info catalog|--generator-package') kind='file'; values='';;
    'info paths|--format') kind='enum'; values='text json';;
    'info paths|--data-dir') kind='directory'; values='';;
    'help|--format') kind='enum'; values='text json';;
  esac
  COMPREPLY=()
  if [[ -n $values ]]; then while IFS= read -r word; do COMPREPLY+=("$prefix$word"); done < <(compgen -W "$values" -- "$cur");
  elif [[ $kind == directory ]]; then while IFS= read -r word; do COMPREPLY+=("$prefix$word"); done < <(compgen -d -- "$cur");
  elif [[ $kind == file ]]; then while IFS= read -r word; do COMPREPLY+=("$prefix$word"); done < <(compgen -f -- "$cur");
  elif [[ -z $kind ]]; then while IFS= read -r word; do COMPREPLY+=("$word"); done < <(compgen -W "$opts" -- "$cur");
    if [[ $cur != -* && -n $path ]]; then while IFS= read -r word; do COMPREPLY+=("$word"); done < <(compgen -f -- "$cur"); fi
  fi
}
complete -F _glob2_complete glob2
