#!/bin/sh
rsync -z --delete-after data/gfx/*.png glob2@yog.globulation2.org:~/rsync/data/gfx/
rsync -z --delete-after data/gfx/cursor/*.png glob2@yog.globulation2.org:~/rsync/data/gfx/cursor/
rsync -z --delete-after data/fonts/*.ttf glob2@yog.globulation2.org:~/rsync/data/fonts/
rsync -z --delete-after data/gui/*.png glob2@yog.globulation2.org:~/rsync/data/gui/
rsync -z --delete-after data/zik/*.ogg glob2@yog.globulation2.org:~/rsync/data/zik/
rsync -z --delete-after data/icons/*.png glob2@yog.globulation2.org:~/rsync/data/icons/
