#!/bin/sh
rsync -z --delete-after data/gfx/*.png glob2@yog.globulation2.org:~/glob2data/gfx/
rsync -z --delete-after data/gfx/cursor/*.png glob2@yog.globulation2.org:~/glob2data/gfx/cursor
rsync -z --delete-after data/fonts/*.ttf glob2@yog.globulation2.org:~/glob2data/fonts/
rsync -z --delete-after data/gui/*.png glob2@yog.globulation2.org:~/glob2data/gui/
rsync -z --delete-after data/zik/*.ogg glob2@yog.globulation2.org:~/glob2data/zik/
rsync -z --delete-after data/icons/*.png glob2@yog.globulation2.org:~/glob2data/icons/
