import { firefox } from '../../platform/node_modules/playwright-core/index.mjs';
const browser = await firefox.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.route('**/api/**', route => route.fulfill({status:401, body:'{}'}));
await page.goto('http://127.0.0.1:5178/skins');
await page.getByLabel('Skin name').waitFor();
await page.evaluate(() => document.documentElement.dataset.theme = 'dark');
await page.getByLabel('Choose paint color', { exact:true }).click();
await page.getByLabel('Paint color', {exact:true}).fill('#8e52cc');
await page.getByLabel('Paint color', {exact:true}).press('Tab');
await page.locator('.skin-toolbox .skin-color-picker').first().screenshot({path:'artifacts/color-picker/picker-preview.png'});
await page.locator('.skin-buildings > summary').click();
await page.getByLabel('Choose building color', {exact:true}).click();
await page.getByLabel('Building color', {exact:true}).fill('#39bca2');
await page.getByLabel('Building color', {exact:true}).press('Tab');
if (await page.getByLabel('Building color', {exact:true}).inputValue() !== '#39bca2') throw new Error('Building color did not update');
await page.getByRole('button', {name:'Patterns',exact:true}).click();
await page.getByLabel('Choose pattern color',{exact:true}).click();
await page.getByLabel('Pattern color',{exact:true}).fill('#4aa6df');
await page.getByLabel('Pattern color',{exact:true}).press('Tab');
if (await page.getByLabel('Pattern color', {exact:true}).inputValue() !== '#4aa6df') throw new Error('Pattern color did not update');
console.log('Firefox: building and pattern palettes passed');
await browser.close();
