# SPDX-License-Identifier: GPL-3.0-or-later
"""Command line: ``python3 -m glob2music <command>`` (run from ``tools/music``).

Commands:

    list                      the sets under sets/, with method, licence and status
    fetch SET_ID...           download and verify a set's pinned sources, and for
                              sample sets its locked samples and sfizz_render
    build SET_ID... [--seed N] [--offline] [--no-preview] [--allow-regenerate]
                              recipe -> master -> out/<id>/a1..a3.ogg, preview, qa.json
    check DIR|SET_ID [--json] [--verbose] [--only a,b] [--manifest set.toml]
                              run the QA suite; exit 1 on any fail
    preview DIR|SET_ID [-o OUT] [--crossfade S] [--segment S]
                              calm -> building -> combat -> calm listening file
    install SET_ID [--data-dir DIR]
                              check, then copy into data/zik/<id>/ with SConscripts
    calibrate [--json OUT] [--jobs N]
                              rerun QA over the listening-verdict corpus

``check`` accepts any directory holding a1/a2/a3.ogg. When the directory or argument
names a set under ``sets/``, that set's waivers are applied (``--manifest`` points at
another ``set.toml``). A set id checks ``out/<id>``, or the installed
``data/zik/<id>`` when the set ships and has not been built locally. Exit codes:
0 pass (warnings allowed), 1 a check failed, 2 usage or input error.
"""
import argparse
import logging
from pathlib import Path
import shutil
import sys

from .manifest import OUT_DIR, REPO_ROOT, SETS_DIR, ManifestError, build_set, list_sets, load_manifest, set_spec
from .genai.acestep import GenAIUnavailable, GenerationMismatch
from .sources import SourceError, fetch_source
from .spec import DEFAULT_SPEC, FILENAMES, MOODS

# Installed next to each set's Oggs; installs a1/a2/a3.ogg and LICENSE.txt.
SCONSCRIPT = '''# Installs one soundtrack set: a1/a2/a3.ogg plus its LICENSE.txt.
# Generated by tools/music (python3 -m glob2music install); do not edit by hand.
import os

Import("env")
Import("PackTar")

if 'dist' in COMMAND_LINE_TARGETS or 'install' in COMMAND_LINE_TARGETS:
    source = env.Dir(".").srcnode().abspath
    target = env["INSTALLDIR"] + "/glob2/data/zik/" + os.path.basename(source)
    for file in sorted(os.listdir(source)):
        if file.endswith(".ogg") or file == "LICENSE.txt":
            PackTar(env["TARFILE"], file)
            env.Install(target, file)
    PackTar(env["TARFILE"], "SConscript")
    env.Alias("install", target)
'''


# Licence texts that attribution licences require a link to.
LICENSE_URLS = {
    'CC0-1.0': 'https://creativecommons.org/publicdomain/zero/1.0/',
    'CC-BY-3.0': 'https://creativecommons.org/licenses/by/3.0/',
    'CC-BY-4.0': 'https://creativecommons.org/licenses/by/4.0/',
    'GPL-3.0-or-later': 'https://www.gnu.org/licenses/gpl-3.0.html',
}


def license_text(m):
    """The LICENSE.txt shipped beside a set's Oggs, generated from its set.toml.

    Credit lines, licence, change notes and any AI disclosure all live in set.toml,
    so the notice that travels with the files can never drift from the recipe.
    """
    lines = [f'Globulation 2 soundtrack set "{m.set_id}": {m.title}',
             'Files: a1.ogg (calm), a2.ogg (building), a3.ogg (combat)', '',
             f'Licence: {m.license}' + (f' ({LICENSE_URLS[m.license]})' if m.license in LICENSE_URLS else '')]
    if m.credits:
        lines += ['', 'Credits:'] + [f'  {c}' for c in m.credits]
    if m.ai_generated:
        lines += ['', m.ai['disclosure'].strip(), '']
        for key, label in _AI_PINS:
            if m.ai.get(key) not in (None, ''):
                lines.append(f'{label}: {m.ai[key]}')
        lines.append(f'Prompt and generation settings: tools/music/sets/{m.set_id}/recipe.py and set.toml '
                     'in the Globulation 2 source tree.')
    if m.description.strip():
        lines += ['', m.description.strip()]
    lines += ['', f'Built by tools/music/sets/{m.set_id} in the Globulation 2 source tree.']
    return '\n'.join(lines) + '\n'


#: ``[ai]`` keys copied into an AI-generated set's LICENSE.txt, with their labels.
_AI_PINS = (('model', 'Model'), ('model_code', 'Model code'), ('model_weights', 'Model weights'),
            ('seed', 'Seed'), ('post_processing', 'Post-processing'))


def _resolve(target):
    """(directory, manifest or None) for a check/preview target."""
    p = Path(target)
    if (p / FILENAMES['calm']).exists():
        manifest = None
        if (SETS_DIR / p.name / 'set.toml').exists():
            manifest = load_manifest(p.name)
        return p, manifest
    if (SETS_DIR / target / 'set.toml').exists():
        manifest = load_manifest(target)
        # Reference sets (the original soundtrack) have no recipe; check the files
        # the game ships instead of a build output.
        installed = REPO_ROOT / 'data' / 'zik' / target
        if manifest.method == 'reference':
            return installed, manifest
        # A shipped set that has not been built locally is checked as installed.
        if manifest.shipped and not (OUT_DIR / target / FILENAMES['calm']).exists() \
                and (installed / FILENAMES['calm']).exists():
            return installed, manifest
        return OUT_DIR / target, manifest
    raise FileNotFoundError(f'{target}: neither a directory with a1.ogg nor a set id under {SETS_DIR}')


def cmd_list(args):
    sets = list_sets()
    if not sets:
        print(f'no sets under {SETS_DIR}')
        return 0
    rows = []
    for m in sets:
        built = (OUT_DIR / m.set_id / 'a1.ogg').exists()
        flags = ', '.join(f for f, on in (('shipped', m.shipped), ('AI', m.ai_generated), ('built', built)) if on)
        rows.append((m.set_id, m.method, m.license, flags))
    widths = [max(len(r[i]) for r in rows) for i in range(3)]
    for r in rows:
        print(('  '.join(c.ljust(w) for c, w in zip(r, widths)) + '  ' + r[3]).rstrip())
    return 0


def cmd_fetch(args):
    for set_id in args.sets:
        m = load_manifest(set_id)
        lock = m.path.parent / 'samples.lock'
        for s in m.sources:
            print(f'{set_id}: {s.name} -> {fetch_source(s, offline=args.offline)}')
        if lock.exists():
            # Sample sets pin their files in samples.lock rather than [[sources]].
            from .backends import sfizz
            entries = sfizz.read_lock(lock)
            sfizz.materialize(entries, offline=args.offline)
            libraries = sorted({e.library for e in entries})
            print(f'{set_id}: {len(entries)} locked sample files -> '
                  + ', '.join(str(sfizz.library_root(lib)) for lib in libraries))
            print(f'{set_id}: sfizz_render -> {sfizz.sfizz_render(offline=args.offline)}')
        if not m.sources and not lock.exists():
            print(f'{set_id}: nothing to fetch (no [[sources]] in set.toml and no samples.lock)')
        if m.method == 'generated':
            print(f'{set_id}: generated audio cannot be fetched; maintainers hold the approved generation '
                  f'locally (see sets/{set_id}/recipe.py and glob2music/genai/acestep.py)')
    return 0


def cmd_build(args):
    status = 0
    for set_id in args.sets:
        _, report = build_set(set_id, seed=args.seed, offline=args.offline, preview=not args.no_preview,
                              allow_regenerate=args.allow_regenerate)
        print(report.format_table())
        status |= int(report.failed)
    return status


def cmd_check(args):
    from .qa import run_checks
    directory, manifest = _resolve(args.target)
    if args.manifest:
        manifest = load_manifest(args.manifest)
    waivers = manifest.waivers if manifest else {}
    only = None
    if args.only:
        from .qa import CHECK_NAMES
        only = {name.strip() for name in args.only.split(',') if name.strip()}
        unknown = sorted(only - set(CHECK_NAMES))
        if unknown or not only:
            print(f'error: unknown check name(s) {", ".join(unknown) or "(none given)"}; '
                  f'valid names: {", ".join(CHECK_NAMES)}', file=sys.stderr)
            return 2
    spec = set_spec(manifest) if manifest else DEFAULT_SPEC
    report = run_checks(directory, spec=spec, waivers=waivers, only=only)
    print(report.to_json() if args.json else report.format_table(verbose=args.verbose))
    return 1 if report.failed else 0


def cmd_preview(args):
    from . import preview
    directory, _ = _resolve(args.target)
    out = Path(args.output) if args.output else directory / 'preview.ogg'
    preview.make(directory, out, crossfade_s=args.crossfade, segment_s=args.segment)
    print(out)
    return 0


def _registered_sconscript(zik_dir, set_id):
    """The text of data/zik/SConscript with ``set_id`` in its list of set directories.

    Raises ``ManifestError`` when the file is missing or does not have the expected
    shape (the original ``SConscript("original/SConscript")`` call or the generated
    ``for music_set in (...)`` loop), so ``install`` can refuse before copying files.
    """
    path = Path(zik_dir) / 'SConscript'
    if not path.exists():
        raise ManifestError(f'{path}: not found; is {zik_dir} a data/zik directory?')
    text = path.read_text()
    original, loop_head = 'SConscript("original/SConscript")', 'for music_set in ('
    if original not in text and loop_head not in text:
        raise ManifestError(f'{path}: found neither {original} nor a "{loop_head}...)" loop to extend')
    sets = sorted({d.parent.name for d in Path(zik_dir).glob('*/SConscript')} | {set_id})
    sets = ['original'] + [s for s in sets if s != 'original']
    loop = loop_head + ', '.join(f'"{s}"' for s in sets) + '):\n    SConscript(music_set + "/SConscript")\n'
    head = text.split(original)[0].split(loop_head)[0].rstrip() + '\n\n'
    return head + loop


def _register_set(zik_dir, set_id):
    """Add ``set_id`` to data/zik/SConscript's list of set directories (idempotent)."""
    text = _registered_sconscript(zik_dir, set_id)
    (Path(zik_dir) / 'SConscript').write_text(text)


def cmd_install(args):
    from .qa import run_checks
    m = load_manifest(args.set_id)
    src = OUT_DIR / m.set_id
    report = run_checks(src, spec=set_spec(m), waivers=m.waivers)
    print(report.format_table())
    if report.failed:
        print(f'{m.set_id}: QA failed; not installed', file=sys.stderr)
        return 1
    if not m.shipped and not args.unshipped:
        print(f'{m.set_id}: set.toml has shipped = false (pass --unshipped to install anyway)', file=sys.stderr)
        return 2
    zik = Path(args.data_dir) if args.data_dir else REPO_ROOT / 'data' / 'zik'
    _registered_sconscript(zik, m.set_id)       # validate before touching any file
    dest = zik / m.set_id
    dest.mkdir(parents=True, exist_ok=True)
    for mood in MOODS:
        shutil.copyfile(src / FILENAMES[mood], dest / FILENAMES[mood])
    (dest / 'SConscript').write_text(SCONSCRIPT)
    (dest / 'LICENSE.txt').write_text(license_text(m))
    _register_set(zik, m.set_id)
    print(f'installed {m.set_id} into {dest}')
    return 0


def cmd_calibrate(args):
    from .qa.calibrate import calibrate, contract_summary
    results = calibrate(jobs=args.jobs, json_out=args.json)
    return 0 if contract_summary(results).startswith('Contract met') else 1


def main(argv=None):
    ap = argparse.ArgumentParser(prog='glob2music', description=__doc__.split('\n\n')[0])
    ap.add_argument('-v', '--log', action='store_true', help='log build progress')
    sub = ap.add_subparsers(dest='command', required=True)
    sub.add_parser('list', help='list sets').set_defaults(fn=cmd_list)
    p = sub.add_parser('fetch', help='download pinned sources')
    p.add_argument('sets', nargs='+')
    p.add_argument('--offline', action='store_true')
    p.set_defaults(fn=cmd_fetch)
    p = sub.add_parser('build', help='build sets')
    p.add_argument('sets', nargs='+')
    p.add_argument('--seed', type=int)
    p.add_argument('--offline', action='store_true')
    p.add_argument('--no-preview', action='store_true')
    p.add_argument('--allow-regenerate', action='store_true',
                   help='accept generated audio whose SHA-256 differs from the recorded one '
                        '(a new, unreviewed piece; see glob2music/genai/acestep.py)')
    p.set_defaults(fn=cmd_build)
    p = sub.add_parser('check', help='run the QA suite on a trio directory or set id')
    p.add_argument('target')
    p.add_argument('--json', action='store_true', help='machine-readable report')
    p.add_argument('--verbose', action='store_true', help='list every measure')
    p.add_argument('--only', help='comma-separated check names')
    p.add_argument('--manifest', help='set.toml whose waivers apply')
    p.set_defaults(fn=cmd_check)
    p = sub.add_parser('preview', help='write a listening preview')
    p.add_argument('target')
    p.add_argument('-o', '--output')
    p.add_argument('--crossfade', type=float, default=3.0)
    p.add_argument('--segment', type=float, default=40.0)
    p.set_defaults(fn=cmd_preview)
    p = sub.add_parser('install', help='install a built set into data/zik')
    p.add_argument('set_id')
    p.add_argument('--data-dir')
    p.add_argument('--unshipped', action='store_true')
    p.set_defaults(fn=cmd_install)
    p = sub.add_parser('calibrate', help='rerun QA over the calibration corpus')
    p.add_argument('--json')
    p.add_argument('--jobs', type=int, default=4)
    p.set_defaults(fn=cmd_calibrate)
    args = ap.parse_args(argv)
    logging.basicConfig(level=logging.INFO if args.log else logging.WARNING, format='%(name)s: %(message)s')
    try:
        return args.fn(args)
    except (FileNotFoundError, ManifestError, SourceError, GenAIUnavailable, GenerationMismatch) as e:
        print(f'error: {e}', file=sys.stderr)
        return 2


if __name__ == '__main__':
    sys.exit(main())
