from pathlib import Path
import json
r=Path('artifacts/resource-growth/attribution-v2');s=json.load(open(r/'summary.json'))
def percent(d):return f"{d['median']*100:+.1f}% [{d['ci95'][0]*100:+.1f}, {d['ci95'][1]*100:+.1f}]"
lines=['# Remaining resource-growth cost: controlled ablations and copy-path experiments','',
'Source under test: `5430ef31c135667deeb8043c827d79b3fec4cda4`. Original immediate implementation: `d42d3e512`. These are experimental binaries built from copied translation units; production objects and the source branch were not replaced. Compiler/link commands and generated sources accompany this report. The baseline data/source root remains paired with its archived executable.', '',
'## Proposal writes','',
'The count-only kernel reads identical snapshots and consumes identical RNG draws, preserving the proposal count and sampled-cell count while omitting record stores. Inputs and RNGs are reset outside timing. Fifteen map/scenario combinations, 128 correctness seeds each, one warm-up and ten measured pairs of 1,024 calculations. There are no proposal-vector growth allocations in the measured kernel.', '',
'The first ablation unexpectedly became slower: GCC inlined its proposal helper while outlining the writer. Merely adding a second diagnostic function also changed the writer’s inlining decision. Those raw trials are retained as `writes.json` and `writes-outlined.json`, but the controlled result is `writes-matched.json`: BOTH helpers explicitly use the same noinline boundary. Generated symbol sizes confirm outer loops of 0x1df1 and 0x1da2 bytes. This is an ablation, not an exact instruction-by-instruction decomposition; code generation can still differ.', '',
'| Map | Scenario | Kernel time saved by omitting records, 95% interval | Absolute saving, µs/batch | Proposals/batch |','|---|---|---:|---:|---:|']
for key,d in s['writes-matched'].items():
 size,scenario=key.split('-');lines.append(f"| {size}² | {scenario} | {percent(d['reduction'])} | {d['saved_us_per_batch']['median']:+.3f} | {d['proposals_per_batch']:.1f} |")
lines+=['','Removing stores is generally around a 0–2% change in these warm-input controls, sometimes negative. It does not identify proposal packing or reserved-vector stores as a large remaining bottleneck. It does not establish their cost for cold inputs or arbitrary custom resource definitions.', '',
'## Identical-input snapshot controls','',
'The baseline consumer requests the gradient-style Catalogs/Terrain/Resources/Occupancy/Areas union. Growth adds Growth/Rules and, when necessary, a capture every tick. Both modes receive the same sixteen deterministic stock edits per tick outside timing, and final stocks match. Initial captures and growth-field preparation are outside timing. Each case measures 256 ticks, one warm-up and ten rotated pairs.', '',
'| Map | Existing capture cadence | Existing capture ms | With growth ms | Extra capture ms, 95% interval | Tracked copied MB, existing → growth |','|---|---:|---:|---:|---:|---:|']
for key,d in s['capture'].items():
 size,cadence=key.split('-cadence');x=d['extra_ms'];lines.append(f"| {size}² | {cadence} | {d['baseline_ms']:.3f} | {d['growth_ms']:.3f} | {x['median']:+.3f} [{x['ci95'][0]:+.3f}, {x['ci95'][1]:+.3f}] | {d['baseline_MB']:.2f} → {d['growth_MB']:.2f} |")
lines+=['','At the same per-tick boundary with the necessary arrays already captured, growth adds no measurable capture cost and exactly zero additional copied array bytes here. Additional capture frequency has a cost.', '',
'A separate control keeps the capture cadence and edits fixed, warms 32 ticks to populate the buffer pool, then measures 256 ticks while retaining 0/1/4/8 prior growth projections. Retention does not change stocks. It changes how old the available pooled buffers are.', '',
'| Map | Retained snapshots | Capture ms | Tracked copied MB |','|---|---:|---:|---:|']
for key,d in s['retention'].items():
 size,retained=key.split('-retain');lines.append(f"| {size}² | {retained} | {d['capture_ms']:.3f} | {d['copied_MB']:.2f} |")
lines+=['','This identifies a retention mechanism, not the actual growth lease duration in every engine workload. Growth releases its snapshot when calculation completes, not at publication. The eight-tick publication horizon therefore does not imply eight-tick snapshot retention.', '',
'## Publication/statistics ablation','',
'The diagnostic omits growth-statistics writes while keeping all resource mutations and acceptance/clamping counters. This is NOT a valid production mode. All growth counters and final engine checksums match in the four fixtures; checksum equality alone does not validate statistics, which are intentionally missing. Existing display statistics must be preserved.', '',
'| Scenario | Publication time reduction | Whole-engine throughput gain | Saved wall ms / 1,024 ticks |','|---|---:|---:|---:|']
for scenario,data in s['statistics'].items():
 d=data['no-statistics'];p=d.get('growth_publicationNs');lines.append(f"| {scenario} | {percent(p['reduction']) if p else 'no growth'} | {percent(d['throughput_gain'])} | {d['run_ns']['saved_ms']['median']:+.2f} |")
lines+=['','Statistics consume much of dense publication time, but removing them produces only a small or inconclusive total-engine change. A valid alternative was tested: aggregate global material counters per batch, use bit masks to visit covered teams, and use map shifts/masks instead of division for coordinates. It passes differential checks against original publication for 32,768 mixed signed operations, four teams, overlapping coverage, and material stocks after each batch (3,146,307 assertions), plus all ten growth tests. Its actual throughput result is below; fewer-looking operations did not guarantee a win.', '',
'## Copy-path candidate and complete-engine measurements','',
'Current dirty-chunk refresh performs sixteen row copies per dirty 16×16 chunk. The candidate counts dirty chunks and chooses one contiguous array copy when more than half are dirty. It deliberately copies some unchanged cells to reduce tiny-copy overhead. This applies to shared snapshot arrays, not just growth.', '',
'One warm-up and ten rotated paired repetitions, 1,024 ticks, four executor slots, growth delay eight, fixed AI/gradient settings and identical starting saves. Timers include final compute drain and omit per-tick checksum sidecars. Every candidate has matching final checksums and growth counters against the current implementation. The batched statistics candidate is a separate variant; it is not combined with the copy change.', '',
'| Scenario | Batched-statistics throughput gain | Large-copy throughput gain | Large-copy process CPU reduction |','|---|---:|---:|---:|']
for scenario,data in s['batched'].items():
 a=data['batched-statistics'];b=data['bulk-copy'];lines.append(f"| {scenario} | {percent(a['throughput_gain'])} | {percent(b['throughput_gain'])} | {percent(b['benchmark_run_cpu_ns']['reduction'])} |")
lines+=['','The statistics candidate is not adopted: it regresses dense throughput and does not establish a gain elsewhere. The copy candidate improves the multi-material case; other scenarios must be judged by their intervals, not their point estimates.', '',
'## Fair optimized-original comparison','',
'The SAME dirty-copy threshold is applied to the original immediate engine and the delayed shared engine. Ten paired measurements after one warm-up per fixture. This avoids attributing a generally useful snapshot optimization solely to parallel growth. These are still different gameplay revisions: RNG sequencing, within-pass feedback, publication timing and one-unit multi-material seeds differ. Earlier ecology measurements quantify those differences; no exact old/new behavioral equivalence is claimed.', '',
'| Scenario | Optimized original median ticks/s | Optimized delayed median ticks/s | Delayed throughput gain, 95% interval | Delayed CPU change |','|---|---:|---:|---:|---:|']
for scenario,d in s.get('fair',{}).items():lines.append(f"| {scenario} | {d['legacy_TPS']:.1f} | {d['current_TPS']:.1f} | {percent(d['throughput_gain'])} | {percent(d['cpu_change'])} |")
lines+=['','Ticks/s columns are independent medians; gains are paired ratios and need not equal ratios of the displayed medians.', '',
'## Coarse CPU attribution','',
'Five measured repetitions after warm-up. Thread-CPU clocks wrap capture, calculation, publication, submission, gradient seeding/propagation and AI; nested scopes subtract child CPU. This avoids treating queue latency or descheduling as computation. Instrumented results are attribution evidence, not speedup measurements. Small scopes include probe overhead. Values below are median CPU ms per 1,024 ticks; independent medians need not sum exactly.', '',
'| Scenario / revision | Snapshot capture | Growth calculation or old immediate pass | Publication | Submission | Gradient seed + propagation | AI | Total process CPU |','|---|---:|---:|---:|---:|---:|---:|']
for scenario,data in s.get('stages',{}).items():
 for variant,d in data.items():lines.append(f"| {scenario} / {variant} | {d['capture']:.1f} | {d['old_growth']+d['calculate']:.1f} | {d['publish']:.1f} | {d['submit']:.1f} | {d['gradient_seed']+d['gradient_propagate']:.1f} | {d['AI']:.1f} | {d['total_cpu']:.1f} |")
lines+=['','Old/new attribution combines implementation overhead with changed game trajectories and integrated source revisions. It must not be read as an identical-work kernel comparison; the dedicated controls above address that question.', '',
'## Measurement limits, interruptions and validation','',
'- Linux x86-64, AMD Threadripper 2950X, GCC 15.2 release/O3. The same SDL3/recording dependencies and production object files are reused. No builds or correctness suites overlap timing. Only light inspection/report work ran during measurements.',
'- Reserve physical cores 0–3 and SMT siblings 16–19; engine affinity 0–3; performance governor. This does not isolate package power, memory bandwidth, shared caches or all kernel work. Intervals are 2,000-resample deterministic bootstrap intervals for paired medians on this host, not population guarantees.',
'- Two original-wrapper attempts stopped when unrelated reservations changed the ordinary root CPU set. Our own exclusive CPU partition remained intact. Both owned groups were removed and governors restored; the first recovery audit explicitly verifies root CPUs/affinity returned. Completed pairs were retained; interrupted runs were not counted. Resume metadata and all failure logs are included.',
'- A local audited wrapper variant allows unrelated root partitions to change ordinary CPUs while still validating our exact effective/exclusive CPU set, root-partition validity, memory node, controllers, unprivileged process identity and engine affinity. It only removes its own group. Five focused fake-system checks validate acceptance of unrelated partitions and rejection of own-partition/memory/overlap changes. Its source and restoration audit are included; it is not a committed infrastructure change.',
'- Snapshot copy candidate: 27 of 28 snapshot tests pass. The sole failure is the old metric assertion requiring exactly three chunks to be copied when three of four chunks changed; the experimental threshold copies all four. Content/isolation assertions pass. This known contract change must be updated/tested before promoting the candidate.',
'- Found a pre-existing accounting gap: `WorldCapture.cpp` copies the multi-material stock sidecar via `copyArray`, which does not increment `storage.bytesCopied`. Full-engine copied-byte counters therefore omit that sidecar and must not be described as total copy traffic. The single-material capture/retention controls do not have that sidecar. Wall/CPU timings are unaffected by this reporting gap.',
'- Native final checksums are checked for both experimental candidates; the statistics differential additionally compares the actual measurement arrays because normal engine checksums do not include them. No cross-platform or actual threadless candidate validation is claimed. Production snapshot contracts, platform coverage and an appropriate copy-policy regression test remain work before adoption.',
'- Fresh master remains `52e4d3dc0440e12ff65494ad3eb1681e9c2c0af3`; the existing tested source integrates `06a106d3a888ef11482a955bddb713d584cd5570`. Only scripting tests/traces differ on that newer base. The source worktree remains clean.',
'', 'Raw rows, source copies, compiler/link commands, test logs, scripts, interrupted audits and successful restoration audits accompany this report. Experimental binaries and object files are omitted from the evidence branch; their hashes are in run metadata.']
lines+=['', '## Direct-owner scheduling control', '', 'OwnerOnly jobs are invisible to workers, but any owner join can execute older queued jobs; they do not necessarily remain uncomputed until their own publication deadline. The first attempted eager control immediately joined each growth batch. Inspection showed that this also steals earlier AI/gradient jobs onto the owner. Its interrupted `owner-control` rows are retained but excluded from pure placement conclusions.', '', 'The corrected direct-owner diagnostic invokes only the pure growth job on the simulation owner at capture, without submitting a growth executor job or draining unrelated jobs, then retains its output until the unchanged eight-tick publication deadline. Shared and direct modes use the SAME experimental executable, large-copy policy, four executor slots, starting saves and AI/gradient settings. Ten rotated measured pairs after one warm-up; 1,024 ticks each. This compares shared execution with a strong serial baseline, including queue and lease effects, rather than claiming to isolate only thread dispatch instructions.', '', '| Scenario | Shared throughput gain vs direct-owner | Shared process CPU change | Saved wall ms / 1,024 ticks |', '|---|---:|---:|---:|']
for scenario,d in s.get('direct-control',{}).items():lines.append(f"| {scenario} | {percent(d['shared_throughput_gain'])} | {percent(d['shared_cpu_change'])} | {d['wall_saved_ms']['median']:+.2f} |")
lines+=['', '| Scenario / mode | Wall ms | Process CPU ms | Capture ms | Tracked copied MB |', '|---|---:|---:|---:|---:|']
for scenario,d in s.get('direct-control',{}).items():
 for mode in ['shared','owner-direct']:
  x=d[mode];lines.append(f"| {scenario} / {mode} | {x['wall_ms']:.1f} | {x['cpu_ms']:.1f} | {x['capture_ms']:.1f} | {x['tracked_copy_MB']:.1f} |")
lines+=['', 'Direct-owner validation: all ten growth tests pass. Six separate 128-tick runs match exact world and replay checksum sidecars between owner/shared for all three active scenarios at delay 8/thread count 4. All timing runs additionally require equal final checksums and growth counters. The direct mode is an experimental scheduling control, not a supported production mode. Earlier eager-join tests had nine passes and one expected deferral-metric failure; their six checksum runs also matched, but this did not make their scheduling comparison clean.', '']
(r/'README.md').write_text('\n'.join(lines)+'\n')
