import os

Import("env")

for file in os.listdir("."):
    if file.find(".ogg") != -1:
        env.Tar(env["TARFILE"], file)
        env.Install(env["INSTALLDIR"]+"/glob2/data/zik", file)

env.Tar(env["TARFILE"], "SConscript")
