# SPDX-License-Identifier: GPL-3.0-or-later
"""Command-line helpers: LICENSE.txt generation, target resolution, install, check
arguments, waiver reporting, Ogg stream parsing and the ACE-Step hash gate."""
import contextlib
import hashlib
import io
from pathlib import Path
import sys
import tempfile
import unittest
from unittest import mock

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from glob2music import cli  # noqa: E402
from glob2music.audio import AudioFormatError, ogg_streams, write_ogg  # noqa: E402
from glob2music.genai import acestep  # noqa: E402
from glob2music.manifest import ManifestError, load_manifest, parse_manifest  # noqa: E402
from glob2music.qa import CHECK_NAMES  # noqa: E402
from glob2music.qa.calibrate import spec_and_waivers  # noqa: E402
from glob2music.qa.result import FAIL, PASS, CheckResult, Report  # noqa: E402
from glob2music.spec import DEFAULT_SPEC, SAMPLE_RATE as SR  # noqa: E402

ZIK_SCONSCRIPT = '''import os

Import("env")

SConscript("original/SConscript")'''


def manifest(**overrides):
    data = {'title': 'Test Set', 'method': 'adapted', 'license': 'CC-BY-4.0', 'shipped': True,
            'credits': ['"Tune" by Someone, CC BY 4.0, https://example.org/tune'],
            'description': 'Changes made:\n- Looped and remixed.'}
    data.update(overrides)
    return parse_manifest(data, 'test-set')


class LicenseTextTest(unittest.TestCase):
    def test_cc_by_carries_credit_licence_link_and_changes(self):
        text = cli.license_text(manifest())
        self.assertIn('Licence: CC-BY-4.0 (https://creativecommons.org/licenses/by/4.0/)', text)
        self.assertIn('"Tune" by Someone, CC BY 4.0', text)
        self.assertIn('Changes made:', text)
        self.assertNotIn('AI-GENERATED', text)
        self.assertTrue(text.endswith('\n'))

    def test_ai_sets_ship_their_disclosure_and_pins(self):
        m = manifest(license='GPL-3.0-or-later', ai_generated=True, ai={
            'model': 'ACE-Step 1.5', 'model_code': 'https://example.org/code @ abc (MIT)',
            'model_weights': 'https://example.org/weights @ def (MIT)', 'seed': 11,
            'disclosure': 'AI-GENERATED AUDIO. The notes were generated by a model.'})
        text = cli.license_text(m)
        self.assertIn('AI-GENERATED AUDIO. The notes were generated by a model.', text)
        self.assertIn('Model: ACE-Step 1.5', text)
        self.assertIn('Model code: https://example.org/code @ abc (MIT)', text)
        self.assertIn('Model weights: https://example.org/weights @ def (MIT)', text)
        self.assertIn('Seed: 11', text)
        self.assertIn('tools/music/sets/test-set/recipe.py', text)

    def test_shipped_ai_set_license_has_its_disclosure(self):
        m = load_manifest('orchestral-dawn')
        text = cli.license_text(m)
        self.assertIn(m.ai['disclosure'].strip(), text)
        self.assertIn(m.ai['model_weights'], text)


class ResolveTest(unittest.TestCase):
    def test_directory_set_id_and_installed_fallback(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp = Path(tmp)
            plain = tmp / 'candidate'
            plain.mkdir()
            (plain / 'a1.ogg').write_bytes(b'')
            self.assertEqual(cli._resolve(str(plain)), (plain, None))
            out, repo = tmp / 'out', tmp / 'repo'
            (repo / 'data' / 'zik' / 'woodland').mkdir(parents=True)
            with mock.patch.object(cli, 'OUT_DIR', out), mock.patch.object(cli, 'REPO_ROOT', repo):
                # Reference sets are always the shipped files.
                self.assertEqual(cli._resolve('original')[0], repo / 'data' / 'zik' / 'original')
                # A shipped set not built locally falls back to data/zik only when installed.
                self.assertEqual(cli._resolve('woodland')[0], out / 'woodland')
                (repo / 'data' / 'zik' / 'woodland' / 'a1.ogg').write_bytes(b'')
                directory, m = cli._resolve('woodland')
                self.assertEqual((directory, m.set_id), (repo / 'data' / 'zik' / 'woodland', 'woodland'))
                (out / 'woodland').mkdir(parents=True)
                (out / 'woodland' / 'a1.ogg').write_bytes(b'')
                self.assertEqual(cli._resolve('woodland')[0], out / 'woodland')
            with self.assertRaises(FileNotFoundError):
                cli._resolve(str(tmp / 'no-such-set'))


class RegisterAndInstallTest(unittest.TestCase):
    def zik(self, tmp, text=ZIK_SCONSCRIPT):
        zik = Path(tmp) / 'zik'
        (zik / 'original').mkdir(parents=True)
        (zik / 'original' / 'SConscript').write_text('')
        (zik / 'SConscript').write_text(text)
        return zik

    def test_register_set_is_idempotent_and_keeps_original_first(self):
        with tempfile.TemporaryDirectory() as tmp:
            zik = self.zik(tmp)
            cli._register_set(zik, 'woodland')
            first = (zik / 'SConscript').read_text()
            self.assertTrue(first.startswith('import os\n\nImport("env")\n\nfor music_set in ("original", "woodland"):'))
            (zik / 'woodland').mkdir()
            (zik / 'woodland' / 'SConscript').write_text('')
            cli._register_set(zik, 'woodland')
            self.assertEqual((zik / 'SConscript').read_text(), first)
            cli._register_set(zik, 'apple-cider')
            self.assertIn('("original", "apple-cider", "woodland")', (zik / 'SConscript').read_text())

    def test_register_set_refuses_an_unexpected_sconscript(self):
        with tempfile.TemporaryDirectory() as tmp:
            zik = self.zik(tmp, 'print("hand written")\n')
            with self.assertRaises(ManifestError):
                cli._register_set(zik, 'woodland')
            with self.assertRaises(ManifestError):
                cli._register_set(Path(tmp) / 'missing', 'woodland')

    def install(self, tmp, zik, failed=False, shipped=True):
        set_dir = Path(tmp) / 'sets' / 'test-set'
        set_dir.mkdir(parents=True)
        (set_dir / 'set.toml').write_text(
            'title = "Test Set"\nmethod = "adapted"\nlicense = "CC0-1.0"\n'
            f'shipped = {"true" if shipped else "false"}\ndescription = "A test."\n')
        out = Path(tmp) / 'out'
        (out / 'test-set').mkdir(parents=True)
        for name in ('a1.ogg', 'a2.ogg', 'a3.ogg'):
            (out / 'test-set' / name).write_bytes(name.encode())
        report = Report('test')
        cr = CheckResult('format')
        cr.add('x', FAIL if failed else PASS)
        report.results.append(cr)
        stdout, stderr = io.StringIO(), io.StringIO()
        with mock.patch.object(cli, 'OUT_DIR', out), mock.patch('glob2music.qa.run_checks', return_value=report), \
                contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
            return cli.main(['install', str(set_dir / 'set.toml'), '--data-dir', str(zik)])

    def test_install_copies_files_writes_license_and_registers(self):
        with tempfile.TemporaryDirectory() as tmp:
            zik = self.zik(tmp)
            self.assertEqual(self.install(tmp, zik), 0)
            dest = zik / 'test-set'
            self.assertEqual((dest / 'a2.ogg').read_bytes(), b'a2.ogg')
            self.assertEqual((dest / 'SConscript').read_text(), cli.SCONSCRIPT)
            self.assertIn('Licence: CC0-1.0', (dest / 'LICENSE.txt').read_text())
            self.assertIn('"test-set"', (zik / 'SConscript').read_text())

    def test_install_refuses_failed_unshipped_or_unregistrable_sets(self):
        for kwargs, text in (({'failed': True}, ZIK_SCONSCRIPT), ({'shipped': False}, ZIK_SCONSCRIPT),
                             ({}, 'print("hand written")\n')):
            with self.subTest(**kwargs, text=text[:10]), tempfile.TemporaryDirectory() as tmp:
                zik = self.zik(tmp, text)
                self.assertNotEqual(self.install(tmp, zik, **kwargs), 0)
                self.assertFalse((zik / 'test-set').exists())


class CheckArgumentsTest(unittest.TestCase):
    def test_only_rejects_unknown_check_names(self):
        stderr = io.StringIO()
        with contextlib.redirect_stderr(stderr), tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / 'a1.ogg').write_bytes(b'')
            self.assertEqual(cli.main(['check', tmp, '--only', 'seam,loudnes']), 2)
        self.assertIn('loudnes', stderr.getvalue())
        for name in CHECK_NAMES:
            self.assertIn(name, stderr.getvalue())

    def test_waivers_of_checks_that_did_not_run_are_not_stale(self):
        report = Report('test')
        cr = CheckResult('seam')
        cr.add('calm.step', PASS)
        report.results.append(cr)
        report.apply_waivers({'seam.combat.gap': 'A written reason for this.',
                              'loudness.ladder': 'A written reason for that.'})
        stale = [m.value for r in report.results if r.name == 'waivers' for m in r.measures]
        self.assertEqual(stale, ['seam.combat.gap'])

    def test_calibrate_checks_sets_with_their_own_manifest(self):
        spec, waivers = spec_and_waivers('original')
        self.assertIn('loudness.ladder', waivers)
        spec, _ = spec_and_waivers('curious-critters')
        self.assertEqual(spec.target_lufs['calm'], DEFAULT_SPEC.target_lufs['calm'] - 1.0)
        self.assertEqual(spec_and_waivers('codex-seedling'), (DEFAULT_SPEC, {}))


class OggStreamsTest(unittest.TestCase):
    def test_single_chained_and_invalid_files(self):
        y = np.zeros((SR // 2, 2), dtype=np.float32)
        with tempfile.TemporaryDirectory() as tmp:
            a, b = Path(tmp) / 'a.ogg', Path(tmp) / 'b.ogg'
            write_ogg(y, a)
            write_ogg(y, b)
            streams = ogg_streams(a)
            self.assertEqual(len(streams), 1)
            self.assertEqual(streams[0]['codec'], 'vorbis')
            self.assertEqual(streams[0]['last_granule'], len(y))
            chained = Path(tmp) / 'chained.ogg'
            chained.write_bytes(a.read_bytes() + b.read_bytes())
            self.assertEqual([s['codec'] for s in ogg_streams(chained)], ['vorbis', 'vorbis'])
            junk = Path(tmp) / 'junk.ogg'
            junk.write_bytes(b'RIFF....WAVE')
            with self.assertRaises(AudioFormatError):
                ogg_streams(junk)
            empty = Path(tmp) / 'empty.ogg'
            empty.write_bytes(b'')
            with self.assertRaises(AudioFormatError):
                ogg_streams(empty)


class AceStepHashGateTest(unittest.TestCase):
    REQUEST = acestep.Request(caption='test', bpm=96, keyscale='C major', duration=10, seed=1)

    def test_mismatch_is_an_error_unless_regeneration_is_allowed(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = acestep.cache_path(self.REQUEST, tmp)
            path.parent.mkdir(parents=True)
            path.write_bytes(b'a generation')
            good = hashlib.sha256(b'a generation').hexdigest()
            self.assertEqual(acestep.generate(self.REQUEST, tmp, expected_sha256=good), path)
            with self.assertRaises(acestep.GenerationMismatch):
                acestep.generate(self.REQUEST, tmp, expected_sha256='0' * 64)
            with self.assertLogs('glob2music.genai.acestep', 'WARNING'):
                self.assertEqual(acestep.generate(self.REQUEST, tmp, expected_sha256='0' * 64,
                                                  allow_mismatch=True), path)

    def test_cache_miss_does_not_regenerate_without_opt_in(self):
        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaisesRegex(acestep.GenAIUnavailable, 'allow-regenerate'):
                acestep.generate(self.REQUEST, tmp, expected_sha256='0' * 64, checkout=tmp)


if __name__ == '__main__':
    unittest.main()
