import os
Import("env")
Import("PackTar")
    
if 'dist' or 'install' in COMMAND_LINE_TARGETS:
    for file in os.listdir("."):
        if file.find(".txt") != -1 or file.find(".py") != -1:
            PackTar(env["TARFILE"], file)
            env.Install(env["INSTALLDIR"]+"/glob2/data/translations", file)

    env.Alias("install", env["INSTALLDIR"]+"/glob2/data/translations")

    PackTar(env["TARFILE"], "SConscript")
