Import("env")

env.Tar(env["TARFILE"], "sans.ttf")
env.Install(env["INSTALLDIR"]+"/glob2/data/fonts", "sans.ttf")
env.Alias("install", env["INSTALLDIR"]+"/glob2/data/fonts")

env.Tar(env["TARFILE"], "SConscript")
