#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Export reversible GSK camera transforms without changing geometry or UVs.
Run in pinned Blender 3.6.23, --background --factory-startup -t 1.
The classic swarm is reconstructed once to verify its projection against the
installed payload. All sidecars are bound to that payload's SHA-256.
"""
import hashlib
import json
from pathlib import Path
import struct
import sys
import tempfile

import bpy
import numpy as np
from mathutils import Vector

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).parent))
from export_units import open_source, MODELS
from generate_swarms import camera_fit
from export_swarm import export


def write(name, projection, rotation, pivot=None):
    path = ROOT / 'data/skins/colony-v1' / (name + '.gsk')
    data = path.read_bytes()
    _, count, indices, frames, _ = struct.unpack_from('<4sIIII', data)
    poses = np.frombuffer(data, '<f4', offset=20 + count * 8 + indices * 4).reshape(frames, count, 6)
    inverse = np.linalg.inv(projection)
    points = np.column_stack((poses[0, :, :3], np.ones(count))) @ inverse.T
    if pivot is None:
        pivot = (points[:, :3].min(axis=0) + points[:, :3].max(axis=0)) / 2
    radius = float(np.linalg.norm(points[:, :3] - pivot, axis=1).max())
    record = dict(version=1, meshSha256=hashlib.sha256(data).hexdigest(),
                  clipToModel=inverse.flatten().tolist(), modelToClip=projection.flatten().tolist(),
                  normalToModel=rotation.T.flatten().tolist(), pivot=list(pivot), radius=radius)
    for folder in ('data/skins/colony-v1', 'platform/apps/web/public/skins/models'):
        (ROOT / folder / (name + '.view.json')).write_text(json.dumps(record, indent=2) + '\n')
    return record


def main():
    assert bpy.app.version[:3] == (3, 6, 23)
    for model, (size, clips) in MODELS.items():
        for clip in clips:
            _, scene = open_source(model, clip)
            camera = np.linalg.inv(np.array(scene.camera.matrix_world))
            scale = -camera[2, 3] * 32 / scene.camera.data.lens
            projection = np.diag([2 / scale, 2 / scale, -0.01, 1]) @ camera
            if model == 'explorer':
                projection[0, 3] -= 1 / size
                projection[1, 3] -= 1 / size
            write(model + '-' + clip, projection, camera[:3, :3])
    rotation, centre, scale, depth = camera_fit()
    projection = np.eye(4)
    projection[:3, :3] = rotation
    projection[:3, 3] = -centre
    projection = np.diag([scale, scale, -depth, 1]) @ projection
    records = {}
    for shape in ('crown', 'clutch', 'toadstool', 'coral', 'skep', 'bloom'):
        records[shape] = write('swarm-' + shape, projection, rotation, np.array([0., 0., 0.]))
    with tempfile.TemporaryDirectory() as directory:
        bpy.ops.wm.read_factory_settings(use_empty=True)
        export(Path(directory))
        generated = (Path(directory) / 'swarm.gsk').read_bytes()
        installed = (ROOT / 'data/skins/colony-v1/swarm.gsk').read_bytes()
        _, count, indices, _, _ = struct.unpack_from('<4sIIII', installed)
        start = 20 + count * 8 + indices * 4
        assert generated[:start] == installed[:start], 'Classic topology or UVs changed'
        assert np.allclose(np.frombuffer(generated, '<f4', offset=start), np.frombuffer(installed, '<f4', offset=start), atol=1e-6, rtol=0), 'Classic geometry changed'
        positions = np.array([v.co[:] for v in bpy.context.object.data.vertices])
        positions -= (positions.min(axis=0) + positions.max(axis=0)) / 2
        rotation = np.array(Vector((6, -8, 10)).to_track_quat('Z', 'Y').to_matrix()).T
        view = positions @ rotation.T
        projection = np.eye(4)
        projection[:3, :3] = np.diag([1.8 / np.ptp(view[:, :2], axis=0).max()] * 2 + [-0.5 / np.ptp(view[:, 2])]) @ rotation
        records['classic'] = write('swarm', projection, rotation, np.array([0., 0., 0.]))
    # Generated native constants use exactly the web sidecars; no JSON parser on
    # the render path and no changes to GSK1 or its compatibility boundaries.
    lines = ['// Generated by tools/skins/export_views.py; do not edit.', '#pragma once', '#include <array>', 'namespace Online {', 'struct SkinViewTransform { std::array<float,16> inverse, projection; std::array<float,9> normals; };', 'inline constexpr std::array<SkinViewTransform,7> SkinViews = {{']
    for shape in ('classic', 'crown', 'clutch', 'toadstool', 'coral', 'skep', 'bloom'):
        r = records[shape]
        arrays = ['{{' + ','.join(format(float(v), '.9e') + 'f' for v in r[key]) + '}}' for key in ('clipToModel', 'modelToClip', 'normalToModel')]
        lines.append('    {' + ','.join(arrays) + '}, // ' + shape)
    lines.extend(['}};', '}'])
    (ROOT / 'src/online/SkinViewTransforms.h').write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
