import os

Import("env")
Import("PackTar")

any=False
for file in os.listdir("."):
    if file.find(".txt") != -1:
        any=True
        PackTar(env["TARFILE"], file)
        env.Install(env["INSTALLDIR"]+"/glob2/campaigns", hello)

if any:
    env.Alias("install", env["INSTALLDIR"]+"/glob2/campaigns")

PackTar(env["TARFILE"], "SConscript")
