import os
Import('env')
Import("PackTar")

if 'dist' or 'install' in COMMAND_LINE_TARGETS:
    for file in os.listdir("."):
        if file.find(".py") != -1:
            PackTar(env["TARFILE"], file)

    PackTar(env["TARFILE"], "SConscript")
