Import("env")
Import("PackTar")
    
if 'dist' in COMMAND_LINE_TARGETS or 'install' in COMMAND_LINE_TARGETS:
    PackTar(env["TARFILE"], "SConscript")
SConscript("src/SConscript")
SConscript("test/SConscript")
