libgag_sources = [
	"win32_dirent.cpp",
	"GraphicContext.cpp",
	"Sprite.cpp",
	"TrueTypeFont.cpp",
	"TrueTypeFont.h",
	"FileManager.cpp",
	"Toolkit.cpp",
	"StringTable.cpp",
	"CursorManager.cpp",
	"SupportFunctions.cpp",
	"GUIBase.cpp",
	"GUIList.cpp",
	"GUIFileList.cpp",
	"GUIKeySelector.cpp",
	"GUIRatio.cpp",
	"GUITextArea.cpp",
	"GUIButton.cpp",
	"GUINumber.cpp",
	"GUIText.cpp",
	"GUITextInput.cpp",
	"KeyPress.cpp",
	"GUISelector.cpp",
	"GUIAnimation.cpp",
	"GUIMessageBox.cpp",
	"GUIStyle.cpp",
	"StreamBackend.cpp",
	"StreamFilter.cpp",
	"Stream.cpp",
	"BinaryStream.cpp",
	"TextStream.cpp",
	"FormatableString.cpp"]


Import("env")
l = env.Library("gag", libgag_sources)
Default(l)

import os

for file in os.listdir("."):
    if file.find(".cpp") != -1:
        env.Tar(env["TARFILE"], file)
