from sources import GAG_SOURCES
libgag_sources = list(GAG_SOURCES)

from sources import GAG_SERVER_SOURCES
libgag_just_server = list(GAG_SERVER_SOURCES)

    
Import("env")
l1 = env.StaticLibrary("gag", libgag_sources)

l2 = env.StaticLibrary("gag_server", libgag_just_server)


if not env['server']:
    Default(l1)
    aspect_env = env.Clone()
    aspect_env.Append(CPPPATH=['#libgag/src'])
    aspect_test = aspect_env.Program('FullscreenAspectHarness',
        [aspect_env.Object('FullscreenAspectHarness.o', '#test/FullscreenAspectHarness.cpp'), l1])
    env.Alias('aspect-test', aspect_test)
    resize_test = aspect_env.Program('WindowResizeHarness',
        [aspect_env.Object('WindowResizeHarness.o', '#test/WindowResizeHarness.cpp'), l1])
    env.Alias('resize-test', resize_test)
    screen_test = env.Program('ScreenExecutionHarness',
        [env.Object('ScreenExecutionHarness.o', '#test/ScreenExecutionHarness.cpp'), l1])
    env.Alias('screen-test', screen_test)
else:
    Default(l2)

    
Import("env")
Import("PackTar")
import os
    
if 'dist' in COMMAND_LINE_TARGETS or 'install' in COMMAND_LINE_TARGETS:
    for file in os.listdir("."):
        if file.find(".cpp") != -1:
            PackTar(env["TARFILE"], file)
    
    PackTar(env["TARFILE"], "SConscript")
