Import('env')
Import("PackTar")

if 'dist' or 'install' in COMMAND_LINE_TARGETS:
    PackTar(env["TARFILE"], "SConscript")

SConscript("debian/SConscript")
SConscript("fedora/SConscript")
SConscript("windows/SConscript")