from pathlib import Path
import json,hashlib,xml.etree.ElementTree as ET
out=Path(__file__).resolve().parent;root=Path.cwd()
def read(name):return json.loads((out/name).read_text())
peak=read('peak-comparison.json');phase=read('phase-comparison.json');continuation=read('continuation-comparison.json');capture=read('capture-comparison.json')
cpu=read('cpu-final/comparison.json') if (out/'cpu-final/comparison.json').exists() else {}
tests={}
for name in ['savegame-tests','unit-tests','continuation-tests','compatibility-tests']:
 r=ET.parse(out/(name+'.xml')).getroot()
 tests[name]={k:int(r.attrib.get(k,0)) for k in ['tests','failures','errors','skipped']}
complete=capture['passed'] and len(cpu.get('fixtures',[]))==3 and cpu.get('passed',False) and all(len(f['pairs'])>=7 and f['passed'] for f in cpu.get('fixtures',[]))
report={'candidate_sha256':hashlib.sha256((root/'build/darwin/client/release/src/glob2').read_bytes()).hexdigest(),'baseline_sha256':hashlib.sha256((out/'baseline/glob2').read_bytes()).hexdigest(),'cpu_gate_complete':complete,'peak_limit_bytes':int(2.5*2**30),'peak_limit_passed':all(r['maximum_resident_bytes']<=2.5*2**30 for r in peak if r['variant']=='candidate'),'peak':peak,'phase':phase,'capture':capture,'cpu':cpu,'continuation':continuation,'tests':tests,'platform_execution':['macOS arm64'],'unverified':['Linux/Windows execution','interactive maintainer playtest']}
(out/'validation.json').write_text(json.dumps(report,indent=2))
lines=['# Save/load peak memory improvements','','Extends the prior optimized native build with chunked snapshots and direct gzip I/O. No disk spilling, save-format/version changes, or simulation changes.','',f'Candidate SHA256: `{report["candidate_sha256"]}`.',f'Baseline SHA256: `{report["baseline_sha256"]}`.','','## Peak resident memory','','Separate native processes, no malloc logging; default gzip compression. Each run loads the fixture, advances one tick, and optionally saves. Exact commands, binary hashes, and save hashes are in `peak-comparison.json`.','','| Fixture tick | Load baseline → candidate, GiB | Load/save baseline → candidate, GiB |','| --- | ---: | ---: |']
for tick in [0,15000,45000]:
 values={(r['variant'],r['save']):r['maximum_resident_bytes']/2**30 for r in peak if r['tick']==tick}
 lines.append(f'| {tick:,} | {values["baseline",False]:.3f} → {values["candidate",False]:.3f} | {values["baseline",True]:.3f} → {values["candidate",True]:.3f} |')
late=[r for r in peak if r['tick']==45000 and r['save']];old=next(r['maximum_resident_bytes'] for r in late if r['variant']=='baseline');new=next(r['maximum_resident_bytes'] for r in late if r['variant']=='candidate')
lines+=['',f'Late-game peak fell {100*(1-new/old):.1f}%; the ≤2.5 GiB gate passes. The earlier pre-edge-fix pilot measured 2.07 GiB; final measurements above use the final binary.','','## Snapshot capture and compression','','Seven paired interleaved processes use the same final engine and saved state, comparing contiguous versus chunked deferred snapshots. CPU time excludes scheduler pauses; wall time in this condition includes injected pauses and is not an interactive GUI latency estimate. Each pair produced byte-identical compressed saves.','','| Stage | CPU change | One-sided 95% upper bound |','| --- | ---: | ---: |']
for name in ['capture','hash','compression','total']:
 c=phase['cpu'][name];lines.append(f'| {name} | {c["paired_change_percent"]:+.2f}% | {c["upper_95_percent"]:+.2f}% |')
lines+=['','Seven uninhibited alternating capture triplets use the same warmed engine; reservation is included in capture time. This separately checks the prior autosave reservation, rather than only growing contiguous buffers.','','| Baseline capture | CPU change | CPU 95% upper | Wall change | Wall 95% upper |','| --- | ---: | ---: | ---: | ---: |']
for label in ['growing','reserved']:
 c=capture['cpu'][label];w=capture['wall'][label];lines.append(f'| {label} | {c["paired_change_percent"]:+.2f}% | {c["upper_95_percent"]:+.2f}% | {w["paired_change_percent"]:+.2f}% | {w["upper_95_percent"]:+.2f}% |')
first=phase['pairs'][0]['candidate']['capture'];lines+=['',f'Late snapshot: {first["snapshot_bytes"]:,} bytes; allocated blocks: {first["snapshot_capacity"]:,} bytes; block table: {first["table_capacity"]:,} bytes. Capacity is within one 1 MiB block of its byte length. Idle releases owned blocks; allocator retention can keep resident memory elevated afterwards.','','## Native full-game CPU gate','',f'Complete: **{complete}**. Alternating pairs with 0.1-second interleaving, 1024 warmup ticks and 4096 measured ticks. The runner was paused during the mid-game set for the separate capture check and during the late-game set for the final integration recheck; process CPU clocks exclude those pauses. Compare against the prior optimized binary, not the original pre-optimization engine. Each pair checks final simulation checksums and exact compressed saves.','', '| Tick | Stage | Pairs | CPU change | 95% upper bound |','| --- | --- | ---: | ---: | ---: |']
for f in cpu.get('fixtures',[]):
 for key,c in f.get('cpu',{}).items():lines.append(f'| {f["initial_tick"]:,} | {key} | {c["pairs"]} | {c["paired_change_percent"]:+.2f}% | {c["upper_95_percent"]:+.2f}% |')
lines+=['','## Compatibility and tests','',f'All {sum(t["tests"] for t in tests.values())} selected cases passed, including 393 unit cases, persistence fault handling, legacy version 84/88 saves, version 108/121/124 fixtures, and replay/network acceptance boundaries. Client and server release builds succeeded.','',f'Continuations from ticks 0, 15,000 and 45,000 matched all 1024 detailed ticks per fixture ({sum(c["baseline"]["bytes"] for c in continuation):,} bytes total), final saves and replays. Complete matched checksum streams are retained as `continuation-*-checksums.bin.gz`; raw duplicate streams were removed.','', 'Linux/Windows execution and an interactive maintainer playtest remain unverified. Autosave may pause while a preceding writer completes. Optional level-zero compression retains the legacy whole-buffer path and is outside the default-save memory gate.','', 'Pre-edge-fix CPU pilot results are not the final CPU acceptance evidence. Build logs, JUnit, fixture/binary hashes, raw CPU results, save files, helper sources and commands remain in this ignored artifact directory.']
(out/'review.md').write_text('\n'.join(lines)+'\n')
print({'complete':complete,'peak_passed':report['peak_limit_passed'],'tests':tests})
