
import os
import SCons.Script.Main

Import('env')
Import('PackTar')


if 'dist' or 'install' in COMMAND_LINE_TARGETS:
    files = Split("""changelog  glob2.6             glob2.docs         glob2-server.install  README.source
                     compat     glob2-data.dirs     glob2.install      glob2.sgml            rules
                     control    glob2-data.install  glob2.menu                               SConscript
                     copyright  glob2.dirs          glob2-server.dirs  README.Debian""")
    PackTar(env['TARFILE'], files)

    patches = Split("""patches/01_remove_home_directory_browsing.patch  patches/03_headers_order.patch
                       patches/02_upstream_changelog.patch              patches/series""")
    PackTar(env['TARFILE'], patches)

if env['mingwcross']:
    Return()

if 'dist' in COMMAND_LINE_TARGETS and os.path.exists('/etc/debian_version'):
    dpkg = env.Command('deb', None, 'dpkg-buildpackage -S -I.hg')
    env.AlwaysBuild(dpkg)
    env.Alias('dist', 'deb')

    # Impossible to pass -uuploadfilesdir option to dpkg-genchanges through dpkg-buildpackage.
    # Just move output files.
    mv = env.Command('debmove', None, "mv -f ../glob2*.changes ../glob2*.dsc"
                                        + " ../glob2*.tar.gz debian/")
    env.AlwaysBuild(mv)
    env.Depends('debmove', dpkg)
    env.Alias('dist', 'debmove')

    if env.GetOption('clean'):
        env.Execute('dpkg-buildpackage -Tclean', chdir='..')
        env.Execute('rm -f glob2*.deb glob2*.changes')


