Import("env")
Import("PackTar")
    
if 'dist' in COMMAND_LINE_TARGETS or 'install' in COMMAND_LINE_TARGETS:
    PackTar(env["TARFILE"], "sha1.c")
    PackTar(env["TARFILE"], "sha1.h")
    PackTar(env["TARFILE"], "SConscript")
