from pathlib import Path
import json, statistics
base=Path('artifacts/resource-growth/remaining')
lines=['# Resource-growth optimization experiments', '', 'Baseline: `edb09d40204a1fdb3a6d0e5934ef34e9c344de60`. Candidate confirmation master: `0f1a2569ab7f23c8702a078978054f73f4ddb9cc`. Intermediate retained comparison master: `6487b873dd3f29ad3ab75c7513597fa47905c132`. Final retained comparison master: `67fd5b935` (full identities in final-integration-freeze.json). Linux x86-64, GCC 15.2, release/O3. See frozen inputs, build commands, fixture hashes, and reservation audits in this directory.', '', 'Positive throughput and CPU-reduction values favor the candidate. Intervals are paired bootstrap 95% intervals (2,000 resamples); absolute savings are medians of paired differences, not differences between independent medians. Warm-ups are excluded. No measured slow runs are discarded.', '']
def percent(v):return f"{100*v['median']:+.2f}% [{100*v['ci95'][0]:+.2f}, {100*v['ci95'][1]:+.2f}]"
def table(summary):
 for case, scenarios in summary['results'].items():
  lines.extend([f'## {case}', '', '| Scenario | Pairs | Throughput change [95% CI] | Engine CPU reduction [95% CI] | Wall saved / 1024 ticks | CPU saved / 1024 ticks | p99 change | Peak RSS change |','|---|---:|---|---|---:|---:|---:|---:|'])
  for s,d in scenarios.items():
   tail=lambda key: 'Unavailable' if not d.get(key) or 'median' not in d[key] else percent(d[key])
   lines.append(f"| {s} | {d['pairs']} | {percent(d['tps_gain'])} | {percent(d['cpu_reduction'])} | {d['saved_ms']['median']:+.2f} ms | {d['cpu_saved_ms']['median']:+.2f} ms | {tail('p99_change')} | {tail('rss_change')} |")
  lines.append('')
for folder in ['extended','confirmation','sensitivity','retained-comparison','final-integration-comparison']:
 p=base/folder/'summary.json'
 if not p.exists():continue
 lines.extend([f'# {folder.title()} comparisons', '', f'Raw measurements and metadata: [`{folder}/`](./{folder}/).', ''])
 table(json.load(p.open()))
lines.extend(['# Interpretation and limitations', '', '- Untouched master and optimized-original retain immediate growth. They differ from delayed growth in RNG, within-pass feedback, and publication timing. Their throughput comparisons are not same-work proofs; use the accompanying final stock, deposit, and growth-statistic records. Delayed variants must match checksums and all accepted-work counters.', '- Optimized-original applies the applicable common A/C/D and contiguous-copy improvements to confirmation master 0f1a2569, retaining its immediate growth algorithm. B is specific to proposals.', '- The initial all-off pilot changed layout and setter scaffolding, so its results are excluded. Corrected variants keep non-C layouts and B-off setter code unchanged. Pilot evidence and the reason for exclusion are retained.', '- Stage wall timers overlap; never add snapshot, worker, queue, deadline-wait, and publication timers to infer total engine cost. Separate instrumented CPU attribution is diagnostic, not adoption evidence.', '- Core isolation reserves physical cores and their SMT siblings. Shared memory/cache/package-power contention remains possible. Confirmation uses four physical cores; the planned timing sensitivity sweep was not run because no candidate qualified after integration.', '- Snapshot allocation counts cover snapshot buffers only, not every heap allocation. Explicit copy bytes exclude allocator relocations and stamp metadata. Native retained-byte counters omit stock sidecars/stamps; OS peak RSS is used for memory acceptance.', '- Untouched master has histogram tick percentiles rather than exact p99. No exact master p99 is fabricated. Master also lacks the extra branch world-checksum trace; replay traces are retained.', '- Linux results do not establish Windows, macOS, Android, browser, or threadless determinism. These platforms were unavailable for execution in this experiment.', '', 'See [timer boundaries](./timing-boundaries.md) and the verification logs for detailed coverage.'])
(base/'performance-tables.md').write_text('\n'.join(lines)+'\n')
