from pathlib import Path
import shutil
b=Path('artifacts/resource-growth/remaining');f=Path('test/fixtures/resources/growth-save-layout');shutil.copy2(b/'retained-work/sparse/final.game.gz',f/'growth146.game.gz')
p=Path('src/map/ResourceGrowthTest.cpp');s=p.read_text().replace('#include "MapAssetBundle.h"','#include "MapAssetBundle.h"\n#include "BuildingArtwork.h"').replace('"growth145.game.gz", "artwork144.game.gz", "empty-artwork144.game.gz"','"growth145.game.gz", "growth146.game.gz", "artwork144.game.gz", "empty-artwork144.game.gz", "building145.game.gz", "empty-building145.game.gz"')
s=s.replace('const auto pending = original.game.map.gradientRuntime->growth.count();','CHECK(bool(original.game.gameHeader.getBuildingArtwork()) == (std::string_view(name) == "building145.game.gz"));\n        const auto artwork = original.game.gameHeader.getBuildingArtwork() ? original.game.gameHeader.getBuildingArtwork()->bytes() : std::string{};\n        const auto pending = original.game.map.gradientRuntime->growth.count();').replace('CHECK(restored.game.map.gradientRuntime->growth.count() == pending);','CHECK(restored.game.map.gradientRuntime->growth.count() == pending);\n        CHECK((restored.game.gameHeader.getBuildingArtwork() ? restored.game.gameHeader.getBuildingArtwork()->bytes() : std::string{}) == artwork);')
p.write_text(s)
p=Path('docs/development/reference.md');s=p.read_text().replace('Format 146 combines embedded map artwork with compact pending growth deltas,\nseeds and remaining deadlines. Format 145 growth saves remain readable. Two','Format 147 combines embedded map and building artwork with compact pending growth\ndeltas, seeds and remaining deadlines. Formats 145/146 growth saves remain readable.\nReleased format 145 adds building artwork; its bounded header is distinguished\nfrom the earlier compact-growth format 145, including empty artwork. Two');p.write_text(s)
p=Path('docs/development/headless-replays.md');s=p.read_text().replace('current replay floor is 146','current replay floor is 147').replace('Format 146 preserves both embedded artwork and compact signed resource-growth proposals.\nThe loader retains format 145 growth saves and both format 144 lineages (artwork\nand the earlier growth prototype), converting legacy pending work on load.','Format 147 preserves embedded map/building artwork and compact signed resource-growth\nproposals. The loader retains format 146 growth saves and both format 144/145\nlineages (released artwork and earlier growth prototypes), converting legacy\npending work on load.');p.write_text(s)
p=Path('docs/features/resource-catalogs.md');s=p.read_text().replace('current format 146 combines it with delayed growth. The loader also accepts the\nseparate format-144 growth prototype and format-145 compact growth saves.\nSimulation revision 31 identifies the integrated behavior for online matches.','current format 147 combines it with building artwork and delayed growth. The\nloader also accepts the separate format-144 growth prototype, format-145 compact\ngrowth saves, released format-145 building artwork and format-146 growth saves.\nSimulation revision 32 identifies the integrated behavior for online matches.');p.write_text(s)
