// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2004 Martin Voelkle <martin.voelkle@epfl.ch>

#include "type.h"

#define TYPES_VALUES_BUILTIN(x) const Types::Builtin* Types::Builtin::x = new Types::Builtin(sizeof(Values::x))
TYPES_VALUES_BUILTIN(Void);
TYPES_VALUES_BUILTIN(Bool);
TYPES_VALUES_BUILTIN(Char);
TYPES_VALUES_BUILTIN(Nat);
TYPES_VALUES_BUILTIN(Int);
TYPES_VALUES_BUILTIN(Nat8);
TYPES_VALUES_BUILTIN(Int8);
TYPES_VALUES_BUILTIN(Nat16);
TYPES_VALUES_BUILTIN(Int16);
TYPES_VALUES_BUILTIN(Nat32);
TYPES_VALUES_BUILTIN(Int32);
TYPES_VALUES_BUILTIN(Nat64);
TYPES_VALUES_BUILTIN(Int64);
TYPES_VALUES_BUILTIN(ValueRef);
TYPES_VALUES_BUILTIN(ObjectRef);
