import os
    
Import("env")
Import("PackTar")
    
    
if 'dist' in COMMAND_LINE_TARGETS or 'install' in COMMAND_LINE_TARGETS:
    any=False
    for file in os.listdir("."):
        if file.find(".spec")!=-1:
            any=True
            PackTar(env["TARFILE"], file)
   	
    PackTar(env["TARFILE"], "SConscript")
