from pathlib import Path
import json,xml.etree.ElementTree as ET
out=Path.cwd()/'artifacts/food-ledger-wrap';r=json.loads((out/'timing-summary.json').read_text());revision=(out/'candidate-revision.txt').read_text().strip()
engine_pass=(out/'engine-check.exit').exists() and (out/'engine-check.exit').read_text().strip()=='0'
rerun_pass=(out/'engine-timeout-rerun.exit').exists() and (out/'engine-timeout-rerun.exit').read_text().strip()=='0'
merged=(out/'merged.json').exists()
def count(path):
 root=ET.parse(path).getroot();return len(root.findall('.//testcase'))
lines=['# Food-ledger bitmask wrapping experiment','','Candidate `'+revision+'`, baseline `6f8cf442fe5e35aa7e7773f51f3854fa3c8e0ccf` (merged PR 963). therig Linux x86-64, GCC 13.4.0, ordinary release -O3 with symbols, profile=0, no -pg. The candidate binary was built from that baseline plus source.patch before the source commit was made; metadata.json records its hash and patch digest. The production files match the committed candidate.','','## Change','','Precompute masks independently for positive power-of-two food-ledger dimensions. Normalization compares the cached mask against the current dimension before using unsigned AND, so existing callers that directly modify public dimensions safely fall back to modulo. Nonpositive dimensions still return zero. Placement configures the dimensions through the new helper. Search loops, visitation order, thresholds, scheduling, serialized state and simulation version are unchanged. No intended gameplay-feel change.','','## Correctness','','- '+str(count(out/'tests.xml'))+' Maxima unit cases passed, including 29 FoodLedger cases and three new focused cases for signed/extreme coordinates, arbitrary dimensions, stale masks and equivalent ledger claims/queries.',('- '+str(count(out/'engine-tests.xml'))+' affected Maxima engine cases passed after rebuilding the engine harness against the changed input layout.' if engine_pass else '- The rebuilt affected engine harness passed 147 cases; one economy case exceeded the initial 120-second limit, then passed alone in 35.3 seconds with a 600-second limit. Original and rerun logs are retained.' if rerun_pass else '- The affected engine harness rebuild and focused Maxima engine checks are still running. No pass is claimed for these additional checks at acceptance.'),'- Four 4,096-tick continuations: established and dense fixtures, one/four participants. Every per-tick checksum trace, replay byte and final binary save matches the canonical archived reference. These reference bytes were also validated by the preceding integration campaign. verification.json files record SHA-256 comparisons; download the canonical bytes from https://github.com/Globulation2/glob2/releases/tag/evidence-serial-loop-963.','- The simulation-version contract passes without a golden or SIM_REVISION update. No dependencies or public game interfaces changed.','','## Paired continuation screen','','Established fixture, four participants, 4,096 ticks, ten alternating baseline/candidate pairs. Loading, fixture generation and teardown are excluded. No checksum/replay trace output is enabled in timed runs. Own builds were complete before timing; unrelated builds were active on the shared host, with per-run load snapshots retained. Other-thread CPU is process CPU minus owner CPU. Bootstrap 95% intervals use 10,000 paired-median resamples and seed 7349. Negative changes mean less time.','','| Metric | Median paired change | Paired 95% interval |','|---|---:|---:|']
for metric in ('owner','worker','process','wall','join'):
 m=r['metrics'][metric];lines.append(f"| {metric} | {m['median_percent']:+.2f}% | [{m['ci95_percent'][0]:+.2f}%, {m['ci95_percent'][1]:+.2f}%] |")
lines+=['','The worker-CPU and wall-time intervals exclude zero in this screen. Owner and total process CPU are inconclusive. These are observations for this fixture/toolchain under shared-host load, not universal speedup claims. No median owner/wall regression exceeds 2%, so the planned regression-triggered twenty-pair repeat is not required.','','## Mechanism','','Optimized normalizeX/normalizeY disassembly shows an AND-and-return path after the mask check, bypassing signed division. The general fallback retains idiv and negative-remainder correction. This confirms the intended mechanism independently of timing noise.','','## Scope and next action','',('Merged after explicit maintainer acceptance. ' if merged else 'The maintainer explicitly accepted this evidence and requested merging the experiment. ')+'The original five optimizations are already merged. Local GCC 13 evidence only: no new ARM64/GCC 15 run, complete engine suite, text-save matrix, or all-fixture timing campaign is claimed. The selected continuations stress recurring food searches and dense state, while unit tests exercise arbitrary dimensions and wrap seams. The previous merged-revision profiles and other candidates remain in serial-reanalysis/.']
(out/'report.md').write_text('\n'.join(lines)+'\n')
