set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
set(VCPKG_CMAKE_SYSTEM_VERSION 26)
if(PORT STREQUAL "sdl2")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS -DANDROID_PLATFORM=android-26 -DCMAKE_SYSTEM_VERSION=26)

# The pinned codecs predate CMake 3.5; CMake 4 requires an explicit policy floor.
list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS -DCMAKE_POLICY_VERSION_MINIMUM=3.5)
