import os
    
Import("env")
Import("PackTar")
    
    
if 'dist' or 'install' in COMMAND_LINE_TARGETS:
    any=False
    for file in os.listdir("."):
        if file.find(".c") != -1 or file.find(".h") != -1 or file.find(".py") != -1:
            PackTar(env["TARFILE"], file)
    
    PackTar(env["TARFILE"], "SConscript")
