import os
    
Import('env')
Import("PackTar")
    
if 'dist' in COMMAND_LINE_TARGETS or 'install' in COMMAND_LINE_TARGETS:
    for file in os.listdir("."):
        if file.find(".txt") != -1:
            PackTar(env["TARFILE"], file)
            env.Install(env["INSTALLDIR"] + "/glob2/data", file)
        
    
    env.InstallAs(env["INSTALLDIR"] + "/applications/org.globulation2.Globulation2.desktop", "glob2.desktop")
    env.Install(env["INSTALLDIR"] + "/metainfo", "org.globulation2.Globulation2.metainfo.xml")
    env.Alias("install", env["INSTALLDIR"]+"/glob2/data")
    env.Alias("install", env["INSTALLDIR"]+"/applications")
    env.Alias("install", env["INSTALLDIR"]+"/metainfo")
    PackTar(env["TARFILE"], "glob2.desktop")
    PackTar(env["TARFILE"], "org.globulation2.Globulation2.metainfo.xml")
    PackTar(env["TARFILE"], "SConscript")
    
SConscript("maxima/SConscript")
SConscript("fonts/SConscript")
SConscript("gfx/SConscript")
SConscript("gui/SConscript")
SConscript("icons/SConscript")
SConscript("zik/SConscript")
    

SConscript("highres/SConscript")
SConscript("menu/SConscript")
