// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/map-generators/generate_js_bindings.py.
#pragma once
#include "ToolkitBinding.h"
#include "ToolkitFertilityContracts.h"
#include "ToolkitControlContracts.h"
#include "ToolkitGraphContracts.h"
#include "map/FertilityField.h"
#include "map/generator/shared/BalancedStarts.h"
#include "map/generator/shared/Biomes.h"
#include "map/generator/shared/Centrepieces.h"
#include "map/generator/shared/Channels.h"
#include "map/generator/shared/ClearingLandscape.h"
#include "map/generator/shared/Contact.h"
#include "map/generator/shared/DesignCache.h"
#include "map/generator/shared/Drawing.h"
#include "map/generator/shared/FairnessModel.h"
#include "map/generator/shared/Farmland.h"
#include "map/generator/shared/Geometry.h"
#include "map/generator/shared/GraphMaze.h"
#include "map/generator/shared/Grid.h"
#include "map/generator/shared/Growth.h"
#include "map/generator/shared/HeightMap.h"
#include "map/generator/shared/HierarchicalCrossings.h"
#include "map/generator/shared/Homes.h"
#include "map/generator/shared/Landmass.h"
#include "map/generator/shared/LatticeNoise.h"
#include "map/generator/shared/Morphology.h"
#include "map/generator/shared/Noise.h"
#include "map/generator/shared/Orbits.h"
#include "map/generator/shared/Patterns.h"
#include "map/generator/shared/Pipeline.h"
#include "map/generator/shared/Planting.h"
#include "map/generator/shared/Points.h"
#include "map/generator/shared/Raster.h"
#include "map/generator/shared/RecursiveGeometry.h"
#include "map/generator/shared/ResourceSemantics.h"
#include "map/generator/shared/Resources.h"
#include "map/generator/shared/Rivers.h"
#include "map/generator/shared/Roads.h"
#include "map/generator/shared/Room.h"
#include "map/generator/shared/Routes.h"
#include "map/generator/shared/ScoredSettlements.h"
#include "map/generator/shared/Settlements.h"
#include "map/generator/shared/Sketch.h"
#include "map/generator/shared/Solve.h"
#include "map/generator/shared/StartDiagnostics.h"
#include "map/generator/shared/StartQuality.h"
#include "map/generator/shared/StartingLayout.h"
#include "map/generator/shared/Terrain.h"
#include "map/generator/shared/Territories.h"
#include "map/generator/shared/Tessellation.h"
#include "map/generator/shared/Topology.h"
#include "map/generator/shared/Towers.h"
#include "map/generator/shared/WalkBandStarts.h"
#include "map/generator/shared/Walls.h"
#include "map/generator/shared/Wedge.h"
#include "map/generator/shared/WorldAtlas.h"
#include "map/generator/shared/legacy/Distances.h"
#include "map/generator/shared/legacy/Regions.h"
#include "map/generator/shared/legacy/StartingPositions.h"
namespace MapGeneration::JavaScript {
using namespace ::MapGeneration;
template<> struct Record<Fertility::Field> { static Fertility::Field read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const Fertility::Field&); };
template<> struct Record<GeneratorControl> { static GeneratorControl read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const GeneratorControl&); };
template<> struct Record<MapGeneration::Torus> { static MapGeneration::Torus read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Torus&); };
template<> struct Record<MapGeneration::Axes> { static MapGeneration::Axes read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Axes&); };
template<> struct Record<MapGeneration::Flood> { static MapGeneration::Flood read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Flood&); };
template<> struct Record<MapGeneration::Reach> { static MapGeneration::Reach read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Reach&); };
template<> struct Record<MapGeneration::SeparatedSites> { static MapGeneration::SeparatedSites read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::SeparatedSites&); };
template<> struct Record<MapGeneration::Island> { static MapGeneration::Island read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Island&); };
template<> struct Record<MapGeneration::IslandPlacement> { static MapGeneration::IslandPlacement read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::IslandPlacement&); };
template<> struct Record<MapGeneration::BiomeKit> { static MapGeneration::BiomeKit read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::BiomeKit&); };
template<> struct Record<MapGeneration::BiomeTerrain> { static MapGeneration::BiomeTerrain read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::BiomeTerrain&); };
template<> struct Record<MapGeneration::RegionBounds> { static MapGeneration::RegionBounds read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RegionBounds&); };
template<> struct Record<MapGeneration::ShapePoint> { static MapGeneration::ShapePoint read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ShapePoint&); };
template<> struct Record<MapGeneration::Stretch> { static MapGeneration::Stretch read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Stretch&); };
template<> struct Record<MapGeneration::AxisFrame> { static MapGeneration::AxisFrame read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::AxisFrame&); };
template<> struct Record<MapGeneration::ShapeTransform> { static MapGeneration::ShapeTransform read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ShapeTransform&); };
template<> struct Record<MapGeneration::RadialShape> { static MapGeneration::RadialShape read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RadialShape&); };
template<> struct Record<MapGeneration::Teardrop> { static MapGeneration::Teardrop read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Teardrop&); };
template<> struct Record<MapGeneration::StrokePoint> { static MapGeneration::StrokePoint read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::StrokePoint&); };
template<> struct Record<MapGeneration::DownhillStyle> { static MapGeneration::DownhillStyle read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::DownhillStyle&); };
template<> struct Record<MapGeneration::PathBounds> { static MapGeneration::PathBounds read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::PathBounds&); };
template<> struct Record<MapGeneration::Branch> { static MapGeneration::Branch read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Branch&); };
template<> struct Record<MapGeneration::ForkStyle> { static MapGeneration::ForkStyle read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ForkStyle&); };
template<> struct Record<MapGeneration::Zigzag> { static MapGeneration::Zigzag read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Zigzag&); };
template<> struct Record<MapGeneration::SubtilePoint> { static MapGeneration::SubtilePoint read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::SubtilePoint&); };
template<> struct Record<MapGeneration::SandFord> { static MapGeneration::SandFord read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::SandFord&); };
template<> struct Record<MapGeneration::ChannelCrossing> { static MapGeneration::ChannelCrossing read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ChannelCrossing&); };
template<> struct Record<MapGeneration::ClearingLandscapeOptions> { static MapGeneration::ClearingLandscapeOptions read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ClearingLandscapeOptions&); };
template<> struct Record<MapGeneration::ClearingLandscape> { static MapGeneration::ClearingLandscape read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ClearingLandscape&); };
template<> struct Record<MapGeneration::ComponentLabels> { static MapGeneration::ComponentLabels read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ComponentLabels&); };
template<> struct Record<MapGeneration::DisjointSets> { static MapGeneration::DisjointSets read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::DisjointSets&); };
template<> struct Record<MapGeneration::StepCosts> { static MapGeneration::StepCosts read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::StepCosts&); };
template<> struct Record<MapGeneration::ContactReport> { static MapGeneration::ContactReport read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ContactReport&); };
template<> struct Record<MapGeneration::StartQualityScale> { static MapGeneration::StartQualityScale read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::StartQualityScale&); };
template<> struct Record<MapGeneration::ColonyQuality> { static MapGeneration::ColonyQuality read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ColonyQuality&); };
template<> struct Record<MapGeneration::ColonyQuality::DistanceBand> { static MapGeneration::ColonyQuality::DistanceBand read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ColonyQuality::DistanceBand&); };
template<> struct Record<MapGeneration::ColonyQuality::MaterialAccess> { static MapGeneration::ColonyQuality::MaterialAccess read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ColonyQuality::MaterialAccess&); };
template<> struct Record<MapGeneration::StartQualityReport> { static MapGeneration::StartQualityReport read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::StartQualityReport&); };
template<> struct Record<MapGeneration::FairnessModelTerm> { static MapGeneration::FairnessModelTerm read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::FairnessModelTerm&); };
template<> struct Record<MapGeneration::ShoreField> { static MapGeneration::ShoreField read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ShoreField&); };
template<> struct Record<MapGeneration::FarmRows> { static MapGeneration::FarmRows read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::FarmRows&); };
template<> struct Record<MapGeneration::Farm> { static MapGeneration::Farm read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Farm&); };
template<> struct Record<MapGeneration::ContourWobble> { static MapGeneration::ContourWobble read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ContourWobble&); };
template<> struct Record<MapGeneration::ContourFarmStyle> { static MapGeneration::ContourFarmStyle read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ContourFarmStyle&); };
template<> struct Record<MapGeneration::ContourFarm> { static MapGeneration::ContourFarm read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ContourFarm&); };
template<> struct Record<MapGeneration::FarmPlot> { static MapGeneration::FarmPlot read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::FarmPlot&); };
template<> struct Record<MapGeneration::FarmBridges> { static MapGeneration::FarmBridges read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::FarmBridges&); };
template<> struct Record<MapGeneration::SealedOval> { static MapGeneration::SealedOval read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::SealedOval&); };
template<> struct Record<MapGeneratorPoint> { static MapGeneratorPoint read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneratorPoint&); };
template<> struct Record<MapGeneration::ResourceDensities> { static MapGeneration::ResourceDensities read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ResourceDensities&); };
template<> struct Record<MapGeneration::ResourceFrontage> { static MapGeneration::ResourceFrontage read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ResourceFrontage&); };
template<> struct Record<MapGeneration::Site> { static MapGeneration::Site read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Site&); };
template<> struct Record<MapGeneration::NearestSites> { static MapGeneration::NearestSites read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::NearestSites&); };
template<> struct Record<MapGeneration::RankedSite> { static MapGeneration::RankedSite read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RankedSite&); };
template<> struct Record<MapGeneration::Grain> { static MapGeneration::Grain read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Grain&); };
template<> struct Record<MapGeneration::Tessellation> { static MapGeneration::Tessellation read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Tessellation&); };
template<> struct Record<MapGeneration::Tessellation::Cell> { static MapGeneration::Tessellation::Cell read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Tessellation::Cell&); };
template<> struct Record<MapGeneration::Tessellation::Edge> { static MapGeneration::Tessellation::Edge read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Tessellation::Edge&); };
template<> struct Record<MapGeneration::CellGraph> { static MapGeneration::CellGraph read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::CellGraph&); };
template<> struct Record<MapGeneration::DryStartPonds> { static MapGeneration::DryStartPonds read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::DryStartPonds&); };
template<> struct Record<MapGeneration::DryStartWatering> { static MapGeneration::DryStartWatering read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::DryStartWatering&); };
template<> struct Record<GenerationNoise> { static GenerationNoise read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const GenerationNoise&); };
template<> struct Record<HeightMap> { static HeightMap read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const HeightMap&); };
template<> struct Record<MapGeneration::RecursiveRegion> { static MapGeneration::RecursiveRegion read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RecursiveRegion&); };
template<> struct Record<MapGeneration::RegionTree> { static MapGeneration::RegionTree read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RegionTree&); };
template<> struct Record<MapGeneration::RecursiveSegment> { static MapGeneration::RecursiveSegment read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RecursiveSegment&); };
template<> struct Record<MapGeneration::HilbertPath> { static MapGeneration::HilbertPath read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::HilbertPath&); };
template<> struct Record<MapGeneration::RegionEdge> { static MapGeneration::RegionEdge read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RegionEdge&); };
template<> struct Record<MapGeneration::CrossingCandidate> { static MapGeneration::CrossingCandidate read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::CrossingCandidate&); };
template<> struct Record<MapGeneration::CrossingProposals> { static MapGeneration::CrossingProposals read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::CrossingProposals&); };
template<> struct Record<MapGeneration::CrossingGraph> { static MapGeneration::CrossingGraph read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::CrossingGraph&); };
template<> struct Record<MapGeneration::CrossingSelection> { static MapGeneration::CrossingSelection read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::CrossingSelection&); };
template<> struct Record<MapGeneration::PeriodicNoise> { static MapGeneration::PeriodicNoise read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::PeriodicNoise&); };
template<> struct Record<MapGeneration::ResourceStock> { static MapGeneration::ResourceStock read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ResourceStock&); };
template<> struct Record<MapGeneration::PatchBudgetResult> { static MapGeneration::PatchBudgetResult read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::PatchBudgetResult&); };
template<> struct Record<MapGeneration::KitSeed> { static MapGeneration::KitSeed read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::KitSeed&); };
template<> struct Record<MapGeneration::Kit> { static MapGeneration::Kit read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Kit&); };
template<> struct Record<MapGeneration::KitFrame> { static MapGeneration::KitFrame read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::KitFrame&); };
template<> struct Record<MapGeneration::AlgaeBand> { static MapGeneration::AlgaeBand read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::AlgaeBand&); };
template<> struct Record<MapGeneration::Territories> { static MapGeneration::Territories read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Territories&); };
template<> struct Record<MapGeneration::TeardropHome> { static MapGeneration::TeardropHome read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::TeardropHome&); };
template<> struct Record<MapGeneration::RegionHome> { static MapGeneration::RegionHome read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RegionHome&); };
template<> struct Record<MapGeneration::GroundAmounts> { static MapGeneration::GroundAmounts read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::GroundAmounts&); };
template<> struct Record<MapGeneration::WheatTopUp> { static MapGeneration::WheatTopUp read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::WheatTopUp&); };
template<> struct Record<MapGeneration::CoastCleaning> { static MapGeneration::CoastCleaning read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::CoastCleaning&); };
template<> struct Record<MapGeneration::Isometry> { static MapGeneration::Isometry read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Isometry&); };
template<> struct Record<MapGeneration::Symmetry> { static MapGeneration::Symmetry read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Symmetry&); };
template<> struct Record<MapGeneration::LatticeSites> { static MapGeneration::LatticeSites read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::LatticeSites&); };
template<> struct Record<MapGeneration::TuringStyle> { static MapGeneration::TuringStyle read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::TuringStyle&); };
template<> struct Record<MapGeneration::StripeStyle> { static MapGeneration::StripeStyle read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::StripeStyle&); };
template<> struct Record<MapGeneration::ResourceAmounts> { static MapGeneration::ResourceAmounts read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ResourceAmounts&); };
template<> struct Record<MapGeneration::MaterialAccessRule> { static MapGeneration::MaterialAccessRule read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::MaterialAccessRule&); };
template<> struct Record<MapGeneration::ColonyWalk> { static MapGeneration::ColonyWalk read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ColonyWalk&); };
template<> struct Record<MapGeneration::CropsInReach> { static MapGeneration::CropsInReach read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::CropsInReach&); };
template<> struct Record<MapGeneration::RasterFit> { static MapGeneration::RasterFit read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RasterFit&); };
template<> struct Record<MapGeneration::RasterFit::Cells> { static MapGeneration::RasterFit::Cells read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RasterFit::Cells&); };
template<> struct Record<MapGeneration::Anneal> { static MapGeneration::Anneal read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Anneal&); };
template<> struct Record<MapGeneration::SolveReport> { static MapGeneration::SolveReport read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::SolveReport&); };
template<> struct Record<MapGeneration::Objective> { static MapGeneration::Objective read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Objective&); };
template<> struct Record<MapGeneration::Objective::Term> { static MapGeneration::Objective::Term read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Objective::Term&); };
template<> struct Record<MapGeneration::Brief> { static MapGeneration::Brief read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Brief&); };
template<> struct Record<MapGeneration::RiverStyle> { static MapGeneration::RiverStyle read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RiverStyle&); };
template<> struct Record<MapGeneration::River> { static MapGeneration::River read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::River&); };
template<> struct Record<MapGeneration::RiverChoice> { static MapGeneration::RiverChoice read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RiverChoice&); };
template<> struct Record<MapGeneration::RiverFord> { static MapGeneration::RiverFord read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RiverFord&); };
template<> struct Record<MapGeneration::FordConnections> { static MapGeneration::FordConnections read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::FordConnections&); };
template<> struct Record<MapGeneration::BuildingGrid> { static MapGeneration::BuildingGrid read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::BuildingGrid&); };
template<> struct Record<MapGeneration::BuildingArrangement> { static MapGeneration::BuildingArrangement read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::BuildingArrangement&); };
template<> struct Record<MapGeneration::ScoredSettlementChoice> { static MapGeneration::ScoredSettlementChoice read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ScoredSettlementChoice&); };
template<> struct Record<MapGeneration::ColonyDiagnostics> { static MapGeneration::ColonyDiagnostics read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::ColonyDiagnostics&); };
template<> struct Record<MapGeneration::StartDiagnosticsReport> { static MapGeneration::StartDiagnosticsReport read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::StartDiagnosticsReport&); };
template<> struct Record<MapGeneration::StartingLayout> { static MapGeneration::StartingLayout read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::StartingLayout&); };
template<> struct Record<MapGeneration::HeightFieldOptions> { static MapGeneration::HeightFieldOptions read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::HeightFieldOptions&); };
template<> struct Record<MapGeneration::HeightFieldTiling> { static MapGeneration::HeightFieldTiling read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::HeightFieldTiling&); };
template<> struct Record<MapGeneration::HeightFieldLevels> { static MapGeneration::HeightFieldLevels read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::HeightFieldLevels&); };
template<> struct Record<MapGeneration::TowerPlan> { static MapGeneration::TowerPlan read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::TowerPlan&); };
template<> struct Record<MapGeneration::TowerRequest> { static MapGeneration::TowerRequest read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::TowerRequest&); };
template<> struct Record<MapGeneration::WalkBandRequest> { static MapGeneration::WalkBandRequest read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::WalkBandRequest&); };
template<> struct Record<MapGeneration::WalkBandStarts> { static MapGeneration::WalkBandStarts read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::WalkBandStarts&); };
template<> struct Record<MapGeneration::DesignedStone> { static MapGeneration::DesignedStone read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::DesignedStone&); };
template<> struct Record<MapGeneration::TileGate> { static MapGeneration::TileGate read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::TileGate&); };
template<> struct Record<MapGeneration::GatePartitionCheck> { static MapGeneration::GatePartitionCheck read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::GatePartitionCheck&); };
template<> struct Record<MapGeneration::WalkSpread> { static MapGeneration::WalkSpread read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::WalkSpread&); };
template<> struct Record<MapGeneration::RegionLeak> { static MapGeneration::RegionLeak read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::RegionLeak&); };
template<> struct Record<MapGeneration::WedgeFrame> { static MapGeneration::WedgeFrame read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::WedgeFrame&); };
template<> struct Record<MapGeneration::WedgeFrame::Cell> { static MapGeneration::WedgeFrame::Cell read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::WedgeFrame::Cell&); };
template<> struct Record<MapGeneration::Blob> { static MapGeneration::Blob read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::Blob&); };
template<> struct Record<MapGeneration::WedgeField> { static MapGeneration::WedgeField read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::WedgeField&); };
template<> struct Record<MapGeneration::AtlasRegion> { static MapGeneration::AtlasRegion read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::AtlasRegion&); };
template<> struct Record<MapGeneration::PlayerLandResources> { static MapGeneration::PlayerLandResources read(Binding &,JSValueConst); static void attach(Binding &,JSValueConst); static std::uint64_t footprint(Binding &,const MapGeneration::PlayerLandResources&); };
}
