// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/map-generators/generate_js_bindings.py.
#include "ToolkitRecords.h"
namespace MapGeneration::JavaScript {
MapGeneration::StrokePoint Record<MapGeneration::StrokePoint>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::StrokePoint>(v,[](Binding &e,MapGeneration::StrokePoint &value,JSValueConst v){ e.readField(value,v,"x",&MapGeneration::StrokePoint::x); e.readField(value,v,"y",&MapGeneration::StrokePoint::y); e.readField(value,v,"halfWidth",&MapGeneration::StrokePoint::halfWidth); }); }
std::uint64_t Record<MapGeneration::StrokePoint>::footprint(Binding &e,const MapGeneration::StrokePoint&v) { return sizeof(v)+(e.footprint(v.x)-sizeof(v.x)) + (e.footprint(v.y)-sizeof(v.y)) + (e.footprint(v.halfWidth)-sizeof(v.halfWidth)); }
void Record<MapGeneration::StrokePoint>::attach(Binding &e,JSValueConst v) { e.field(v,"x",&MapGeneration::StrokePoint::x); e.field(v,"y",&MapGeneration::StrokePoint::y); e.field(v,"halfWidth",&MapGeneration::StrokePoint::halfWidth); }
MapGeneration::DownhillStyle Record<MapGeneration::DownhillStyle>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::DownhillStyle>(v,[](Binding &e,MapGeneration::DownhillStyle &value,JSValueConst v){ e.readField(value,v,"step",&MapGeneration::DownhillStyle::step); e.readField(value,v,"memory",&MapGeneration::DownhillStyle::memory); e.readField(value,v,"angularNoise",&MapGeneration::DownhillStyle::angularNoise); e.readField(value,v,"maxDrift",&MapGeneration::DownhillStyle::maxDrift); }); }
std::uint64_t Record<MapGeneration::DownhillStyle>::footprint(Binding &e,const MapGeneration::DownhillStyle&v) { return sizeof(v)+(e.footprint(v.step)-sizeof(v.step)) + (e.footprint(v.memory)-sizeof(v.memory)) + (e.footprint(v.angularNoise)-sizeof(v.angularNoise)) + (e.footprint(v.maxDrift)-sizeof(v.maxDrift)); }
void Record<MapGeneration::DownhillStyle>::attach(Binding &e,JSValueConst v) { e.field(v,"step",&MapGeneration::DownhillStyle::step); e.field(v,"memory",&MapGeneration::DownhillStyle::memory); e.field(v,"angularNoise",&MapGeneration::DownhillStyle::angularNoise); e.field(v,"maxDrift",&MapGeneration::DownhillStyle::maxDrift); }
MapGeneration::PathBounds Record<MapGeneration::PathBounds>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::PathBounds>(v,[](Binding &e,MapGeneration::PathBounds &value,JSValueConst v){ e.readField(value,v,"x",&MapGeneration::PathBounds::x); e.readField(value,v,"y",&MapGeneration::PathBounds::y); e.readField(value,v,"radius",&MapGeneration::PathBounds::radius); }); }
std::uint64_t Record<MapGeneration::PathBounds>::footprint(Binding &e,const MapGeneration::PathBounds&v) { return sizeof(v)+(e.footprint(v.x)-sizeof(v.x)) + (e.footprint(v.y)-sizeof(v.y)) + (e.footprint(v.radius)-sizeof(v.radius)); }
void Record<MapGeneration::PathBounds>::attach(Binding &e,JSValueConst v) { e.field(v,"x",&MapGeneration::PathBounds::x); e.field(v,"y",&MapGeneration::PathBounds::y); e.field(v,"radius",&MapGeneration::PathBounds::radius); }
MapGeneration::Branch Record<MapGeneration::Branch>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::Branch>(v,[](Binding &e,MapGeneration::Branch &value,JSValueConst v){ e.readField(value,v,"path",&MapGeneration::Branch::path); e.readField(value,v,"parent",&MapGeneration::Branch::parent); e.readField(value,v,"depth",&MapGeneration::Branch::depth); e.readField(value,v,"bounds",&MapGeneration::Branch::bounds); e.readField(value,v,"heading",&MapGeneration::Branch::heading); e.readField(value,v,"leaf",&MapGeneration::Branch::leaf); }); }
std::uint64_t Record<MapGeneration::Branch>::footprint(Binding &e,const MapGeneration::Branch&v) { return sizeof(v)+(e.footprint(v.path)-sizeof(v.path)) + (e.footprint(v.parent)-sizeof(v.parent)) + (e.footprint(v.depth)-sizeof(v.depth)) + (e.footprint(v.bounds)-sizeof(v.bounds)) + (e.footprint(v.heading)-sizeof(v.heading)) + (e.footprint(v.leaf)-sizeof(v.leaf)); }
void Record<MapGeneration::Branch>::attach(Binding &e,JSValueConst v) { e.field(v,"path",&MapGeneration::Branch::path); e.field(v,"parent",&MapGeneration::Branch::parent); e.field(v,"depth",&MapGeneration::Branch::depth); e.field(v,"bounds",&MapGeneration::Branch::bounds); e.field(v,"heading",&MapGeneration::Branch::heading); e.field(v,"leaf",&MapGeneration::Branch::leaf); }
MapGeneration::ForkStyle Record<MapGeneration::ForkStyle>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::ForkStyle>(v,[](Binding &e,MapGeneration::ForkStyle &value,JSValueConst v){ e.readField(value,v,"spread",&MapGeneration::ForkStyle::spread); e.readField(value,v,"spreadJitter",&MapGeneration::ForkStyle::spreadJitter); e.readField(value,v,"lengthRatio",&MapGeneration::ForkStyle::lengthRatio); e.readField(value,v,"lengthJitter",&MapGeneration::ForkStyle::lengthJitter); e.readField(value,v,"widthRatio",&MapGeneration::ForkStyle::widthRatio); e.readField(value,v,"bend",&MapGeneration::ForkStyle::bend); e.readField(value,v,"minimumLength",&MapGeneration::ForkStyle::minimumLength); e.readField(value,v,"minimumHalfWidth",&MapGeneration::ForkStyle::minimumHalfWidth); }); }
std::uint64_t Record<MapGeneration::ForkStyle>::footprint(Binding &e,const MapGeneration::ForkStyle&v) { return sizeof(v)+(e.footprint(v.spread)-sizeof(v.spread)) + (e.footprint(v.spreadJitter)-sizeof(v.spreadJitter)) + (e.footprint(v.lengthRatio)-sizeof(v.lengthRatio)) + (e.footprint(v.lengthJitter)-sizeof(v.lengthJitter)) + (e.footprint(v.widthRatio)-sizeof(v.widthRatio)) + (e.footprint(v.bend)-sizeof(v.bend)) + (e.footprint(v.minimumLength)-sizeof(v.minimumLength)) + (e.footprint(v.minimumHalfWidth)-sizeof(v.minimumHalfWidth)); }
void Record<MapGeneration::ForkStyle>::attach(Binding &e,JSValueConst v) { e.field(v,"spread",&MapGeneration::ForkStyle::spread); e.field(v,"spreadJitter",&MapGeneration::ForkStyle::spreadJitter); e.field(v,"lengthRatio",&MapGeneration::ForkStyle::lengthRatio); e.field(v,"lengthJitter",&MapGeneration::ForkStyle::lengthJitter); e.field(v,"widthRatio",&MapGeneration::ForkStyle::widthRatio); e.field(v,"bend",&MapGeneration::ForkStyle::bend); e.field(v,"minimumLength",&MapGeneration::ForkStyle::minimumLength); e.field(v,"minimumHalfWidth",&MapGeneration::ForkStyle::minimumHalfWidth); }
MapGeneration::Zigzag Record<MapGeneration::Zigzag>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::Zigzag>(v,[](Binding &e,MapGeneration::Zigzag &value,JSValueConst v){ e.readField(value,v,"path",&MapGeneration::Zigzag::path); e.readField(value,v,"legs",&MapGeneration::Zigzag::legs); e.readField(value,v,"finishAcross",&MapGeneration::Zigzag::finishAcross); }); }
std::uint64_t Record<MapGeneration::Zigzag>::footprint(Binding &e,const MapGeneration::Zigzag&v) { return sizeof(v)+(e.footprint(v.path)-sizeof(v.path)) + (e.footprint(v.legs)-sizeof(v.legs)) + (e.footprint(v.finishAcross)-sizeof(v.finishAcross)); }
void Record<MapGeneration::Zigzag>::attach(Binding &e,JSValueConst v) { e.field(v,"path",&MapGeneration::Zigzag::path); e.field(v,"legs",&MapGeneration::Zigzag::legs); e.field(v,"finishAcross",&MapGeneration::Zigzag::finishAcross); }
MapGeneration::SubtilePoint Record<MapGeneration::SubtilePoint>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::SubtilePoint>(v,[](Binding &e,MapGeneration::SubtilePoint &value,JSValueConst v){ e.readField(value,v,"x",&MapGeneration::SubtilePoint::x); e.readField(value,v,"y",&MapGeneration::SubtilePoint::y); }); }
std::uint64_t Record<MapGeneration::SubtilePoint>::footprint(Binding &e,const MapGeneration::SubtilePoint&v) { return sizeof(v)+(e.footprint(v.x)-sizeof(v.x)) + (e.footprint(v.y)-sizeof(v.y)); }
void Record<MapGeneration::SubtilePoint>::attach(Binding &e,JSValueConst v) { e.field(v,"x",&MapGeneration::SubtilePoint::x); e.field(v,"y",&MapGeneration::SubtilePoint::y); e.overload(v,"equals",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::SubtilePoint &> arg0(e,a[0]);
  return e.write(e.native<MapGeneration::SubtilePoint>(self,false).operator==(arg0.get()));
})(e,self,n,a); }); }
MapGeneration::DryStartPonds Record<MapGeneration::DryStartPonds>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::DryStartPonds>(v,[](Binding &e,MapGeneration::DryStartPonds &value,JSValueConst v){ e.readField(value,v,"ponds",&MapGeneration::DryStartPonds::ponds); e.readField(value,v,"corners",&MapGeneration::DryStartPonds::corners); e.readField(value,v,"nearest",&MapGeneration::DryStartPonds::nearest); e.readField(value,v,"farthest",&MapGeneration::DryStartPonds::farthest); e.readField(value,v,"step",&MapGeneration::DryStartPonds::step); }); }
std::uint64_t Record<MapGeneration::DryStartPonds>::footprint(Binding &e,const MapGeneration::DryStartPonds&v) { return sizeof(v)+(e.footprint(v.ponds)-sizeof(v.ponds)) + (e.footprint(v.corners)-sizeof(v.corners)) + (e.footprint(v.nearest)-sizeof(v.nearest)) + (e.footprint(v.farthest)-sizeof(v.farthest)) + (e.footprint(v.step)-sizeof(v.step)); }
void Record<MapGeneration::DryStartPonds>::attach(Binding &e,JSValueConst v) { e.field(v,"ponds",&MapGeneration::DryStartPonds::ponds); e.field(v,"corners",&MapGeneration::DryStartPonds::corners); e.field(v,"nearest",&MapGeneration::DryStartPonds::nearest); e.field(v,"farthest",&MapGeneration::DryStartPonds::farthest); e.field(v,"step",&MapGeneration::DryStartPonds::step); }
MapGeneration::DryStartWatering Record<MapGeneration::DryStartWatering>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::DryStartWatering>(v,[](Binding &e,MapGeneration::DryStartWatering &value,JSValueConst v){ e.readField(value,v,"before",&MapGeneration::DryStartWatering::before); e.readField(value,v,"after",&MapGeneration::DryStartWatering::after); e.readField(value,v,"dug",&MapGeneration::DryStartWatering::dug); }); }
std::uint64_t Record<MapGeneration::DryStartWatering>::footprint(Binding &e,const MapGeneration::DryStartWatering&v) { return sizeof(v)+(e.footprint(v.before)-sizeof(v.before)) + (e.footprint(v.after)-sizeof(v.after)) + (e.footprint(v.dug)-sizeof(v.dug)); }
void Record<MapGeneration::DryStartWatering>::attach(Binding &e,JSValueConst v) { e.field(v,"before",&MapGeneration::DryStartWatering::before); e.field(v,"after",&MapGeneration::DryStartWatering::after); e.field(v,"dug",&MapGeneration::DryStartWatering::dug); }
MapGeneration::PlayerLandResources Record<MapGeneration::PlayerLandResources>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::PlayerLandResources>(v,[](Binding &e,MapGeneration::PlayerLandResources &value,JSValueConst v){ e.readField(value,v,"wheat",&MapGeneration::PlayerLandResources::wheat); e.readField(value,v,"wood",&MapGeneration::PlayerLandResources::wood); e.readField(value,v,"stone",&MapGeneration::PlayerLandResources::stone); }); }
std::uint64_t Record<MapGeneration::PlayerLandResources>::footprint(Binding &e,const MapGeneration::PlayerLandResources&v) { return sizeof(v)+(e.footprint(v.wheat)-sizeof(v.wheat)) + (e.footprint(v.wood)-sizeof(v.wood)) + (e.footprint(v.stone)-sizeof(v.stone)); }
void Record<MapGeneration::PlayerLandResources>::attach(Binding &e,JSValueConst v) { e.field(v,"wheat",&MapGeneration::PlayerLandResources::wheat); e.field(v,"wood",&MapGeneration::PlayerLandResources::wood); e.field(v,"stone",&MapGeneration::PlayerLandResources::stone); }
MapGeneration::RasterFit Record<MapGeneration::RasterFit>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::RasterFit>(v,[](Binding &e,MapGeneration::RasterFit &value,JSValueConst v){ e.readField(value,v,"sourceWidth",&MapGeneration::RasterFit::sourceWidth); e.readField(value,v,"sourceHeight",&MapGeneration::RasterFit::sourceHeight); e.readField(value,v,"left",&MapGeneration::RasterFit::left); e.readField(value,v,"top",&MapGeneration::RasterFit::top); e.readField(value,v,"width",&MapGeneration::RasterFit::width); e.readField(value,v,"height",&MapGeneration::RasterFit::height); e.readField(value,v,"turned",&MapGeneration::RasterFit::turned); e.readField(value,v,"num",&MapGeneration::RasterFit::num); e.readField(value,v,"den",&MapGeneration::RasterFit::den); }); }
std::uint64_t Record<MapGeneration::RasterFit>::footprint(Binding &e,const MapGeneration::RasterFit&v) { return sizeof(v)+(e.footprint(v.sourceWidth)-sizeof(v.sourceWidth)) + (e.footprint(v.sourceHeight)-sizeof(v.sourceHeight)) + (e.footprint(v.left)-sizeof(v.left)) + (e.footprint(v.top)-sizeof(v.top)) + (e.footprint(v.width)-sizeof(v.width)) + (e.footprint(v.height)-sizeof(v.height)) + (e.footprint(v.turned)-sizeof(v.turned)) + (e.footprint(v.num)-sizeof(v.num)) + (e.footprint(v.den)-sizeof(v.den)); }
void Record<MapGeneration::RasterFit>::attach(Binding &e,JSValueConst v) { e.field(v,"sourceWidth",&MapGeneration::RasterFit::sourceWidth); e.field(v,"sourceHeight",&MapGeneration::RasterFit::sourceHeight); e.field(v,"left",&MapGeneration::RasterFit::left); e.field(v,"top",&MapGeneration::RasterFit::top); e.field(v,"width",&MapGeneration::RasterFit::width); e.field(v,"height",&MapGeneration::RasterFit::height); e.field(v,"turned",&MapGeneration::RasterFit::turned); e.field(v,"num",&MapGeneration::RasterFit::num); e.field(v,"den",&MapGeneration::RasterFit::den); e.overload(v,"cellsOf",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<int> arg0(e,a[0]);
  e.preflight("x",arg0.get());
  Argument<int> arg1(e,a[1]);
  e.preflight("y",arg1.get());
  return e.write(e.native<MapGeneration::RasterFit>(self,false).cellsOf(arg0.get(), arg1.get()));
})(e,self,n,a); }); e.overload(v,"covers",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<int> arg0(e,a[0]);
  e.preflight("x",arg0.get());
  Argument<int> arg1(e,a[1]);
  e.preflight("y",arg1.get());
  return e.write(e.native<MapGeneration::RasterFit>(self,false).covers(arg0.get(), arg1.get()));
})(e,self,n,a); }); }
MapGeneration::RasterFit::Cells Record<MapGeneration::RasterFit::Cells>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::RasterFit::Cells>(v,[](Binding &e,MapGeneration::RasterFit::Cells &value,JSValueConst v){ e.readField(value,v,"x0",&MapGeneration::RasterFit::Cells::x0); e.readField(value,v,"x1",&MapGeneration::RasterFit::Cells::x1); e.readField(value,v,"y0",&MapGeneration::RasterFit::Cells::y0); e.readField(value,v,"y1",&MapGeneration::RasterFit::Cells::y1); }); }
std::uint64_t Record<MapGeneration::RasterFit::Cells>::footprint(Binding &e,const MapGeneration::RasterFit::Cells&v) { return sizeof(v)+(e.footprint(v.x0)-sizeof(v.x0)) + (e.footprint(v.x1)-sizeof(v.x1)) + (e.footprint(v.y0)-sizeof(v.y0)) + (e.footprint(v.y1)-sizeof(v.y1)); }
void Record<MapGeneration::RasterFit::Cells>::attach(Binding &e,JSValueConst v) { e.field(v,"x0",&MapGeneration::RasterFit::Cells::x0); e.field(v,"x1",&MapGeneration::RasterFit::Cells::x1); e.field(v,"y0",&MapGeneration::RasterFit::Cells::y0); e.field(v,"y1",&MapGeneration::RasterFit::Cells::y1); e.overload(v,"empty",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<0 || n>0) throw TypeMismatch("Wrong argument count");
  return e.write(e.native<MapGeneration::RasterFit::Cells>(self,false).empty());
})(e,self,n,a); }); }
MapGeneration::ScoredSettlementChoice Record<MapGeneration::ScoredSettlementChoice>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::ScoredSettlementChoice>(v,[](Binding &e,MapGeneration::ScoredSettlementChoice &value,JSValueConst v){ e.readField(value,v,"sites",&MapGeneration::ScoredSettlementChoice::sites); e.readField(value,v,"quality",&MapGeneration::ScoredSettlementChoice::quality); e.readField(value,v,"selected",&MapGeneration::ScoredSettlementChoice::selected); e.readField(value,v,"viable",&MapGeneration::ScoredSettlementChoice::viable); e.readField(value,v,"failure",&MapGeneration::ScoredSettlementChoice::failure); }); }
std::uint64_t Record<MapGeneration::ScoredSettlementChoice>::footprint(Binding &e,const MapGeneration::ScoredSettlementChoice&v) { return sizeof(v)+(e.footprint(v.sites)-sizeof(v.sites)) + (e.footprint(v.quality)-sizeof(v.quality)) + (e.footprint(v.selected)-sizeof(v.selected)) + (e.footprint(v.viable)-sizeof(v.viable)) + (e.footprint(v.failure)-sizeof(v.failure)); }
void Record<MapGeneration::ScoredSettlementChoice>::attach(Binding &e,JSValueConst v) { e.field(v,"sites",&MapGeneration::ScoredSettlementChoice::sites); e.field(v,"quality",&MapGeneration::ScoredSettlementChoice::quality); e.field(v,"selected",&MapGeneration::ScoredSettlementChoice::selected); e.field(v,"viable",&MapGeneration::ScoredSettlementChoice::viable); e.field(v,"failure",&MapGeneration::ScoredSettlementChoice::failure); }
MapGeneration::Territories Record<MapGeneration::Territories>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::Territories>(v,[](Binding &e,MapGeneration::Territories &value,JSValueConst v){ e.readField(value,v,"labels",&MapGeneration::Territories::labels); e.readField(value,v,"areas",&MapGeneration::Territories::areas); }); }
std::uint64_t Record<MapGeneration::Territories>::footprint(Binding &e,const MapGeneration::Territories&v) { return sizeof(v)+(e.footprint(v.labels)-sizeof(v.labels)) + (e.footprint(v.areas)-sizeof(v.areas)); }
void Record<MapGeneration::Territories>::attach(Binding &e,JSValueConst v) { e.field(v,"labels",&MapGeneration::Territories::labels); e.field(v,"areas",&MapGeneration::Territories::areas); e.overload(v,"smallest",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<0 || n>0) throw TypeMismatch("Wrong argument count");
  return e.write(e.native<MapGeneration::Territories>(self,false).smallest());
})(e,self,n,a); }); e.overload(v,"largest",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<0 || n>0) throw TypeMismatch("Wrong argument count");
  return e.write(e.native<MapGeneration::Territories>(self,false).largest());
})(e,self,n,a); }); }
void registerToolkit6(Binding &e,JSValueConst root) {
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"StrokePoint",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::StrokePoint>(a[0]):e.defaultRecord<MapGeneration::StrokePoint>()); })(e,self,n,a);});
e.overload(object,"DownhillStyle",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::DownhillStyle>(a[0]):e.defaultRecord<MapGeneration::DownhillStyle>()); })(e,self,n,a);});
e.overload(object,"PathBounds",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::PathBounds>(a[0]):e.defaultRecord<MapGeneration::PathBounds>()); })(e,self,n,a);});
e.overload(object,"Branch",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::Branch>(a[0]):e.defaultRecord<MapGeneration::Branch>()); })(e,self,n,a);});
e.overload(object,"ForkStyle",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::ForkStyle>(a[0]):e.defaultRecord<MapGeneration::ForkStyle>()); })(e,self,n,a);});
e.overload(object,"Zigzag",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::Zigzag>(a[0]):e.defaultRecord<MapGeneration::Zigzag>()); })(e,self,n,a);});
e.overload(object,"SubtilePoint",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::SubtilePoint>(a[0]):e.defaultRecord<MapGeneration::SubtilePoint>()); })(e,self,n,a);});
e.overload(object,"fillRectangle",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<MapGeneration::RegionBounds> arg2(e,a[2]);
  unsigned char default3 = 1;
  Script::JSValueOwner fallback3(e.ctx, (n>3 && !JS_IsUndefined(a[3]))?JS_UNDEFINED:e.write(default3));
  Argument<unsigned char> arg3(e,(n>3 && !JS_IsUndefined(a[3]))?a[3]:fallback3.get());
  MapGeneration::fillRectangle(arg0.get(), arg1.get(), arg2.get(), arg3.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"polarPoint",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<double> arg0(e,a[0]);
  e.preflight("cx",arg0.get());
  Argument<double> arg1(e,a[1]);
  e.preflight("cy",arg1.get());
  Argument<double> arg2(e,a[2]);
  e.preflight("radius",arg2.get());
  Argument<double> arg3(e,a[3]);
  e.preflight("angle",arg3.get());
  return e.write(MapGeneration::polarPoint(arg0.get(), arg1.get(), arg2.get(), arg3.get()));
})(e,self,n,a);});
e.overload(object,"strokePath",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>5) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<const std::vector<MapGeneration::StrokePoint> &> arg2(e,a[2]);
  unsigned char default3 = 1;
  Script::JSValueOwner fallback3(e.ctx, (n>3 && !JS_IsUndefined(a[3]))?JS_UNDEFINED:e.write(default3));
  Argument<unsigned char> arg3(e,(n>3 && !JS_IsUndefined(a[3]))?a[3]:fallback3.get());
  bool default4 = false;
  Script::JSValueOwner fallback4(e.ctx, (n>4 && !JS_IsUndefined(a[4]))?JS_UNDEFINED:e.write(default4));
  Argument<bool> arg4(e,(n>4 && !JS_IsUndefined(a[4]))?a[4]:fallback4.get());
  MapGeneration::strokePath(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"strokeIntersectsMask",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<const std::vector<MapGeneration::StrokePoint> &> arg1(e,a[1]);
  Argument<const std::vector<unsigned char> &> arg2(e,a[2]);
  return e.write(MapGeneration::strokeIntersectsMask(arg0.get(), arg1.get(), arg2.get()));
})(e,self,n,a);});
e.overload(object,"tracePath",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<const std::vector<MapGeneration::StrokePoint> &> arg2(e,a[2]);
  unsigned char default3 = 1;
  Script::JSValueOwner fallback3(e.ctx, (n>3 && !JS_IsUndefined(a[3]))?JS_UNDEFINED:e.write(default3));
  Argument<unsigned char> arg3(e,(n>3 && !JS_IsUndefined(a[3]))?a[3]:fallback3.get());
  MapGeneration::tracePath(arg0.get(), arg1.get(), arg2.get(), arg3.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"traceRay",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<6 || n>7) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<MapGeneration::ShapePoint> arg2(e,a[2]);
  Argument<double> arg3(e,a[3]);
  e.preflight("heading",arg3.get());
  Argument<double> arg4(e,a[4]);
  e.preflight("length",arg4.get());
  Argument<std::function<bool(int)>> arg5(e,a[5]);
  unsigned char default6 = 1;
  Script::JSValueOwner fallback6(e.ctx, (n>6 && !JS_IsUndefined(a[6]))?JS_UNDEFINED:e.write(default6));
  Argument<unsigned char> arg6(e,(n>6 && !JS_IsUndefined(a[6]))?a[6]:fallback6.get());
  return e.write(MapGeneration::traceRay(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get()));
})(e,self,n,a);});
e.overload(object,"downhillPath",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<7 || n>9) throw TypeMismatch("Wrong argument count");
  Argument<MapGeneration::ShapePoint> arg0(e,a[0]);
  Argument<double> arg1(e,a[1]);
  e.preflight("fromRadius",arg1.get());
  Argument<double> arg2(e,a[2]);
  e.preflight("toRadius",arg2.get());
  Argument<double> arg3(e,a[3]);
  e.preflight("heading",arg3.get());
  Argument<double> arg4(e,a[4]);
  e.preflight("fromHalfWidth",arg4.get());
  Argument<double> arg5(e,a[5]);
  e.preflight("toHalfWidth",arg5.get());
  Argument<std::mt19937 &> arg6(e,a[6]);
  MapGeneration::DownhillStyle default7 = { };
  Script::JSValueOwner fallback7(e.ctx, (n>7 && !JS_IsUndefined(a[7]))?JS_UNDEFINED:e.write(default7));
  Argument<const MapGeneration::DownhillStyle &> arg7(e,(n>7 && !JS_IsUndefined(a[7]))?a[7]:fallback7.get());
  MapGeneration::Stretch default8 = { };
  Script::JSValueOwner fallback8(e.ctx, (n>8 && !JS_IsUndefined(a[8]))?JS_UNDEFINED:e.write(default8));
  Argument<const MapGeneration::Stretch &> arg8(e,(n>8 && !JS_IsUndefined(a[8]))?a[8]:fallback8.get());
  return e.write(MapGeneration::downhillPath(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get(), arg8.get()));
})(e,self,n,a);});
e.overload(object,"bezierPath",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<6 || n>6) throw TypeMismatch("Wrong argument count");
  Argument<MapGeneration::ShapePoint> arg0(e,a[0]);
  Argument<MapGeneration::ShapePoint> arg1(e,a[1]);
  Argument<MapGeneration::ShapePoint> arg2(e,a[2]);
  Argument<double> arg3(e,a[3]);
  e.preflight("fromHalfWidth",arg3.get());
  Argument<double> arg4(e,a[4]);
  e.preflight("toHalfWidth",arg4.get());
  Argument<int> arg5(e,a[5]);
  e.preflight("segments",arg5.get());
  return e.write(MapGeneration::bezierPath(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get()));
})(e,self,n,a);});
e.overload(object,"bentPath",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<7 || n>7) throw TypeMismatch("Wrong argument count");
  Argument<MapGeneration::ShapePoint> arg0(e,a[0]);
  Argument<double> arg1(e,a[1]);
  e.preflight("heading",arg1.get());
  Argument<double> arg2(e,a[2]);
  e.preflight("length",arg2.get());
  Argument<double> arg3(e,a[3]);
  e.preflight("bend",arg3.get());
  Argument<double> arg4(e,a[4]);
  e.preflight("fromHalfWidth",arg4.get());
  Argument<double> arg5(e,a[5]);
  e.preflight("toHalfWidth",arg5.get());
  Argument<int> arg6(e,a[6]);
  e.preflight("segments",arg6.get());
  return e.write(MapGeneration::bentPath(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get()));
})(e,self,n,a);});
e.overload(object,"splinePath",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<MapGeneration::ShapePoint> &> arg0(e,a[0]);
  Argument<double> arg1(e,a[1]);
  e.preflight("step",arg1.get());
  return e.write(MapGeneration::splinePath(arg0.get(), arg1.get()));
})(e,self,n,a);});
e.overload(object,"wanderingPath",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<7 || n>7) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<MapGeneration::ShapePoint> arg1(e,a[1]);
  Argument<MapGeneration::ShapePoint> arg2(e,a[2]);
  Argument<double> arg3(e,a[3]);
  e.preflight("halfWidth",arg3.get());
  Argument<double> arg4(e,a[4]);
  e.preflight("wander",arg4.get());
  Argument<double> arg5(e,a[5]);
  e.preflight("widthJitter",arg5.get());
  Argument<std::mt19937 &> arg6(e,a[6]);
  return e.write(MapGeneration::wanderingPath(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get()));
})(e,self,n,a);});
e.overload(object,"carveCorridor",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<8 || n>9) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<MapGeneration::ShapePoint> arg2(e,a[2]);
  Argument<MapGeneration::ShapePoint> arg3(e,a[3]);
  Argument<double> arg4(e,a[4]);
  e.preflight("halfWidth",arg4.get());
  Argument<double> arg5(e,a[5]);
  e.preflight("wander",arg5.get());
  Argument<double> arg6(e,a[6]);
  e.preflight("widthJitter",arg6.get());
  Argument<std::mt19937 &> arg7(e,a[7]);
  unsigned char default8 = 1;
  Script::JSValueOwner fallback8(e.ctx, (n>8 && !JS_IsUndefined(a[8]))?JS_UNDEFINED:e.write(default8));
  Argument<unsigned char> arg8(e,(n>8 && !JS_IsUndefined(a[8]))?a[8]:fallback8.get());
  MapGeneration::carveCorridor(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get(), arg8.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"pathClearance",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>3) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<MapGeneration::StrokePoint> &> arg0(e,a[0]);
  Argument<const std::vector<MapGeneration::StrokePoint> &> arg1(e,a[1]);
  double default2 = 0;
  Script::JSValueOwner fallback2(e.ctx, (n>2 && !JS_IsUndefined(a[2]))?JS_UNDEFINED:e.write(default2));
  Argument<double> arg2(e,(n>2 && !JS_IsUndefined(a[2]))?a[2]:fallback2.get());
  if(n>2) e.preflight("skip",arg2.get());
  return e.write(MapGeneration::pathClearance(arg0.get(), arg1.get(), arg2.get()));
})(e,self,n,a);});
e.overload(object,"pathBounds",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<MapGeneration::StrokePoint> &> arg0(e,a[0]);
  return e.write(MapGeneration::pathBounds(arg0.get()));
})(e,self,n,a);});
e.overload(object,"growBranches",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<10 || n>10) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<MapGeneration::Branch> &> arg0(e,a[0]);
  Argument<int> arg1(e,a[1]);
  e.preflight("parent",arg1.get());
  Argument<MapGeneration::ShapePoint> arg2(e,a[2]);
  Argument<double> arg3(e,a[3]);
  e.preflight("heading",arg3.get());
  Argument<double> arg4(e,a[4]);
  e.preflight("length",arg4.get());
  Argument<double> arg5(e,a[5]);
  e.preflight("halfWidth",arg5.get());
  Argument<int> arg6(e,a[6]);
  e.preflight("forks",arg6.get());
  Argument<const MapGeneration::ForkStyle &> arg7(e,a[7]);
  Argument<std::function<double()> &> arg8(e,a[8]);
  Argument<std::function<bool(const std::vector<StrokePoint>&,int)> &> arg9(e,a[9]);
  return e.write(MapGeneration::growBranches(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get(), arg8.get(), arg9.get()));
})(e,self,n,a);});
e.overload(object,"forEachTileInShape",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<6 || n>7) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<double> arg1(e,a[1]);
  e.preflight("cx",arg1.get());
  Argument<double> arg2(e,a[2]);
  e.preflight("cy",arg2.get());
  Argument<const MapGeneration::RadialShape &> arg3(e,a[3]);
  Argument<double> arg4(e,a[4]);
  e.preflight("turn",arg4.get());
  Argument<std::function<void(int,double,double)>> arg5(e,a[5]);
  MapGeneration::Stretch default6 = { };
  Script::JSValueOwner fallback6(e.ctx, (n>6 && !JS_IsUndefined(a[6]))?JS_UNDEFINED:e.write(default6));
  Argument<const MapGeneration::Stretch &> arg6(e,(n>6 && !JS_IsUndefined(a[6]))?a[6]:fallback6.get());
  MapGeneration::forEachTileInShape(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"fillShape",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<5 || n>8) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<double> arg2(e,a[2]);
  e.preflight("cx",arg2.get());
  Argument<double> arg3(e,a[3]);
  e.preflight("cy",arg3.get());
  Argument<const MapGeneration::RadialShape &> arg4(e,a[4]);
  double default5 = 0;
  Script::JSValueOwner fallback5(e.ctx, (n>5 && !JS_IsUndefined(a[5]))?JS_UNDEFINED:e.write(default5));
  Argument<double> arg5(e,(n>5 && !JS_IsUndefined(a[5]))?a[5]:fallback5.get());
  if(n>5) e.preflight("turn",arg5.get());
  unsigned char default6 = 1;
  Script::JSValueOwner fallback6(e.ctx, (n>6 && !JS_IsUndefined(a[6]))?JS_UNDEFINED:e.write(default6));
  Argument<unsigned char> arg6(e,(n>6 && !JS_IsUndefined(a[6]))?a[6]:fallback6.get());
  MapGeneration::Stretch default7 = { };
  Script::JSValueOwner fallback7(e.ctx, (n>7 && !JS_IsUndefined(a[7]))?JS_UNDEFINED:e.write(default7));
  Argument<const MapGeneration::Stretch &> arg7(e,(n>7 && !JS_IsUndefined(a[7]))?a[7]:fallback7.get());
  MapGeneration::fillShape(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"forEachTileInTeardrop",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<6 || n>6) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<double> arg1(e,a[1]);
  e.preflight("cx",arg1.get());
  Argument<double> arg2(e,a[2]);
  e.preflight("cy",arg2.get());
  Argument<double> arg3(e,a[3]);
  e.preflight("heading",arg3.get());
  Argument<const MapGeneration::Teardrop &> arg4(e,a[4]);
  Argument<std::function<void(int,double,double)>> arg5(e,a[5]);
  MapGeneration::forEachTileInTeardrop(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"fillTeardrop",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<6 || n>7) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<double> arg2(e,a[2]);
  e.preflight("cx",arg2.get());
  Argument<double> arg3(e,a[3]);
  e.preflight("cy",arg3.get());
  Argument<double> arg4(e,a[4]);
  e.preflight("heading",arg4.get());
  Argument<const MapGeneration::Teardrop &> arg5(e,a[5]);
  unsigned char default6 = 1;
  Script::JSValueOwner fallback6(e.ctx, (n>6 && !JS_IsUndefined(a[6]))?JS_UNDEFINED:e.write(default6));
  Argument<unsigned char> arg6(e,(n>6 && !JS_IsUndefined(a[6]))?a[6]:fallback6.get());
  MapGeneration::fillTeardrop(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"arcPath",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<6 || n>7) throw TypeMismatch("Wrong argument count");
  Argument<double> arg0(e,a[0]);
  e.preflight("cx",arg0.get());
  Argument<double> arg1(e,a[1]);
  e.preflight("cy",arg1.get());
  Argument<double> arg2(e,a[2]);
  e.preflight("radius",arg2.get());
  Argument<double> arg3(e,a[3]);
  e.preflight("from",arg3.get());
  Argument<double> arg4(e,a[4]);
  e.preflight("to",arg4.get());
  Argument<double> arg5(e,a[5]);
  e.preflight("halfWidth",arg5.get());
  double default6 = 3;
  Script::JSValueOwner fallback6(e.ctx, (n>6 && !JS_IsUndefined(a[6]))?JS_UNDEFINED:e.write(default6));
  Argument<double> arg6(e,(n>6 && !JS_IsUndefined(a[6]))?a[6]:fallback6.get());
  if(n>6) e.preflight("step",arg6.get());
  return e.write(MapGeneration::arcPath(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get()));
})(e,self,n,a);});
e.overload(object,"zigzagPath",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<8 || n>8) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::AxisFrame &> arg0(e,a[0]);
  Argument<double> arg1(e,a[1]);
  e.preflight("start",arg1.get());
  Argument<double> arg2(e,a[2]);
  e.preflight("firstLeg",arg2.get());
  Argument<double> arg3(e,a[3]);
  e.preflight("pitch",arg3.get());
  Argument<int> arg4(e,a[4]);
  e.preflight("legs",arg4.get());
  Argument<double> arg5(e,a[5]);
  e.preflight("span",arg5.get());
  Argument<double> arg6(e,a[6]);
  e.preflight("finish",arg6.get());
  Argument<double> arg7(e,a[7]);
  e.preflight("halfWidth",arg7.get());
  return e.write(MapGeneration::zigzagPath(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get()));
})(e,self,n,a);});
e.overload(object,"ringWithGates",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<8 || n>8) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<double> arg1(e,a[1]);
  e.preflight("cx",arg1.get());
  Argument<double> arg2(e,a[2]);
  e.preflight("cy",arg2.get());
  Argument<double> arg3(e,a[3]);
  e.preflight("radius",arg3.get());
  Argument<double> arg4(e,a[4]);
  e.preflight("halfWidth",arg4.get());
  Argument<const std::vector<double> &> arg5(e,a[5]);
  Argument<double> arg6(e,a[6]);
  e.preflight("gateHalfWidth",arg6.get());
  Argument<std::function<void(int,int)>> arg7(e,a[7]);
  MapGeneration::ringWithGates(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"stretchPath",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<MapGeneration::StrokePoint> &> arg0(e,a[0]);
  Argument<double> arg1(e,a[1]);
  e.preflight("cx",arg1.get());
  Argument<double> arg2(e,a[2]);
  e.preflight("cy",arg2.get());
  Argument<const MapGeneration::Stretch &> arg3(e,a[3]);
  return e.write(MapGeneration::stretchPath(arg0.get(), arg1.get(), arg2.get(), arg3.get()));
})(e,self,n,a);});
e.overload(object,"subtileCentre",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<int> arg0(e,a[0]);
  e.preflight("tileX",arg0.get());
  Argument<int> arg1(e,a[1]);
  e.preflight("tileY",arg1.get());
  return e.write(MapGeneration::subtileCentre(arg0.get(), arg1.get()));
})(e,self,n,a);});
e.overload(object,"subtileTile",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<long long> arg0(e,a[0]);
  e.preflight("v",arg0.get());
  return e.write(MapGeneration::subtileTile(arg0.get()));
})(e,self,n,a);});
e.overload(object,"sealedSegmentTiles",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<MapGeneration::SubtilePoint> arg0(e,a[0]);
  Argument<MapGeneration::SubtilePoint> arg1(e,a[1]);
  return e.write(MapGeneration::sealedSegmentTiles(arg0.get(), arg1.get()));
})(e,self,n,a);});
e.overload(object,"traceSealedPath",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>5) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<const std::vector<MapGeneration::SubtilePoint> &> arg2(e,a[2]);
  unsigned char default3 = 1;
  Script::JSValueOwner fallback3(e.ctx, (n>3 && !JS_IsUndefined(a[3]))?JS_UNDEFINED:e.write(default3));
  Argument<unsigned char> arg3(e,(n>3 && !JS_IsUndefined(a[3]))?a[3]:fallback3.get());
  bool default4 = false;
  Script::JSValueOwner fallback4(e.ctx, (n>4 && !JS_IsUndefined(a[4]))?JS_UNDEFINED:e.write(default4));
  Argument<bool> arg4(e,(n>4 && !JS_IsUndefined(a[4]))?a[4]:fallback4.get());
  MapGeneration::traceSealedPath(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"traceSealedLap",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<5 || n>6) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<bool> arg2(e,a[2]);
  Argument<int> arg3(e,a[3]);
  e.preflight("step",arg3.get());
  Argument<std::function<double(int)>> arg4(e,a[4]);
  unsigned char default5 = 1;
  Script::JSValueOwner fallback5(e.ctx, (n>5 && !JS_IsUndefined(a[5]))?JS_UNDEFINED:e.write(default5));
  Argument<unsigned char> arg5(e,(n>5 && !JS_IsUndefined(a[5]))?a[5]:fallback5.get());
  MapGeneration::traceSealedLap(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"forEachTileInPolygon",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<const std::vector<MapGeneration::SubtilePoint> &> arg1(e,a[1]);
  Argument<std::function<void(int)>> arg2(e,a[2]);
  MapGeneration::forEachTileInPolygon(arg0.get(), arg1.get(), arg2.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"fillPolygon",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<const std::vector<MapGeneration::SubtilePoint> &> arg2(e,a[2]);
  unsigned char default3 = 1;
  Script::JSValueOwner fallback3(e.ctx, (n>3 && !JS_IsUndefined(a[3]))?JS_UNDEFINED:e.write(default3));
  Argument<unsigned char> arg3(e,(n>3 && !JS_IsUndefined(a[3]))?a[3]:fallback3.get());
  MapGeneration::fillPolygon(arg0.get(), arg1.get(), arg2.get(), arg3.get()); return JS_UNDEFINED;
})(e,self,n,a);});
if(JS_SetPropertyStr(e.ctx,object,"kSubtile",e.write(MapGeneration::kSubtile))<0)e.fail();
if(JS_SetPropertyStr(e.ctx,root,"Drawing",objectOwner.release())<0)e.fail(); }
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"DryStartPonds",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::DryStartPonds>(a[0]):e.defaultRecord<MapGeneration::DryStartPonds>()); })(e,self,n,a);});
e.overload(object,"DryStartWatering",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::DryStartWatering>(a[0]):e.defaultRecord<MapGeneration::DryStartWatering>()); })(e,self,n,a);});
e.overload(object,"cropSeedsIn",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting) throw TypeMismatch("World access unavailable in this callback");
  Argument<const std::vector<unsigned char> &> arg1(e,a[0]);
  return e.write(MapGeneration::cropSeedsIn(e.game->map, arg1.get()));
})(e,self,n,a);});
e.overload(object,"cropSpreadEnvelope",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<0 || n>1) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting) throw TypeMismatch("World access unavailable in this callback");
  Fertility::Field * default1 = nullptr;
  Script::JSValueOwner fallback1(e.ctx, (n>0 && !JS_IsUndefined(a[0]))?JS_UNDEFINED:JS_NULL);
  Argument<const Fertility::Field *> arg1(e,(n>0 && !JS_IsUndefined(a[0]))?a[0]:fallback1.get());
  if(arg1.get()) prepareFertilityRead(*arg1.get());
  return e.write(MapGeneration::cropSpreadEnvelope(e.game->map, arg1.get()));
})(e,self,n,a);});
e.overload(object,"fertileCropEnvelope",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting) throw TypeMismatch("World access unavailable in this callback");
  Argument<const Fertility::Field &> arg1(e,a[0]);
  prepareFertilityRead(arg1.get());
  return e.write(MapGeneration::fertileCropEnvelope(e.game->map, arg1.get()));
})(e,self,n,a);});
e.overload(object,"cropGrowthField",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  return e.write(MapGeneration::cropGrowthField(arg0.get(), arg1.get()));
})(e,self,n,a);});
e.overload(object,"wateredShare",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>3) throw TypeMismatch("Wrong argument count");
  Argument<const Fertility::Field &> arg0(e,a[0]);
  prepareFertilityRead(arg0.get());
  Argument<const std::vector<unsigned char> &> arg1(e,a[1]);
  unsigned int default2 = 1;
  Script::JSValueOwner fallback2(e.ctx, (n>2 && !JS_IsUndefined(a[2]))?JS_UNDEFINED:e.write(default2));
  Argument<unsigned int> arg2(e,(n>2 && !JS_IsUndefined(a[2]))?a[2]:fallback2.get());
  if(n>2) e.preflight("minimum",arg2.get());
  return e.write(MapGeneration::wateredShare(arg0.get(), arg1.get(), arg2.get()));
})(e,self,n,a);});
e.overload(object,"wetTiles",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<const Fertility::Field &> arg0(e,a[0]);
  prepareFertilityRead(arg0.get());
  Argument<const std::vector<unsigned char> &> arg1(e,a[1]);
  return e.write(MapGeneration::wetTiles(arg0.get(), arg1.get()));
})(e,self,n,a);});
e.overload(object,"dryZone",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<const std::vector<unsigned char> &> arg1(e,a[1]);
  return e.write(MapGeneration::dryZone(arg0.get(), arg1.get()));
})(e,self,n,a);});
e.overload(object,"drainWithin",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const std::vector<unsigned char> &> arg1(e,a[1]);
  return e.write(MapGeneration::drainWithin(arg0.get(), arg1.get()));
})(e,self,n,a);});
e.overload(object,"meanFertilityAround",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<const Fertility::Field &> arg0(e,a[0]);
  prepareFertilityRead(arg0.get());
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<int> arg2(e,a[2]);
  e.preflight("site",arg2.get());
  Argument<int> arg3(e,a[3]);
  e.preflight("radius",arg3.get());
  return e.write(MapGeneration::meanFertilityAround(arg0.get(), arg1.get(), arg2.get(), arg3.get()));
})(e,self,n,a);});
e.overload(object,"meanFertilityField",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  Argument<const Fertility::Field &> arg0(e,a[0]);
  prepareFertilityRead(arg0.get());
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<int> arg2(e,a[2]);
  e.preflight("radius",arg2.get());
  return e.write(MapGeneration::meanFertilityField(arg0.get(), arg1.get(), arg2.get()));
})(e,self,n,a);});
e.overload(object,"digPond",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<10 || n>10) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<int> arg2(e,a[2]);
  e.preflight("site",arg2.get());
  Argument<int> arg3(e,a[3]);
  e.preflight("nearest",arg3.get());
  Argument<int> arg4(e,a[4]);
  e.preflight("farthest",arg4.get());
  Argument<int> arg5(e,a[5]);
  e.preflight("corners",arg5.get());
  Argument<std::function<bool(int)>> arg6(e,a[6]);
  Argument<std::function<double(int)>> arg7(e,a[7]);
  Argument<std::vector<int> &> arg8(e,a[8]);
  Argument<int> arg9(e,a[9]);
  e.preflight("stamp",arg9.get());
  return e.write(MapGeneration::digPond(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get(), arg8.get(), arg9.get()));
})(e,self,n,a);});
e.overload(object,"waterDrySite",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<10 || n>10) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<int> arg2(e,a[2]);
  e.preflight("site",arg2.get());
  Argument<int> arg3(e,a[3]);
  e.preflight("radius",arg3.get());
  Argument<unsigned int> arg4(e,a[4]);
  e.preflight("floor",arg4.get());
  Argument<const MapGeneration::DryStartPonds &> arg5(e,a[5]);
  Argument<std::function<bool(int)>> arg6(e,a[6]);
  Argument<std::function<double(int)>> arg7(e,a[7]);
  Argument<std::vector<int> &> arg8(e,a[8]);
  Argument<int> arg9(e,a[9]);
  e.preflight("stampBase",arg9.get());
  return e.write(MapGeneration::waterDrySite(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get(), arg8.get(), arg9.get()));
})(e,self,n,a);});
if(JS_SetPropertyStr(e.ctx,object,"kCropProbeReach",e.write(MapGeneration::kCropProbeReach))<0)e.fail();
if(JS_SetPropertyStr(e.ctx,root,"Growth",objectOwner.release())<0)e.fail(); }
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"PlayerLandResources",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::PlayerLandResources>(a[0]):e.defaultRecord<MapGeneration::PlayerLandResources>()); })(e,self,n,a);});
e.overload(object,"divideUpPlayerLands",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>4) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  if(!e.generation || e.inspecting) throw TypeMismatch("Generation context unavailable");
  Argument<std::vector<int> &> arg2(e,a[0]);
  Argument<std::vector<int> &> arg3(e,a[1]);
  Argument<int &> arg4(e,a[2]);
  MapGeneration::PlayerLandResources default5 = { };
  Script::JSValueOwner fallback5(e.ctx, (n>3 && !JS_IsUndefined(a[3]))?JS_UNDEFINED:e.write(default5));
  Argument<const MapGeneration::PlayerLandResources &> arg5(e,(n>3 && !JS_IsUndefined(a[3]))?a[3]:fallback5.get());
  auto nativeResult=MapGeneration::divideUpPlayerLands((*e.game), (*e.generation), arg2.get(), arg3.get(), arg4.get(), arg5.get());
  Script::JSValueOwner result(e.ctx,JS_NewObject(e.ctx));e.check(result.get());
  if(JS_SetPropertyStr(e.ctx,result.get(),"result",e.write(nativeResult))<0)e.fail();
  if(JS_SetPropertyStr(e.ctx,result.get(),"areaNumber",e.write(arg4.get()))<0)e.fail();
  return result.release();
})(e,self,n,a);});
e.overload(object,"chooseFreeForBuildingSquares",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<std::vector<MapGeneratorPoint> &> arg1(e,a[0]);
  Argument<BuildingType *> arg2(e,a[1]);
  Argument<int> arg3(e,a[2]);
  e.preflight("team",arg3.get());
  MapGeneration::chooseFreeForBuildingSquares((*e.game), arg1.get(), arg2.get(), arg3.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"chooseFreeForGroundUnits",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<std::vector<MapGeneratorPoint> &> arg1(e,a[0]);
  Argument<int> arg2(e,a[1]);
  e.preflight("team",arg2.get());
  MapGeneration::chooseFreeForGroundUnits(e.game->map, arg1.get(), arg2.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"chooseTouchingBuilding",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<std::vector<MapGeneratorPoint> &> arg1(e,a[0]);
  Argument<Building *> arg2(e,a[1]);
  MapGeneration::chooseTouchingBuilding(e.game->map, arg1.get(), arg2.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"addBuilding",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<6 || n>6) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<int> arg1(e,a[0]);
  e.preflight("x",arg1.get());
  Argument<int> arg2(e,a[1]);
  e.preflight("y",arg2.get());
  Argument<int> arg3(e,a[2]);
  e.preflight("team",arg3.get());
  Argument<int> arg4(e,a[3]);
  e.preflight("type",arg4.get());
  Argument<int> arg5(e,a[4]);
  e.preflight("level",arg5.get());
  Argument<bool> arg6(e,a[5]);
  return e.write(MapGeneration::addBuilding((*e.game), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get()));
})(e,self,n,a);});
e.overload(object,"placeStarts",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<0 || n>0) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  if(!e.generation || e.inspecting) throw TypeMismatch("Generation context unavailable");
  return e.write(MapGeneration::placeStarts((*e.game), (*e.generation)));
})(e,self,n,a);});
e.overload(object,"placeArchipelagoStarts",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  if(!e.generation || e.inspecting) throw TypeMismatch("Generation context unavailable");
  Argument<int> arg2(e,a[0]);
  e.preflight("islandSize",arg2.get());
  return e.write(MapGeneration::placeArchipelagoStarts((*e.game), (*e.generation), arg2.get()));
})(e,self,n,a);});
if(JS_SetPropertyStr(e.ctx,root,"LegacyStartingPositions",objectOwner.release())<0)e.fail(); }
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"RasterFit",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::RasterFit>(a[0]):e.defaultRecord<MapGeneration::RasterFit>()); })(e,self,n,a);});
e.overload(object,"Cells",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::RasterFit::Cells>(a[0]):e.defaultRecord<MapGeneration::RasterFit::Cells>()); })(e,self,n,a);});
e.overload(object,"fitRaster",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<6 || n>6) throw TypeMismatch("Wrong argument count");
  Argument<int> arg0(e,a[0]);
  e.preflight("sourceWidth",arg0.get());
  Argument<int> arg1(e,a[1]);
  e.preflight("sourceHeight",arg1.get());
  Argument<int> arg2(e,a[2]);
  e.preflight("mapWidth",arg2.get());
  Argument<int> arg3(e,a[3]);
  e.preflight("mapHeight",arg3.get());
  Argument<int> arg4(e,a[4]);
  e.preflight("margin",arg4.get());
  Argument<bool> arg5(e,a[5]);
  return e.write(MapGeneration::fitRaster(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get()));
})(e,self,n,a);});
e.overload(object,"resampleRaster",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<5 || n>5) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::RasterFit &> arg1(e,a[1]);
  Argument<const MapGeneration::Torus &> arg2(e,a[2]);
  Argument<unsigned char> arg3(e,a[3]);
  Argument<std::function<unsigned char(const std::vector<unsigned char>&)>> arg4(e,a[4]);
  return e.write(MapGeneration::resampleRaster(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get()));
})(e,self,n,a);});
e.overload(object,"resampleMajority",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<5 || n>5) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::RasterFit &> arg1(e,a[1]);
  Argument<const MapGeneration::Torus &> arg2(e,a[2]);
  Argument<unsigned char> arg3(e,a[3]);
  Argument<unsigned char> arg4(e,a[4]);
  return e.write(MapGeneration::resampleMajority(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get()));
})(e,self,n,a);});
e.overload(object,"resampleAny",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::RasterFit &> arg1(e,a[1]);
  Argument<const MapGeneration::Torus &> arg2(e,a[2]);
  Argument<unsigned char> arg3(e,a[3]);
  return e.write(MapGeneration::resampleAny(arg0.get(), arg1.get(), arg2.get(), arg3.get()));
})(e,self,n,a);});
if(JS_SetPropertyStr(e.ctx,root,"Raster",objectOwner.release())<0)e.fail(); }
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"ScoredSettlementChoice",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::ScoredSettlementChoice>(a[0]):e.defaultRecord<MapGeneration::ScoredSettlementChoice>()); })(e,self,n,a);});
e.overload(object,"chooseScoredSettlements",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  if(!e.generation || e.inspecting) throw TypeMismatch("Generation context unavailable");
  Argument<const std::vector<std::vector<int>> &> arg1(e,a[0]);
  Argument<const std::function<bool (Game &, GenerationContext &, const std::vector<int> &)> &> arg2(e,a[1]);
  Argument<const std::function<std::string (const MapGeneration::StartQualityReport &)> &> arg3(e,a[2]);
  return e.write(MapGeneration::chooseScoredSettlements((*e.generation), arg1.get(), arg2.get(), arg3.get()));
})(e,self,n,a);});
if(JS_SetPropertyStr(e.ctx,root,"ScoredSettlements",objectOwner.release())<0)e.fail(); }
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"Territories",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::Territories>(a[0]):e.defaultRecord<MapGeneration::Territories>()); })(e,self,n,a);});
e.overload(object,"growTerritories",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>5) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<const std::vector<unsigned char> &> arg1(e,a[1]);
  Argument<const std::vector<std::vector<int>> &> arg2(e,a[2]);
  Argument<std::function<long long(int)>> arg3(e,a[3]);
  std::vector<double> * default4 = nullptr;
  Script::JSValueOwner fallback4(e.ctx, (n>4 && !JS_IsUndefined(a[4]))?JS_UNDEFINED:JS_NULL);
  Argument<const std::vector<double> *> arg4(e,(n>4 && !JS_IsUndefined(a[4]))?a[4]:fallback4.get());
  return e.write(MapGeneration::growTerritories(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get()));
})(e,self,n,a);});
e.overload(object,"balancedTerritories",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>6) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<const std::vector<unsigned char> &> arg1(e,a[1]);
  Argument<const std::vector<int> &> arg2(e,a[2]);
  double default3 = 0;
  Script::JSValueOwner fallback3(e.ctx, (n>3 && !JS_IsUndefined(a[3]))?JS_UNDEFINED:e.write(default3));
  Argument<double> arg3(e,(n>3 && !JS_IsUndefined(a[3]))?a[3]:fallback3.get());
  if(n>3) e.preflight("keep",arg3.get());
  int default4 = 80;
  Script::JSValueOwner fallback4(e.ctx, (n>4 && !JS_IsUndefined(a[4]))?JS_UNDEFINED:e.write(default4));
  Argument<int> arg4(e,(n>4 && !JS_IsUndefined(a[4]))?a[4]:fallback4.get());
  if(n>4) e.preflight("rounds",arg4.get());
  double default5 = 0.01;
  Script::JSValueOwner fallback5(e.ctx, (n>5 && !JS_IsUndefined(a[5]))?JS_UNDEFINED:e.write(default5));
  Argument<double> arg5(e,(n>5 && !JS_IsUndefined(a[5]))?a[5]:fallback5.get());
  if(n>5) e.preflight("tolerance",arg5.get());
  return e.write(MapGeneration::balancedTerritories(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get()));
})(e,self,n,a);});
e.overload(object,"smoothLabels",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>6) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<std::vector<int> &> arg1(e,a[1]);
  Argument<int> arg2(e,a[2]);
  e.preflight("passes",arg2.get());
  Argument<const std::vector<unsigned char> &> arg3(e,a[3]);
  int default4 = 1;
  Script::JSValueOwner fallback4(e.ctx, (n>4 && !JS_IsUndefined(a[4]))?JS_UNDEFINED:e.write(default4));
  Argument<int> arg4(e,(n>4 && !JS_IsUndefined(a[4]))?a[4]:fallback4.get());
  if(n>4) e.preflight("radius",arg4.get());
  double default5 = 0.7;
  Script::JSValueOwner fallback5(e.ctx, (n>5 && !JS_IsUndefined(a[5]))?JS_UNDEFINED:e.write(default5));
  Argument<double> arg5(e,(n>5 && !JS_IsUndefined(a[5]))?a[5]:fallback5.get());
  if(n>5) e.preflight("share",arg5.get());
  MapGeneration::smoothLabels(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"separateTerritories",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<std::vector<int> &> arg1(e,a[1]);
  Argument<int> arg2(e,a[2]);
  e.preflight("gap",arg2.get());
  MapGeneration::separateTerritories(arg0.get(), arg1.get(), arg2.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"fillToNearest",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<std::vector<int> &> arg1(e,a[1]);
  Argument<const std::vector<unsigned char> &> arg2(e,a[2]);
  Argument<int> arg3(e,a[3]);
  e.preflight("reach",arg3.get());
  return e.write(MapGeneration::fillToNearest(arg0.get(), arg1.get(), arg2.get(), arg3.get()));
})(e,self,n,a);});
e.overload(object,"strandedGround",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<const std::vector<int> &> arg1(e,a[1]);
  Argument<const std::vector<unsigned char> &> arg2(e,a[2]);
  return e.write(MapGeneration::strandedGround(arg0.get(), arg1.get(), arg2.get()));
})(e,self,n,a);});
e.overload(object,"growFarLake",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<9 || n>9) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<std::vector<unsigned char> &> arg1(e,a[1]);
  Argument<const std::vector<int> &> arg2(e,a[2]);
  Argument<const std::vector<int> &> arg3(e,a[3]);
  Argument<int> arg4(e,a[4]);
  e.preflight("gap",arg4.get());
  Argument<int> arg5(e,a[5]);
  e.preflight("target",arg5.get());
  Argument<std::function<double(int)>> arg6(e,a[6]);
  Argument<std::vector<int> &> arg7(e,a[7]);
  Argument<int> arg8(e,a[8]);
  e.preflight("stamp",arg8.get());
  return e.write(MapGeneration::growFarLake(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get(), arg8.get()));
})(e,self,n,a);});
e.overload(object,"growLakeBeside",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<14 || n>14) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<std::vector<unsigned char> &> arg1(e,a[1]);
  Argument<const std::vector<int> &> arg2(e,a[2]);
  Argument<const std::vector<int> &> arg3(e,a[3]);
  Argument<int> arg4(e,a[4]);
  e.preflight("gap",arg4.get());
  Argument<int> arg5(e,a[5]);
  e.preflight("target",arg5.get());
  Argument<int> arg6(e,a[6]);
  e.preflight("site",arg6.get());
  Argument<double> arg7(e,a[7]);
  e.preflight("heading",arg7.get());
  Argument<int> arg8(e,a[8]);
  e.preflight("side",arg8.get());
  Argument<int> arg9(e,a[9]);
  e.preflight("siteGap",arg9.get());
  Argument<int> arg10(e,a[10]);
  e.preflight("reach",arg10.get());
  Argument<std::function<double(int)>> arg11(e,a[11]);
  Argument<std::vector<int> &> arg12(e,a[12]);
  Argument<int> arg13(e,a[13]);
  e.preflight("stamp",arg13.get());
  return e.write(MapGeneration::growLakeBeside(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get(), arg8.get(), arg9.get(), arg10.get(), arg11.get(), arg12.get(), arg13.get()));
})(e,self,n,a);});
e.overload(object,"siteAtDepth",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<5 || n>5) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<int> &> arg0(e,a[0]);
  Argument<const std::vector<int> &> arg1(e,a[1]);
  Argument<int> arg2(e,a[2]);
  e.preflight("target",arg2.get());
  Argument<int> arg3(e,a[3]);
  e.preflight("minimumRoom",arg3.get());
  Argument<int> arg4(e,a[4]);
  e.preflight("spread",arg4.get());
  return e.write(MapGeneration::siteAtDepth(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get()));
})(e,self,n,a);});
if(JS_SetPropertyStr(e.ctx,root,"Territories",objectOwner.release())<0)e.fail(); }
}
}
