// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/map-generators/generate_js_bindings.py.
#include "ToolkitRecords.h"
namespace MapGeneration::JavaScript {
MapGeneration::SeparatedSites Record<MapGeneration::SeparatedSites>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::SeparatedSites>(v,[](Binding &e,MapGeneration::SeparatedSites &value,JSValueConst v){ e.readField(value,v,"indices",&MapGeneration::SeparatedSites::indices); e.readField(value,v,"attempts",&MapGeneration::SeparatedSites::attempts); e.readField(value,v,"failure",&MapGeneration::SeparatedSites::failure); }); }
std::uint64_t Record<MapGeneration::SeparatedSites>::footprint(Binding &e,const MapGeneration::SeparatedSites&v) { return sizeof(v)+(e.footprint(v.indices)-sizeof(v.indices)) + (e.footprint(v.attempts)-sizeof(v.attempts)) + (e.footprint(v.failure)-sizeof(v.failure)); }
void Record<MapGeneration::SeparatedSites>::attach(Binding &e,JSValueConst v) { e.field(v,"indices",&MapGeneration::SeparatedSites::indices); e.field(v,"attempts",&MapGeneration::SeparatedSites::attempts); e.field(v,"failure",&MapGeneration::SeparatedSites::failure); }
MapGeneration::ShoreField Record<MapGeneration::ShoreField>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::ShoreField>(v,[](Binding &e,MapGeneration::ShoreField &value,JSValueConst v){ e.readField(value,v,"tiles",&MapGeneration::ShoreField::tiles); e.readField(value,v,"seedTiles",&MapGeneration::ShoreField::seedTiles); e.readField(value,v,"court",&MapGeneration::ShoreField::court); e.readField(value,v,"growthPotential",&MapGeneration::ShoreField::growthPotential); }); }
std::uint64_t Record<MapGeneration::ShoreField>::footprint(Binding &e,const MapGeneration::ShoreField&v) { return sizeof(v)+(e.footprint(v.tiles)-sizeof(v.tiles)) + (e.footprint(v.seedTiles)-sizeof(v.seedTiles)) + (e.footprint(v.court)-sizeof(v.court)) + (e.footprint(v.growthPotential)-sizeof(v.growthPotential)); }
void Record<MapGeneration::ShoreField>::attach(Binding &e,JSValueConst v) { e.field(v,"tiles",&MapGeneration::ShoreField::tiles); e.field(v,"seedTiles",&MapGeneration::ShoreField::seedTiles); e.field(v,"court",&MapGeneration::ShoreField::court); e.field(v,"growthPotential",&MapGeneration::ShoreField::growthPotential); }
MapGeneration::FarmRows Record<MapGeneration::FarmRows>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::FarmRows>(v,[](Binding &e,MapGeneration::FarmRows &value,JSValueConst v){ e.readField(value,v,"crops",&MapGeneration::FarmRows::crops); e.readField(value,v,"water",&MapGeneration::FarmRows::water); }); }
std::uint64_t Record<MapGeneration::FarmRows>::footprint(Binding &e,const MapGeneration::FarmRows&v) { return sizeof(v)+(e.footprint(v.crops)-sizeof(v.crops)) + (e.footprint(v.water)-sizeof(v.water)); }
void Record<MapGeneration::FarmRows>::attach(Binding &e,JSValueConst v) { e.field(v,"crops",&MapGeneration::FarmRows::crops); e.field(v,"water",&MapGeneration::FarmRows::water); e.overload(v,"period",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<0 || n>0) throw TypeMismatch("Wrong argument count");
  return e.write(e.native<MapGeneration::FarmRows>(self,false).period());
})(e,self,n,a); }); }
MapGeneration::Farm Record<MapGeneration::Farm>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::Farm>(v,[](Binding &e,MapGeneration::Farm &value,JSValueConst v){ e.readField(value,v,"water",&MapGeneration::Farm::water); e.readField(value,v,"row",&MapGeneration::Farm::row); e.readField(value,v,"rows",&MapGeneration::Farm::rows); e.readField(value,v,"sand",&MapGeneration::Farm::sand); e.readField(value,v,"plot",&MapGeneration::Farm::plot); e.readField(value,v,"plotX",&MapGeneration::Farm::plotX); e.readField(value,v,"plotY",&MapGeneration::Farm::plotY); }); }
std::uint64_t Record<MapGeneration::Farm>::footprint(Binding &e,const MapGeneration::Farm&v) { return sizeof(v)+(e.footprint(v.water)-sizeof(v.water)) + (e.footprint(v.row)-sizeof(v.row)) + (e.footprint(v.rows)-sizeof(v.rows)) + (e.footprint(v.sand)-sizeof(v.sand)) + (e.footprint(v.plot)-sizeof(v.plot)) + (e.footprint(v.plotX)-sizeof(v.plotX)) + (e.footprint(v.plotY)-sizeof(v.plotY)); }
void Record<MapGeneration::Farm>::attach(Binding &e,JSValueConst v) { e.field(v,"water",&MapGeneration::Farm::water); e.field(v,"row",&MapGeneration::Farm::row); e.field(v,"rows",&MapGeneration::Farm::rows); e.field(v,"sand",&MapGeneration::Farm::sand); e.field(v,"plot",&MapGeneration::Farm::plot); e.field(v,"plotX",&MapGeneration::Farm::plotX); e.field(v,"plotY",&MapGeneration::Farm::plotY); }
MapGeneration::ContourWobble Record<MapGeneration::ContourWobble>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::ContourWobble>(v,[](Binding &e,MapGeneration::ContourWobble &value,JSValueConst v){ e.readField(value,v,"amplitude",&MapGeneration::ContourWobble::amplitude); e.readField(value,v,"phase",&MapGeneration::ContourWobble::phase); }); }
std::uint64_t Record<MapGeneration::ContourWobble>::footprint(Binding &e,const MapGeneration::ContourWobble&v) { return sizeof(v)+(e.footprint(v.amplitude)-sizeof(v.amplitude)) + (e.footprint(v.phase)-sizeof(v.phase)); }
void Record<MapGeneration::ContourWobble>::attach(Binding &e,JSValueConst v) { e.field(v,"amplitude",&MapGeneration::ContourWobble::amplitude); e.field(v,"phase",&MapGeneration::ContourWobble::phase); e.overload(v,"at",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<double> arg0(e,a[0]);
  e.preflight("angle",arg0.get());
  return e.write(e.native<MapGeneration::ContourWobble>(self,false).at(arg0.get()));
})(e,self,n,a); }); }
MapGeneration::ContourFarmStyle Record<MapGeneration::ContourFarmStyle>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::ContourFarmStyle>(v,[](Binding &e,MapGeneration::ContourFarmStyle &value,JSValueConst v){ e.readField(value,v,"rows",&MapGeneration::ContourFarmStyle::rows); e.readField(value,v,"innerRadius",&MapGeneration::ContourFarmStyle::innerRadius); e.readField(value,v,"cap",&MapGeneration::ContourFarmStyle::cap); e.readField(value,v,"bands",&MapGeneration::ContourFarmStyle::bands); e.readField(value,v,"crossings",&MapGeneration::ContourFarmStyle::crossings); e.readField(value,v,"crossingHalfWidth",&MapGeneration::ContourFarmStyle::crossingHalfWidth); e.readField(value,v,"phase",&MapGeneration::ContourFarmStyle::phase); e.readField(value,v,"wobbles",&MapGeneration::ContourFarmStyle::wobbles); }); }
std::uint64_t Record<MapGeneration::ContourFarmStyle>::footprint(Binding &e,const MapGeneration::ContourFarmStyle&v) { return sizeof(v)+(e.footprint(v.rows)-sizeof(v.rows)) + (e.footprint(v.innerRadius)-sizeof(v.innerRadius)) + (e.footprint(v.cap)-sizeof(v.cap)) + (e.footprint(v.bands)-sizeof(v.bands)) + (e.footprint(v.crossings)-sizeof(v.crossings)) + (e.footprint(v.crossingHalfWidth)-sizeof(v.crossingHalfWidth)) + (e.footprint(v.phase)-sizeof(v.phase)) + (e.footprint(v.wobbles)-sizeof(v.wobbles)); }
void Record<MapGeneration::ContourFarmStyle>::attach(Binding &e,JSValueConst v) { e.field(v,"rows",&MapGeneration::ContourFarmStyle::rows); e.field(v,"innerRadius",&MapGeneration::ContourFarmStyle::innerRadius); e.field(v,"cap",&MapGeneration::ContourFarmStyle::cap); e.field(v,"bands",&MapGeneration::ContourFarmStyle::bands); e.field(v,"crossings",&MapGeneration::ContourFarmStyle::crossings); e.field(v,"crossingHalfWidth",&MapGeneration::ContourFarmStyle::crossingHalfWidth); e.field(v,"phase",&MapGeneration::ContourFarmStyle::phase); e.field(v,"wobbles",&MapGeneration::ContourFarmStyle::wobbles); e.overload(v,"outerRadius",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<0 || n>0) throw TypeMismatch("Wrong argument count");
  return e.write(e.native<MapGeneration::ContourFarmStyle>(self,false).outerRadius());
})(e,self,n,a); }); e.overload(v,"reach",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<0 || n>0) throw TypeMismatch("Wrong argument count");
  return e.write(e.native<MapGeneration::ContourFarmStyle>(self,false).reach());
})(e,self,n,a); }); }
MapGeneration::ContourFarm Record<MapGeneration::ContourFarm>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::ContourFarm>(v,[](Binding &e,MapGeneration::ContourFarm &value,JSValueConst v){ e.readField(value,v,"farm",&MapGeneration::ContourFarm::farm); e.readField(value,v,"crossings",&MapGeneration::ContourFarm::crossings); }); }
std::uint64_t Record<MapGeneration::ContourFarm>::footprint(Binding &e,const MapGeneration::ContourFarm&v) { return sizeof(v)+(e.footprint(v.farm)-sizeof(v.farm)) + (e.footprint(v.crossings)-sizeof(v.crossings)); }
void Record<MapGeneration::ContourFarm>::attach(Binding &e,JSValueConst v) { e.field(v,"farm",&MapGeneration::ContourFarm::farm); e.field(v,"crossings",&MapGeneration::ContourFarm::crossings); }
MapGeneration::FarmPlot Record<MapGeneration::FarmPlot>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::FarmPlot>(v,[](Binding &e,MapGeneration::FarmPlot &value,JSValueConst v){ e.readField(value,v,"width",&MapGeneration::FarmPlot::width); e.readField(value,v,"height",&MapGeneration::FarmPlot::height); e.readField(value,v,"ring",&MapGeneration::FarmPlot::ring); }); }
std::uint64_t Record<MapGeneration::FarmPlot>::footprint(Binding &e,const MapGeneration::FarmPlot&v) { return sizeof(v)+(e.footprint(v.width)-sizeof(v.width)) + (e.footprint(v.height)-sizeof(v.height)) + (e.footprint(v.ring)-sizeof(v.ring)); }
void Record<MapGeneration::FarmPlot>::attach(Binding &e,JSValueConst v) { e.field(v,"width",&MapGeneration::FarmPlot::width); e.field(v,"height",&MapGeneration::FarmPlot::height); e.field(v,"ring",&MapGeneration::FarmPlot::ring); }
MapGeneration::FarmBridges Record<MapGeneration::FarmBridges>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::FarmBridges>(v,[](Binding &e,MapGeneration::FarmBridges &value,JSValueConst v){ e.readField(value,v,"spacing",&MapGeneration::FarmBridges::spacing); e.readField(value,v,"water",&MapGeneration::FarmBridges::water); e.readField(value,v,"crops",&MapGeneration::FarmBridges::crops); }); }
std::uint64_t Record<MapGeneration::FarmBridges>::footprint(Binding &e,const MapGeneration::FarmBridges&v) { return sizeof(v)+(e.footprint(v.spacing)-sizeof(v.spacing)) + (e.footprint(v.water)-sizeof(v.water)) + (e.footprint(v.crops)-sizeof(v.crops)); }
void Record<MapGeneration::FarmBridges>::attach(Binding &e,JSValueConst v) { e.field(v,"spacing",&MapGeneration::FarmBridges::spacing); e.field(v,"water",&MapGeneration::FarmBridges::water); e.field(v,"crops",&MapGeneration::FarmBridges::crops); e.overload(v,"crosses",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<bool> arg0(e,a[0]);
  return e.write(e.native<MapGeneration::FarmBridges>(self,false).crosses(arg0.get()));
})(e,self,n,a); }); }
MapGeneration::SealedOval Record<MapGeneration::SealedOval>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::SealedOval>(v,[](Binding &e,MapGeneration::SealedOval &value,JSValueConst v){ e.readField(value,v,"x",&MapGeneration::SealedOval::x); e.readField(value,v,"y",&MapGeneration::SealedOval::y); e.readField(value,v,"angle",&MapGeneration::SealedOval::angle); e.readField(value,v,"radius",&MapGeneration::SealedOval::radius); e.readField(value,v,"stretch",&MapGeneration::SealedOval::stretch); e.readField(value,v,"sealWidth",&MapGeneration::SealedOval::sealWidth); e.readField(value,v,"sway",&MapGeneration::SealedOval::sway); }); }
std::uint64_t Record<MapGeneration::SealedOval>::footprint(Binding &e,const MapGeneration::SealedOval&v) { return sizeof(v)+(e.footprint(v.x)-sizeof(v.x)) + (e.footprint(v.y)-sizeof(v.y)) + (e.footprint(v.angle)-sizeof(v.angle)) + (e.footprint(v.radius)-sizeof(v.radius)) + (e.footprint(v.stretch)-sizeof(v.stretch)) + (e.footprint(v.sealWidth)-sizeof(v.sealWidth)) + (e.footprint(v.sway)-sizeof(v.sway)); }
void Record<MapGeneration::SealedOval>::attach(Binding &e,JSValueConst v) { e.field(v,"x",&MapGeneration::SealedOval::x); e.field(v,"y",&MapGeneration::SealedOval::y); e.field(v,"angle",&MapGeneration::SealedOval::angle); e.field(v,"radius",&MapGeneration::SealedOval::radius); e.field(v,"stretch",&MapGeneration::SealedOval::stretch); e.field(v,"sealWidth",&MapGeneration::SealedOval::sealWidth); e.field(v,"sway",&MapGeneration::SealedOval::sway); }
MapGeneration::RegionEdge Record<MapGeneration::RegionEdge>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::RegionEdge>(v,[](Binding &e,MapGeneration::RegionEdge &value,JSValueConst v){ e.readField(value,v,"from",&MapGeneration::RegionEdge::from); e.readField(value,v,"to",&MapGeneration::RegionEdge::to); e.readField(value,v,"length",&MapGeneration::RegionEdge::length); }); }
std::uint64_t Record<MapGeneration::RegionEdge>::footprint(Binding &e,const MapGeneration::RegionEdge&v) { return sizeof(v)+(e.footprint(v.from)-sizeof(v.from)) + (e.footprint(v.to)-sizeof(v.to)) + (e.footprint(v.length)-sizeof(v.length)); }
void Record<MapGeneration::RegionEdge>::attach(Binding &e,JSValueConst v) { e.field(v,"from",&MapGeneration::RegionEdge::from); e.field(v,"to",&MapGeneration::RegionEdge::to); e.field(v,"length",&MapGeneration::RegionEdge::length); }
MapGeneration::CrossingCandidate Record<MapGeneration::CrossingCandidate>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::CrossingCandidate>(v,[](Binding &e,MapGeneration::CrossingCandidate &value,JSValueConst v){ e.readField(value,v,"id",&MapGeneration::CrossingCandidate::id); e.readField(value,v,"fromRegion",&MapGeneration::CrossingCandidate::fromRegion); e.readField(value,v,"toRegion",&MapGeneration::CrossingCandidate::toRegion); e.readField(value,v,"level",&MapGeneration::CrossingCandidate::level); e.readField(value,v,"parentRegion",&MapGeneration::CrossingCandidate::parentRegion); e.readField(value,v,"length",&MapGeneration::CrossingCandidate::length); e.readField(value,v,"from",&MapGeneration::CrossingCandidate::from); e.readField(value,v,"to",&MapGeneration::CrossingCandidate::to); }); }
std::uint64_t Record<MapGeneration::CrossingCandidate>::footprint(Binding &e,const MapGeneration::CrossingCandidate&v) { return sizeof(v)+(e.footprint(v.id)-sizeof(v.id)) + (e.footprint(v.fromRegion)-sizeof(v.fromRegion)) + (e.footprint(v.toRegion)-sizeof(v.toRegion)) + (e.footprint(v.level)-sizeof(v.level)) + (e.footprint(v.parentRegion)-sizeof(v.parentRegion)) + (e.footprint(v.length)-sizeof(v.length)) + (e.footprint(v.from)-sizeof(v.from)) + (e.footprint(v.to)-sizeof(v.to)); }
void Record<MapGeneration::CrossingCandidate>::attach(Binding &e,JSValueConst v) { e.field(v,"id",&MapGeneration::CrossingCandidate::id); e.field(v,"fromRegion",&MapGeneration::CrossingCandidate::fromRegion); e.field(v,"toRegion",&MapGeneration::CrossingCandidate::toRegion); e.field(v,"level",&MapGeneration::CrossingCandidate::level); e.field(v,"parentRegion",&MapGeneration::CrossingCandidate::parentRegion); e.field(v,"length",&MapGeneration::CrossingCandidate::length); e.field(v,"from",&MapGeneration::CrossingCandidate::from); e.field(v,"to",&MapGeneration::CrossingCandidate::to); }
MapGeneration::CrossingProposals Record<MapGeneration::CrossingProposals>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::CrossingProposals>(v,[](Binding &e,MapGeneration::CrossingProposals &value,JSValueConst v){ e.readField(value,v,"candidates",&MapGeneration::CrossingProposals::candidates); e.readField(value,v,"failure",&MapGeneration::CrossingProposals::failure); }); }
std::uint64_t Record<MapGeneration::CrossingProposals>::footprint(Binding &e,const MapGeneration::CrossingProposals&v) { return sizeof(v)+(e.footprint(v.candidates)-sizeof(v.candidates)) + (e.footprint(v.failure)-sizeof(v.failure)); }
void Record<MapGeneration::CrossingProposals>::attach(Binding &e,JSValueConst v) { e.field(v,"candidates",&MapGeneration::CrossingProposals::candidates); e.field(v,"failure",&MapGeneration::CrossingProposals::failure); }
MapGeneration::CrossingGraph Record<MapGeneration::CrossingGraph>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::CrossingGraph>(v,[](Binding &e,MapGeneration::CrossingGraph &value,JSValueConst v){ e.readField(value,v,"edges",&MapGeneration::CrossingGraph::edges); e.readField(value,v,"regions",&MapGeneration::CrossingGraph::regions); e.readField(value,v,"failure",&MapGeneration::CrossingGraph::failure); }); }
std::uint64_t Record<MapGeneration::CrossingGraph>::footprint(Binding &e,const MapGeneration::CrossingGraph&v) { return sizeof(v)+(e.footprint(v.edges)-sizeof(v.edges)) + (e.footprint(v.regions)-sizeof(v.regions)) + (e.footprint(v.failure)-sizeof(v.failure)); }
void Record<MapGeneration::CrossingGraph>::attach(Binding &e,JSValueConst v) { e.field(v,"edges",&MapGeneration::CrossingGraph::edges); e.field(v,"regions",&MapGeneration::CrossingGraph::regions); e.field(v,"failure",&MapGeneration::CrossingGraph::failure); }
MapGeneration::CrossingSelection Record<MapGeneration::CrossingSelection>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::CrossingSelection>(v,[](Binding &e,MapGeneration::CrossingSelection &value,JSValueConst v){ e.readField(value,v,"selected",&MapGeneration::CrossingSelection::selected); e.readField(value,v,"benefits",&MapGeneration::CrossingSelection::benefits); e.readField(value,v,"mandatory",&MapGeneration::CrossingSelection::mandatory); e.readField(value,v,"local",&MapGeneration::CrossingSelection::local); e.readField(value,v,"major",&MapGeneration::CrossingSelection::major); e.readField(value,v,"localShortfall",&MapGeneration::CrossingSelection::localShortfall); e.readField(value,v,"majorShortfall",&MapGeneration::CrossingSelection::majorShortfall); e.readField(value,v,"failure",&MapGeneration::CrossingSelection::failure); }); }
std::uint64_t Record<MapGeneration::CrossingSelection>::footprint(Binding &e,const MapGeneration::CrossingSelection&v) { return sizeof(v)+(e.footprint(v.selected)-sizeof(v.selected)) + (e.footprint(v.benefits)-sizeof(v.benefits)) + (e.footprint(v.mandatory)-sizeof(v.mandatory)) + (e.footprint(v.local)-sizeof(v.local)) + (e.footprint(v.major)-sizeof(v.major)) + (e.footprint(v.localShortfall)-sizeof(v.localShortfall)) + (e.footprint(v.majorShortfall)-sizeof(v.majorShortfall)) + (e.footprint(v.failure)-sizeof(v.failure)); }
void Record<MapGeneration::CrossingSelection>::attach(Binding &e,JSValueConst v) { e.field(v,"selected",&MapGeneration::CrossingSelection::selected); e.field(v,"benefits",&MapGeneration::CrossingSelection::benefits); e.field(v,"mandatory",&MapGeneration::CrossingSelection::mandatory); e.field(v,"local",&MapGeneration::CrossingSelection::local); e.field(v,"major",&MapGeneration::CrossingSelection::major); e.field(v,"localShortfall",&MapGeneration::CrossingSelection::localShortfall); e.field(v,"majorShortfall",&MapGeneration::CrossingSelection::majorShortfall); e.field(v,"failure",&MapGeneration::CrossingSelection::failure); }
GenerationNoise Record<GenerationNoise>::read(Binding &e,JSValueConst v) { return e.record<GenerationNoise>(v,[](Binding &e,GenerationNoise &value,JSValueConst v){  }); }
std::uint64_t Record<GenerationNoise>::footprint(Binding &e,const GenerationNoise&v) { return sizeof(v)+0; }
void Record<GenerationNoise>::attach(Binding &e,JSValueConst v) {  e.overload(v,"reseed",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<unsigned int> arg0(e,a[0]);
  e.preflight("rSeed",arg0.get());
  e.native<GenerationNoise>(self,true).reseed(arg0.get()); return JS_UNDEFINED;
})(e,self,n,a); }); e.overload(v,"Noise1d",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<float[1]> arg0(e,a[0]);
  return e.write(e.native<GenerationNoise>(self,true).Noise1d(arg0.get()));
})(e,self,n,a); }); e.overload(v,"Noise2d",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<float[2]> arg0(e,a[0]);
  return e.write(e.native<GenerationNoise>(self,true).Noise2d(arg0.get()));
})(e,self,n,a); }); e.overload(v,"Noise3d",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<float[3]> arg0(e,a[0]);
  return e.write(e.native<GenerationNoise>(self,true).Noise3d(arg0.get()));
})(e,self,n,a); }); e.overload(v,"Noise",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<float> arg0(e,a[0]);
  e.preflight("",arg0.get());
  return e.write(e.native<GenerationNoise>(self,true).Noise(arg0.get()));
})(e,self,n,a); }); e.overload(v,"Noise",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<float> arg0(e,a[0]);
  e.preflight("",arg0.get());
  Argument<float> arg1(e,a[1]);
  e.preflight("",arg1.get());
  return e.write(e.native<GenerationNoise>(self,true).Noise(arg0.get(), arg1.get()));
})(e,self,n,a); }); e.overload(v,"Noise",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  Argument<float> arg0(e,a[0]);
  e.preflight("",arg0.get());
  Argument<float> arg1(e,a[1]);
  e.preflight("",arg1.get());
  Argument<float> arg2(e,a[2]);
  e.preflight("",arg2.get());
  return e.write(e.native<GenerationNoise>(self,true).Noise(arg0.get(), arg1.get(), arg2.get()));
})(e,self,n,a); }); }
MapGeneration::Island Record<MapGeneration::Island>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::Island>(v,[](Binding &e,MapGeneration::Island &value,JSValueConst v){ e.readField(value,v,"x",&MapGeneration::Island::x); e.readField(value,v,"y",&MapGeneration::Island::y); e.readField(value,v,"reach",&MapGeneration::Island::reach); e.readField(value,v,"tiles",&MapGeneration::Island::tiles); }); }
std::uint64_t Record<MapGeneration::Island>::footprint(Binding &e,const MapGeneration::Island&v) { return sizeof(v)+(e.footprint(v.x)-sizeof(v.x)) + (e.footprint(v.y)-sizeof(v.y)) + (e.footprint(v.reach)-sizeof(v.reach)) + (e.footprint(v.tiles)-sizeof(v.tiles)); }
void Record<MapGeneration::Island>::attach(Binding &e,JSValueConst v) { e.field(v,"x",&MapGeneration::Island::x); e.field(v,"y",&MapGeneration::Island::y); e.field(v,"reach",&MapGeneration::Island::reach); e.field(v,"tiles",&MapGeneration::Island::tiles); }
MapGeneration::IslandPlacement Record<MapGeneration::IslandPlacement>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::IslandPlacement>(v,[](Binding &e,MapGeneration::IslandPlacement &value,JSValueConst v){ e.readField(value,v,"stream",&MapGeneration::IslandPlacement::stream); e.readField(value,v,"wanted",&MapGeneration::IslandPlacement::wanted); e.readField(value,v,"attemptsPerIsland",&MapGeneration::IslandPlacement::attemptsPerIsland); e.readField(value,v,"moat",&MapGeneration::IslandPlacement::moat); }); }
std::uint64_t Record<MapGeneration::IslandPlacement>::footprint(Binding &e,const MapGeneration::IslandPlacement&v) { return sizeof(v)+(e.footprint(v.stream)-sizeof(v.stream)) + (e.footprint(v.wanted)-sizeof(v.wanted)) + (e.footprint(v.attemptsPerIsland)-sizeof(v.attemptsPerIsland)) + (e.footprint(v.moat)-sizeof(v.moat)); }
void Record<MapGeneration::IslandPlacement>::attach(Binding &e,JSValueConst v) { e.field(v,"stream",&MapGeneration::IslandPlacement::stream); e.field(v,"wanted",&MapGeneration::IslandPlacement::wanted); e.field(v,"attemptsPerIsland",&MapGeneration::IslandPlacement::attemptsPerIsland); e.field(v,"moat",&MapGeneration::IslandPlacement::moat); }
MapGeneration::ComponentLabels Record<MapGeneration::ComponentLabels>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::ComponentLabels>(v,[](Binding &e,MapGeneration::ComponentLabels &value,JSValueConst v){ e.readField(value,v,"owners",&MapGeneration::ComponentLabels::owners); e.readField(value,v,"conflictTile",&MapGeneration::ComponentLabels::conflictTile); }); }
std::uint64_t Record<MapGeneration::ComponentLabels>::footprint(Binding &e,const MapGeneration::ComponentLabels&v) { return sizeof(v)+(e.footprint(v.owners)-sizeof(v.owners)) + (e.footprint(v.conflictTile)-sizeof(v.conflictTile)); }
void Record<MapGeneration::ComponentLabels>::attach(Binding &e,JSValueConst v) { e.field(v,"owners",&MapGeneration::ComponentLabels::owners); e.field(v,"conflictTile",&MapGeneration::ComponentLabels::conflictTile); }
MapGeneration::DisjointSets Record<MapGeneration::DisjointSets>::read(Binding &e,JSValueConst v) { return e.record<MapGeneration::DisjointSets>(v,[](Binding &e,MapGeneration::DisjointSets &value,JSValueConst v){ e.readField(value,v,"parent",&MapGeneration::DisjointSets::parent); }); }
std::uint64_t Record<MapGeneration::DisjointSets>::footprint(Binding &e,const MapGeneration::DisjointSets&v) { return sizeof(v)+(e.footprint(v.parent)-sizeof(v.parent)); }
void Record<MapGeneration::DisjointSets>::attach(Binding &e,JSValueConst v) { e.field(v,"parent",&MapGeneration::DisjointSets::parent); e.overload(v,"find",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<int> arg0(e,a[0]);
  e.preflight("a",arg0.get());
  return e.write(e.native<MapGeneration::DisjointSets>(self,true).find(arg0.get()));
})(e,self,n,a); }); e.overload(v,"unite",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<int> arg0(e,a[0]);
  e.preflight("a",arg0.get());
  Argument<int> arg1(e,a[1]);
  e.preflight("b",arg1.get());
  return e.write(e.native<MapGeneration::DisjointSets>(self,true).unite(arg0.get(), arg1.get()));
})(e,self,n,a); }); e.overload(v,"joined",[&e](JSValueConst self,int n,JSValueConst*a) { return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<int> arg0(e,a[0]);
  e.preflight("a",arg0.get());
  Argument<int> arg1(e,a[1]);
  e.preflight("b",arg1.get());
  return e.write(e.native<MapGeneration::DisjointSets>(self,true).joined(arg0.get(), arg1.get()));
})(e,self,n,a); }); }
void registerToolkit0(Binding &e,JSValueConst root) {
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"SeparatedSites",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::SeparatedSites>(a[0]):e.defaultRecord<MapGeneration::SeparatedSites>()); })(e,self,n,a);});
e.overload(object,"selectSeparatedSites",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>5) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<const std::vector<int> &> arg1(e,a[1]);
  Argument<int> arg2(e,a[2]);
  e.preflight("count",arg2.get());
  Argument<int> arg3(e,a[3]);
  e.preflight("minimumSeparation",arg3.get());
  int default4 = 64;
  Script::JSValueOwner fallback4(e.ctx, (n>4 && !JS_IsUndefined(a[4]))?JS_UNDEFINED:e.write(default4));
  Argument<int> arg4(e,(n>4 && !JS_IsUndefined(a[4]))?a[4]:fallback4.get());
  if(n>4) e.preflight("maximumAttempts",arg4.get());
  return e.write(MapGeneration::selectSeparatedSites(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get()));
})(e,self,n,a);});
e.overload(object,"chooseBalancedStarts",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  if(!e.generation || e.inspecting) throw TypeMismatch("Generation context unavailable");
  Argument<int> arg2(e,a[0]);
  e.preflight("minDistSquare",arg2.get());
  return e.write(MapGeneration::chooseBalancedStarts((*e.game), (*e.generation), arg2.get()));
})(e,self,n,a);});
if(JS_SetPropertyStr(e.ctx,root,"BalancedStarts",objectOwner.release())<0)e.fail(); }
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"ShoreField",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::ShoreField>(a[0]):e.defaultRecord<MapGeneration::ShoreField>()); })(e,self,n,a);});
e.overload(object,"FarmRows",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::FarmRows>(a[0]):e.defaultRecord<MapGeneration::FarmRows>()); })(e,self,n,a);});
e.overload(object,"Farm",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::Farm>(a[0]):e.defaultRecord<MapGeneration::Farm>()); })(e,self,n,a);});
e.overload(object,"ContourWobble",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::ContourWobble>(a[0]):e.defaultRecord<MapGeneration::ContourWobble>()); })(e,self,n,a);});
e.overload(object,"ContourFarmStyle",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::ContourFarmStyle>(a[0]):e.defaultRecord<MapGeneration::ContourFarmStyle>()); })(e,self,n,a);});
e.overload(object,"ContourFarm",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::ContourFarm>(a[0]):e.defaultRecord<MapGeneration::ContourFarm>()); })(e,self,n,a);});
e.overload(object,"FarmPlot",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::FarmPlot>(a[0]):e.defaultRecord<MapGeneration::FarmPlot>()); })(e,self,n,a);});
e.overload(object,"FarmBridges",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::FarmBridges>(a[0]):e.defaultRecord<MapGeneration::FarmBridges>()); })(e,self,n,a);});
e.overload(object,"SealedOval",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::SealedOval>(a[0]):e.defaultRecord<MapGeneration::SealedOval>()); })(e,self,n,a);});
e.overload(object,"layShoreFields",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<5 || n>6) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<const std::vector<unsigned char> &> arg2(e,a[2]);
  Argument<std::vector<int> &> arg3(e,a[3]);
  Argument<int> arg4(e,a[4]);
  e.preflight("firstPlot",arg4.get());
  bool default5 = true;
  Script::JSValueOwner fallback5(e.ctx, (n>5 && !JS_IsUndefined(a[5]))?JS_UNDEFINED:e.write(default5));
  Argument<bool> arg5(e,(n>5 && !JS_IsUndefined(a[5]))?a[5]:fallback5.get());
  return e.write(MapGeneration::layShoreFields(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get()));
})(e,self,n,a);});
e.overload(object,"plantShoreFields",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>4) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<const MapGeneration::Torus &> arg1(e,a[0]);
  Argument<const std::vector<MapGeneration::ShoreField> &> arg2(e,a[1]);
  Argument<const Fertility::Field &> arg3(e,a[2]);
  prepareFertilityRead(arg3.get());
  Argument<int> arg4(e,a[3]);
  e.preflight("percent",arg4.get());
  return e.write(MapGeneration::plantShoreFields(e.game->map, arg1.get(), arg2.get(), arg3.get(), arg4.get()));
})(e,self,n,a);});
e.overload(object,"stampContainedPlot",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<const std::vector<int> &> arg2(e,a[2]);
  int default3 = 2;
  Script::JSValueOwner fallback3(e.ctx, (n>3 && !JS_IsUndefined(a[3]))?JS_UNDEFINED:e.write(default3));
  Argument<int> arg3(e,(n>3 && !JS_IsUndefined(a[3]))?a[3]:fallback3.get());
  if(n>3) e.preflight("margin",arg3.get());
  return e.write(MapGeneration::stampContainedPlot(arg0.get(), arg1.get(), arg2.get(), arg3.get()));
})(e,self,n,a);});
e.overload(object,"plantContainedPlot",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<5 || n>6) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<const MapGeneration::Torus &> arg1(e,a[0]);
  Argument<const std::vector<int> &> arg2(e,a[1]);
  Argument<const Fertility::Field &> arg3(e,a[2]);
  prepareFertilityRead(arg3.get());
  Argument<int> arg4(e,a[3]);
  e.preflight("resource",arg4.get());
  Argument<int> arg5(e,a[4]);
  e.preflight("wanted",arg5.get());
  bool default6 = true;
  Script::JSValueOwner fallback6(e.ctx, (n>5 && !JS_IsUndefined(a[5]))?JS_UNDEFINED:e.write(default6));
  Argument<bool> arg6(e,(n>5 && !JS_IsUndefined(a[5]))?a[5]:fallback6.get());
  return e.write(MapGeneration::plantContainedPlot(e.game->map, arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get()));
})(e,self,n,a);});
e.overload(object,"containedPlotsMismatch",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>4) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting) throw TypeMismatch("World access unavailable in this callback");
  Argument<const MapGeneration::Torus &> arg1(e,a[0]);
  Argument<const std::vector<int> &> arg2(e,a[1]);
  Fertility::Field * default3 = nullptr;
  Script::JSValueOwner fallback3(e.ctx, (n>2 && !JS_IsUndefined(a[2]))?JS_UNDEFINED:JS_NULL);
  Argument<const Fertility::Field *> arg3(e,(n>2 && !JS_IsUndefined(a[2]))?a[2]:fallback3.get());
  if(arg3.get()) prepareFertilityRead(*arg3.get());
  std::vector<unsigned char> * default4 = nullptr;
  Script::JSValueOwner fallback4(e.ctx, (n>3 && !JS_IsUndefined(a[3]))?JS_UNDEFINED:JS_NULL);
  Argument<const std::vector<unsigned char> *> arg4(e,(n>3 && !JS_IsUndefined(a[3]))?a[3]:fallback4.get());
  return e.write(MapGeneration::containedPlotsMismatch(e.game->map, arg1.get(), arg2.get(), arg3.get(), arg4.get()));
})(e,self,n,a);});
e.overload(object,"bestFarmRows",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<double> arg0(e,a[0]);
  e.preflight("angle",arg0.get());
  return e.write(MapGeneration::bestFarmRows(arg0.get()));
})(e,self,n,a);});
e.overload(object,"farmYield",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<double> arg0(e,a[0]);
  e.preflight("angle",arg0.get());
  return e.write(MapGeneration::farmYield(arg0.get()));
})(e,self,n,a);});
e.overload(object,"contourNominal",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::ContourFarmStyle &> arg0(e,a[0]);
  Argument<unsigned long> arg1(e,a[1]);
  e.preflight("centre",arg1.get());
  Argument<double> arg2(e,a[2]);
  e.preflight("distance",arg2.get());
  Argument<double> arg3(e,a[3]);
  e.preflight("angle",arg3.get());
  return e.write(MapGeneration::contourNominal(arg0.get(), arg1.get(), arg2.get(), arg3.get()));
})(e,self,n,a);});
e.overload(object,"layContourFarm",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<const std::vector<MapGeneration::ShapePoint> &> arg2(e,a[2]);
  Argument<const MapGeneration::ContourFarmStyle &> arg3(e,a[3]);
  return e.write(MapGeneration::layContourFarm(arg0.get(), arg1.get(), arg2.get(), arg3.get()));
})(e,self,n,a);});
e.overload(object,"waterCrossingsControl",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<0 || n>0) throw TypeMismatch("Wrong argument count");
  return e.write(MapGeneration::waterCrossingsControl());
})(e,self,n,a);});
e.overload(object,"cropCrossingsControl",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<0 || n>0) throw TypeMismatch("Wrong argument count");
  return e.write(MapGeneration::cropCrossingsControl());
})(e,self,n,a);});
e.overload(object,"layFarm",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<7 || n>11) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<const std::vector<unsigned char> &> arg2(e,a[2]);
  Argument<double> arg3(e,a[3]);
  e.preflight("angle",arg3.get());
  Argument<MapGeneration::ShapePoint> arg4(e,a[4]);
  Argument<int> arg5(e,a[5]);
  e.preflight("rim",arg5.get());
  Argument<const MapGeneration::FarmRows &> arg6(e,a[6]);
  MapGeneration::FarmPlot * default7 = nullptr;
  Script::JSValueOwner fallback7(e.ctx, (n>7 && !JS_IsUndefined(a[7]))?JS_UNDEFINED:JS_NULL);
  Argument<const MapGeneration::FarmPlot *> arg7(e,(n>7 && !JS_IsUndefined(a[7]))?a[7]:fallback7.get());
  MapGeneration::FarmBridges default8 = { };
  Script::JSValueOwner fallback8(e.ctx, (n>8 && !JS_IsUndefined(a[8]))?JS_UNDEFINED:e.write(default8));
  Argument<const MapGeneration::FarmBridges &> arg8(e,(n>8 && !JS_IsUndefined(a[8]))?a[8]:fallback8.get());
  bool default9 = true;
  Script::JSValueOwner fallback9(e.ctx, (n>9 && !JS_IsUndefined(a[9]))?JS_UNDEFINED:e.write(default9));
  Argument<bool> arg9(e,(n>9 && !JS_IsUndefined(a[9]))?a[9]:fallback9.get());
  std::vector<int> * default10 = nullptr;
  Script::JSValueOwner fallback10(e.ctx, (n>10 && !JS_IsUndefined(a[10]))?JS_UNDEFINED:JS_NULL);
  Argument<std::vector<int> *> arg10(e,(n>10 && !JS_IsUndefined(a[10]))?a[10]:fallback10.get());
  return e.write(MapGeneration::layFarm(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get(), arg8.get(), arg9.get(), arg10.get()));
})(e,self,n,a);});
e.overload(object,"stampFarmPlot",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<6 || n>6) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<MapGeneration::Farm &> arg2(e,a[2]);
  Argument<int> arg3(e,a[3]);
  e.preflight("x0",arg3.get());
  Argument<int> arg4(e,a[4]);
  e.preflight("y0",arg4.get());
  Argument<const MapGeneration::FarmPlot &> arg5(e,a[5]);
  MapGeneration::stampFarmPlot(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"growFarmFields",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<9 || n>11) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<const std::vector<unsigned char> &> arg1(e,a[1]);
  Argument<const std::vector<int> &> arg2(e,a[2]);
  Argument<const std::vector<unsigned char> &> arg3(e,a[3]);
  Argument<const std::vector<MapGeneration::ShapePoint> &> arg4(e,a[4]);
  Argument<const std::vector<int> &> arg5(e,a[5]);
  Argument<const std::vector<MapGeneration::ShapePoint> &> arg6(e,a[6]);
  Argument<int> arg7(e,a[7]);
  e.preflight("gap",arg7.get());
  Argument<double> arg8(e,a[8]);
  e.preflight("neckHalfWidth",arg8.get());
  std::vector<double> default9 = { };
  Script::JSValueOwner fallback9(e.ctx, (n>9 && !JS_IsUndefined(a[9]))?JS_UNDEFINED:e.write(default9));
  Argument<const std::vector<double> &> arg9(e,(n>9 && !JS_IsUndefined(a[9]))?a[9]:fallback9.get());
  int default10 = kFarmOpening;
  Script::JSValueOwner fallback10(e.ctx, (n>10 && !JS_IsUndefined(a[10]))?JS_UNDEFINED:e.write(default10));
  Argument<int> arg10(e,(n>10 && !JS_IsUndefined(a[10]))?a[10]:fallback10.get());
  if(n>10) e.preflight("opening",arg10.get());
  return e.write(MapGeneration::growFarmFields(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get(), arg8.get(), arg9.get(), arg10.get()));
})(e,self,n,a);});
e.overload(object,"farmReachable",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting) throw TypeMismatch("World access unavailable in this callback");
  Argument<const MapGeneration::Torus &> arg1(e,a[0]);
  Argument<const MapGeneration::Farm &> arg2(e,a[1]);
  Argument<const std::vector<int> &> arg3(e,a[2]);
  return e.write(MapGeneration::farmReachable(e.game->map, arg1.get(), arg2.get(), arg3.get()));
})(e,self,n,a);});
e.overload(object,"clearFarmPlots",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<const MapGeneration::Torus &> arg1(e,a[0]);
  Argument<const std::vector<MapGeneration::Farm> &> arg2(e,a[1]);
  MapGeneration::clearFarmPlots(e.game->map, arg1.get(), arg2.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"plantFarm",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<5 || n>5) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<const MapGeneration::Torus &> arg1(e,a[0]);
  Argument<const MapGeneration::Farm &> arg2(e,a[1]);
  Argument<int> arg3(e,a[2]);
  e.preflight("wheat",arg3.get());
  Argument<int> arg4(e,a[3]);
  e.preflight("wood",arg4.get());
  Argument<std::function<bool(int)>> arg5(e,a[4]);
  return e.write(MapGeneration::plantFarm(e.game->map, arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get()));
})(e,self,n,a);});
e.overload(object,"stampSealedOval",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<5 || n>5) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<const std::vector<unsigned char> &> arg2(e,a[2]);
  Argument<const MapGeneration::SealedOval &> arg3(e,a[3]);
  Argument<const std::vector<int> &> arg4(e,a[4]);
  return e.write(MapGeneration::stampSealedOval(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get()));
})(e,self,n,a);});
e.overload(object,"plantSealedGarden",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<6 || n>6) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<const MapGeneration::Torus &> arg1(e,a[0]);
  if(!e.generation || e.inspecting) throw TypeMismatch("Generation context unavailable");
  Argument<const std::vector<unsigned char> &> arg3(e,a[1]);
  Argument<int> arg4(e,a[2]);
  e.preflight("wheat",arg4.get());
  Argument<int> arg5(e,a[3]);
  e.preflight("wood",arg5.get());
  Argument<const std::string &> arg6(e,a[4]);
  Argument<const std::string &> arg7(e,a[5]);
  return e.write(MapGeneration::plantSealedGarden(e.game->map, arg1.get(), (*e.generation), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get()));
})(e,self,n,a);});
e.overload(object,"trimFieldsBeyondWater",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<6 || n>6) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<const MapGeneration::Torus &> arg1(e,a[0]);
  Argument<const std::vector<unsigned char> &> arg2(e,a[1]);
  Argument<const Fertility::Field &> arg3(e,a[2]);
  prepareFertilityRead(arg3.get());
  Argument<int> arg4(e,a[3]);
  e.preflight("leastReach",arg4.get());
  Argument<int> arg5(e,a[4]);
  e.preflight("reachSpread",arg5.get());
  Argument<const std::vector<int> &> arg6(e,a[5]);
  return e.write(MapGeneration::trimFieldsBeyondWater(e.game->map, arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get()));
})(e,self,n,a);});
e.overload(object,"frayFieldEdges",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>4) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<const MapGeneration::Torus &> arg1(e,a[0]);
  Argument<const std::vector<unsigned char> &> arg2(e,a[1]);
  Argument<int> arg3(e,a[2]);
  e.preflight("depth",arg3.get());
  Argument<const std::vector<int> &> arg4(e,a[3]);
  return e.write(MapGeneration::frayFieldEdges(e.game->map, arg1.get(), arg2.get(), arg3.get(), arg4.get()));
})(e,self,n,a);});
e.overload(object,"removeCropSlivers",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<const MapGeneration::Torus &> arg1(e,a[0]);
  Argument<const std::vector<unsigned char> &> arg2(e,a[1]);
  return e.write(MapGeneration::removeCropSlivers(e.game->map, arg1.get(), arg2.get()));
})(e,self,n,a);});
if(JS_SetPropertyStr(e.ctx,object,"kBridgeHalfWidth",e.write(MapGeneration::kBridgeHalfWidth))<0)e.fail();
if(JS_SetPropertyStr(e.ctx,object,"kFarmOpening",e.write(MapGeneration::kFarmOpening))<0)e.fail();
if(JS_SetPropertyStr(e.ctx,root,"Farmland",objectOwner.release())<0)e.fail(); }
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"RegionEdge",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::RegionEdge>(a[0]):e.defaultRecord<MapGeneration::RegionEdge>()); })(e,self,n,a);});
e.overload(object,"CrossingCandidate",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::CrossingCandidate>(a[0]):e.defaultRecord<MapGeneration::CrossingCandidate>()); })(e,self,n,a);});
e.overload(object,"CrossingProposals",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::CrossingProposals>(a[0]):e.defaultRecord<MapGeneration::CrossingProposals>()); })(e,self,n,a);});
e.overload(object,"CrossingGraph",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::CrossingGraph>(a[0]):e.defaultRecord<MapGeneration::CrossingGraph>()); })(e,self,n,a);});
e.overload(object,"CrossingSelection",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::CrossingSelection>(a[0]):e.defaultRecord<MapGeneration::CrossingSelection>()); })(e,self,n,a);});
e.overload(object,"transverseCrossings",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<MapGeneration::RecursiveSegment> &> arg0(e,a[0]);
  Argument<const std::vector<double> &> arg1(e,a[1]);
  Argument<double> arg2(e,a[2]);
  e.preflight("halfSpan",arg2.get());
  Argument<double> arg3(e,a[3]);
  e.preflight("endClearance",arg3.get());
  return e.write(MapGeneration::transverseCrossings(arg0.get(), arg1.get(), arg2.get(), arg3.get()));
})(e,self,n,a);});
e.overload(object,"crossingEndpointGraph",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<const std::vector<unsigned char> &> arg1(e,a[1]);
  Argument<std::vector<MapGeneration::CrossingCandidate> &> arg2(e,a[2]);
  return e.write(MapGeneration::crossingEndpointGraph(arg0.get(), arg1.get(), arg2.get()));
})(e,self,n,a);});
e.overload(object,"selectCrossings",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<9 || n>10) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<int> arg1(e,a[1]);
  e.preflight("regions",arg1.get());
  Argument<const std::vector<MapGeneration::RegionEdge> &> arg2(e,a[2]);
  Argument<const std::vector<int> &> arg3(e,a[3]);
  Argument<const std::vector<MapGeneration::CrossingCandidate> &> arg4(e,a[4]);
  Argument<int> arg5(e,a[5]);
  e.preflight("localPerParent",arg5.get());
  Argument<int> arg6(e,a[6]);
  e.preflight("majorBudget",arg6.get());
  Argument<int> arg7(e,a[7]);
  e.preflight("separation",arg7.get());
  Argument<unsigned int> arg8(e,a[8]);
  e.preflight("seed",arg8.get());
  std::function<bool (const MapGeneration::CrossingCandidate &, const MapGeneration::CrossingCandidate &)> default9 = { };
  Script::JSValueOwner fallback9(e.ctx, (n>9 && !JS_IsUndefined(a[9]))?JS_UNDEFINED:e.write(default9));
  Argument<const std::function<bool (const MapGeneration::CrossingCandidate &, const MapGeneration::CrossingCandidate &)> &> arg9(e,(n>9 && !JS_IsUndefined(a[9]))?a[9]:fallback9.get());
  return e.write(MapGeneration::selectCrossings(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get(), arg8.get(), arg9.get()));
})(e,self,n,a);});
if(JS_SetPropertyStr(e.ctx,root,"HierarchicalCrossings",objectOwner.release())<0)e.fail(); }
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"GenerationNoise",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<unsigned int> arg0(e,a[0]);
  e.preflight("seed",arg0.get());
  e.allocate(256+sizeof(GenerationNoise));
  auto pointer=std::make_shared<GenerationNoise>(arg0.get());
  e.allocate(e.footprint(*pointer)-sizeof(GenerationNoise));
  return e.handle(pointer.get(),pointer);
})(e,self,n,a);});
if(JS_SetPropertyStr(e.ctx,root,"Noise",objectOwner.release())<0)e.fail(); }
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"permanentResourceBarrier",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>2) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting) throw TypeMismatch("World access unavailable in this callback");
  Argument<unsigned long> arg1(e,a[0]);
  e.preflight("index",arg1.get());
  bool default2 = false;
  Script::JSValueOwner fallback2(e.ctx, (n>1 && !JS_IsUndefined(a[1]))?JS_UNDEFINED:e.write(default2));
  Argument<bool> arg2(e,(n>1 && !JS_IsUndefined(a[1]))?a[1]:fallback2.get());
  return e.write(MapGeneration::permanentResourceBarrier(e.game->map, arg1.get(), arg2.get()));
})(e,self,n,a);});
if(JS_SetPropertyStr(e.ctx,root,"ResourceSemantics",objectOwner.release())<0)e.fail(); }
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"Island",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::Island>(a[0]):e.defaultRecord<MapGeneration::Island>()); })(e,self,n,a);});
e.overload(object,"IslandPlacement",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::IslandPlacement>(a[0]):e.defaultRecord<MapGeneration::IslandPlacement>()); })(e,self,n,a);});
e.overload(object,"layBeaches",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  MapGeneration::layBeaches(arg0.get(), arg1.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"writeVertices",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<const std::vector<unsigned char> &> arg1(e,a[0]);
  MapGeneration::writeVertices(e.game->map, arg1.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"paintTile",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting || e.readonly) throw TypeMismatch("World access unavailable in this callback");
  Argument<int> arg1(e,a[0]);
  e.preflight("x",arg1.get());
  Argument<int> arg2(e,a[1]);
  e.preflight("y",arg2.get());
  Argument<TerrainType> arg3(e,a[2]);
  MapGeneration::paintTile(e.game->map, arg1.get(), arg2.get(), arg3.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"countTiles",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<TerrainType> arg1(e,a[1]);
  return e.write(MapGeneration::countTiles(arg0.get(), arg1.get()));
})(e,self,n,a);});
e.overload(object,"tileCorners",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<const std::vector<unsigned char> &> arg1(e,a[1]);
  return e.write(MapGeneration::tileCorners(arg0.get(), arg1.get()));
})(e,self,n,a);});
e.overload(object,"pureTiles",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<TerrainType> arg2(e,a[2]);
  return e.write(MapGeneration::pureTiles(arg0.get(), arg1.get(), arg2.get()));
})(e,self,n,a);});
e.overload(object,"pureTiles",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  if(!e.game || e.inspecting) throw TypeMismatch("World access unavailable in this callback");
  Argument<TerrainType> arg1(e,a[0]);
  return e.write(MapGeneration::pureTiles(e.game->map, arg1.get()));
})(e,self,n,a);});
e.overload(object,"sprinkleSand",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<6 || n>6) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<const std::vector<unsigned char> &> arg2(e,a[2]);
  Argument<double> arg3(e,a[3]);
  e.preflight("share",arg3.get());
  Argument<int> arg4(e,a[4]);
  e.preflight("inland",arg4.get());
  Argument<std::function<double(int)>> arg5(e,a[5]);
  MapGeneration::sprinkleSand(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"keepRoadInland",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>4) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  Argument<const std::vector<unsigned char> &> arg2(e,a[2]);
  Argument<int> arg3(e,a[3]);
  e.preflight("gap",arg3.get());
  MapGeneration::keepRoadInland(arg0.get(), arg1.get(), arg2.get(), arg3.get()); return JS_UNDEFINED;
})(e,self,n,a);});
e.overload(object,"roadTiles",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<const std::vector<unsigned char> &> arg1(e,a[1]);
  return e.write(MapGeneration::roadTiles(arg0.get(), arg1.get()));
})(e,self,n,a);});
e.overload(object,"growWater",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<8 || n>8) throw TypeMismatch("Wrong argument count");
  Argument<const MapGeneration::Torus &> arg0(e,a[0]);
  Argument<std::vector<unsigned char> &> arg1(e,a[1]);
  Argument<int> arg2(e,a[2]);
  e.preflight("seed",arg2.get());
  Argument<int> arg3(e,a[3]);
  e.preflight("target",arg3.get());
  Argument<std::function<bool(int)>> arg4(e,a[4]);
  Argument<std::function<double(int)>> arg5(e,a[5]);
  Argument<std::vector<int> &> arg6(e,a[6]);
  Argument<int> arg7(e,a[7]);
  e.preflight("stamp",arg7.get());
  return e.write(MapGeneration::growWater(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get(), arg5.get(), arg6.get(), arg7.get()));
})(e,self,n,a);});
e.overload(object,"raiseIslands",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<3 || n>3) throw TypeMismatch("Wrong argument count");
  Argument<std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<const MapGeneration::Torus &> arg1(e,a[1]);
  if(!e.generation || e.inspecting) throw TypeMismatch("Generation context unavailable");
  Argument<const MapGeneration::IslandPlacement &> arg3(e,a[2]);
  return e.write(MapGeneration::raiseIslands(arg0.get(), arg1.get(), (*e.generation), arg3.get()));
})(e,self,n,a);});
if(JS_SetPropertyStr(e.ctx,root,"Sketch",objectOwner.release())<0)e.fail(); }
 { Script::JSValueOwner objectOwner(e.ctx,JS_NewObject(e.ctx));auto object=objectOwner.get();e.check(object);
e.overload(object,"ComponentLabels",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e,JSValueConst,int n,JSValueConst*a)->JSValue { if(n>1)throw TypeMismatch("Expected optional record"); return e.write(n?e.read<MapGeneration::ComponentLabels>(a[0]):e.defaultRecord<MapGeneration::ComponentLabels>()); })(e,self,n,a);});
e.overload(object,"DisjointSets",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<1 || n>1) throw TypeMismatch("Wrong argument count");
  Argument<int> arg0(e,a[0]);
  e.preflight("n",arg0.get());
  e.allocate(256+sizeof(MapGeneration::DisjointSets));
  auto pointer=std::make_shared<MapGeneration::DisjointSets>(arg0.get());
  e.allocate(e.footprint(*pointer)-sizeof(MapGeneration::DisjointSets));
  return e.handle(pointer.get(),pointer);
})(e,self,n,a);});
e.overload(object,"graphDistances",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<std::vector<int>> &> arg0(e,a[0]);
  Argument<const std::vector<int> &> arg1(e,a[1]);
  return e.write(MapGeneration::graphDistances(arg0.get(), arg1.get()));
})(e,self,n,a);});
e.overload(object,"connectedRegions",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<4 || n>5) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<unsigned char> &> arg0(e,a[0]);
  Argument<int> arg1(e,a[1]);
  e.preflight("width",arg1.get());
  Argument<int> arg2(e,a[2]);
  e.preflight("height",arg2.get());
  Argument<bool> arg3(e,a[3]);
  MapGeneration::GridNeighbors default4 = GridNeighbors :: Cardinal;
  Script::JSValueOwner fallback4(e.ctx, (n>4 && !JS_IsUndefined(a[4]))?JS_UNDEFINED:e.write(default4));
  Argument<MapGeneration::GridNeighbors> arg4(e,(n>4 && !JS_IsUndefined(a[4]))?a[4]:fallback4.get());
  return e.write(MapGeneration::connectedRegions(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get()));
})(e,self,n,a);});
e.overload(object,"labelComponents",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<2 || n>2) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<int> &> arg0(e,a[0]);
  Argument<const std::vector<int> &> arg1(e,a[1]);
  return e.write(MapGeneration::labelComponents(arg0.get(), arg1.get()));
})(e,self,n,a);});
e.overload(object,"regionAdjacency",[&e](JSValueConst self,int n,JSValueConst*a){return ([](Binding &e, JSValueConst self, int n, JSValueConst *a)->JSValue {
  if(n<5 || n>5) throw TypeMismatch("Wrong argument count");
  Argument<const std::vector<int> &> arg0(e,a[0]);
  Argument<int> arg1(e,a[1]);
  e.preflight("width",arg1.get());
  Argument<int> arg2(e,a[2]);
  e.preflight("height",arg2.get());
  Argument<const std::vector<int> &> arg3(e,a[3]);
  Argument<bool> arg4(e,a[4]);
  return e.write(MapGeneration::regionAdjacency(arg0.get(), arg1.get(), arg2.get(), arg3.get(), arg4.get()));
})(e,self,n,a);});
 { Script::JSValueOwner valuesOwner(e.ctx,JS_NewObject(e.ctx));auto values=valuesOwner.get();e.check(values);
if(JS_SetPropertyStr(e.ctx,values,"Cardinal",e.write(MapGeneration::GridNeighbors::Cardinal))<0)e.fail();
if(JS_SetPropertyStr(e.ctx,values,"Eight",e.write(MapGeneration::GridNeighbors::Eight))<0)e.fail();
if(JS_SetPropertyStr(e.ctx,object,"GridNeighbors",valuesOwner.release())<0)e.fail(); }
if(JS_SetPropertyStr(e.ctx,root,"Topology",objectOwner.release())<0)e.fail(); }
}
}
