#!/bin/bash
#
# Installs all dependencies
#
# Usage: 
#
#   sudo ./install_deps
#

sudo apt install -qq libboost-all-dev mercurial scons libsdl1.2-dev libsdl-net1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev zlibc libspeex-dev libogg-dev libvorbis-dev libboost-thread-dev libboost-date-time-dev qt5-qmake qt5-default cppcheck valgrind sloccount
