#!/bin/bash
# 
# Builds and installs the CppUnit library
#
# Usage:
#
#   sudo ./globulation2/scripts/install_cppunit
#
#
git clone git://anongit.freedesktop.org/git/libreoffice/cppunit/
cd cppunit
./autogen.sh
./configure
make
make check # optional
sudo make install


