import os

Import("env")
Import("PackTar")

for file in os.listdir("."):
    if file.find(".sgsl") != -1:
        PackTar(env["TARFILE"], file)
        env.Install(env["INSTALLDIR"]+"/glob2/scripts", file)

env.Alias("install", env["INSTALLDIR"]+"/glob2/scripts")
PackTar(env["TARFILE"], "SConscript")
