import os
Import("env")
Import("PackTar")

if 'dist' or 'install' in COMMAND_LINE_TARGETS:
    for file in os.listdir("."):
        if file.find(".usl") != -1:
            PackTar(env["TARFILE"], file)
            env.Install(env["INSTALLDIR"]+"/glob2/data/usl/Language/Runtime", file)

    env.Alias("install", env["INSTALLDIR"]+"/glob2/data/usl/Language/Runtime")

    PackTar(env["TARFILE"], "SConscript")
