// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/gradient_depth_fit.py -- do not edit by hand.
//
// Predicted settle depth for a building walking field (see
// docs/building-gradient-depth-model.md). The depth only moves worker CPU:
// readers still resolve unsettled cells synchronously, so a different table
// never changes a simulation result and needs no SIM_REVISION bump.
//
// Fitted on 69 games, 322917 field lifetimes;
// keys previous, type, progress, per_size False.
// Operating points p80 (q 0.8), p90 (q 0.9), p95 (q 0.95); default p90.
// Default, held out by game: hit rate 0.9003, coverage 0.9226, extra CPU 1.8415, owner saving 0.9397.
#pragma once

#include <string_view>

namespace BuildingGradientDepth
{
/// The owner inputs a prediction may read, each O(1) at rebuild time.
struct Query
{
	int route = 0; // 0 footprint, 1 clearing, 2 combat
	int swim = 0;
	std::string_view type; // BuildingType::type
	int level = 0, site = 0;
	int construction = 0; // BuildingStateRecord::ConstructionResultState
	int progress = -1; // delivered/needed material quartile on sites, else -1
	int width = 0, height = 0; // map tiles
	int units = 0, buildings = 0; // the team's live counts
	int previous = -1; // the field's previous settled cost, -1 if none
};

enum class Key { Route, Swim, Type, Level, Site, Construction, Progress, Size, Units, Buildings, Previous };

/// floor(log2(value + 1)) for value >= 0, else -1.
constexpr int log2Bucket(int value)
{
	if (value < 0)
		return -1;
	int bucket = 0;
	for (unsigned v = unsigned(value) + 1; v > 1; v >>= 1)
		++bucket;
	return bucket;
}

constexpr int keyValue(Key key, const Query &q)
{
	switch (key)
	{
	case Key::Route: return q.route;
	case Key::Swim: return q.swim;
	case Key::Level: return q.level;
	case Key::Site: return q.site;
	case Key::Construction: return q.construction;
	case Key::Progress: return q.progress;
	case Key::Size: return q.width + q.height;
	case Key::Units: return log2Bucket(q.units);
	case Key::Buildings: return log2Bucket(q.buildings);
	case Key::Previous: return q.previous < 0 ? -1 : log2Bucket(q.previous / 80);
	default: return 0;
	}
}

inline constexpr int MIN_DEPTH = 32;
inline constexpr int MAX_DEPTH = 65535;
/// When true, a rule's value is Q8 cost per tile of (width + height).
inline constexpr bool PER_SIZE = false;
inline constexpr int PER_SIZE_SCALE = 256;
inline constexpr int KEY_COUNT = 3;
inline constexpr Key KEYS[3] = {Key::Previous, Key::Type, Key::Progress};

/// Operating points: the same cells at different quantiles of the depth
/// their lifetimes needed. A higher quantile moves more search off the owner
/// for more total CPU. Define GLOB2_BUILDING_GRADIENT_DEPTH_POINT to an index
/// to choose another point at build time.
inline constexpr int POINT_COUNT = 3;
inline constexpr std::string_view POINT_NAMES[POINT_COUNT] = {"p80", "p90", "p95"};
inline constexpr int POINT_QUANTILE_PERMILLE[POINT_COUNT] = {800, 900, 950};
inline constexpr int DEFAULT_POINT = 1; // p90
#ifdef GLOB2_BUILDING_GRADIENT_DEPTH_POINT
inline constexpr int ACTIVE_POINT = GLOB2_BUILDING_GRADIENT_DEPTH_POINT;
#else
inline constexpr int ACTIVE_POINT = DEFAULT_POINT;
#endif
static_assert(ACTIVE_POINT >= 0 && ACTIVE_POINT < POINT_COUNT);

/// Matches when the first `matched` selected keys equal `values` (and `type`
/// when Type is among them). Rules are most specific first; the last one
/// matches everything.
struct Rule
{
	int matched;
	int values[3];
	std::string_view type;
	int depth[POINT_COUNT];
};

inline constexpr Rule RULES[] = {
	{3, {-1, 0, -1}, "barracks", {304, 432, 560}},
	{3, {-1, 0, 0}, "barracks", {1936, 2112, 2848}},
	{3, {-1, 0, 1}, "barracks", {1904, 1968, 2784}},
	{3, {-1, 0, 2}, "barracks", {1904, 1936, 2880}},
	{3, {-1, 0, 3}, "barracks", {1888, 2016, 3776}},
	{3, {-1, 0, -1}, "clearingflag", {448, 608, 720}},
	{3, {-1, 0, -1}, "defencetower", {1872, 2048, 3904}},
	{3, {-1, 0, 0}, "defencetower", {1920, 2192, 2896}},
	{3, {-1, 0, 1}, "defencetower", {1888, 1984, 3872}},
	{3, {-1, 0, 2}, "defencetower", {1840, 2208, 2976}},
	{3, {-1, 0, 3}, "defencetower", {1488, 1904, 3264}},
	{3, {-1, 0, -1}, "hospital", {560, 848, 1248}},
	{3, {-1, 0, 0}, "hospital", {1936, 2032, 2800}},
	{3, {-1, 0, 1}, "hospital", {1888, 2064, 3632}},
	{3, {-1, 0, 2}, "hospital", {1136, 1936, 2592}},
	{3, {-1, 0, -1}, "inn", {1456, 1920, 2048}},
	{3, {-1, 0, 0}, "inn", {1936, 2064, 2800}},
	{3, {-1, 0, 1}, "inn", {1664, 1968, 2256}},
	{3, {-1, 0, 2}, "inn", {1216, 1920, 2160}},
	{3, {-1, 0, 3}, "inn", {1376, 1888, 2624}},
	{3, {-1, 0, -1}, "racetrack", {288, 480, 672}},
	{3, {-1, 0, 0}, "racetrack", {1872, 2192, 3040}},
	{3, {-1, 0, 1}, "racetrack", {1632, 2256, 3456}},
	{3, {-1, 0, 2}, "racetrack", {1664, 2640, 4048}},
	{3, {-1, 0, 3}, "racetrack", {1408, 1920, 2304}},
	{3, {-1, 0, -1}, "school", {400, 528, 624}},
	{3, {-1, 0, 0}, "school", {1952, 2304, 3248}},
	{3, {-1, 0, 1}, "school", {2000, 2640, 2752}},
	{3, {-1, 0, 2}, "school", {1904, 2560, 3168}},
	{3, {-1, 0, 3}, "school", {1040, 2512, 4000}},
	{3, {-1, 0, -1}, "swarm", {1936, 2496, 3120}},
	{3, {-1, 0, 0}, "swarm", {1904, 2160, 2736}},
	{3, {-1, 0, 1}, "swarm", {1920, 2176, 2880}},
	{3, {-1, 0, 2}, "swarm", {1920, 2416, 3040}},
	{3, {-1, 0, 3}, "swarm", {1984, 2240, 2656}},
	{3, {-1, 0, -1}, "swimmingpool", {288, 400, 560}},
	{3, {-1, 0, 0}, "swimmingpool", {1904, 2528, 3232}},
	{3, {-1, 0, 1}, "swimmingpool", {1888, 3360, 4160}},
	{3, {-1, 0, 2}, "swimmingpool", {1952, 4080, 4544}},
	{3, {-1, 0, 3}, "swimmingpool", {976, 1872, 2080}},
	{3, {-1, 0, -1}, "warflag", {768, 1008, 1200}},
	{3, {0, 0, -1}, "barracks", {288, 368, 400}},
	{3, {0, 0, 0}, "barracks", {1968, 2064, 4000}},
	{3, {0, 0, 1}, "barracks", {1888, 1936, 2480}},
	{3, {0, 0, 2}, "barracks", {1888, 1984, 2064}},
	{3, {0, 0, 3}, "barracks", {1904, 1968, 2208}},
	{3, {0, 0, -1}, "clearingflag", {48, 368, 512}},
	{3, {0, 0, -1}, "defencetower", {1904, 2032, 2352}},
	{3, {0, 0, -1}, "hospital", {448, 608, 720}},
	{3, {0, 0, 0}, "hospital", {1936, 2048, 2672}},
	{3, {0, 0, 1}, "hospital", {1920, 2000, 3008}},
	{3, {0, 0, 2}, "hospital", {1904, 2080, 2896}},
	{3, {0, 0, -1}, "inn", {1008, 1904, 1984}},
	{3, {0, 0, 0}, "inn", {2016, 3328, 4224}},
	{3, {0, 0, 1}, "inn", {1936, 2208, 3056}},
	{3, {0, 0, 2}, "inn", {1760, 1968, 2640}},
	{3, {0, 0, 3}, "inn", {2112, 2880, 3008}},
	{3, {0, 0, -1}, "racetrack", {240, 320, 480}},
	{3, {0, 0, 3}, "racetrack", {1120, 1824, 1984}},
	{3, {0, 0, -1}, "school", {336, 432, 544}},
	{3, {0, 0, 0}, "school", {1536, 1920, 2032}},
	{3, {0, 0, 2}, "school", {1872, 1968, 4656}},
	{3, {0, 0, 3}, "school", {1872, 2512, 5760}},
	{3, {0, 0, -1}, "swarm", {1936, 2128, 2960}},
	{3, {0, 0, 0}, "swarm", {1888, 1952, 3888}},
	{3, {0, 0, 2}, "swarm", {1888, 1936, 3936}},
	{3, {0, 0, -1}, "swimmingpool", {256, 320, 448}},
	{3, {0, 0, 3}, "swimmingpool", {1888, 1920, 3136}},
	{3, {0, 0, -1}, "warflag", {112, 224, 400}},
	{3, {1, 0, -1}, "barracks", {160, 176, 224}},
	{3, {1, 0, 0}, "barracks", {1840, 1920, 2080}},
	{3, {1, 0, 1}, "barracks", {1872, 2128, 2944}},
	{3, {1, 0, 2}, "barracks", {1344, 1888, 2016}},
	{3, {1, 0, 3}, "barracks", {224, 432, 1280}},
	{3, {1, 0, -1}, "clearingflag", {160, 208, 272}},
	{3, {1, 0, -1}, "defencetower", {1568, 2192, 2880}},
	{3, {1, 0, 0}, "defencetower", {1776, 2096, 2944}},
	{3, {1, 0, 1}, "defencetower", {1616, 2512, 3040}},
	{3, {1, 0, 2}, "defencetower", {1056, 1888, 2096}},
	{3, {1, 0, 3}, "defencetower", {400, 688, 2448}},
	{3, {1, 0, -1}, "hospital", {192, 288, 432}},
	{3, {1, 0, 0}, "hospital", {1008, 1920, 2000}},
	{3, {1, 0, 1}, "hospital", {1200, 1952, 2080}},
	{3, {1, 0, 2}, "hospital", {336, 1536, 1952}},
	{3, {1, 0, 3}, "hospital", {336, 1264, 2016}},
	{3, {1, 0, -1}, "inn", {368, 1328, 1920}},
	{3, {1, 0, 0}, "inn", {912, 1920, 2336}},
	{3, {1, 0, 1}, "inn", {960, 1920, 2352}},
	{3, {1, 0, 2}, "inn", {256, 672, 1760}},
	{3, {1, 0, 3}, "inn", {1344, 1584, 2880}},
	{3, {1, 0, -1}, "racetrack", {160, 208, 272}},
	{3, {1, 0, 0}, "racetrack", {1456, 2496, 3424}},
	{3, {1, 0, 1}, "racetrack", {1920, 2208, 2880}},
	{3, {1, 0, 2}, "racetrack", {1328, 1968, 3056}},
	{3, {1, 0, 3}, "racetrack", {256, 672, 1856}},
	{3, {1, 0, -1}, "school", {192, 240, 336}},
	{3, {1, 0, 0}, "school", {1888, 2112, 2976}},
	{3, {1, 0, 1}, "school", {1680, 1920, 2656}},
	{3, {1, 0, 2}, "school", {1472, 1936, 3424}},
	{3, {1, 0, 3}, "school", {288, 496, 1008}},
	{3, {1, 0, -1}, "swarm", {1872, 2048, 2736}},
	{3, {1, 0, 0}, "swarm", {1520, 1904, 2848}},
	{3, {1, 0, 1}, "swarm", {1504, 2016, 2864}},
	{3, {1, 0, 2}, "swarm", {1808, 2080, 2608}},
	{3, {1, 0, 3}, "swarm", {1248, 1904, 2176}},
	{3, {1, 0, -1}, "swimmingpool", {176, 208, 256}},
	{3, {1, 0, 0}, "swimmingpool", {1888, 1968, 2448}},
	{3, {1, 0, 1}, "swimmingpool", {1888, 1968, 2656}},
	{3, {1, 0, 2}, "swimmingpool", {1904, 2256, 2576}},
	{3, {1, 0, 3}, "swimmingpool", {304, 1408, 1920}},
	{3, {1, 0, -1}, "warflag", {176, 192, 288}},
	{3, {2, 0, -1}, "barracks", {368, 416, 464}},
	{3, {2, 0, 0}, "barracks", {1872, 1936, 2656}},
	{3, {2, 0, 1}, "barracks", {1776, 1920, 2112}},
	{3, {2, 0, 2}, "barracks", {1040, 1904, 1984}},
	{3, {2, 0, 3}, "barracks", {448, 688, 1920}},
	{3, {2, 0, -1}, "clearingflag", {384, 448, 480}},
	{3, {2, 0, -1}, "defencetower", {1008, 1888, 2736}},
	{3, {2, 0, 0}, "defencetower", {1600, 1968, 2784}},
	{3, {2, 0, 1}, "defencetower", {1744, 2512, 2768}},
	{3, {2, 0, 2}, "defencetower", {1008, 1872, 2640}},
	{3, {2, 0, 3}, "defencetower", {496, 1008, 1888}},
	{3, {2, 0, -1}, "hospital", {432, 496, 576}},
	{3, {2, 0, 0}, "hospital", {592, 1856, 1936}},
	{3, {2, 0, 1}, "hospital", {720, 1776, 2016}},
	{3, {2, 0, 2}, "hospital", {528, 1024, 1888}},
	{3, {2, 0, -1}, "inn", {560, 1312, 1920}},
	{3, {2, 0, 0}, "inn", {528, 1056, 1936}},
	{3, {2, 0, 1}, "inn", {560, 1504, 2016}},
	{3, {2, 0, 2}, "inn", {528, 656, 1520}},
	{3, {2, 0, 3}, "inn", {1376, 1440, 2800}},
	{3, {2, 0, -1}, "racetrack", {400, 448, 480}},
	{3, {2, 0, 0}, "racetrack", {1360, 1856, 2496}},
	{3, {2, 0, 1}, "racetrack", {1776, 2032, 2640}},
	{3, {2, 0, 2}, "racetrack", {1040, 1712, 2240}},
	{3, {2, 0, 3}, "racetrack", {608, 1328, 1744}},
	{3, {2, 0, -1}, "school", {432, 480, 512}},
	{3, {2, 0, 0}, "school", {1872, 1936, 2240}},
	{3, {2, 0, 1}, "school", {1872, 1984, 2176}},
	{3, {2, 0, 2}, "school", {800, 1888, 1968}},
	{3, {2, 0, 3}, "school", {496, 560, 816}},
	{3, {2, 0, -1}, "swarm", {1504, 1920, 2016}},
	{3, {2, 0, 0}, "swarm", {1584, 1968, 2384}},
	{3, {2, 0, 1}, "swarm", {1856, 1952, 2080}},
	{3, {2, 0, 2}, "swarm", {1888, 1968, 2192}},
	{3, {2, 0, 3}, "swarm", {1456, 1936, 2032}},
	{3, {2, 0, -1}, "swimmingpool", {384, 432, 480}},
	{3, {2, 0, 0}, "swimmingpool", {560, 1680, 1904}},
	{3, {2, 0, 1}, "swimmingpool", {1744, 2560, 3376}},
	{3, {2, 0, 2}, "swimmingpool", {1360, 1888, 2160}},
	{3, {2, 0, 3}, "swimmingpool", {448, 1312, 1904}},
	{3, {2, 0, -1}, "warflag", {432, 480, 496}},
	{3, {3, 0, -1}, "barracks", {880, 992, 1056}},
	{3, {3, 0, 0}, "barracks", {1072, 1152, 1216}},
	{3, {3, 0, 1}, "barracks", {1056, 1072, 1152}},
	{3, {3, 0, 2}, "barracks", {1056, 1088, 1168}},
	{3, {3, 0, 3}, "barracks", {944, 1056, 1152}},
	{3, {3, 0, -1}, "clearingflag", {688, 800, 992}},
	{3, {3, 0, -1}, "defencetower", {944, 992, 1104}},
	{3, {3, 0, 0}, "defencetower", {992, 1104, 1200}},
	{3, {3, 0, 1}, "defencetower", {1040, 1104, 1152}},
	{3, {3, 0, 2}, "defencetower", {992, 1152, 1248}},
	{3, {3, 0, 3}, "defencetower", {736, 976, 1056}},
	{3, {3, 0, -1}, "hospital", {832, 1024, 1120}},
	{3, {3, 0, 0}, "hospital", {1024, 1104, 1200}},
	{3, {3, 0, 1}, "hospital", {1008, 1088, 1200}},
	{3, {3, 0, 2}, "hospital", {992, 1088, 1232}},
	{3, {3, 0, -1}, "inn", {1040, 1200, 1888}},
	{3, {3, 0, 0}, "inn", {1056, 1104, 1200}},
	{3, {3, 0, 1}, "inn", {1040, 1088, 1216}},
	{3, {3, 0, 2}, "inn", {928, 1056, 1088}},
	{3, {3, 0, 3}, "inn", {1088, 1104, 1168}},
	{3, {3, 0, -1}, "racetrack", {896, 992, 1072}},
	{3, {3, 0, 0}, "racetrack", {1088, 1184, 1280}},
	{3, {3, 0, 1}, "racetrack", {1088, 1168, 1216}},
	{3, {3, 0, 2}, "racetrack", {1072, 1216, 1568}},
	{3, {3, 0, 3}, "racetrack", {976, 1136, 1184}},
	{3, {3, 0, -1}, "school", {688, 768, 880}},
	{3, {3, 0, 0}, "school", {1088, 1168, 1312}},
	{3, {3, 0, 1}, "school", {1088, 1168, 1328}},
	{3, {3, 0, 2}, "school", {1024, 1104, 1584}},
	{3, {3, 0, 3}, "school", {960, 1072, 1104}},
	{3, {3, 0, -1}, "swarm", {1072, 1136, 1328}},
	{3, {3, 0, 0}, "swarm", {1072, 1312, 1920}},
	{3, {3, 0, 1}, "swarm", {1072, 1328, 1920}},
	{3, {3, 0, 2}, "swarm", {1072, 1168, 1888}},
	{3, {3, 0, 3}, "swarm", {1072, 1168, 1904}},
	{3, {3, 0, -1}, "swimmingpool", {768, 896, 992}},
	{3, {3, 0, 0}, "swimmingpool", {1040, 1120, 1168}},
	{3, {3, 0, 1}, "swimmingpool", {992, 1024, 1120}},
	{3, {3, 0, 2}, "swimmingpool", {992, 1024, 1152}},
	{3, {3, 0, 3}, "swimmingpool", {1024, 1136, 1168}},
	{3, {3, 0, -1}, "warflag", {960, 1056, 1104}},
	{3, {4, 0, 0}, "barracks", {1936, 1984, 2064}},
	{3, {4, 0, 1}, "barracks", {1920, 1984, 2048}},
	{3, {4, 0, 2}, "barracks", {1888, 1936, 2000}},
	{3, {4, 0, 3}, "barracks", {1888, 1920, 1984}},
	{3, {4, 0, -1}, "defencetower", {1920, 2032, 2192}},
	{3, {4, 0, 0}, "defencetower", {1968, 2096, 2256}},
	{3, {4, 0, 1}, "defencetower", {1744, 1888, 1920}},
	{3, {4, 0, 2}, "defencetower", {1920, 1984, 2080}},
	{3, {4, 0, 3}, "defencetower", {1616, 1904, 1952}},
	{3, {4, 0, -1}, "hospital", {1664, 1808, 2000}},
	{3, {4, 0, 0}, "hospital", {1952, 2000, 2032}},
	{3, {4, 0, 1}, "hospital", {1936, 2000, 2064}},
	{3, {4, 0, 2}, "hospital", {1904, 1984, 2064}},
	{3, {4, 0, -1}, "inn", {1904, 1952, 2000}},
	{3, {4, 0, 0}, "inn", {1952, 2016, 2176}},
	{3, {4, 0, 1}, "inn", {1920, 1968, 2064}},
	{3, {4, 0, 2}, "inn", {1888, 1952, 2144}},
	{3, {4, 0, 3}, "inn", {1424, 1888, 2256}},
	{3, {4, 0, 0}, "racetrack", {1920, 1984, 2112}},
	{3, {4, 0, 1}, "racetrack", {1888, 2032, 2224}},
	{3, {4, 0, 2}, "racetrack", {1856, 2064, 2224}},
	{3, {4, 0, 3}, "racetrack", {1776, 1936, 2000}},
	{3, {4, 0, -1}, "school", {1696, 1744, 1792}},
	{3, {4, 0, 0}, "school", {1936, 2000, 2096}},
	{3, {4, 0, 1}, "school", {1936, 2016, 2096}},
	{3, {4, 0, 2}, "school", {1920, 1984, 2160}},
	{3, {4, 0, 3}, "school", {1888, 1984, 2416}},
	{3, {4, 0, -1}, "swarm", {1936, 1984, 2064}},
	{3, {4, 0, 0}, "swarm", {1936, 2032, 2176}},
	{3, {4, 0, 1}, "swarm", {1936, 2064, 2224}},
	{3, {4, 0, 2}, "swarm", {1936, 2080, 2320}},
	{3, {4, 0, 3}, "swarm", {1920, 2016, 2224}},
	{3, {4, 0, -1}, "swimmingpool", {1824, 2336, 2352}},
	{3, {4, 0, 0}, "swimmingpool", {1952, 2000, 2272}},
	{3, {4, 0, 1}, "swimmingpool", {1904, 2000, 2272}},
	{3, {4, 0, 2}, "swimmingpool", {1904, 1968, 2032}},
	{3, {4, 0, 3}, "swimmingpool", {1888, 1968, 1984}},
	{3, {4, 0, -1}, "warflag", {1968, 2224, 2416}},
	{3, {5, 0, 0}, "barracks", {3744, 4000, 4016}},
	{3, {5, 0, 1}, "barracks", {3696, 4416, 4704}},
	{3, {5, 0, 2}, "barracks", {3744, 4208, 4704}},
	{3, {5, 0, 3}, "barracks", {3584, 4000, 4032}},
	{3, {5, 0, -1}, "defencetower", {3264, 3856, 4592}},
	{3, {5, 0, 0}, "defencetower", {3024, 3504, 3584}},
	{3, {5, 0, 1}, "defencetower", {2976, 3504, 3792}},
	{3, {5, 0, 2}, "defencetower", {3504, 3776, 3888}},
	{3, {5, 0, 0}, "hospital", {3776, 4048, 4336}},
	{3, {5, 0, 1}, "hospital", {3568, 4064, 4272}},
	{3, {5, 0, 2}, "hospital", {3184, 3616, 4144}},
	{3, {5, 0, -1}, "inn", {3328, 3936, 4560}},
	{3, {5, 0, 0}, "inn", {3584, 4048, 4160}},
	{3, {5, 0, 1}, "inn", {3392, 3712, 3968}},
	{3, {5, 0, 2}, "inn", {3760, 3776, 4384}},
	{3, {5, 0, 3}, "inn", {2912, 3008, 4160}},
	{3, {5, 0, 0}, "racetrack", {3664, 4128, 4256}},
	{3, {5, 0, 1}, "racetrack", {3424, 3824, 4272}},
	{3, {5, 0, 2}, "racetrack", {3344, 4048, 4208}},
	{3, {5, 0, 0}, "school", {3552, 3904, 4240}},
	{3, {5, 0, 1}, "school", {3584, 3904, 4496}},
	{3, {5, 0, 2}, "school", {3568, 3904, 4208}},
	{3, {5, 0, 3}, "school", {3152, 4048, 4192}},
	{3, {5, 0, -1}, "swarm", {3328, 4048, 4672}},
	{3, {5, 0, 0}, "swarm", {3056, 3744, 3904}},
	{3, {5, 0, 1}, "swarm", {3168, 3776, 3888}},
	{3, {5, 0, 2}, "swarm", {3248, 3776, 4032}},
	{3, {5, 0, 3}, "swarm", {3168, 3536, 4016}},
	{3, {5, 0, 0}, "swimmingpool", {3280, 4128, 4416}},
	{3, {5, 0, 1}, "swimmingpool", {3376, 4160, 4208}},
	{3, {5, 0, 2}, "swimmingpool", {4144, 4208, 4560}},
	{3, {5, 0, 3}, "swimmingpool", {3104, 4208, 4336}},
	{3, {5, 0, -1}, "warflag", {3504, 3536, 3568}},
	{3, {6, 0, -1}, "defencetower", {6016, 6032, 6240}},
	{3, {6, 0, 0}, "defencetower", {5552, 6000, 6224}},
	{3, {6, 0, -1}, "inn", {6224, 7344, 7856}},
	{3, {6, 0, 0}, "inn", {5568, 6128, 7216}},
	{3, {6, 0, 1}, "inn", {6544, 6624, 7472}},
	{3, {6, 0, 2}, "inn", {5936, 6576, 7504}},
	{3, {6, 0, 0}, "school", {6224, 6384, 6400}},
	{3, {6, 0, 3}, "school", {5472, 6240, 6272}},
	{3, {6, 0, -1}, "swarm", {6224, 7248, 7920}},
	{3, {6, 0, 0}, "swarm", {6176, 6176, 7968}},
	{3, {6, 0, 1}, "swarm", {6240, 6272, 6288}},
	{3, {6, 0, 2}, "swarm", {6176, 6288, 6320}},
	{2, {-1, 0, 0}, "barracks", {1856, 1920, 2048}},
	{2, {-1, 0, 0}, "clearingflag", {448, 608, 720}},
	{2, {-1, 0, 0}, "defencetower", {1904, 2096, 3760}},
	{2, {-1, 0, 0}, "hospital", {896, 1872, 1968}},
	{2, {-1, 0, 0}, "inn", {1632, 1936, 2208}},
	{2, {-1, 0, 0}, "racetrack", {1136, 1664, 2224}},
	{2, {-1, 0, 0}, "school", {1456, 1952, 2656}},
	{2, {-1, 0, 0}, "swarm", {1936, 2448, 3024}},
	{2, {-1, 0, 0}, "swimmingpool", {704, 1360, 1952}},
	{2, {-1, 0, 0}, "warflag", {768, 1008, 1200}},
	{2, {0, 0, 0}, "barracks", {1056, 1888, 1968}},
	{2, {0, 0, 0}, "clearingflag", {48, 368, 512}},
	{2, {0, 0, 0}, "defencetower", {1904, 2192, 2880}},
	{2, {0, 0, 0}, "hospital", {608, 1856, 1968}},
	{2, {0, 0, 0}, "inn", {1280, 1920, 2208}},
	{2, {0, 0, 0}, "racetrack", {336, 1120, 1904}},
	{2, {0, 0, 0}, "school", {624, 1568, 1968}},
	{2, {0, 0, 0}, "swarm", {1936, 2112, 2960}},
	{2, {0, 0, 0}, "swimmingpool", {304, 688, 1888}},
	{2, {0, 0, 0}, "warflag", {112, 224, 400}},
	{2, {1, 0, 0}, "barracks", {192, 432, 1856}},
	{2, {1, 0, 0}, "clearingflag", {160, 208, 272}},
	{2, {1, 0, 0}, "defencetower", {1488, 2080, 2880}},
	{2, {1, 0, 0}, "hospital", {240, 464, 1344}},
	{2, {1, 0, 0}, "inn", {384, 1392, 1936}},
	{2, {1, 0, 0}, "racetrack", {208, 512, 1488}},
	{2, {1, 0, 0}, "school", {256, 592, 1744}},
	{2, {1, 0, 0}, "swarm", {1872, 2032, 2736}},
	{2, {1, 0, 0}, "swimmingpool", {192, 256, 480}},
	{2, {1, 0, 0}, "warflag", {176, 192, 288}},
	{2, {2, 0, 0}, "barracks", {464, 1024, 1904}},
	{2, {2, 0, 0}, "clearingflag", {384, 448, 480}},
	{2, {2, 0, 0}, "defencetower", {1184, 1904, 2768}},
	{2, {2, 0, 0}, "hospital", {464, 560, 976}},
	{2, {2, 0, 0}, "inn", {560, 1296, 1920}},
	{2, {2, 0, 0}, "racetrack", {480, 976, 1696}},
	{2, {2, 0, 0}, "school", {496, 608, 1568}},
	{2, {2, 0, 0}, "swarm", {1536, 1920, 2048}},
	{2, {2, 0, 0}, "swimmingpool", {400, 480, 640}},
	{2, {2, 0, 0}, "warflag", {432, 480, 496}},
	{2, {3, 0, 0}, "barracks", {1056, 1104, 1168}},
	{2, {3, 0, 0}, "clearingflag", {688, 800, 992}},
	{2, {3, 0, 0}, "defencetower", {976, 1040, 1168}},
	{2, {3, 0, 0}, "hospital", {976, 1072, 1184}},
	{2, {3, 0, 0}, "inn", {1040, 1184, 1888}},
	{2, {3, 0, 0}, "racetrack", {1056, 1136, 1232}},
	{2, {3, 0, 0}, "school", {1024, 1104, 1184}},
	{2, {3, 0, 0}, "swarm", {1072, 1152, 1680}},
	{2, {3, 0, 0}, "swimmingpool", {992, 1056, 1136}},
	{2, {3, 0, 0}, "warflag", {960, 1056, 1104}},
	{2, {4, 0, 0}, "barracks", {1920, 1968, 2032}},
	{2, {4, 0, 0}, "defencetower", {1920, 2000, 2192}},
	{2, {4, 0, 0}, "hospital", {1920, 1984, 2032}},
	{2, {4, 0, 0}, "inn", {1904, 1952, 2016}},
	{2, {4, 0, 0}, "racetrack", {1888, 2000, 2160}},
	{2, {4, 0, 0}, "school", {1920, 2000, 2112}},
	{2, {4, 0, 0}, "swarm", {1936, 1984, 2096}},
	{2, {4, 0, 0}, "swimmingpool", {1904, 1984, 2272}},
	{2, {4, 0, 0}, "warflag", {1968, 2224, 2416}},
	{2, {5, 0, 0}, "barracks", {3744, 4096, 4384}},
	{2, {5, 0, 0}, "defencetower", {3424, 3776, 3936}},
	{2, {5, 0, 0}, "hospital", {3520, 4000, 4176}},
	{2, {5, 0, 0}, "inn", {3488, 3904, 4416}},
	{2, {5, 0, 0}, "racetrack", {3424, 4000, 4256}},
	{2, {5, 0, 0}, "school", {3536, 3920, 4208}},
	{2, {5, 0, 0}, "swarm", {3296, 3952, 4640}},
	{2, {5, 0, 0}, "swimmingpool", {3472, 4160, 4336}},
	{2, {5, 0, 0}, "warflag", {3504, 3536, 3568}},
	{2, {6, 0, 0}, "barracks", {5952, 6208, 6224}},
	{2, {6, 0, 0}, "defencetower", {6016, 6032, 6240}},
	{2, {6, 0, 0}, "inn", {6224, 7168, 7840}},
	{2, {6, 0, 0}, "racetrack", {5856, 6000, 6000}},
	{2, {6, 0, 0}, "school", {6000, 6240, 6400}},
	{2, {6, 0, 0}, "swarm", {6208, 6336, 7904}},
	{1, {-1, 0, 0}, "", {1472, 1936, 2256}},
	{1, {0, 0, 0}, "", {1632, 1920, 2112}},
	{1, {1, 0, 0}, "", {352, 1392, 1936}},
	{1, {2, 0, 0}, "", {544, 1344, 1920}},
	{1, {3, 0, 0}, "", {1040, 1136, 1568}},
	{1, {4, 0, 0}, "", {1920, 1984, 2064}},
	{1, {5, 0, 0}, "", {3456, 3952, 4352}},
	{1, {6, 0, 0}, "", {6192, 6320, 7728}},
	{0, {0, 0, 0}, "", {1680, 1936, 2448}},
};

constexpr bool matches(const Rule &rule, const Query &q)
{
	for (int i = 0; i < rule.matched; ++i)
	{
		if (KEYS[i] == Key::Type ? rule.type != q.type : rule.values[i] != keyValue(KEYS[i], q))
			return false;
	}
	return true;
}

/// The cost to settle up front. Never affects results, only who pays.
constexpr int target(const Query &q, int point = ACTIVE_POINT)
{
	for (const Rule &rule : RULES)
		if (matches(rule, q))
		{
			long long depth = rule.depth[point];
			if (PER_SIZE)
				depth = depth * (q.width + q.height) / PER_SIZE_SCALE;
			return int(depth < MIN_DEPTH ? MIN_DEPTH : depth > MAX_DEPTH ? MAX_DEPTH : depth);
		}
	return MAX_DEPTH;
}
} // namespace BuildingGradientDepth
