// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/gradient_depth_fit.py -- do not edit by hand.
//
// Predicted settle depth for a scheduled building walking field (see
// docs/ai/architecture/building-gradient-depth-model.md), from the field's own past depths.
// The depth only moves worker CPU: readers still resolve unsettled cells
// synchronously, so a different depth never changes a simulation result
// and needs no SIM_REVISION bump.
//
// Fitted on 1472 games, 3408777 scheduled field lifetimes.
// Default l0100 (lambda 0.1).
// Default, held out by game: hit rate 0.9686, coverage 0.9702, extra CPU 1.3641, owner saving 0.9415.
#pragma once

#include <string_view>

namespace BuildingGradientDepth
{
inline constexpr int MIN_DEPTH = 32;
inline constexpr int MAX_DEPTH = 65535;

/// One operating point: depth = offset + (slope256 * m) >> 8 for m, the
/// deeper of the two past depths. A lower lambda moves more search off the
/// owner for more worker CPU.
struct Point
{
	std::string_view name;
	int offset, slope256;
};

inline constexpr Point POINTS[] = {
	{"l0100", 166, 292},
	{"l0200", 88, 268},
	{"l0300", 56, 266},
	{"l0500", 38, 257},
};
inline constexpr int POINT_COUNT = 4;
inline constexpr int DEFAULT_POINT = 0; // l0100

/// The cost to settle up front from reader demand on the serving field
/// `serving` and its last replaced lifetime `previous` (each -1 if
/// unknown). Without either, as after loading a save, minimum depth lets the
/// readers decide. Never affects results, only who pays.
constexpr int target(int serving, int previous, int point = DEFAULT_POINT)
{
	const Point &p = POINTS[point];
	const int m = serving > previous ? serving : previous;
	if (m < 0)
		return MIN_DEPTH;
	const long long d = p.offset + ((long long)p.slope256 * m >> 8);
	return int(d < MIN_DEPTH ? MIN_DEPTH : d > MAX_DEPTH ? MAX_DEPTH : d);
}

/// The index of the point named `name`, or -1.
constexpr int pointIndex(std::string_view name)
{
	for (int i = 0; i < POINT_COUNT; ++i)
		if (POINTS[i].name == name)
			return i;
	return -1;
}
} // namespace BuildingGradientDepth
