Import("env")
Import("PackTar")

if 'dist' or 'install' in COMMAND_LINE_TARGETS:
    PackTar(env["TARFILE"], "strnatcmp.c")
    PackTar(env["TARFILE"], "strnatcmp.h")

    PackTar(env["TARFILE"], "SConscript")
