import os

Import("env")
Import("PackTar")

for file in os.listdir("."):
    if file.find(".png") != -1:
        PackTar(env["TARFILE"], file)
        env.Install(env["INSTALLDIR"]+"/glob2/data/icons", file)

env.Alias("install", env["INSTALLDIR"]+"/glob2/data/icons")
PackTar(env["TARFILE"], "SConscript")
