import os
    
Import("env")
Import("PackTar")
    
if 'dist' or 'install' in COMMAND_LINE_TARGETS:
    for file in os.listdir("."):
        if file.find(".png") != -1:
            PackTar(env["TARFILE"], file)
    
    PackTar(env["TARFILE"], "SConscript")
    env.InstallAs(env["INSTALLDIR"]+"/icons/hicolor/16x16/apps/glob2.png", "glob2-icon-16x16.png")
    env.Alias("install", env["INSTALLDIR"]+"/icons/hicolor/16x16/apps/")
    env.InstallAs(env["INSTALLDIR"]+"/icons/hicolor/24x24/apps/glob2.png", "glob2-icon-24x24.png")
    env.Alias("install", env["INSTALLDIR"]+"/icons/hicolor/24x24/apps/")
    env.InstallAs(env["INSTALLDIR"]+"/icons/hicolor/32x32/apps/glob2.png", "glob2-icon-32x32.png")
    env.Alias("install", env["INSTALLDIR"]+"/icons/hicolor/32x32/apps/")
    env.InstallAs(env["INSTALLDIR"]+"/icons/hicolor/48x48/apps/glob2.png", "glob2-icon-48x48.png")
    env.Alias("install", env["INSTALLDIR"]+"/icons/hicolor/48x48/apps/")
    env.InstallAs(env["INSTALLDIR"]+"/icons/hicolor/64x64/apps/glob2.png", "glob2-icon-64x64.png")
    env.Alias("install", env["INSTALLDIR"]+"/icons/hicolor/64x64/apps/")
    env.InstallAs(env["INSTALLDIR"]+"/icons/hicolor/128x128/apps/glob2.png", "glob2-icon-128x128.png")
    env.Alias("install", env["INSTALLDIR"]+"/icons/hicolor/128x128/apps/")
