import os

Import("env")

for file in os.listdir("."):
    if file.find(".png") != -1:
        env.Tar(env["TARFILE"], file)
        env.Install(env["INSTALLDIR"]+"/glob2/data/icons", file)

env.Alias("install", env["INSTALLDIR"]+"/glob2/data/icons")
env.Tar(env["TARFILE"], "SConscript")
