#pragma once
// Generated by SCons.

// Name of package
#define PACKAGE "glob2"

// Define to the address where bug reports for this package should be sent.
#define PACKAGE_BUGREPORT "glob2-devel@nongnu.org"

// data directory
#define PACKAGE_DATA_DIR "/usr/local/share"

// source directory
#define PACKAGE_SOURCE_DIR "/home/bradley/Documents/Codex/2026-10-10/can-you-look-at-pr-1045/work/evidence"

// generated WebP artwork for source builds
#define PACKAGE_RUNTIME_ASSET_DIR "/home/bradley/Documents/Codex/2026-10-10/can-you-look-at-pr-1045/work/evidence/build/linux/client/release/runtime-assets"

// Define to the full name of this package.
#define PACKAGE_NAME "Globulation 2"

// Define to the one symbol short name of this package.
#define PACKAGE_TARNAME "glob2"

// Define to the version of this package.
#define PACKAGE_VERSION "0.11.0.0"

// Set the audio input type to OSS; the UNIX Open Sound System
#define AUDIO_RECORDER_OSS 

// This is the primary font Globulation 2 will use
#define PRIMARY_FONT "sans.ttf"

// Defined when native secure WebSocket support is compiled
#define GLOB2_NATIVE_WSS 

// Defined when OpenGL support is present and compiled
#define HAVE_OPENGL  

// Defined when FRIBIDI support is present and compiled
#define HAVE_FRIBIDI  

