from pathlib import Path
import json,xml.etree.ElementTree as ET,hashlib
root=Path(__file__).resolve().parents[2];out=root/'artifacts/memory-optimization'
read=lambda p:json.loads(p.read_text())
cpu=read(out/'cpu-final/comparison.json')['fixtures'][:2]+read(out/'cpu-interleaved/comparison.json')['fixtures']
complete=all(f['passed'] and len(f['pairs'])>=7 for f in cpu) and len(cpu)==4 and read(out/'cpu-interleaved/comparison.json').get('passed',False)
checks=read(out/'checksum-v2-comparison.json');memory=read(out/'memory-comparison.json');peak=read(out/'peak-memory.json')
tests={}
for name in ('unit','maxima','save','stats','archive','engine'):
 f=out/f'{name}-junit.xml'
 if f.exists():tests[name]=ET.parse(f).getroot().attrib
manifest={'base_revision':'a231b3ed4562a4ba5293acfd41de804c20d06702','worktree':str(root),'cpu_gate_complete':complete,'cpu_fixtures':cpu,'live_memory':memory,'peak_memory':peak,'determinism':{k:v for k,v in checks.items() if k!='segments'},'save_and_replay':read(out/'save-v2-comparison.json'),'farming_kernels':read(out/'kernel-comparison.json'),'distance_kernel':read(out/'distance-comparison.json'),'tests':tests,'platforms_verified':['macOS arm64'],'platforms_unverified':['Linux','Windows'],'limitations':['Later CPU fixtures use two resident processes alternating 100ms time slices; sequential populated measurements were inconclusive under changing background builds/tests.','Peak RSS is a single sequential load/one-tick/save pair.','Interactive maintainer playtesting was not performed.','Level-zero gzip retains legacy whole-buffer output for byte identity.']}
(out/'validation.json').write_text(json.dumps(manifest,indent=2))
lines=['# Memory optimization validation','','Implemented compact Maxima fields and farming buffers, shared immutable geometry/water caches, compact growth counters, and reduced transient save/load copies. Legacy wire formats and engine version gates remain unchanged.','','## Live allocations','','| Capture tick | Baseline MiB | Candidate MiB | Saved MiB |','| --- | ---: | ---: | ---: |']
for r in memory:lines.append(f"| {r['candidate_capture']['observed_tick_lower_bound']} | {r['baseline_live_bytes']/1048576:.2f} | {r['candidate_live_bytes']/1048576:.2f} | {r['saved_bytes']/1048576:.2f} |")
lines+=['',f"Late load/save peak RSS: {peak['baseline']['maximum_resident_bytes']/2**30:.2f} GiB → {peak['candidate']['maximum_resident_bytes']/2**30:.2f} GiB (one sequential pair).",'','## CPU comparison','','Negative percentages mean less process CPU. The one-sided 95% paired-bootstrap upper bound must be at most +2%. Early/middle fixtures used sequential alternating pairs; populated fixtures used 100ms within-pair interleaving after sequential timings proved noisy. Both interleaved processes stay resident.','','| Initial tick | Pairs | Load change / upper bound | Simulation change / upper bound | Save change / upper bound |','| --- | ---: | ---: | ---: | ---: |']
for f in cpu:
 vals=[f"{f['cpu'][k]['paired_change_percent']:+.2f}% / {f['cpu'][k]['upper_95_percent']:+.2f}%" for k in ('benchmark_setup_cpu_ns','benchmark_run_cpu_ns','benchmark_save_cpu_ns')];lines.append(f"| {f['initial_tick']} | {len(f['pairs'])} | {' | '.join(vals)} |")
lines+=['',f"CPU gate complete: **{complete}**.",'','## Compatibility and verification','',f"The uninterrupted 512×512, 11-AI, map-seed-42/game-seed-19 comparison matched all {checks['bytes']:,} detailed simulation bytes through 45,000 ticks. Checkpoint saves, final save and replay bytes matched exactly. All resumed benchmark pairs also check final simulation checksums and compressed save hashes.",'','The full unit run contains 393 passing cases. Relevant Maxima suites (142 cases), gzip/stream, compact counter, gradient lifecycle and continuation checks passed. Client and server release builds succeeded. Isolated farming and distance-field kernels passed the CPU gate with identical output hashes. See the JUnit files and raw logs in this directory.','','## Review limits','','Only native macOS arm64 execution was verified; Linux/Windows replay equivalence and interactive maintainer playtesting remain unverified. The shared-machine timing conditions do not establish a portable speedup. Level-zero gzip deliberately keeps legacy buffering because changing zlib output capacity changes its stored-block bytes.','','Exact commands, binary/fixture hashes, raw timings, per-pair output hashes, allocation captures and category totals are retained under this ignored artifact directory. `validation.json` collects the results; the sequential timing limitations are retained under `cpu-final/` and `cpu-populated/`.']
(out/'review.md').write_text('\n'.join(lines)+'\n');print('CPU gate complete:',complete)
