#!/usr/bin/env python3
"""Generate/check CLI reference, man page and shell completions from a real binary."""

import argparse
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
START = "<!-- BEGIN GENERATED CLI REFERENCE -->"
END = "<!-- END GENERATED CLI REFERENCE -->"


def invoke(binary, *args):
    return subprocess.check_output([str(binary), *args], text=True, timeout=30)


def syntax(command):
    positionals = [
        name if index < command["minimum_positionals"] else f"[{name}]"
        for index, name in enumerate(command["positionals"])
    ]
    return " ".join(["glob2", command["path"], *positionals, "[OPTIONS]"])


def reference(schema):
    blocks = []
    for command in schema["commands"]:
        blocks += [
            f"### `glob2 {command['path']}`",
            "",
            command["description"] + ".",
            "",
            "```text",
            syntax(command),
            "```",
            "",
            "Outputs: " + command["outputs"] + ".",
            "",
            "Platform: " + command["platform"] + ".",
            "",
            "| Option | Value / default | Meaning |",
            "| --- | --- | --- |",
        ]
        for option in command["options"]:
            detail = ", ".join(option["choices"]) or option["type"]
            if option["default"]:
                detail += "; default " + option["default"]
            if option.get("units"):
                detail += "; " + option["units"]
            if option["type"] in ("integer", "real"):
                detail += f"; {option['minimum']}..{option['maximum']}"
            qualifiers = (" Required." if option["required"] else "") + (
                " Repeatable." if option["repeatable"] else ""
            )
            blocks.append(
                f"| `{option['name']}` | {detail} | {option['description']}.{qualifiers} |"
            )
        blocks.append("")
        for constraint in command["constraints"]:
            blocks += [constraint + ".", ""]
        for keys in command.get("conflicts", []):
            blocks += [
                "Choose at most one: "
                + ", ".join("`" + key + "`" for key in keys)
                + ".",
                "",
            ]
        for key, parents in command.get("requirements", {}).items():
            blocks += [
                "`"
                + key
                + "` requires "
                + " or ".join("`" + parent + "`" for parent in parents)
                + ".",
                "",
            ]
        if command["environment"]:
            blocks += [
                "Applicable environment variables: "
                + ", ".join("`" + key + "`" for key in command["environment"])
                + ".",
                "",
            ]
        blocks += ["```sh", *command["examples"], "```", ""]
    return "\n".join(blocks).rstrip() + "\n"


def man(schema):
    def escape(text):
        return text.replace("\\", r"\e").replace("-", r"\-").replace("\n", " ")

    rows = [
        '.\\" Generated by tools/cli_reference.py; edit the registry and CLI guide.',
        ".TH GLOB2 6",
        ".SH NAME",
        "glob2 \\- Globulation 2 game and tools",
        ".SH SYNOPSIS",
        ".B glob2",
        "[COMMAND] [OPTIONS]",
        ".SH DESCRIPTION",
        "Without arguments, launches the game. Use glob2 help COMMAND for detailed help.",
        "Use glob2 help --format json for the self-describing CLI schema.",
        ".SH COMMANDS",
    ]
    for command in schema["commands"]:
        rows += [
            '.SS "' + escape(command["path"]) + '"',
            escape(command["description"]),
            ".PP",
            escape("Usage: " + syntax(command)),
        ]
        for option in command["options"]:
            rows += [
                ".TP",
                ".B " + escape(option["name"]),
                escape(option["description"])
                + (
                    escape(" Default: " + option["default"] + ".")
                    if option["default"]
                    else ""
                )
                + (
                    escape(" Allowed: " + ", ".join(option["choices"]) + ".")
                    if option["choices"]
                    else ""
                )
                + (
                    escape(" Type: " + option["type"] + ".")
                    if option["type"] != "flag"
                    else ""
                )
                + (
                    escape(" Units: " + option["units"] + ".")
                    if option.get("units")
                    else ""
                )
                + (
                    escape(f" Range: {option['minimum']}..{option['maximum']}.")
                    if option["type"] in ("integer", "real")
                    else ""
                )
                + (" Required." if option["required"] else "")
                + (" Repeatable." if option["repeatable"] else ""),
            ]
        for constraint in command["constraints"]:
            rows += [".PP", escape(constraint)]
        for keys in command.get("conflicts", []):
            rows += [".PP", escape("Choose at most one: " + ", ".join(keys))]
        for key, parents in command.get("requirements", {}).items():
            rows += [".PP", escape(key + " requires " + " or ".join(parents))]
        if command["environment"]:
            rows += [".PP", escape("Environment: " + ", ".join(command["environment"]))]
        for example in command["examples"]:
            rows += [".PP", ".nf", escape(example), ".fi"]
        rows += [
            ".PP",
            escape("Outputs: " + command["outputs"]),
            ".PP",
            escape("Platform: " + command["platform"]),
        ]
    rows += [
        ".SH EXIT STATUS",
        "0 success or help; 2 invalid arguments or rejected input; 3 operational failure.",
        ".SH SEE ALSO",
        "The project CLI guide: docs/tools/cli.md. Shell completion: glob2 completion bash, zsh or fish.",
    ]
    return "\n".join(rows) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    binary = args.binary.resolve()
    schema = json.loads(invoke(binary, "help", "--format", "json"))
    if schema["schema_version"] != 1 or schema["cli_version"] != 2:
        parser.error("requires CLI 2 and description schema 1")
    guide = ROOT / "docs/tools/cli.md"
    original = guide.read_text()
    before, remainder = original.split(START, 1)
    _, after = remainder.split(END, 1)
    rendered = before + START + "\n\n" + reference(schema) + "\n" + END + after
    migration_start, migration_end = (
        "<!-- BEGIN GENERATED CLI MIGRATION -->",
        "<!-- END GENERATED CLI MIGRATION -->",
    )
    left, rest = rendered.split(migration_start, 1)
    _, right = rest.split(migration_end, 1)
    migration = "| Previous spelling | CLI 2 replacement |\n| --- | --- |\n" + "".join(
        f"| `{old}` | `{new}` |\n"
        for old, new in sorted(schema["removed_arguments"].items())
    )
    rendered = (
        left + migration_start + "\n\n" + migration + "\n" + migration_end + right
    )
    outputs = {guide: rendered, ROOT / "debian/glob2.6": man(schema)}
    for shell, name in [
        ("bash", "glob2.bash"),
        ("zsh", "_glob2"),
        ("fish", "glob2.fish"),
    ]:
        outputs[ROOT / "data/completions" / name] = invoke(binary, "completion", shell)
    mismatches = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                mismatches.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if mismatches:
        print("CLI reference drift: " + ", ".join(mismatches), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
