import os

if "mksprite" in COMMAND_LINE_TARGETS:
    env = Environment()
    env.ParseConfig("Magick++-config --cxxflags --cppflags")
    env.ParseConfig("Magick++-config --ldflags --libs")
    env.Program("mksprite", "mksprite.cpp")
