import { chromium } from '../../platform/node_modules/playwright/index.mjs';
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1280,height:860}});
const errors=[];page.on('pageerror',e=>errors.push(String(e)));
await page.route('**/rig-smoke', route=>route.fulfill({contentType:'text/html',body:`<html><head><script type="module">import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;</script></head><body></body></html>`}));
await page.goto('http://127.0.0.1:4297/rig-smoke');
const result=await page.evaluate(async()=>{
 const React=(await import('/node_modules/.vite/deps/react.js')).default;
 const {createRoot}=(await import('/node_modules/.vite/deps/react-dom_client.js')).default;
 const {MeshPreview}=await import('/src/skins/MeshPreview.tsx');
 const {DEFAULT_CAMERA}=await import('/src/skins/geometry.ts');
 const {MODELS}=await import('/src/skins/atlas.ts');
 const texture=document.createElement('canvas');texture.width=texture.height=512;
 const ctx=texture.getContext('2d');ctx.fillStyle='#e6aa66';ctx.fillRect(0,0,512,512);
 const materials=new Uint8Array(512*512).fill(1);
 document.body.innerHTML='<style>.skin-viewport{width:640px;height:640px}canvas{width:100%;height:100%}</style><main id="rig-test" style="width:640px;height:640px"></main>';
 let displayed,brush=false;
 const root=createRoot(document.getElementById('rig-test'));
 const props={texture,materials,revision:0,model:MODELS[0],swarmMesh:'classic',camera:{...DEFAULT_CAMERA,game:false},action:'walk',phase:8,animate:false,active:true,interactive:true,tool:'brush',size:24,hardness:.8,label:'Worker rig test',onScene:s=>{displayed=s;},onCoverage:coverage=>{brush=coverage.some(v=>v>0);}};
 root.render(React.createElement(MeshPreview,props));
 await new Promise((resolve,reject)=>{const started=performance.now();const timer=setInterval(()=>{if(displayed){clearInterval(timer);resolve();}else if(performance.now()-started>20000){clearInterval(timer);reject(new Error('No rig scene'));}},50);});
 if(!displayed.mesh.rig)throw new Error('Baked fallback was used');
 const projection=displayed.projection();
 const visible=projection.visible.findIndex(v=>v>0);if(visible<0)throw new Error('No brush-visible surface');
 window.rigBrushPoint={x:projection.x[visible],y:projection.y[visible]};
 window.rigTestState=()=>({brush,rig:!!displayed.mesh.rig,frame:displayed.frame});
 window.rigAnimate=()=>root.render(React.createElement(MeshPreview,{...props,animate:true}));
 return {frame:displayed.frame,restFloats:displayed.mesh.poses.length,visibleTexels:projection.visible.reduce((a,b)=>a+b,0)};
}).catch(async e=>{console.log(await page.locator('body').innerText());console.log(errors);throw e;});
const canvas=page.getByLabel('Worker rig test');
const bounds=await canvas.boundingBox();const point=await page.evaluate(()=>window.rigBrushPoint);
await page.mouse.move(bounds.x+point.x,bounds.y+point.y);await page.mouse.down();await page.mouse.up();
console.log(JSON.stringify({...result,...await page.evaluate(()=>window.rigTestState())}));
await page.screenshot({path:'artifacts/rig/studio-worker.png'});
await page.evaluate(()=>window.rigAnimate());
await page.waitForFunction(()=>window.rigTestState().frame!==8);
console.log(JSON.stringify({animated:true,...await page.evaluate(()=>window.rigTestState()),errors}));
await page.evaluate(() => {
 const canvas=document.querySelector('canvas');
 const gl=canvas.getContext('webgl2');
 const extension=gl.getExtension('WEBGL_lose_context');
 if(!extension)throw new Error('No context-loss extension');
 window.restoreRigContext=()=>extension.restoreContext();
 extension.loseContext();
});
await page.getByText('The 3D canvas was interrupted. Your painting is safe.').waitFor();
await page.evaluate(()=>window.restoreRigContext());
await page.getByText('The 3D canvas was interrupted. Your painting is safe.').waitFor({state:'hidden'});
await page.waitForFunction(()=>{
 const c=document.querySelector('canvas'),g=c.getContext('webgl2');
 if(g.isContextLost())return false;
 const data=new Uint8Array(c.width*c.height*4);g.readPixels(0,0,c.width,c.height,g.RGBA,g.UNSIGNED_BYTE,data);
 return data.some((v,i)=>i%4===3&&v>0);
});
console.log(JSON.stringify({contextRestored:true,...await page.evaluate(()=>window.rigTestState()),errors}));
await browser.close();
