// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2001-2004 Stephane Magnenat & Luc-Olivier de Charrière

#ifndef __GUIMAPPREVIEW_H
#define __GUIMAPPREVIEW_H

#include <GUIBase.h>
#include "MapGenerationDescriptor.h"
#include <string>
#include "MapThumbnail.h"

namespace GAGCore
{
	class DrawableSurface;
}

using namespace GAGGUI;
using namespace GAGCore;

//! Widget to preview map
/*!
	This widget is used to preview map.
	Each time setMapThmubnail is called a map htumbnail is loaded.
	A map thumbnail is a little image generated by the map editor.
*/
class MapPreview: public RectangularWidget
{
public:
	//! Constructor, takes position, alignement and initial map name
	MapPreview(int x, int y, Uint32 hAlign, Uint32 vAlign);
	//! Constructor, takes position, alignement, initial map name and a tooltip
	MapPreview(int x, int y, Uint32 hAlign, Uint32 vAlign, const std::string &tooltip, const std::string &tooltipFont);
	//! Destructor
	virtual ~MapPreview();
	virtual void paint(void);
	//! Reload thumbnail for a new map
	virtual void setMapThumbnail(const std::string& mapName);
	//! Load from a given thumbnail
	virtual void setMapThumbnail(const MapThumbnail &thumbnail);
	//! Returns last map width
	int getLastWidth(void) { return thumbnail.getMapWidth(); }
	//! Returns last map height
	int getLastHeight(void) { return thumbnail.getMapHeight(); }
	std::string getMethode(void);
	//! Returns true if the thumbnail is laoded, false otherwise
	bool isThumbnailLoaded();
	
protected:
	MapThumbnail thumbnail;
	DrawableSurface* surface;
};

#endif
