/*
 * Globulation 2 header
 * (c) 2001 Stephane Magnenat, Luc-Olivier de Charriere, Ysagoon
 */

#ifndef __NET_CONSTS_H
#define __NET_CONSTS_H

#define SERVER_PORT 7007
#define ANY_PORT 0

// 1s-3.5s-7s-14s
#define SECOND_TIMEOUT 20
#define SHORT_NETWORK_TIMEOUT 70
#define DEFAULT_NETWORK_TIMEOUT 140
#define LONG_NETWORK_TIMEOUT 280

#define DEFAULT_NETWORK_TOTL 3

enum OrderTypes
{
	BAD_ORDER=0,
	
	DATA_SESSION_GAME=11,
	DATA_SESSION_INFO=12,
	
	DATA_BASE_PLAYER=13,
	DATA_BASE_TEAM=14,
	DATA_BASE_MAP=15,
	
	ORDER_CREATE=20,
	ORDER_MODIFY_BUILDING=42,
	ORDER_MODIFY_SWARM=43,
	ORDER_MODIFY_FLAG=44,
	ORDER_DELETE=30,
	ORDER_UPGRADE=31,
	
	ORDER_NULL=51,
	ORDER_QUITED=52,
	ORDER_WAITING_FOR_PLAYER=55,
	ORDER_DROPPING_PLAYER=57,
	ORDER_REQUESTING_AWAY=58,
	ORDER_NO_MORE_ORDER_AVIABLES=59,
	ORDER_PLAYER_QUIT_GAME=60,
	
	ORDER_MODIFY_UNIT=61,
	
	ORDER_TEXT_MESSAGE=71,
	ORDER_SET_ALLIANCE=72,
	ORDER_SUBMIT_CHECK_SUM=73,
	
	NEW_PLAYER_WANTS_SESSION_INFO=81,
	NEW_PLAYER_SEND_CHECKSUM_CONFIRMATION=82,
	
	SERVER_SEND_CHECKSUM_RECEPTION=83,
	
	CLIENT_QUIT_NEW_GAME=84,
	SERVER_QUIT_NEW_GAME=85,
	
	PLAYERS_CAN_START_CROSS_CONNECTIONS=101,
	PLAYERS_CONFIRM_START_CROSS_CONNECTIONS=102,
	PLAYERS_STILL_CROSS_CONNECTING=103,
	SERVER_CONFIRM_CLIENT_STILL_CROSS_CONNECTING=104,
	
	PLAYER_CROSS_CONNECTION_FIRST_MESSAGE=107,
	PLAYER_CROSS_CONNECTION_SECOND_MESSAGE=108,
	
	PLAYERS_CROSS_CONNECTIONS_ACHIEVED=110,
	SERVER_HEARD_CROSS_CONNECTION_CONFIRMATION=111,
	
	SERVER_ASK_FOR_GAME_BEGINNING=117,
	PLAYER_CONFIRM_GAME_BEGINNING=118,
	
	PLAYER_TOTL_AT_GAME_START=120
	
};

#endif 
