// SPDX-License-Identifier: GPL-3.0-or-later
#include "StartQualityScreen.h"
#include "FairnessModel.h"
#include <FormatableString.h>
#include <cstdio>

using namespace Glob2UI;
using namespace MapGeneration;

namespace
{
std::string t(const std::string &s) { return Glob2UI::tr("[" + s + "]"); }
std::string fixed(double v, int decimals = 2)
{
	char text[32];
	std::snprintf(text, sizeof text, "%.*f", decimals, v);
	return text;
}
std::string percent(double v) { return fixed(100.0 * v, 1) + "%"; }
std::string signed_(double v)
{
	// Round before choosing the sign, so a contribution that prints as zero does not come out
	// as "+-0.000" when it happens to be a very small negative number.
	if (v > -0.0005 && v < 0.0005)
		v = 0;
	return (v >= 0 ? "+" : "") + fixed(v, 3);
}
} // namespace

StartQualityScreen::StartQualityScreen(const StartQualityReport &report, std::vector<std::string> colonyLabels,
									   std::vector<GAGCore::Color> colonyColors)
	: report(report), labels(std::move(colonyLabels)), colors(std::move(colonyColors))
{
}

StartQualityScreen::~StartQualityScreen() = default;

// The table: one row per colony, a column per term of the fitted fairness model
// (FairnessModel.h, regenerated by tools/fairness_model.py from real games). Each cell shows
// what was measured on the finished map and, under it, what that measurement added to or took
// off this colony's fitness. The last two columns are the fitness itself and the win chance.
Element StartQualityScreen::table(const Presentation &p)
{
	const int terms = FAIRNESS_MODEL_FEATURE_COUNT;
	const int columns = terms + 3;
	auto cell = [](Element e) { return padding({4, 2, 4, 2}, e); };
	std::vector<Element> cells;
	cells.push_back(cell(paragraph(t("Colony"))));
	// A term's heading is the model's own phrase for the measurement, generated with the
	// coefficients rather than held in the string table.
	for (int c = 0; c < terms; ++c)
		cells.push_back(cell(paragraph(fairnessModelTerms()[c].label, {FontRole::Support})));
	cells.push_back(cell(paragraph(t("Fitness"), {FontRole::Support})));
	cells.push_back(cell(paragraph(t("Win chance"), {FontRole::Support})));
	// The fitted coefficient, so the reader sees which way each measurement pushes.
	cells.push_back(cell(paragraph(t("Coefficient"), {FontRole::Support, true})));
	for (int c = 0; c < terms; ++c)
		cells.push_back(cell(paragraph(signed_(fairnessModelTerms()[c].coefficient), {FontRole::Support, true})));
	cells.push_back(cell(empty()));
	cells.push_back(cell(empty()));
	for (std::size_t i = 0; i < report.colonies.size(); ++i)
	{
		const auto &q = report.colonies[i];
		std::vector<Element> name{label(i < labels.size() ? labels[i] : std::to_string(i + 1))};
		if (i < colors.size())
			name.insert(name.begin(), swatch(colors[i], 14));
		cells.push_back(cell(row(std::move(name), {p.pt(6), CrossAlign::Center})));
		for (int c = 0; c < terms; ++c)
			cells.push_back(cell(column({label(fixed(fairnessModelMeasurement(report.colonies, i, c), 0)),
										 label(signed_(fairnessModelContribution(report.colonies, i, c)), {FontRole::Support, true})},
										{p.pt(2)})));
		cells.push_back(cell(label(signed_(q.fitness))));
		cells.push_back(cell(label(percent(q.winProbability))));
	}
	WrapOptions grid;
	grid.minChildWidth = 1;
	grid.maxColumns = columns;
	grid.gap = p.pt(2);
	return wrap(std::move(cells), grid);
}

Element StartQualityScreen::cards(const Presentation &p)
{
	std::vector<Element> items;
	for (std::size_t i = 0; i < report.colonies.size(); ++i)
	{
		const auto &q = report.colonies[i];
		const auto name = i < labels.size() ? labels[i] : GAGCore::FormattableString(t("Colony %0")).arg(i + 1);
		const auto summary = GAGCore::FormattableString(t("Win chance: %0 · Fitness: %1")).arg(percent(q.winProbability)).arg(signed_(q.fitness));
		const bool open = expanded.count(i) > 0;
		std::vector<Element> header{label(name), Glob2UI::expanded(spacer()), label(open ? "−" : "+")};
		if (i < colors.size())
			header.insert(header.begin(), swatch(colors[i], 20));
		std::vector<Element> body{row(std::move(header), {p.pt(8), CrossAlign::Center}), paragraph(summary, {FontRole::Support, true})};
		if (open)
			for (int c = 0; c < FAIRNESS_MODEL_FEATURE_COUNT; ++c)
			{
				body.push_back(paragraph(fairnessModelTerms()[c].label));
				body.push_back(paragraph(GAGCore::FormattableString(t("%0 · Contribution: %1"))
											 .arg(fixed(fairnessModelMeasurement(report.colonies, i, c), 0))
											 .arg(signed_(fairnessModelContribution(report.colonies, i, c))),
										 {FontRole::Support, true}));
			}
		CardOptions cardOptions;
		cardOptions.color = GAGCore::Color(225, 231, 209);
		cardOptions.shadow = false;
		cardOptions.padding = p.pt(10);
		auto toggleCard = button("quality/colony/" + std::to_string(i), "", [this, i]
								 {
									 if (!expanded.erase(i))
										 expanded.insert(i);
								 },
								 {false, false, true, true});
		items.push_back(stack({toggleCard, card(column(std::move(body), {p.pt(6)}), cardOptions)}));
	}
	return column(std::move(items));
}

Element StartQualityScreen::build(const Presentation &p)
{
	auto intro = paragraph(t("Every colony's start is measured on the finished map, and a model fitted to thousands of games "
							  "between equal opponents turns those measurements into a fitness. The fitness says how likely "
							  "that colony is to win. Fairness is how evenly those chances are shared: 1 when every colony "
							  "is as likely to win as any other, 0 when one colony would take the map."),
						   {FontRole::Support});
	// The headline stays out of the scrolling table so it never scrolls away with eight colonies.
	const std::string totals = t("Fairness") + " " + fixed(report.fairness) + "  /  " + t("Worst") + " " + signed_(report.worstFitness) +
							   "  /  " + t("Best") + " " + signed_(report.bestFitness) + "  /  " + t("Average") + " " + signed_(report.meanFitness);
	char fitted[128];
	std::snprintf(fitted, sizeof fitted, "%s %d", t("Fitted on games:").c_str(), FAIRNESS_MODEL_GAMES);
	Element bodyContent = p.phone() ? cards(p) : table(p);
	auto body = scroll("quality/scroll", column({intro, bodyContent}, {p.pt(12)}));
	auto footerRow = column({paragraph(totals), caption(fitted), actions({{"back", t("Back"), [this] { endExecute(BACK); }, false, SDLK_ESCAPE}}, p)}, {p.pt(6)});
	return page(t("Start quality"), body, footerRow, p, 1000);
}
