// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/fairness_model.py -- do not edit by hand.
//
// How good a start each colony got, fitted to real games rather than chosen.
// Every start gets a fitness F; the probability that it wins its map is
// softmax(F) over that map's colonies, and map fairness is 1 minus the
// colony-count-normalised Gini of those probabilities.
//
// Fitted on 2942 free-for-all games over 1482 randomly drawn maps,
// the same AI in every slot (castor, maxima, nicowar, numbi), at 1af7f82fb.
// Cross-validated McFadden R2 0.0278, 0.0282 in sample.
// See docs/map-generators/FAIRNESS_MODEL.md.
#pragma once
#include "Ressource.h"
#include "StartQuality.h"
#include <algorithm>
#include <cmath>
#include <vector>

namespace MapGeneration
{
/// Softmax fixes the scale of F but not its zero: this anchors the mean fitness
/// of the fitted starts at zero, so an absolute level is a convention, not a
/// measurement. Differences between colonies are what the games determined.
constexpr double FAIRNESS_MODEL_INTERCEPT = -0.8483111076723134;

/// d_wheat_decayed (share)
constexpr double FAIRNESS_MODEL_D_WHEAT_DECAYED_SHARE = 3.05741445359877;
/// band24_tied_nearest_tiles (sqrt)
constexpr double FAIRNESS_MODEL_BAND24_TIED_NEAREST_TILES_SQRT = -0.04033000243089993;
/// build_sites_4x4 (log)
constexpr double FAIRNESS_MODEL_BUILD_SITES_4X4_LOG = 0.10261972855399439;
/// rivals_within_threat (identity)
constexpr double FAIRNESS_MODEL_RIVALS_WITHIN_THREAT_IDENTITY = -0.1264742533066407;
/// band48_wood_amount (identity)
constexpr double FAIRNESS_MODEL_BAND48_WOOD_AMOUNT_IDENTITY = -0.0005368696067905774;

constexpr int FAIRNESS_MODEL_FEATURE_COUNT = 5;
constexpr int FAIRNESS_MODEL_GAMES = 2942;

/// The fitted terms by name, for reports and the lobby's breakdown screen.
struct FairnessModelTerm
{
	const char *name;
	const char *transform;
	const char *label;   ///< a phrase a player can read
	double coefficient;
};
inline const FairnessModelTerm *fairnessModelTerms()
{
	static const FairnessModelTerm terms[] = {
		{"d_wheat_decayed", "share", "Uncontested wheat, nearest counts most", FAIRNESS_MODEL_D_WHEAT_DECAYED_SHARE},
		{"band24_tied_nearest_tiles", "sqrt", "Contested territory within 24 steps", FAIRNESS_MODEL_BAND24_TIED_NEAREST_TILES_SQRT},
		{"build_sites_4x4", "log", "Building sites", FAIRNESS_MODEL_BUILD_SITES_4X4_LOG},
		{"rivals_within_threat", "identity", "Rivals close by", FAIRNESS_MODEL_RIVALS_WITHIN_THREAT_IDENTITY},
		{"band48_wood_amount", "identity", "Wood stock within 48 steps", FAIRNESS_MODEL_BAND48_WOOD_AMOUNT_IDENTITY},
	};
	return terms;
}

/// What one term measures on one colony, before its transform: the number the
/// lobby's breakdown shows next to the term's contribution.
inline double fairnessModelMeasurement(const std::vector<ColonyQuality> &colonies,
									   std::size_t index, int term)
{
	const ColonyQuality &colony = colonies[index];
	switch (term)
	{
	case 0: return (0.6872892787909722 * (double(colony.distanceBands[0].exclusiveStoredAmount[WHEAT])) + 0.32465246735834974 * ((double(colony.distanceBands[1].exclusiveStoredAmount[WHEAT])) - (double(colony.distanceBands[0].exclusiveStoredAmount[WHEAT]))) + 0.10539922456186433 * ((double(colony.distanceBands[2].exclusiveStoredAmount[WHEAT])) - (double(colony.distanceBands[1].exclusiveStoredAmount[WHEAT]))));
	case 1: return double(colony.distanceBands[1].tiedNearestTiles);
	case 2: return double(colony.buildSites);
	case 3: return double(colony.rivalsWithinThreat);
	case 4: return double(colony.distanceBands[2].storedAmount[WOOD]);
	}
	return 0;
}

/// That term's contribution to this colony's fitness: coefficient times transformed value.
inline double fairnessModelContribution(const std::vector<ColonyQuality> &colonies,
										std::size_t index, int term)
{
	const ColonyQuality &colony = colonies[index];
	switch (term)
	{
	case 0:
	{
		double total = 0;
		for (const ColonyQuality &other : colonies)
			total += (0.6872892787909722 * (double(other.distanceBands[0].exclusiveStoredAmount[WHEAT])) + 0.32465246735834974 * ((double(other.distanceBands[1].exclusiveStoredAmount[WHEAT])) - (double(other.distanceBands[0].exclusiveStoredAmount[WHEAT]))) + 0.10539922456186433 * ((double(other.distanceBands[2].exclusiveStoredAmount[WHEAT])) - (double(other.distanceBands[1].exclusiveStoredAmount[WHEAT]))));
		return FAIRNESS_MODEL_D_WHEAT_DECAYED_SHARE * (total > 0 ? ((0.6872892787909722 * (double(colony.distanceBands[0].exclusiveStoredAmount[WHEAT])) + 0.32465246735834974 * ((double(colony.distanceBands[1].exclusiveStoredAmount[WHEAT])) - (double(colony.distanceBands[0].exclusiveStoredAmount[WHEAT]))) + 0.10539922456186433 * ((double(colony.distanceBands[2].exclusiveStoredAmount[WHEAT])) - (double(colony.distanceBands[1].exclusiveStoredAmount[WHEAT]))))) / total : 0.0);
	}
	case 1: return FAIRNESS_MODEL_BAND24_TIED_NEAREST_TILES_SQRT * std::sqrt(std::max(double(colony.distanceBands[1].tiedNearestTiles), 0.0));
	case 2: return FAIRNESS_MODEL_BUILD_SITES_4X4_LOG * std::log1p(std::max(double(colony.buildSites), 0.0));
	case 3: return FAIRNESS_MODEL_RIVALS_WITHIN_THREAT_IDENTITY * double(colony.rivalsWithinThreat);
	case 4: return FAIRNESS_MODEL_BAND48_WOOD_AMOUNT_IDENTITY * double(colony.distanceBands[2].storedAmount[WOOD]);
	}
	return 0;
}

/// The fitness of one colony, given every colony on the same map.
inline double startFitness(const std::vector<ColonyQuality> &colonies, std::size_t index)
{
	const ColonyQuality &colony = colonies[index];
	double fitness = FAIRNESS_MODEL_INTERCEPT;
	{ // d_wheat_decayed, as this colony's share of the map's total
		double total = 0;
		for (const ColonyQuality &other : colonies)
			total += (0.6872892787909722 * (double(other.distanceBands[0].exclusiveStoredAmount[WHEAT])) + 0.32465246735834974 * ((double(other.distanceBands[1].exclusiveStoredAmount[WHEAT])) - (double(other.distanceBands[0].exclusiveStoredAmount[WHEAT]))) + 0.10539922456186433 * ((double(other.distanceBands[2].exclusiveStoredAmount[WHEAT])) - (double(other.distanceBands[1].exclusiveStoredAmount[WHEAT]))));
		fitness += FAIRNESS_MODEL_D_WHEAT_DECAYED_SHARE * (total > 0 ? ((0.6872892787909722 * (double(colony.distanceBands[0].exclusiveStoredAmount[WHEAT])) + 0.32465246735834974 * ((double(colony.distanceBands[1].exclusiveStoredAmount[WHEAT])) - (double(colony.distanceBands[0].exclusiveStoredAmount[WHEAT]))) + 0.10539922456186433 * ((double(colony.distanceBands[2].exclusiveStoredAmount[WHEAT])) - (double(colony.distanceBands[1].exclusiveStoredAmount[WHEAT]))))) / total : 0.0);
	}
	fitness += FAIRNESS_MODEL_BAND24_TIED_NEAREST_TILES_SQRT * std::sqrt(std::max(double(colony.distanceBands[1].tiedNearestTiles), 0.0));
	fitness += FAIRNESS_MODEL_BUILD_SITES_4X4_LOG * std::log1p(std::max(double(colony.buildSites), 0.0));
	fitness += FAIRNESS_MODEL_RIVALS_WITHIN_THREAT_IDENTITY * double(colony.rivalsWithinThreat);
	fitness += FAIRNESS_MODEL_BAND48_WOOD_AMOUNT_IDENTITY * double(colony.distanceBands[2].storedAmount[WOOD]);
	return fitness;
}
} // namespace MapGeneration
