// SPDX-License-Identifier: GPL-3.0-or-later
#include "Orbits.h"
#include "Building.h"
#include "BuildingType.h"
#include "Game.h"
#include "GenerationContext.h"
#include "HeightMap.h"
#include "Map.h"
#include "Unit.h"
#include <algorithm>
#include <climits>
#include <cmath>
#include <numeric>
namespace MapGeneration
{
namespace
{
int wrap(int v, int n)
{
	v %= n;
	return v < 0 ? v + n : v;
}

// The class of a tile's graphic (Map::lookup): grass, grass and sand, sand, sand and water, water. It
// depends only on which terrains a tile's corners hold, not on which corner holds which, so it is
// unchanged by any symmetry.
int terrainClass(Uint16 terrain)
{
	return terrain < 16 ? 0 : terrain < 128 ? 1 : terrain < 144 ? 2 : terrain < 256 ? 3 : 4;
}

std::string at(int x, int y)
{
	return " at (" + std::to_string(x) + ", " + std::to_string(y) + ")";
}
} // namespace

int Symmetry::tile(int e, int x, int y) const
{
	const Isometry &g = elements[e];
	const int X = 2 * x + 1 - width, Y = 2 * y + 1 - height;
	return wrap((g.c * X + g.d * Y + height - 1) / 2 + g.ty, height) * width +
		   wrap((g.a * X + g.b * Y + width - 1) / 2 + g.tx, width);
}

int Symmetry::corner(int e, int u, int v) const
{
	const Isometry &g = elements[e];
	const int U = 2 * u - width, V = 2 * v - height;
	return wrap((g.c * U + g.d * V + height) / 2 + g.ty, height) * width +
		   wrap((g.a * U + g.b * V + width) / 2 + g.tx, width);
}

std::pair<int, int> Symmetry::anchor(int e, int x, int y, int w, int h) const
{
	const Isometry &g = elements[e];
	const int U0 = 2 * x - width, V0 = 2 * y - height;
	const int U1 = 2 * (x + w) - width, V1 = 2 * (y + h) - height;
	const int X = std::min(g.a * U0 + g.b * V0, g.a * U1 + g.b * V1);
	const int Y = std::min(g.c * U0 + g.d * V0, g.c * U1 + g.d * V1);
	return {wrap((X + width) / 2 + g.tx, width), wrap((Y + height) / 2 + g.ty, height)};
}

int Symmetry::orbitKey(int x, int y) const
{
	int first = y * width + x;
	for (int e = 1; e < order(); ++e)
		first = std::min(first, tile(e, x, y));
	return first;
}

Symmetry pointSymmetry(int width, int height, int teams)
{
	Symmetry s;
	s.width = width;
	s.height = height;
	const bool square = width == height;
	if (teams == 2)
		s.elements = {{1, 0, 0, 1}, {-1, 0, 0, -1}};
	else if (teams == 4 && square)
		s.elements = {{1, 0, 0, 1}, {0, -1, 1, 0}, {-1, 0, 0, -1}, {0, 1, -1, 0}};
	else if (teams == 4)
		s.elements = {{1, 0, 0, 1}, {-1, 0, 0, 1}, {-1, 0, 0, -1}, {1, 0, 0, -1}};
	else if (teams == 8 && square)
		s.elements = {{1, 0, 0, 1},   {0, 1, 1, 0},   {0, -1, 1, 0}, {-1, 0, 0, 1},
					  {-1, 0, 0, -1}, {0, -1, -1, 0}, {0, 1, -1, 0}, {1, 0, 0, -1}};
	return s;
}

Symmetry translationSymmetry(int width, int height, int teams, long long *spacing2)
{
	Symmetry best;
	best.width = width;
	best.height = height;
	if (teams < 2 || width <= 0 || height <= 0 || (long long)width * height % teams)
		return best;
	// Every subgroup of the torus's translations, in Hermite normal form: generated by (p, 0) and
	// (s, q), where p divides the width, q the height, 0 <= s < p, and q steps of the second generator
	// land back on a multiple of the first. Its order is (width / p) * (height / q).
	long long bestSpacing = -1;
	const Torus t(width, height);
	for (int p = 1; p <= width; ++p)
	{
		if (width % p)
			continue;
		for (int q = 1; q <= height; ++q)
		{
			if (height % q || (long long)(width / p) * (height / q) != teams)
				continue;
			const int columns = width / p, rows = height / q;
			for (int s = 0; s < p; ++s)
			{
				if ((long long)s * rows % p)
					continue;
				long long spacing = LLONG_MAX;
				for (int j = 0; j < rows; ++j)
					for (int i = 0; i < columns; ++i)
						if (i || j)
						{
							const int dx = t.offsetX(0, i * p + j * s), dy = t.offsetY(0, j * q);
							spacing = std::min(spacing, (long long)dx * dx + (long long)dy * dy);
						}
				if (spacing <= bestSpacing)
					continue;
				bestSpacing = spacing;
				best.elements.clear();
				for (int j = 0; j < rows; ++j)
					for (int i = 0; i < columns; ++i)
						best.elements.push_back({1, 0, 0, 1, wrap(i * p + j * s, width), j * q});
			}
		}
	}
	if (spacing2)
		*spacing2 = bestSpacing;
	return best;
}

int latticePeriod(const Symmetry &s)
{
	int period = std::min(s.width, s.height);
	for (const Isometry &g : s.elements)
	{
		if (g.a != 1 || g.b != 0 || g.c != 0 || g.d != 1)
			return std::min(s.width, s.height);
		period = std::gcd(period, std::gcd(std::abs(g.tx), std::abs(g.ty)));
	}
	return std::max(1, period);
}

LatticeSites latticeSites(int width, int height, int teams, double x0, double y0)
{
	LatticeSites result;
	if (teams < 1)
		return result;
	const Symmetry exact = translationSymmetry(width, height, teams);
	if (exact.order() == teams)
	{
		result.exact = true;
		for (const Isometry &g : exact.elements)
			result.sites.push_back({std::fmod(x0 + g.tx, width), std::fmod(y0 + g.ty, height)});
		return result;
	}
	// Rows of equal length: of the ways to split the colonies into equal rows, the one whose row
	// spacing is nearest a hexagonal lattice's (0.866 of the spacing along a row).
	int rows = 1;
	double bestError = 1e18;
	for (int r = 1; r <= teams; ++r)
	{
		if (teams % r)
			continue;
		const double along = double(width) / (teams / r), across = double(height) / r;
		const double error = std::fabs(std::log(across / (0.866 * along)));
		if (error < bestError - 1e-12)
		{
			bestError = error;
			rows = r;
		}
	}
	const int columns = teams / rows;
	const double along = double(width) / columns, across = double(height) / rows;
	// Each row is shifted from the last by the whole number of steps, over the rows, nearest half a
	// step, so that after all the rows the shift is whole steps and the lattice wraps seamlessly.
	const double shift = along * std::round(rows / 2.0) / rows;
	for (int j = 0; j < rows; ++j)
		for (int i = 0; i < columns; ++i)
			result.sites.push_back(
				{std::fmod(x0 + i * along + j * shift, width), std::fmod(y0 + j * across, height)});
	return result;
}

LatticeSites roomyLatticeSites(int width, int height, int teams, double x0, double y0,
							   int maxVacancies)
{
	// Refuse degenerate dimensions before invoking latticeSites: its ordinary row
	// arithmetic assumes a positive torus. A bad request must not divide by zero.
	if (width <= 0 || height <= 0 || teams < 1)
		return {};
	LatticeSites best = latticeSites(width, height, teams, x0, y0);
	if (teams < 2 || maxVacancies <= 0)
		return best;
	const Torus t(width, height);
	double bestSpacing = nearestSiteDistance(t, best.sites);
	// A prime team count can be forced into a very long single row. A nearby composite
	// count often has a balanced lattice; leave its surplus sites empty instead of rejecting
	// a map on which even more colonies would fit. Four is enough to reach 12 from counts
	// 8..11 (the lobby's maximum is 12); the loop remains bounded for other callers too.
	// Cap caller-supplied work at four spare sites, the useful envelope for the
	// registered 12-colony range; this also prevents a tuning typo from making a
	// pathological search. The public request validator separately bounds teams.
	for (int vacancies = 1; vacancies <= std::min(maxVacancies, 4); ++vacancies)
	{
		LatticeSites candidate = latticeSites(width, height, teams + vacancies, x0, y0);
		if (candidate.sites.size() != size_t(teams + vacancies))
			continue;
		for (int removed = 0; removed < vacancies; ++removed)
		{
			int choice = -1;
			double choiceSpacing = -1;
			for (size_t site = 0; site < candidate.sites.size(); ++site)
			{
				std::vector<ShapePoint> surviving = candidate.sites;
				surviving.erase(surviving.begin() + site);
				const double spacing = nearestSiteDistance(t, surviving);
				if (spacing > choiceSpacing)
				{
					choice = int(site);
					choiceSpacing = spacing;
				}
			}
			candidate.sites.erase(candidate.sites.begin() + choice);
		}
		const double spacing = nearestSiteDistance(t, candidate.sites);
		if (spacing > bestSpacing)
		{
			best = std::move(candidate);
			best.exact = false; // omitted images no longer form the full translation orbit
			best.vacancies = vacancies;
			bestSpacing = spacing;
		}
	}
	return best;
}

std::vector<unsigned char> stampOrbits(const Symmetry &s, const std::vector<unsigned char> &feature,
									   bool corners)
{
	std::vector<unsigned char> result(feature.size(), 0);
	for (int y = 0; y < s.height; ++y)
		for (int x = 0; x < s.width; ++x)
			for (int e = 0; e < s.order(); ++e)
				if (feature[size_t(corners ? s.corner(e, x, y) : s.tile(e, x, y))])
				{
					result[size_t(y) * s.width + x] = 1;
					break;
				}
	return result;
}

std::vector<int> orbitSum(const Symmetry &s, const std::vector<int> &raw, bool corners)
{
	std::vector<int> summed(raw.size(), 0);
	for (int y = 0; y < s.height; ++y)
		for (int x = 0; x < s.width; ++x)
			for (int e = 0; e < s.order(); ++e)
				summed[size_t(y) * s.width + x] +=
					raw[size_t(corners ? s.corner(e, x, y) : s.tile(e, x, y))];
	return summed;
}

std::vector<int> orbitNoise(GenerationContext &context, const Symmetry &s,
							const std::string &stream, float smoothing, bool corners)
{
	const int w = s.width, h = s.height;
	HeightMap noise(w, h, context.stream(stream));
	noise.makePlain(smoothing);
	std::vector<int> raw(size_t(w) * h);
	for (int y = 0; y < h; ++y)
		for (int x = 0; x < w; ++x)
			// Noise as integers (12 bits) so the sum over an orbit is exact: floating-point sums in
			// different orders could differ in the last bit and break the symmetry.
			raw[size_t(y) * w + x] = int(noise(x, y) * 4096);
	return orbitSum(s, raw, corners);
}

std::vector<unsigned char> topShare(const std::vector<int> &value,
									const std::vector<unsigned char> &eligible, double share,
									bool highest)
{
	std::vector<int> pool;
	for (size_t i = 0; i < value.size(); ++i)
		if (eligible[i])
			pool.push_back(value[i]);
	std::vector<unsigned char> mask(value.size(), 0);
	const size_t count =
		std::min(pool.size(), size_t(std::lround(std::max(0.0, share) * pool.size())));
	if (!count)
		return mask;
	std::sort(pool.begin(), pool.end());
	const int threshold = highest ? pool[pool.size() - count] : pool[count - 1];
	for (size_t i = 0; i < value.size(); ++i)
		mask[i] = eligible[i] && (highest ? value[i] >= threshold : value[i] <= threshold);
	return mask;
}

bool equaliseDeposits(Map &map, const Symmetry &s, std::string &detail)
{
	const int w = s.width, h = s.height;
	for (int y = 0; y < h; ++y)
		for (int x = 0; x < w; ++x)
		{
			const int i = y * w + x;
			const int first = s.orbitKey(x, y);
			if (first == i)
				continue;
			const Resource source = map.getResource(size_t(first));
			Resource &target = map.getResource(size_t(i));
			if (source.type != target.type)
			{
				detail = "deposits differ across the orbit of (" + std::to_string(x) + ", " +
						 std::to_string(y) + ")";
				return false;
			}
			target = source;
		}
	return true;
}

std::string orbitMismatch(const Game &game, const Symmetry &s, int teams,
						  std::vector<std::vector<int>> *permutations)
{
	const Map &map = game.map;
	const int w = map.getW(), h = map.getH();
	if (s.order() != teams)
		return "No symmetry gives " + std::to_string(teams) + " colonies the same ground.";
	std::vector<std::vector<int>> images;
	for (int e = 1; e < s.order(); ++e)
	{
		const std::string under = " is not symmetric under symmetry " + std::to_string(e) + ".";
		std::vector<int> image(size_t(teams), -1);
		const auto relate = [&](int from, int to)
		{
			if (from < 0 || from >= teams || to < 0 || to >= teams)
				return false;
			if (image[size_t(from)] < 0)
				image[size_t(from)] = to;
			return image[size_t(from)] == to;
		};
		for (int v = 0; v < h; ++v)
			for (int u = 0; u < w; ++u)
			{
				const int c = s.corner(e, u, v);
				if (map.getUMTerrain(u, v) != map.getUMTerrain(c % w, c / w))
					return "Undermap corner" + at(u, v) + under;
			}
		for (int y = 0; y < h; ++y)
			for (int x = 0; x < w; ++x)
			{
				const int q = s.tile(e, x, y), qx = q % w, qy = q / w;
				if (terrainClass(map.getTerrain(x, y)) != terrainClass(map.getTerrain(qx, qy)))
					return "Terrain" + at(x, y) + under;
				const Resource &ra = map.getResource(x, y), &rb = map.getResource(qx, qy);
				if (ra.type != rb.type || ra.amount != rb.amount)
					return "Deposit" + at(x, y) + under;
				const Uint16 ba = map.getBuilding(x, y), bb = map.getBuilding(qx, qy);
				if ((ba == NOGBID) != (bb == NOGBID))
					return "Building" + at(x, y) + under;
				if (ba != NOGBID && (!relate(Building::GIDtoTeam(ba), Building::GIDtoTeam(bb)) ||
									 game.teams[Building::GIDtoTeam(ba)]
											 ->myBuildings[Building::GIDtoID(ba)]
											 ->type != game.teams[Building::GIDtoTeam(bb)]
														   ->myBuildings[Building::GIDtoID(bb)]
														   ->type))
					return "Building" + at(x, y) + under;
				const Uint16 ua = map.getGroundUnit(x, y), ub = map.getGroundUnit(qx, qy);
				if ((ua == NOGUID) != (ub == NOGUID))
					return "Unit" + at(x, y) + under;
				if (ua != NOGUID &&
					(!relate(Unit::GIDtoTeam(ua), Unit::GIDtoTeam(ub)) ||
					 game.teams[Unit::GIDtoTeam(ua)]->myUnits[Unit::GIDtoID(ua)]->typeNum !=
						 game.teams[Unit::GIDtoTeam(ub)]->myUnits[Unit::GIDtoID(ub)]->typeNum))
					return "Unit" + at(x, y) + under;
			}
		std::vector<unsigned char> hit(size_t(teams), 0);
		for (int team = 0; team < teams; ++team)
		{
			const int to = image[size_t(team)];
			if (to < 0 || hit[size_t(to)])
				return "Symmetry " + std::to_string(e) + " does not map colonies one to one.";
			hit[size_t(to)] = 1;
		}
		images.push_back(image);
	}
	std::vector<int> carried{0};
	std::vector<unsigned char> seen(size_t(teams), 0);
	seen[0] = 1;
	for (size_t head = 0; head < carried.size(); ++head)
		for (const auto &image : images)
			if (!seen[size_t(image[size_t(carried[head])])])
			{
				seen[size_t(image[size_t(carried[head])])] = 1;
				carried.push_back(image[size_t(carried[head])]);
			}
	if (int(carried.size()) != teams)
		return "The symmetries do not carry colony 0 onto every other colony.";
	if (permutations)
		*permutations = images;
	return "";
}
} // namespace MapGeneration
