# SPDX-License-Identifier: GPL-3.0-or-later
"""Colony-skin material registry: one JSON and one GLSL file feed every build.

libgag/shaders/skin-materials.json names the material ids and the fur shell
count; libgag/shaders/skin-material.glsl shades them. The native builds compile
both into include/glob2/SkinMaterials.h; the web studio imports the GLSL raw and
the platform mirrors the id list (platform/packages/protocol/src/skins.ts).
"""
import json
from pathlib import Path
import re

REGISTRY = Path('libgag/shaders/skin-materials.json')
SHADER = Path('libgag/shaders/skin-material.glsl')
HEADER = Path('include/glob2/SkinMaterials.h')
# MSVC caps a string literal at 16380 bytes; keep each raw chunk well under it.
CHUNK = 8000
KEY = re.compile(r'^[a-z][a-z0-9]*$')


def load_registry(root):
    registry = json.loads((Path(root) / REGISTRY).read_text())
    materials = registry['materials']
    ids = [m['id'] for m in materials]
    if ids != list(range(len(materials))):
        raise ValueError('skin material ids must be contiguous from 0')
    keys = [m['key'] for m in materials]
    if len(set(keys)) != len(keys) or not all(KEY.match(k) for k in keys):
        raise ValueError('skin material keys must be unique identifiers')
    if not isinstance(registry['shells'], int) or registry['shells'] < 1:
        raise ValueError('skin material shells must be a positive count')
    for name in ('furLength', 'shellDepth'):
        if not isinstance(registry[name], (int, float)) or registry[name] <= 0:
            raise ValueError('skin material %s must be a positive length' % name)
    return registry


def check_shader(root, registry):
    """The GLSL must define every material and agree on the shell count."""
    text = (Path(root) / SHADER).read_text()
    shells = re.search(r'^#define SKIN_SHELLS (\d+)$', text, re.M)
    if not shells or int(shells.group(1)) != registry['shells']:
        raise ValueError('SKIN_SHELLS in skin-material.glsl must equal "shells" in skin-materials.json')
    for material in registry['materials']:
        if not re.search(r'^void skinMaterial_%s\(' % material['key'], text, re.M):
            raise ValueError('skin-material.glsl does not define skinMaterial_' + material['key'])
    # The dispatch chain is hand-written: every id must call its own material.
    dispatched = re.findall(r'if \(m == (\d+)\) skinMaterial_([a-z0-9]+)\(s, uv, shell\);', text)
    fallback = re.search(r'else skinMaterial_([a-z0-9]+)\(s, uv, shell\);', text)
    if not fallback:
        raise ValueError('skin-material.glsl needs a fallback material for unknown ids')
    expected = {m['id']: m['key'] for m in registry['materials'] if m['key'] != fallback.group(1)}
    if len(dispatched) != len(expected) or {int(i): k for i, k in dispatched} != expected:
        raise ValueError('skinShade must dispatch every material id to its own skinMaterial_<key> exactly once')
    if ')GLSL"' in text:
        raise ValueError('skin-material.glsl cannot contain the raw string terminator )GLSL"')
    return text


def header_text(root):
    registry = load_registry(root)
    shader = check_shader(root, registry)
    chunks = [shader[i:i + CHUNK] for i in range(0, len(shader), CHUNK)] or ['']
    rows = ''.join('    {%d, "%s", "%s", %s},\n' % (m['id'], m['key'], m['name'].replace('"', '\\"'),
                                                    'true' if m['shells'] else 'false')
                   for m in registry['materials'])
    return ('#pragma once\n'
            '// Generated by SCons from libgag/shaders/skin-materials.json and skin-material.glsl.\n'
            '#define SKIN_MATERIAL_COUNT %d\n'
            '#define SKIN_MATERIAL_SHELLS %d\n'
            '// Fur shells reach this far outward in tile NDC and sit this much\n'
            '// nearer per shell so strands win the depth test over the body.\n'
            '#define SKIN_FUR_LENGTH %sf\n'
            '#define SKIN_SHELL_DEPTH %sf\n'
            'namespace GAGCore\n{\n'
            'struct SkinMaterialInfo { unsigned id; const char *key; const char *name; bool shells; };\n'
            'inline constexpr SkinMaterialInfo SkinMaterials[SKIN_MATERIAL_COUNT] = {\n%s};\n'
            '// The shared material GLSL, without a version line or main().\n'
            'inline const char *const SkinMaterialGLSL =\n%s;\n'
            '}\n') % (len(registry['materials']), registry['shells'],
                      repr(float(registry['furLength'])), repr(float(registry['shellDepth'])), rows,
                      '\n'.join('    R"GLSL(%s)GLSL"' % chunk for chunk in chunks))


def generate(root, output):
    """Writes the header under output/include when it changed; returns its path."""
    from build_layout import write_if_changed
    path = Path(output) / HEADER
    write_if_changed(path, header_text(root))
    return path


def inputs(root):
    return [Path(root) / REGISTRY, Path(root) / SHADER]


def register(env):
    """Registers the generated header with SCons, as BuildConfig.h is: the
    content itself is the source, so edits to this generator regenerate too and
    registry errors fail at parse time."""
    from SCons.Script import Action, Value
    from build_layout import write_if_changed
    content = header_text(env.Dir('#').abspath)

    def write(target, source, env):
        write_if_changed(str(target[0]), content)
        return 0
    env.Command(str(Path(env['BUILDDIR']) / HEADER), Value(content), Action(write, 'Generating $TARGET'))
