name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Ubuntu-Bulid:
    name: Ubuntu Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -a
          pwd
